usr/share/rear/verify/TSM/default/40_verify_tsm.sh

See Issue #528
The TSM_RESTORE_FILESPACE_NUMS defaulted to all known filespaces
which might not be desired if the filesystem was not recovered
as part of the rescue image. This change still allows to choose
any filespaces that TSM knows about but will default to only those
that are part of the rescue image.
- Created new TSM_FILESPACE_INCLUDED_NUMS array which is now used
as the default for the TSM_RESTORE_FILESPACE_NUMS
- Populated the MOUNTPOINTS_TO_RESTORE variable with those
fileystems that were excluded from the rescue image because TSM
does not recreate those by default

Change TSM default filespaces restored

---

usr/share/rear/layout/prepare/GNU/Linux/10_include_partition_code.sh
usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_filesystem_code.sh
usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_subvolumes_code.sh
usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh

See https://github.com/rear/rear/issues/497
and https://github.com/rear/rear/issues/533

Generic basic btrfs support plus proposed fix for issue#533 (udevadm settle)

---

usr/share/rear/layout/prepare/GNU/Linux/10_include_partition_code.sh

Reasoning: At least on RHEL6 when parted created a raid partition on disk,
udev (via /lib/udev/rules.d/65-md-incremental.rules) wakes up mdadm which locks the disk,
so further parted commands with the disk will fail since the disk is busy now.
The /lib/udev/rules.d/65-md-incremental.rules detects anaconda (the Red Hat installer),
and if it find itself running under anaconda, it will not run.
Accordingly also for other installers (in particular the rear installer)
this rule should not be there (and other Linux distros probably do not have it)
which means removing it is the right solution to make rear work also for RHEL6.
See https://github.com/rear/rear/issues/533

Prevent udev waking up mdadm later.

---

usr/share/rear/layout/prepare/default/20_recreate_hpraid.sh

to fix commit ae3a930bf26f82e5739c7799e1be0d79444dc19e
see https://github.com/rear/rear/issues/534

Using "do_something || Error_handling" when "set -e" is set

---

usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh

neither somehow truncated nor does it have multiple blanks so that
now the findmnt output is just like the traditional "mount" output
(except that mount outputs the mount options in parenthesis).
Removed not neeed " | tr -s '[:blank:]' ' ' " for findmnt and mount
because their output fields are separated by a single space.
Should fix https://github.com/rear/rear/issues/555

Use findmnt options '-nrv' in particular '-r' for raw output that is

---

usr/share/rear/build/default/99_update_os_conf.sh

os.conf MUST be at /etc/rear/os.conf in the rescue image. $CONF_DIR may have been different depending on the rear installation directory.

write os.conf to /etc/rear/

---

usr/share/rear/lib/framework-functions.sh

Hi,
this is the pull request for  #575 to delete $BUILD_DIR/outputfs if it is not mounted anymore.
regards
goldzahn

rm -Rf $BUILD_DIR/outputfs if it is not mounted anymore

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/Linux-i386/21_install_grub.sh
usr/share/rear/output/default/94_grub2_rescue.sh
usr/share/rear/prep/GNU/Linux/30_include_grub_tools.sh

GRUB2 now supported.
Requires a superuser and a pbkdf2 hash.
Problems found:
The 21_install_grub.sh checked for GRUB2 which is not part of the first 2048 bytes of a disk - only GRUB was present  - thus the check for grub-probe/grub2-probe.
I couldn't get the 94_grub2_rescue.sh to update the /boot/grub2/grub.cfg correctly without the grub-mkconfig/grub2-mkconfig before adding the ReaR menuentry.

Adding GRUB2 support

---

usr/share/rear/build/Debian/61_jessie_link_systemd_lib.sh

hi,
this could be a workaround for issue #599. I have only tested it briefly on debian jessie and it makes the boot process not error out due to missing systemd files. Maybe there is a better solution ..

add workaround for systemd scripts on debian 8: issue #599

---

packaging/debian/rules

because the extension has been changed from .txt to .asciidoc, the build fails, because it cannot remove missing file ...rear.8.txt

fix debian package build error

---

packaging/debian/rules

Debian package could not be built.

fix debian build. README has been renamed to README.adoc

---

usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/ISO/Linux-ppc64/30_create_yaboot.sh
usr/share/rear/output/ISO/Linux-ppc64/80_create_isofs.sh

This is a fix for issue #610 
There is a new function in usr/share/rear/lib/bootloader-functions.sh that is used to find the yaboot binary. It's stored in a different place on SUSE based systems.
There was also some needed changes in usr/share/rear/output/ISO/Linux-ppc64/30_create_yaboot.sh and usr/share/rear/output/ISO/Linux-ppc64/80_create_isofs.sh.
These were necessary since the yaboot binary from SLES is compiled to look for the kernel in the same directory, unlike the versions in Red Hat-type distros.

Add SLES ppc64 support

---

usr/share/rear/layout/prepare/GNU/Linux/11_include_lvm_code.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh

Hi,
I first did not want to create this pull request because I still have some kind of bug in it. The fix is working *correct*. When systemd is present in a recent version, then - in recovery - no additional drivers are loaded.
But when recovery starts, it find the disk (with same size), recreates the LVM group but then fails to create the filesystem on /. I'm very sorry, that I don't have the error message right here (only at home). I think I remember, that I saw a message, that `0 logical volumes are now active` and because of this, the `mkfs` fails. Later, in recovery shell, I could manually do the `mkfs`, so this might be a timing problem.
I will append further information as soon as possible and I hope, that this information is useful for you.

This should fix the loading of modules when systemd is present

---

usr/share/rear/conf/Linux-ppc64le.conf
usr/share/rear/finalize/Linux-ppc64le/22_install_grub2.sh
usr/share/rear/layout/prepare/GNU/Linux/13_include_filesystem_code.sh
usr/share/rear/output/ISO/Linux-ppc64le/30_create_grub2.sh
usr/share/rear/output/ISO/Linux-ppc64le/80_create_isofs.sh
usr/share/rear/pack/Linux-ppc64le/30_copy_kernel.sh
usr/share/rear/rescue/Linux-ppc64le/41_use_hvc_console.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh
usr/share/rear/skel/default/usr/lib/systemd/system/sysinit.service

Hi,
I've created the initial support for new ppc64 little endian platform, ppc64le.
PowerVM: RHEL7.1 LE / Ubuntu 14.04.2 / Ubuntu 15.04
PowerKVM : RHEL7.1LE / Ubuntu 14.04.2 / Uubntu 15.04
* usr/share/rear/layout/prepare/GNU/Linux/13_include_filesystem_code.sh
- I got intermittent error in creating filesystem. Need to wait device creation with udevsettle
* usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh
* usr/share/rear/skel/default/usr/lib/systemd/system/sysinit.service
- Need to skip starting udevd in case of systemd-udevd environment. 
- Also need to add dependency sysinit.service after systemd-udevd.service
For regression test of general fixes, I confirmed backup and recovery on RHEL7.1 x86_64 works correctly.
Please review the code and let me …

Add RHEL/Ubuntu PPC64LE support

---

packaging/rpm/rear.spec

In packaging/rpm/rear.spec replaced "BuildArch: noarch"
with "ExclusiveArch: %ix86 x86_64 ppc ppc64" that should
tell the user that rear is known to work only
on %ix86 x86_64 ppc ppc64
and removed "Requires: yaboot" for ppc ppc64 because
that is the default installed bootloader on ppc ppc64
see the GitHub issue https://github.com/rear/rear/issues/629
Additionally replaced the incomplete and outdated
changelog entries with one generic entry that is always valid.

change rear.spec from noarch to architecture dependent build

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/save/default/31_include_exclude.sh

Hi,
this is only a suggestion that might be included into rear.
We use this kind of patch on all of our servers to only backup filesystems and directories, that are explicitly given in BACKUP_PROG_INCLUDE. So later added mountpoints and big data does NOT blow up the amount of data within the rear backup, when someone misses to update the local.conf.
Currently, we use the variable "MANUAL_INCLUDE" which we set to "YES" in "local.conf" to activate this mode.
As I said....just an idea.

Added possibility to only backup BACKUP_PROG_INCLUDE

---

packaging/debian/control

This PR removes the dependency nfs-client and adds it as recommendation.
The reasons for this are
* NFS is not really a dependency for rear, as there are many other ways to use it
* In my eyes NFS is a quite heavy dependency, as it depends on portmap which opens tcp/111 udp/111 by default

Move nfs-client from depends to recommends

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/ISO/Linux-i386/20_mount_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/25_populate_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/80_create_isofs.sh
usr/share/rear/output/ISO/Linux-i386/82_create_iso_image.sh
usr/share/rear/prep/ISO/GNU/Linux/32_verify_mkisofs.sh

Hello guys,
Yesterday, I've release a small tool called ebiso (https://github.com/gozora/ebiso), which is capable of creating bootable UEFI ISO image (basically just to cover gap on SLES11).
This patch integrates ebiso to rear, so maybe you can find it useful ...
I've did the testing on SLES11SP3 (with elilo) and Centos 6.7 (with GRUB).
Hope it helps.
Best regards
Vlado

ebiso support added

---

usr/share/rear/rescue/GNU/Linux/31_network_devices.sh

The changed 31_network_devies.sh does two things different than before:
1) It doesn't depend on a name based guess for identifing a network device as physical.
It now gets the list of all network devices from /sys/class/net, and 'subtracts' the list of virtual network devices from /sys/devices/virtual/net.
2) It supports VLANs ontop of a bonding interface as well as bonding over multiple VLAN interfaces.
Before it brings up a VLAN, it checks whether its parent device is a bonding interface. If yes, the parent is configured first. Same goes for bonding interfaces.
I hope I didn't introduce any regressions or broke something... :-/

improve network configuration detection

---

usr/share/rear/rescue/GNU/Linux/35_routing.sh
usr/share/rear/rescue/GNU/Linux/36_teaming.sh

Hi guys, as discussed in Issue https://github.com/rear/rear/issues/655 I created a workaround for me to add the teaming function easily to rear. I changed the routing script so that no routing of teaming interfaces will be done within and created a new script 36_teaming which handles everything about the teaming function. Because teaming runs in user space we would need more than just the kernel and the driver (e.g. daemons and tools). Because of this I simplified the function that all ip-addresses and routing-entries of a teaming-interface will be attached to its first available teaming-member (output by teamdctl).
Tested with RHEL 7.1, latest. Also single interfaces and bonding interfaces were working after this changes.
Maybe it is something to add to rear, because from my point of …

Teaming enhancement

---

packaging/rpm/rear.spec

Adding ppc64le arch into rpm spec file for RHEL7/ppc64le.
This arch will be used for SLES12 and OpenSUSE as well.
See #663 for details.

Add ppc64le arch into rpmspec

---

usr/share/rear/conf/Linux-ppc64.conf
usr/share/rear/finalize/Linux-ppc64/20_install_yaboot.sh
usr/share/rear/finalize/Linux-ppc64/22_install_grub2.sh
usr/share/rear/output/ISO/Linux-ppc64/30_create_yaboot.sh
usr/share/rear/output/ISO/Linux-ppc64/31_create_grub2.sh

To support rear in RHEL7/ppc64 big endian distribution, I've added grub2 support in ppc64 platform.
Tested platform:
RHEL7.1 ppc64 Big Endian / PowerKVM
This is minor change, but I verified other following distribution works correctly with this patch.
SLES11 ppc64 / PowerKVM
RHEL6.7 ppc64 / PowerKVM

Add grub2 support in ppc64 platform

---

usr/share/rear/conf/Linux-ppc64.conf
usr/share/rear/finalize/Linux-ppc64/22_install_grub2.sh
usr/share/rear/finalize/Linux-ppc64le/22_install_grub2.sh
usr/share/rear/rescue/Linux-ppc64/41_use_hvc_console.sh

In addition to #672 (for PowerKVM), some changes are needed for another virtualization environment, PowerVM.
Tested platform:
RHEL7.1 ppc64 Big Endian / PowerVM
Other verified platform for regression:
SLES11 ppc64 / PowerVM
RHEL6.7 ppc64 / PowerVM

Add ppc64 grub support for PowerVM virtualization environment

---

usr/share/rear/skel/default/etc/init/tty.conf

In case the rear image does not have mingetty, getty/agetty handling is needed in upstart tty script.
Refer to #661 for details.

Add getty and agetty handling to upstart tty script

---

doc/user-guide/03-configuration.adoc
usr/share/rear/conf/default.conf
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/restore/BAREOS/default/40_restore_backup.sh

Mainly needed for automating the recover process, i.e. create a boot image that will automatically go into recover mode. BAREOS_FILESET option is needed, if you have more than one fileset defined for the recovery-client, otherwise bconsole will interactively ask for the fileset to use.

Adding ISO_DEFAULT boot option and BAREOS_FILESET for automation purposes

---

usr/share/rear/prep/default/40_save_mountpoint_details.sh

Fixes a bug where missing mountpoints are created in ```/``` and not in ```/mnt/local``` within ```rear recover```. See issue #690

Missing mountpoints after recovery

---

usr/share/rear/finalize/GNU/Linux/16_rename_diskbyid.sh

After a successful recovery, during boot, warnings like
WARNING: Bad format on line 10 of /etc/fstab
are printed. The reason is, ```usr/share/rear/finalize/GNU/Linux/16_rename_diskbyid.sh``` adds extra space on every fstab line, including also the empty ones. The ```fsck``` called at boot time reports the above warning for every such line. 
The patch attempts to address this (in a rather expensive way). 
In the addition, a bug regarding exclusion of device-mapper devices from renaming is addressed.

Fix "WARNING: Bad format on line 10 of /etc/fstab" after recovery

---

usr/share/rear/finalize/Linux-i386/22_install_elilo.sh

Rear recovery fails at final stage with ```Could not find elilo.efi``` error. Manual run of ```elilo``` works ok. This patch addresses this bug.

Fix for "Could not find elilo.efi"

---

usr/share/rear/layout/prepare/GNU/Linux/13_include_filesystem_code.sh
usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh
usr/share/rear/lib/layout-functions.sh
usr/share/rear/prep/default/31_include_uefi_tools.sh

SLE 11 SP3 **dosfsutils** package does not include **dosfslabel** utility. This patch obsoletes **dosfslabel** by **blkid** and **mkfs.vfat**. The installation of no external **dosfsutils** package would be required on UEFI booting system. See also #229.

obsolete the requirement of dosfslabel

---

usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/ISO/Linux-i386/20_mount_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/25_populate_efibootimg.sh

An attempt for "secure boot" support for ReaR: 
* if ```shim.efi``` is used as a bootloader, we also copy follow-up loader to the image (we assume it's ```grub*.efi```)
* In addition, ```KERNEL_CMDLINE``` option is now honored also for uefi-booting menu.
We also slightly re-arrange the uefi code, moving some common parts to libs/
I tested this only on SLES11 SP3 (boot-from-san, btrfs).

support for UEFI secure boot

---

usr/share/rear/finalize/Linux-i386/23_run_efibootmgr.sh
usr/share/rear/layout/save/GNU/Linux/20_partition_layout.sh
usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh
usr/share/rear/lib/layout-functions.sh

Multiple san-booting/uefi related fixes implemented.
* correctly find disk and partition number for efibootmgr.
* find now partition start also for multipath (dm-XX) disk
* save ```/dev/mapper/mpathX``` dev names instead of ```dm-XX``` names to the disklayout file for btrfs and ```/dev/disk/by-id/``` disks description.  Addresses the issue, when ```/dev/dm-XX``` is recoreded in disklayout, but ```dm-XX``` can by different disk with the same size in the recovery environment.

SAN booting related improvements

---

usr/sbin/rear
usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/conf/Linux-i386.conf
usr/share/rear/conf/default.conf
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/array-functions.sh
usr/share/rear/lib/checklayout-workflow.sh
usr/share/rear/lib/config-functions.sh
usr/share/rear/lib/framework-functions.sh
usr/share/rear/lib/help-workflow.sh
usr/share/rear/lib/sesam-functions.sh
usr/share/rear/prep/default/95_check_missing_programs.sh

This is a huge pull request with lots of things in it.
Its initial intent was https://github.com/rear/rear/issues/688
by adding a separated debugscripts option so that e.g.
<pre>
rear --debugscripts 'ue +h -o pipefail' help
</pre>
now works as an initial proof of concept that rear can be
made working with things like 'set -eu'.
Because my final goal behind https://github.com/rear/rear/issues/688
is to make rear working with things like 'set -ue -o pipefail' I like
to have as a precondition support for advanced debugging settings
built-in in rear (instead of manually modifying the scripts).
While I implemented the debugscripts option I tested how it works
with things like
<pre>
rear --debugscripts 'xvue -o pipefail' help
</pre>
and during this testing I fixed all what fails in the rear …

Added separated debugscripts option and first steps so that 'set -eu' works

---

usr/share/rear/layout/prepare/GNU/Linux/13_include_filesystem_code.sh

Use wipefs when available to clean up disk partitions
before creating filesystems there,
see https://github.com/rear/rear/issues/540
and https://github.com/rear/rear/issues/649#issuecomment-148725865
Currently "when available" means that on has to manually add it
to the rear recovery system in in /etc/rear/local.conf via
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" wipefs )
Making wipefs automatically available to the rear recovery system
when it is available in the original system is a next step.

Use wipefs when available to clean up disk partitions

---

usr/share/rear/rescue/default/50_ssh.sh

The following tip
<pre>
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
</pre>
was shown when SSH_ROOT_PASSWORD is set in /etc/rear/local.conf.
This pull request adds a test so that this tip is not shown when SSH_ROOT_PASSWORD is set in /etc/rear/local.conf.

Show login as root tip only when needed.

---

usr/sbin/rear
usr/share/rear/conf/default.conf
usr/share/rear/finalize/Fedora/i386/17_rebuild_initramfs.sh
usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_filesystem_code.sh
usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_subvolumes_code.sh
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/format-workflow.sh
usr/share/rear/lib/framework-functions.sh
usr/share/rear/restore/NBU/default/40_restore_with_nbu.sh
usr/share/rear/restore/NETFS/Linux-i386/51_selinux_fixfiles_exclude_dirs.sh
usr/share/rear/restore/NETFS/default/40_restore_backup.sh
usr/share/rear/restore/NETFS/default/50_selinux_autorelabel.sh
usr/share/rear/restore/SUSE_LINUX/91_create_missing_directories.sh
usr/share/rear/wrapup/default/98_good_bye.sh

In particular have '/mnt/local' as readonly
variable RECOVERY_FS_ROOT in usr/sbin/rear
see https://github.com/rear/rear/issues/708
and use $RECOVERY_FS_ROOT in the scripts instead
of hardcoded '/mnt/local' but currently only a few scripts
are adapted so that I can test if it works at all (and for me
it does work).
Have several more readonly constants in the main rear script
like SHARE_DIR CONFIG_DIR VAR_DIR LOG_DIR ...
see https://github.com/rear/rear/issues/678
and fixed if readonly constants are modified in other scripts
as far as currently possible for me.
Additionally the DISKLAYOUT_FILE variable is moved from
usr/share/rear/conf/default.conf to usr/sbin/rear because
it is not meant to be configured by the user
see https://github.com/rear/rear/issues/678
By the way fixed creation of …

Have readonly constants in the main rear script

---

usr/share/rear/wrapup/default/99_copy_logfile.sh

Hereby during "rear recover" the following from the recovery system
<pre>
/var/log/rear/rear-&lt;hostname&gt;.log
/var/lib/rear/layout/*
/var/lib/rear/recovery/*
</pre>
gets copied into the recovered system to a restricted directory
<pre>
drwx------ /var/log/rear/recover/
</pre>
plus a backward compatible symbolic link
<pre>
/root/rear-&lt;date&gt;.log -&gt; /var/log/rear/recover/rear-&lt;hostname&gt;.log
</pre>
is created.
See https://github.com/rear/rear/issues/706

Copy rear recover log et alii into recovered system

---

usr/sbin/rear
usr/share/rear/lib/framework-functions.sh

Implemented simple functions get_bash_flags_and_options_commands
and apply_bash_flags_and_options_commands that are used
in a fail-safe way via an explicit variable that
stores the current bash flags and options commands
and using that explicit variable to re-apply them, i.e. like
<pre>
saved_flags_options_cmds="$( get_bash_flags_and_options_commands )"
... [change bash flags and options] ...
... [do something] ...
apply_bash_flags_and_options_commands "$saved_flags_options_cmds"
</pre>
Currently those functions are used in framework-functions.sh
when "Entering debugscripts mode" and "Leaving debugscripts mode"
so that the workaround by using DEBUGSCRIPTS_OPPOSITE_ARGUMENT is obsoleted.
See https://github.com/rear/rear/issues/700

Get and apply bash flags and options settings

---

usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_filesystem_code.sh

Better wording by using variable named "attributes" and "attribute" (instead of "options" and "option") so that the wording in the code
matches the comment in disklayout.conf and avoids confusion by multiple
meanings of the word "option(s)" see https://github.com/rear/rear/issues/561

Better wording by using variable named "attributes" and "attribute"

---

usr/share/rear/layout/save/default/31_autoexclude_usb.sh
usr/share/rear/output/USB/Linux-i386/85_make_USB_bootable.sh

Signed-off-by: Petr Hracek <phracek@redhat.com>
Remove experimental 'grep -P' switch in the executable scripts
https://bugzilla.redhat.com/show_bug.cgi?id=1290205
When rear is being executed, e.g. /usr/sbin/rear mkrescue an SELinux AVC is generated. 
~~~
type=AVC msg=audit(1448377615.693:35710): avc:  denied  { execmem } for  pid=21398 comm="grep" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process
type=SYSCALL msg=audit(1448377615.693:35710): arch=x86_64 syscall=mmap success=no exit=EACCES a0=0 a1=10000 a2=7 a3=22 items=0 ppid=9928 pid=21398 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=4294967295 comm=grep exe=/usr/bin/grep …

Replace experimental option 'grep -P' to 'grep -E'

---

usr/sbin/rear
usr/share/rear/conf/default.conf
usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_filesystem_code.sh
usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_subvolumes_code.sh
usr/share/rear/restore/NETFS/Linux-i386/51_selinux_fixfiles_exclude_dirs.sh
usr/share/rear/restore/NETFS/default/40_restore_backup.sh
usr/share/rear/restore/NETFS/default/50_selinux_autorelabel.sh
usr/share/rear/restore/SUSE_LINUX/91_create_missing_directories.sh
usr/share/rear/wrapup/default/98_good_bye.sh

Rename RECOVERY_FS_ROOT into TARGET_FS_ROOT to describe what it actually is.
The former name RECOVERY_FS_ROOT (see https://github.com/rear/rear/issues/708) is misleading.
In the "recover" workflow it is not the root of the filesystem tree of the recovery system
but it is the root of the filesystem tree of the to-be-recovered system
i.e. it is the root of the filesystem tree of the target system of the "recover" workflow.
Furthermore the former name RECOVERY_FS_ROOT is incomprehensible in future workflows
like the "install" workflow (see https://github.com/rear/rear/issues/732)
where the root of the filesystem tree of the to-be-installed system
would have to be called INSTALL_FS_ROOT to have a meaningful name.
Therefore the name TARGET_FS_ROOT is now used because
it describes what it …

Rename RECOVERY_FS_ROOT into TARGET_FS_ROOT

---

usr/share/rear/rescue/GNU/Linux/31_network_devices.sh

fixed third time all remaining bash 3.x errors in 31_network_devices.sh
see https://github.com/rear/rear/issues/758 plus heavy syntax cleanup that I needed to understand that code at least to the extent that (hopefully) enables me to fix the bash 3.x errors correctly - i.e. without breaking the functionality of the code.
I would very much appreciate it if someone with proper networking knowledge can verify if the functionality of the code is still o.k.

fixed third time bash 3.x errors in 31_network_devices.sh

---

usr/share/rear/conf/default.conf
usr/share/rear/restore/default/99_move_away_restored_files.sh

moves away restored files that should not have been restored according to the BACKUP_RESTORE_MOVE_AWAY_DIRECTORY and BACKUP_RESTORE_MOVE_AWAY_FILES settings, see https://github.com/rear/rear/issues/779

new usr/share/rear/restore/default/99_move_away_restored_files.sh

---

usr/share/rear/conf/default.conf
usr/share/rear/restore/default/99_move_away_restored_files.sh

more safely remove for move away functionality so that only the directory content is removed but the empty directory itself is kept (e.g. useful to remove content in /var/tmp but keep /var/tmp), see https://github.com/rear/rear/issues/779

more safely remove for move away functionality

---

usr/share/rear/finalize/SUSE_LINUX/i386/17_rebuild_initramfs.sh

workaround the problem in which the partition containing `/boot/` is detected with a wrong uuid when creating the initrd. 
As mentioned, it's a workaround because it fixes the problem but not the cause.

workaround for rear/rear#649

---

usr/share/rear/output/ISO/Linux-i386/82_create_iso_image.sh

in 82_create_iso_image.sh error out if ebiso is used but no UEFI,
see https://github.com/rear/rear/issues/801

in 82_create_iso_image.sh error out if ebiso is used but no UEFI (issue 801)

---

usr/share/rear/backup/NETFS/default/50_make_backup.sh
usr/share/rear/conf/default.conf
usr/share/rear/finalize/Linux-i386/21_install_grub.sh
usr/share/rear/finalize/Linux-i386/22_install_elilo.sh
usr/share/rear/finalize/Linux-i386/22_install_grub2.sh
usr/share/rear/finalize/Linux-i386/23_run_efibootmgr.sh
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/lib/global-functions.sh
usr/share/rear/output/ISO/Linux-i386/20_mount_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/25_populate_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/70_umount_efibootimg.sh
usr/share/rear/output/default/94_grub2_rescue.sh
usr/share/rear/output/default/94_grub_rescue.sh
usr/share/rear/prep/default/32_include_uefi_env.sh
usr/share/rear/rescue/default/85_save_sysfs_uefi_vars.sh
usr/share/rear/restore/NETFS/Linux-i386/51_selinux_fixfiles_exclude_dirs.sh

allow generic yes/no values for USING_UEFI_BOOTLOADER
as a conseqence use everywhere generic tests via
is_true $USING_UEFI_BOOTLOADER
and
is_false $USING_UEFI_BOOTLOADER
the latter requires the new counterpart function
is_false to test for an explicit no value
see https://github.com/rear/rear/issues/801

allow generic yes/no values for USING_UEFI_BOOTLOADER (issue 801)

---

usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/ISO/Linux-i386/20_mount_efibootimg.sh

The patch increases the UEFI image size, if BACKUP is TSM. The reference issue: #810
I must admit I start to dislike this UEFI image size determination code (which is my own partly).
Perhaps we should think about more scientific approach to calculate needed size for the UEFI image?
On the other hands its just few lines of code (compared to bit more if 'more scientific approach' is in place). Any comments please?

ebiso image size is too small if BACKUP is TSM

---

usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/ISO/Linux-i386/20_mount_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/70_create_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/70_umount_efibootimg.sh

Fix for manual detection of EFI virtual image (efiboot.img) size.

Determine EFI virtual disk size automatically (take 2)

---

usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf
usr/share/rear/conf/examples/SLE12-btrfs-example.conf

removed EXCLUDE_RECREATE from
SLE12-SP1-btrfs-example.conf and
SLE12-btrfs-example.conf
see https://github.com/rear/rear/issues/821

removed EXCLUDE_RECREATE from btrfs example configs

---

packaging/rpm/rear.spec

Fix license in rear.spec to "GPL-2.0+ and GPL-3.0"
see issue https://github.com/rear/rear/issues/825

fix license in rear.spec to "GPL-2.0+ and GPL-3.0"

---

usr/share/rear/skel/default/etc/scripts/run-sshd
usr/share/rear/verify/TSM/default/40_verify_tsm.sh

Avoid Problems with ssh-logins when the original sshd_config has some extra secure lines.
Fix the problem where the btrfs subvlums are not restored via TSM.
See Issue #823

Fix btrfs subvolumes with TSM, sshd config

---

usr/share/rear/prep/NETFS/default/05_check_NETFS_requirements.sh

added check for vaild BACKUP_URL schemes
see https://github.com/rear/rear/issues/842
currently 'nfs' 'cifs' 'usb' 'tape' 'file' 'sshfs' are valid
according to the comment in 05_check_NETFS_requirements.sh

added check for vaild BACKUP_URL schemes

---

usr/share/rear/output/default/94_grub2_rescue.sh

1- Grub2: Using search --fs-uuid instead of hardcoded root='hd0,msdos1'
Actually we found that ppc64 and ppc64le are not aware of "hd0,msdos1", current grub2 rescue does not work without the above option in ppc64 and ppc64le. Since this search option is used even in x86 grub2 distro menu, so it would be better to handle as platform independent option.
By the way, this search option allows to use GPT formated disk ! Which is not the case of 'hd0,msdos1'
2- Changing the way REAR grub2 menuentry is created. By using the standard /etc/grub.d directory to store the REAR menu, we are sure that it will not be removed by a manual grub-mkconfig (or an automated one after a kernel upgrade.)

Grub2: REAR Improvements proposal

---

usr/share/rear/prep/NETFS/default/05_check_NETFS_requirements.sh

fix check for vaild BACKUP_URL schemes
now also iso is a valid scheme
see https://github.com/rear/rear/issues/842

fix check for vaild BACKUP_URL schemes

---

usr/share/rear/layout/save/GNU/Linux/28_multipath_layout.sh

When I boot on rear rescue (tested via grub menu) , I can't use multipath because libaio is missing in the ramdisk.
Here is my proposition for modification:
* Correct `LIB` variable name to `LIBS`
* Changing `${PROGS[@]}` to `${LIBS[@]}`
* Using a local variable to find the directory where libaio is located (can be different depending to the Linux distro and arch; for example `/lib/powerpc64le-linux-gnu/libaio.so.1` for ubuntu 16-04 ppc64le).

Solving Multipath cannot load due to libaio missing in ramdisk

---

usr/share/rear/layout/save/GNU/Linux/20_partition_layout.sh

`20_partition_layout.sh `gets partition size from `/sys/block` filesystem for every hdX or sdX device. 
But if the block device `$blockd` is a path of a multipath device, partition and size information does not exist anymore in `/sys/block` which stop the script with the following message:
> "ERROR: BUG BUG BUG!  Could not determine size of disk sdb/sdb2, please file a bug.
> === Issue report === Please report this unexpected issue at: https://github.com/rear/rear/issues Also include the relevant bits from /var/log/rear/rear-XXXXXXXX.log.lockless"
To avoid this situation, I propose to test if the sdX or hdX (`$blockd`) is part of a multipath device. 
If yes, we ignore it because it will be handled by `28_multipath_layout script` (real multipath device `dm-X` will be treated further by …

Ignoring block device which are part of a multipath device.

---

usr/share/rear/lib/global-functions.sh
usr/share/rear/output/default/95_copy_result_files.sh
usr/share/rear/prep/NETFS/default/05_check_NETFS_requirements.sh

See https://github.com/rear/rear/issues/845
I tested it on SLE12 x86_64 kvm/qemu virtual machine
with BIOS and this /etc/rear/local.conf:
<pre>
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=ftpfs://rear:rear@10.160.4.244/rear
NETFS_KEEP_OLD_BACKUP_COPY=yes
SSH_ROOT_PASSWORD="rear"
USE_DHCLIENT="yes"
</pre>
The currently supported ftpfs BACKUP_URL syntax is
<pre>
ftpfs://user:password@host/path
</pre>
where password is optional.
The only missing piece for me is that
in the rear recovery system one must
manually load the fuse kernel module with
<pre>
modprobe fuse
</pre>
because otherwise "rear recover" aborts with
<pre>
Mount command 'curlftpfs ...' failed.
</pre>
At least for me the backup via curlftpfs is
very much slower than the backup via NFS.
For backup via NFS "rear mkbackup" reports
<pre> …

First step to support new ftpfs BACKUP_URL

---

usr/share/rear/conf/Linux-ppc64le.conf

Need to have `/lib/firmware` in rescue image when running in BareMetal Mode (PowerNV).
Without firmware, we can't get access to the network, SAN disk etc ... 
Since only ppc64le Linux can run in powerNV, we don't need to do the same for Linux-ppc64.conf.
PowerNV mode can be detected in `/proc/cpuinfo`
```
[...]
processor       : 184
cpu             : POWER8E (raw), altivec supported
clock           : 2161.000000MHz
revision        : 2.1 (pvr 004b 0201)
timebase        : 512000000
platform        : PowerNV
model           : 8247-22L
machine         : PowerNV 8247-22L
firmware        : OPAL v3
```
There is may be other solution, If you have a better idea, just tell me.

Adding support for ppc64le PowerNV (non-virtualized aka Bare-Metal)

---

usr/share/rear/output/default/94_grub2_rescue.sh

"`=`" is missing between `--set `and `root`

Correct typo in 94_grub2_rescue.sh

---

usr/share/rear/finalize/Linux-ppc64/22_install_grub2.sh
usr/share/rear/finalize/Linux-ppc64le/22_install_grub2.sh

PowerPC bootlist supports a maximum of 5 entries. If more than 5 paths is given, bootlist is not set.
This is particulary true when boot device is multipathed.
`bootlist -m normal /dev/mapper/mpatha` will failed if `mpatha` has more than 5 paths.
=> We need to check and limit to 5 the number of path given to the bootlist command.

Limit ppc64/ppc64le bootlist parameter to 5 entries

---

usr/share/rear/layout/save/GNU/Linux/20_partition_layout.sh

RHEL 7 is naming multipath partition in a `mpath[1-9] `style.
for example : `/dev/mpath1 `instead of `/dev/mpathp1` or `/dev/mpath-part1 `etc ...
Because of that, `20_partition_layout.sh `failed to detect mpath partition.

BUG: 20_partition_layout.sh : Multipath partition not found in rhel7.2

---

usr/share/rear/verify/NETFS/default/05_start_required_daemons.sh

use plain 'rpcinfo -p'
see https://github.com/rear/rear/issues/889
make it no longer fatal when rpc.statd is unavailable
see https://github.com/rear/rear/issues/870
removed all references to FD8
see https://github.com/rear/rear/issues/887
and https://github.com/rear/rear/pull/874
first steps to be prepared for 'set -eu'
see https://github.com/rear/rear/wiki/Coding-Style

overhauled 05_start_required_daemons.sh

---

usr/share/rear/skel/default/etc/scripts/system-setup

Moved rear invocation so that the assignment return code is not interfering with rear return code processing. I assume the original intention was to only provide the reboot option if rear reports success.

correcting rear return code handling

---

usr/share/rear/layout/prepare/GNU/Linux/13_include_filesystem_code.sh

try to create the filesystem with initially correct UUID (https://github.com/rear/rear/issues/851)
but when 'mkfs -U' fails (e.g. on RHEL 5, https://github.com/rear/rear/issues/890)
assume it failed because of missing support for '-U'
and then fall back to the old way before issue 851
i.e. using mkfs without '-U' plus 'tunefs -U'

fall back to old way when 'mkfs -U' fails (issue 890 and issue 851)

---

usr/share/rear/finalize/Linux-i386/21_install_grub.sh
usr/share/rear/finalize/default/01_prepare_checks.sh

Regarding installing GRUB Legacy as bootloader
overhauled finalize/Linux-i386/21_install_grub.sh and
improved finalie/default/01_prepare_checks.sh
(see issue https://github.com/rear/rear/issues/895)
It is still not fully reliably installing the right bootloader:
When GRUB 2 is installed in addition To GrubLegacy
it still prefers to install GRUB 2 as bootloader
even if the BOOTLOADER variable tells "GRUB"
(which means GRUB Legacy).
I.e. further work is needed...

First steps towards more reliably installing the right bootloader

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh

Tries to fix https://github.com/rear/rear/commit/0ec871676b7cdc52461574200c8a54867d0cfb37
by changing 40-start-udev-or-load-modules.sh
so taht the code that always loads modules
in /etc/modules is always run.

always load modules in /etc/modules (issue905 and others)

---

usr/share/rear/finalize/Linux-ppc64/22_install_grub2.sh
usr/share/rear/finalize/Linux-ppc64le/22_install_grub2.sh

"$" seems to be missing when checking NOBOOTLOADER variable.
Please confirm.

Typo in 22_install_grub2.sh for ppc64/ppc64le

---

usr/share/rear/conf/default.conf
usr/share/rear/format/USB/default/30_format_usb_disk.sh

ask user for EFI partition size on USB disk

---

usr/share/rear/backup/NETFS/default/50_make_backup.sh
usr/share/rear/conf/default.conf
usr/share/rear/restore/NETFS/default/40_restore_backup.sh

Implemented enhancement https://github.com/rear/rear/issues/904
BACKUP_PROG_COMPRESS_OPTIONS is now an array
so that one can use it to provide more complex values.
E.g. to override the gzip default compression level (-6)
via the tar '-I' option like
BACKUP_PROG_COMPRESS_OPTIONS=( -I 'gzip -9 -n -c' )
But using it with command options (as in 'gzip -9')
fails with tar versions before 1.27 with a tar error
message like "gzip -9: Cannot exec" because only
since tar version 1.27 tar supports passing command
line arguments to external commands, see
http://git.savannah.gnu.org/cgit/tar.git/plain/NEWS?id=release_1_27

use BACKUP_PROG_COMPRESS_OPTIONS as an array (issue904)

---

usr/share/rear/backup/default/00_valid_backup_methods.sh

Check what BACKUP methods are mentioned
in the form BACKUP=method in default.conf
and error out when a BACKUP method is not found
this way in default.conf to ensure that the user cannot
specify a non-working BACKUP in /etc/rear/local.conf
and to ensure that each implemented BACKUP method
is mentioned in default.conf to have a minimum documentation
about what BACKUP methods are implemented in rear
see https://github.com/rear/rear/issues/914
and https://github.com/rear/rear/issues/159

error out for unknown BACKUP method (issue914)

---

usr/share/rear/output/PXE/default/82_copy_to_net.sh
usr/share/rear/output/RAMDISK/Linux-i386/90_copy_ramdisk.sh
usr/share/rear/output/default/95_copy_result_files.sh

see https://github.com/rear/rear/issues/931
and
some other fixes:
- first steps to be prepared for 'set -e' which means
replaced COMMAND ; StopIfError
with COMMAND || Error
- in output/PXE/default/82_copy_to_net.sh
error out in case of "Problem transferring..."
for each result file (before it only errors out
in case of "Problem transferring..." for the last
result file because the Errot was after the for loop)

error out instead of bugerror for not implemented URI schemes

---

usr/share/rear/prep/NETFS/default/40_automatic_exclude_recreate.sh

see https://github.com/rear/rear/issues/926
and used better naming for the variables

make test where backup directory is mounted more fail safe

---

usr/share/rear/conf/default.conf
usr/share/rear/output/default/94_grub2_rescue.sh

see https://github.com/rear/rear/issues/938
starting at https://github.com/rear/rear/issues/938#issuecomment-234899163
In its current state it somewhat works for me with
<pre>
GRUB_RESCUE=y
GRUB_RESCUE_PASSWORD="rear"
GRUB_SUPERUSER="root"
</pre>
as follows
<pre>
Relax-and-Recover 1.18 / Git
Using log file: /root/rear/var/log/rear/rear-f121.log
Creating disk layout
Creating root filesystem layout
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Creating initramfs
Making ISO image
Wrote ISO image: /root/rear/var/lib/rear/output/rear-f121.iso (38M)
Setting up GRUB_RESCUE: Adding Relax-and-Recover rescue system to the local GRUB 2 configuration.
Modifying local GRUB 2 configuration.
Finished GRUB_RESCUE setup: Added 'Relax-and-Recover' GRUB 2 menu entry. …

first steps to make GRUB_RESCUE work for GRUB2 on SLES12

---

doc/rear.8
doc/rear.8.adoc
doc/user-guide/03-configuration.adoc

fix manpage and other documentation
regarding cifs credentials filename that
should not be a dot file but a normal filename
see https://github.com/rear/rear/issues/924

fix in documentation cifs credentials file name

---

usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_subvolumes_code.sh

exclude btrfs subvolume @/.snapshots/1/snapshot/var/lib/machines
from being created by 'btrfs subvolume create'
to make rear recover work on SLES12-SP2
because otherwise 'snapper/installation-helper --step '
would fail if that subvolume already exists
see https://github.com/rear/rear/issues/944

first step to make rear recover work on SLES12-SP2

---

usr/share/rear/output/default/94_grub2_rescue.sh

Hello all,
I've managed to find (hopefully) universal solution to boot ReaR on UEFI based systems without endless (and as I've learned pointless) chasing after grub.cfg when **GRUB_RESCUE=y**
The idea behind this pull request is simple:
_Don't modify grub.cfg but rather create separate UEFI boot entry._
**UEFI "Relax-and-Recover" boot entry motivation:**
If UEFI boot is in use, we will not modify grub.cfg, but setup "Relax-and-Recover" entry in UEFI boot menu instead. This looks to be simplest and safest approach since finding out what mechanisms were used to boot OS in UEFI mode, looks to be near to impossible.
One could argue that efibootmgr/efivars can tell you, however this entry is not mandatory and OS could be booted using default values or startup.nsh.
Once UEFI loads Grub2 hell …

GRUB_RESCUE=y now works with UEFI based systems

---

usr/share/rear/conf/default.conf
usr/share/rear/output/default/94_grub2_rescue.sh

and some changes to prepare 94_grub2_rescue.sh
for set -eu (cf. https://github.com/rear/rear/issues/700)
this enhances https://github.com/rear/rear/pull/954

document that GRUB_RESCUE_USER is not supported for UEFI

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/00-functions.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh

Hi guys, 
This should be fix for #958. (in case we confirm that **udevadm trigger** indeed doesn't rename devices under systemd)
Hope it helps.
V.

Enhanced udev device reload for systemd.

---

usr/share/rear/lib/network-functions.sh

I've used more standard **grep -i** (instead of IGNORECASE) as mawk (used e.g. on Debian) doesn't know IGNORECASE. Which resulted this function not to find appropriate device.

get_device_by_hwaddr made a bit more universal

---

packaging/debian/changelog
packaging/debian/control
usr/share/rear/conf/default.conf

@jsmeix 
This should solve #828 and #696. In this pull priority is given to the `xorrisofs` binary over the other binaries (`mkisofs` and `genisoimage`).
Let me know what you guys think.
Cheers.

Improve debian packaging

---

usr/share/rear/prep/GNU/Linux/21_include_dhclient.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/58-start-dhclient.sh

In default.conf we have comment:
> Say "y", "Yes" (or any not empty string) to enable static networking (overrules USE_DHCLIENT):
This is currently not true, because doesn't matter how is USE_STATIC_NETWORKING set, dhcp configuration will be triggered in rear recover.

USE_STATIC_NETWORKING now really overrides USE_DHCLIENT.

---

usr/share/rear/layout/prepare/GNU/Linux/13_include_mount_subvolumes_code.sh
usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh

Now snapper's own subvolumes are excluded from being
automatically recreated by listing them only as comments in
disklayout.conf during "rear mkbackup" (via 23_filesystem_layout.sh)
and furthermore if such subvolumes are active in disklayout.conf
they are skipped during "rear recover" plus LogPrint info for the user
(via 13_include_mount_subvolumes_code.sh).

Make it safe against wrong btrfs subvolumes on sles12 issue963

---

usr/share/rear/conf/default.conf

i.e. no longer TMPDIR setting in default.conf
(only manually by te user if needed in local.conf)
issue https://github.com/rear/rear/issues/968

make TMPDIR work in compliance with Unix standards

---

usr/share/rear/backup/default/01_pre_backup_script.sh
usr/share/rear/backup/default/99_post_backup_script.sh
usr/share/rear/conf/default.conf

Hello,
Those changes add the capacity in rear to stop/start some services or run some required tasks previous to run backup (just like those exist for recovery), this can be useful in some scenarios if, for example, a small database that can be stopped and it's data will be consistent after OS recovery without human intervention.
I've tested and forced error between pre and post to check correct behaviour of Exit Tasks in case of any error during backup if, for example, some service stopped in PRE can be started by Exit Tasks array.
Following changed:
<pre>
if test "$PRE_BACKUP_SCRIPT" ; then
Log "Running PRE_BACKUP_SCRIPT '${PRE_BACKUP_SCRIPT[@]}'"
AddExitTask "${POST_BACKUP_SCRIPT[@]}"
eval "${PRE_BACKUP_SCRIPT[@]}"
fi
</pre>
<pre>
if test "$POST_BACKUP_SCRIPT" ; then
Log "Running …

Added PRE-POST backup scripts

---

usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf

Added SLE12-SP2-btrfs-example.conf
with POST_RECOVERY_SCRIPT that implements btrfs quota
setup for snapper if that is used in the original system,
see https://github.com/rear/rear/issues/999

Added SLE12-SP2-btrfs-example.conf (issue999)

---

doc/rear-release-notes.txt
doc/rear.8
doc/rear.8.adoc
doc/user-guide/03-configuration.adoc
usr/share/rear/conf/default.conf

See https://github.com/rear/rear/issues/974
in particular see
https://github.com/rear/rear/issues/974#issuecomment-248895101
Additionally I dared to enhance the general comment
in default.conf about how to use our variable types
(as far as I see BACKUP_PROG_CRYPT_ENABLED
has ternary semantics because both is_true and is_false
is used for that variable).

Better documentation for BACKUP_TYPE=incremental

---

usr/share/rear/build/GNU/Linux/63_simplify_systemd_reboot_halt_poweroff_shutdown.sh

The new script
build/GNU/Linux/63_simplify_systemd_reboot_halt_poweroff_shutdown.sh
replaces in case of systemd in the rear recovery system
/bin/reboot /bin/halt /bin/poweroff and /bin/shutdown
by scripts that basically do
"umount -a" and "systemctl --force [reboot halt poweroff]"
to make reboot halt poweroff and shutdown work simpler
and more fail-safe, see https://github.com/rear/rear/issues/953

Simplify reboot halt poweroff and shutdown in case of systemd

---

usr/share/rear/backup/DUPLICITY/default/50_make_duplicity_backup.sh
usr/share/rear/lib/mkrescue-functions.sh

Non-ASCII characters (e.g. UTF-8 characters) in scripts
are not wanted, see
https://github.com/rear/rear/issues/1018#issuecomment-251385721
Non-ASCII characters (e.g. UTF-8 characters) in scripts
might even cause failures on systems that do not
support non-POSIX/non-C locales (like UTF-8),
e.g. in the recovery system during "rear recover".
Currently non-ASCII characters were only used in
comments in the scripts but even that makes it at least
hard to read the comments in a non-ASCII locale
in particular because it is impossible to know
what encoding is meant by a sequence of bytes
that is a non-ASCII character, cf.
https://en.opensuse.org/SDB:Plain_Text_versus_Locale

Fixed non ASCII characters in scripts.

---

usr/share/rear/layout/save/default/45_check_bootloader_files.sh
usr/share/rear/prep/default/50_guess_bootloader.sh

Since commit d15591e65461dfa43df6b7dbf23015d8e5598648, POWER arch based system is not able to run mkrescue.
=> `ERROR: BUG BUG BUG!  Unknown bootloader () - ask for sponsoring to get this fixed`
Here is a proposal to fix this.

fix check_bootloader for POWER arch

---

usr/share/rear/finalize/SUSE_LINUX/ppc64/50_rebuild_initramfs.sh

Need to rebuild initramfs after restoring to a new Hardware.
I copy the script file from finalize/SUSE_LINUX/i386/17_rebuild_initramfs.sh to finalize/SUSE_LINUX/ppc64/50_rebuild_initramfs.sh to limit my change to ppc64 architecture only. 
But I think we could put this script directly under finalize/SUSE_LINUX as it is the same mkinitrd command for all the HW architecture.
It seems we need to change the order from 17_ to 50_ to avoid failure during mkinitrd command.

Rebuild initrd after migration (for SUSE_LINUX PPC64)

---

doc/user-guide/04-scenarios.adoc
doc/user-guide/10-integrating-external-backup.adoc
usr/share/rear/backup/BORG/default/10_load_init_archives.sh
usr/share/rear/backup/BORG/default/50_make_backup.sh
usr/share/rear/backup/BORG/default/80_prune_old_backups.sh
usr/share/rear/conf/default.conf
usr/share/rear/prep/BORG/default/10_prep_borg.sh
usr/share/rear/restore/BORG/default/30_load_archives.sh
usr/share/rear/restore/BORG/default/40_restore_backup.sh

Spelling corrections
BORG_* variables renamed to BORGBACKUP_* to avoid collisions with Borg.
When ReaR uses Borg as back end, it defaults to "none" compression to be aligned with Borg defaults.

Applied corrections discussed in #1037

---

usr/share/rear/build/GNU/Linux/10_copy_as_is.sh
usr/share/rear/layout/save/default/45_check_bootloader_files.sh

When _/etc/sysconfig/bootloader_ have LOADER_TYPE=”grub2-efi", ReaR ends up with **"BUG! Unknown bootloader"**.
Related to issue: #1038

Fixed bug, with LOADER_TYPE=”grub2-efi"

---

usr/share/rear/backup/BORG/default/50_make_backup.sh
usr/share/rear/conf/default.conf

Improvements in default compression handling discusses in #1041

BORGBACKUP_COMPRESSION now handles Borg compression defaults correctly

---

doc/user-guide/04-scenarios.adoc
usr/share/rear/backup/BORG/default/10_load_init_archives.sh
usr/share/rear/backup/BORG/default/80_prune_old_backups.sh
usr/share/rear/conf/default.conf

- borg as back end, now accepts options for repository encryption.
- prune now only affects archives with BORGBACKUP_ARCHIVE_PREFIX

Borg as back end, now accepts options for repository encryption (take 2)

---

usr/share/rear/finalize/SUSE_LINUX/ppc64/200_install_yaboot.sh
usr/share/rear/output/ISO/Linux-ppc64/300_create_yaboot.sh

Default LVM layout in SLES11sp4 put /boot in LVM (`/boot` is part of `/` which is a LV).
In this configuration, LILO does not create `/etc/yaboot.conf file`. (Yaboot configuration is directly created in the PPC PReP Boot Partition.)
Without `/etc/yaboot.conf`:   
+ ReaR ISO DVD is not bootable, 
+ and bootloader is not re-created at the end of the restoration process.
I propose the following changes to let LILO creates the bootloader even if `/etc/yaboot.conf` does not exist.
It seems those issues #820 #817 has the problem described here. (Sles11 with default LVM layout => no `/etc/yaboot.conf`).

Allow yaboot bootlader creation even when yaboot.conf is missing (sles11 ppc64 with LVM)

---

usr/share/rear/backup/NETFS/default/400_create_include_exclude_files.sh

In case we are running ```MANUAL_INCLUDE``` mode, there is no need
to add volumes, NOT explicitly excluded via ```EXCLUDE_MOUNTPOINTS```.
This will only add volumes added to ```BACKUP_PROG_INCLUDE``` to ```backup-include.txt```.
As this change is made in ```backup/NETFS/default/400_create_include_exclude_files.sh```, this change will also affect backup types BORG and RSYNC, as these also link to this file.
See also issue #1019.

do not list directories to backup twice in MANUAL_INCLUDE mode

---

usr/share/rear/layout/prepare/GNU/Linux/130_include_filesystem_code.sh

See #1065.
If Self-Describing Metadata (CRC) is enabled on boot filesystem, and `xfs_admin` updates filesystem UUID, this sets incompatible flag (IF) to prevent older kernels to mount this filesystem.
Site effect of IF is that grub-install (resp. grub-probe) fails with _unknown filesystem_ message, which prevents ReaR to correctly install boot loader.

Patch for newer versions of XFS with enabled CRC

---

doc/rear.8
doc/rear.8.adoc
doc/user-guide/03-configuration.adoc
usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/conf/default.conf
usr/share/rear/output/default/950_copy_result_files.sh
usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
usr/share/rear/restore/NETFS/default/400_restore_backup.sh
usr/share/rear/verify/NETFS/default/550_check_backup_archive.sh

See https://github.com/rear/rear/issues/1069
I introduced the new RESTORE_ARCHIVES() array that
contains the restore input files for 400_restore_backup.sh
I did major changes in 400_restore_backup.sh
so that it now launches a separated restore subshell together
with the progress stuff for each element in RESTORE_ARCHIVES.
Together with changes in 070_set_backup_archive.sh
it does now already restore real incremental backups
(i.e. one full backup plus several incremental backups).
For example assume during several "rear mkbackup"
the backup directory contains:
<pre>
2016-11-15-1502-F.tar.gz
2016-11-16-1057-I.tar.gz
2016-11-16-1100-I.tar.gz
2016-11-17-1324-F.tar.gz
2016-11-17-1348-I.tar.gz
2016-11-17-1354-I.tar.gz
2016-11-17-1451-I.tar.gz
</pre>
then "rear recover" will restore those …

Initial support for multiple restore archives (issue1069)

---

usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh

Now e.g. during "rear mkbackup"
a code line in /usr/share/rear/path/to/foo.sh like
<pre>
BugError "Unexpected bar"
</pre>
would show this to the user:
<pre>
ERROR: 
====================
BUG in /usr/share/rear/path/to/foo.sh:
'Unexpected bar'
--------------------
Please report this issue at https://github.com/rear/rear/issues
and include the relevant parts from /var/log/rear/rear-xxx.log
preferably with full debug information via 'rear -d -D mkbackup'
====================
</pre>

Improved BugError message with BASH_SOURCE and WORKFLOW

---

usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/prep/BACULA/default/500_check_BACULA_bconsole_results.sh
usr/share/rear/prep/BAREOS/default/500_check_BAREOS_bconsole_results.sh
usr/share/rear/verify/BACULA/default/050_check_requirements.sh
usr/share/rear/verify/BAREOS/default/050_check_requirements.sh

Removed EXIT_CODE usage from and for Error functions
(namely the Error and BugError functions) because
in this case rear kills itself that results exit code 143
so that setting EXIT_CODE for Error functions is useless,
see https://github.com/rear/rear/issues/1076

Removed EXIT_CODE usage in case of Error functions.

---

doc/user-guide/02-getting-started.adoc
doc/user-guide/03-configuration.adoc
doc/user-guide/04-scenarios.adoc
doc/user-guide/05-integration.adoc
doc/user-guide/06-layout-configuration.adoc
doc/user-guide/09-design-concepts.adoc
doc/user-guide/10-integrating-external-backup.adoc
usr/share/rear/backup/default/005_valid_backup_methods.sh
usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
usr/share/rear/build/GNU/Linux/610_verify_and_adjust_udev_systemd.sh
usr/share/rear/conf/Linux-ia64.conf
usr/share/rear/conf/default.conf
usr/share/rear/conf/examples/SLE11-SLE12-SAP-HANA-UEFI-example.conf
usr/share/rear/conf/examples/SLE12-btrfs-example.conf
usr/share/rear/init/default/030_update_recovery_system.sh
usr/share/rear/init/default/050_check_rear-recover_mode.sh
usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/prepare/GNU/Linux/130_include_mount_subvolumes_code.sh
usr/share/rear/lib/format-workflow.sh
usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
usr/share/rear/output/default/940_grub_rescue.sh
usr/share/rear/prep/GNU/Linux/280_include_systemd.sh
usr/share/rear/prep/README
usr/share/rear/prep/RSYNC/default/150_check_rsync_protocol_version.sh
usr/share/rear/prep/default/320_include_uefi_env.sh
usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
usr/share/rear/rescue/GNU/Linux/990_sysreqs.sh
usr/share/rear/rescue/NSR/default/450_prepare_networker_startup.sh
usr/share/rear/restore/default/990_move_away_restored_files.sh

We use 'ReaR' as official abbreviation for Relax-and-Recover
and 'rear' to point to RPM packages or scripts, see
https://github.com/rear/rear/issues/1086 and
https://github.com/rear/rear/issues/1033

Fixed ReaR versus rear spelling.

---

usr/sbin/rear

Added -C option to source additional config files
is useful in general and in particular it is
needed as prerequirement to implement
support for "Multiple Backup Methods", see
https://github.com/rear/rear/issues/1088

Added -C option to source additional config files

---

usr/sbin/rear
usr/share/rear/backup/NETFS/default/400_create_include_exclude_files.sh
usr/share/rear/backup/readme
usr/share/rear/init/default/050_check_rear-recover_mode.sh
usr/share/rear/lib/finalizeonly-workflow.sh
usr/share/rear/lib/layoutonly-workflow.sh
usr/share/rear/lib/restoreonly-workflow.sh
usr/share/rear/output/default/950_copy_result_files.sh
usr/share/rear/rescue/default/910_copy_logfile.sh
usr/share/rear/restore/default/050_remount_async.sh
usr/share/rear/restore/default/995_remount_sync.sh
usr/share/rear/restore/readme

Now there is a new restoreonly workflow
that is a part of the (unchanged) recover workflow
namely the part that does only restore a backup,
see https://github.com/rear/rear/issues/987
which is a prerequirement for
https://github.com/rear/rear/issues/1088
"support multiple backups".

Split restoreonly workflow from recover workflow

---

usr/share/rear/finalize/default/900_remount_sync.sh
usr/share/rear/restore/default/050_remount_async.sh
usr/share/rear/restore/default/995_remount_sync.sh

Remounting all what is mounted below /mnt/local
with sync option is no longer needed when systemd is used
because when systemd is used reboot, halt, poweroff,
and shutdown are replaced by scripts that do umount
plus sync to safely shut down the recovery system,
see https://github.com/rear/rear/pull/1011
and https://github.com/rear/rear/issues/1097
Furthermore remounting with sync option could become
in practice a major annoyance because it makes writing
anything below /mnt/local basically unusable slow,
see https://github.com/rear/rear/issues/1097

Skip remount sync when systemd is used (issue1097)

---

usr/share/rear/restore/default/050_remount_async.sh

Remounting with async option is not needed
when systemd is used because when systemd
is used remounting with sync option is skipped and
to aviod needless operations remounting with async
option is also skipped, see
https://github.com/rear/rear/issues/1097
and
https://github.com/rear/rear/pull/1099

Skip remount async when systemd is used

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/backup/RSYNC/default/500_make_rsync_backup.sh
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/progresssubsystem.nosh
usr/share/rear/restore/NETFS/default/400_restore_backup.sh
usr/share/rear/restore/RBME/default/400_restore_backup.sh
usr/share/rear/restore/RSYNC/default/400_restore_rsync_backup.sh

Added support for a new variable MESSAGE_PREFIX
that is by default empty so that by default nothing changes
but the user can set it e.g. to MESSAGE_PREFIX="PID$$: "
to get the messages of ReaR output functions
prefixed with ${MESSAGE_PREFIX}.
Added support for a new variable PROGRESS_MODE that
can be PROGRESS_MODE="ANSI" (default/fallback behaviour)
or PROGRESS_MODE="plain" which outputs the same messages
as in default 'ANSI' mode but without ANSI escape sequences.
Added support for a new variable PROGRESS_WAIT_SECONDS
that specifies the number of seconds between progress messages
that are aoutput while a longer task (usually backup or restore) runs.
The default/fallback is 1 second to keep the current behaviour.
Setting at least MESSAGE_PREFIX="PID$$: "
and PROGRESS_MODE="plain" is …

Enhance logging and progress for running in parallel

---

usr/sbin/rear
usr/share/rear/conf/default.conf
usr/share/rear/lib/progresssubsystem.nosh

New SIMULTANEOUS_RUNNABLE_WORKFLOWS variable
lists those workflows that are allowed to run simultaneously
but cannot use LOGFILE.lockless as the LOCKLESS_WORKFLOWS.
Instead the SIMULTANEOUS_RUNNABLE_WORKFLOWS
get a LOGFILE with PID because simultaneously runnable
workflows require unique logfile names, see
https://github.com/rear/rear/issues/1102
Additional enhancements and fixes in usr/sbin/rear:
CONFIG_APPEND_FILES that are not in CONFIG_DIR
get added to COPY_AS_IS to get them copied into the
recovery system.
Moved progress subsystem enablement
(i.e. source $SHARE_DIR/lib/progresssubsystem.nosh)
and enablement of debug output of the progress pipe
after the user config files had been read, because
otherwise a PROGRESS_MODE setting in a
user config file is not used when defining the …

Allow multiple mkbackuponly or restoreonly running in parallel

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

Corrected issue #1106: "Extended partition not detected with util-linux 2.26-rc1"

Corrected issue #1106

---

usr/share/rear/conf/default.conf
usr/share/rear/format/USB/default/200_check_usb_layout.sh
usr/share/rear/format/USB/default/300_format_usb_disk.sh

To support partitioning and formatting a huge medium
by the format workflow there are new variables:
USB_DEVICE_FILESYSTEM specifies the filesystem
to use when formatting a medium via the format workflow.
USB_DEVICE_FILESYSTEM_PERCENTAGE specifies the
percentage of the whole medium that is used for ReaR partitions
when formatting a medium via the format workflow.
For details see conf/default.conf
Cf. https://github.com/rear/rear/issues/1105

Support partitioning and formatting huge USB devices

---

usr/sbin/rear
usr/share/rear/conf/default.conf
usr/share/rear/lib/_input-output-functions.sh

See
https://github.com/rear/rear/issues/1088#issuecomment-265507663
Now when rear errors out it shows the right logfile name, e.g.:
<pre>
Relax-and-Recover 1.19 / Git
Using log file: /root/rear/var/log/rear/rear-f79.16621.log
16621: ERROR: 
====================
BUG in /root/rear/usr/share/rear/init/default/030_update_recovery_system.sh:
'Test Error'
--------------------
Please report this issue at https://github.com/rear/rear/issues
and include the relevant parts from /root/rear/var/log/rear/rear-f79.16621.log
preferably with full debug information via 'rear -d -D mkbackuponly'
====================
Aborting due to an error, check /root/rear/var/log/rear/rear-f79.16621.log for details
Terminated
</pre>
The fix is mainly in usr/sbin/rear and it is a bit ugly
but from my point of view the …

Fix LOGFILE setting

---

usr/share/rear/conf/default.conf

Added a explanatory comment to default.conf
what BACKUP_PROG_ARCHIVE to use
to get the same full backup file name for BACKUP_TYPE=""
as what would be used for BACKUP_TYPE=incremental
and/or BACKUP_TYPE=differential, see
https://github.com/rear/rear/issues/1074

Explain date prefixed backup archive

---

usr/share/rear/wrapup/rescue/default/600_add_galaxy_group.sh

Removed dead wrapup script
wrapup/rescue/default/600_add_galaxy_group.sh
the identical and right one is
rescue/GALAXY10/default/600_add_galaxy_group.sh
see https://github.com/rear/rear/issues/1124

Removed dead wrapup script add_galaxy_group

---

usr/sbin/rear
usr/share/rear/lib/finalizeonly-workflow.sh
usr/share/rear/lib/help-workflow.sh
usr/share/rear/lib/layoutonly-workflow.sh

Do not show experimental workflows in help workflow
namely layoutonly and finalizeonly and let the
help workflow exit with zero exit code, cf
https://github.com/rear/rear/issues/1089#issuecomment-266984698
Additionally suppress some messages in usr/sbin/rear
in case of the help workflow namely the verbose
LogPrint whereto the log file gets copied
"Saving $RUNTIME_LOGFILE as $LOGFILE"
and the final LogToSyslog.

do not show experimental workflows in rear help workflow

---

doc/rear.8
doc/rear.8.adoc
doc/user-guide/03-configuration.adoc
usr/share/rear/conf/default.conf

More explanatory documentation regarding OUTPUT_URL=null
see https://github.com/rear/rear/issues/734
Additionally more explanatory documentation in default.conf
about proper usage of quoting for BACKUP_PROG_INCLUDE
and BACKUP_PROG_EXCLUDE which is crucial to get
the intended results.

Fix documentation regarding OUTPUT_URL=null

---

usr/sbin/rear

The checklayout workflow is special because
it sets EXIT_CODE=1 when the disk layout has changed
or when configuration files have changed
but that exit code 1 is no error but meant as a signal
that things have changed which require a new ISO image
so that users can run "rear checklayout || rear mkrescue"
see https://github.com/rear/rear/issues/564

Special case syslog message for checklayout workflow

---

doc/user-guide/11-multiple-backups.adoc
usr/share/rear/conf/default.conf
usr/share/rear/conf/examples/RHEL6-NETFS-of-NBU-master-example.conf
usr/share/rear/conf/examples/SLE11-SLE12-SAP-HANA-UEFI-example.conf

Fixed BACKUP_PROG_EXCLUDE and BACKUP_PROG_INCLUDE
example values in multiple backups documentation
and in example config files
(related to https://github.com/rear/rear/issues/1068)

Fixed example BACKUP_PROG_EXCLUDE and BACKUP_PROG_INCLUDE values

---

usr/share/rear/lib/format-workflow.sh

Simulation mode for the format workflow should work
even without a device specified
see https://github.com/rear/rear/issues/1098

Implement simulation mode for format workflow

---

doc/rear.8
doc/rear.8.adoc
doc/user-guide/03-configuration.adoc
usr/share/rear/conf/default.conf
usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh

Incremental or differential backup is currently
only known to work with BACKUP_URL=nfs://.
Other BACKUP_URL schemes may work but at least
BACKUP_URL=usb:///... is known not to work with
incremental or differential backup, see
https://github.com/rear/rear/issues/1141
and
https://github.com/rear/rear/issues/1145

Forbid BACKUP_URL=usb for BACKUP_TYPE=incremental/differential

---

doc/user-guide/01-introduction.adoc
doc/user-guide/02-getting-started.adoc

Aligned info about supported distros
in the documentation to what there is
in the current (i.e. ReaR 1.19) release notes.
If the supported distros changes for ReaR 2.0
that documentation needs to be adapted, see
https://github.com/rear/rear/issues/1073#issuecomment-270091799

align supported distros documentation (issue1073)

---

usr/share/rear/skel/BAREOS/var/run/bareos/.gitignore

we are using rear + bareos in our data center.
executing a test recovery revealed that bareos was requesting /var/run/bareos as a system's directory to exist. We've added it to the skel and it works now. We like to share this improvement.

Bareos support: add missing directory /var/run/bareos in recovery system

---

doc/rear.8
doc/rear.8.adoc
doc/user-guide/03-configuration.adoc
usr/share/rear/conf/default.conf
usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
usr/share/rear/prep/USB/default/060_set_usb_device.sh
usr/share/rear/verify/USB/NETFS/default/540_choose_backup_archive.sh

The new config variable USB_SUFFIX
specifies the last part of the backup directory on the USB medium.
When USB_SUFFIX is unset or empty, backup on USB works
in its current default mode (i.e. backward compatible)
which means multiple timestamp backup directories
plus automated rescue environments and backups cleanup
via USB_RETAIN_BACKUP_NR.
When USB_SUFFIX is set, backup on USB works
in compliance with how backup on NFS works
which means a fixed backup directory and
no automated removal of any stuff
(regardless of USB_RETAIN_BACKUP_NR).
When  backup on USB behaves as backup on NFS
(i.e. when USB_SUFFIX is set) multiple backups and
incremental/differential backups also work on USB.
See
https://github.com/rear/rear/issues/1164
https://github.com/rear/rear/issues/1160 …

Align backup on USB with backup on NFS

---

usr/share/rear/conf/default.conf
usr/share/rear/prep/BAREOS/default/450_check_BAREOS_client_configured.sh
usr/share/rear/prep/BAREOS/default/500_check_BAREOS_bconsole_results.sh
usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
usr/share/rear/verify/BAREOS/default/050_check_requirements.sh
usr/share/rear/verify/BAREOS/default/100_start_bareos-fd.sh

Tested with old and new configuration layout on Centos7 in our CI environment.

Adapted to Bareos new (since 16.2) configuration schema. Fixes #1077

---

usr/share/rear/verify/USB/NETFS/default/540_choose_backup_archive.sh

An "Abort" choice in any 'select' dialog is useless
because simple [Ctrl]+[C] also aborts ReaR.
Cf. https://github.com/rear/rear/issues/1166
With that change recovery with backup on USB
and aborting at the USB backup selection dialog
works as follows:
<pre>
RESCUE e205:~ # rear -d -D recover
...
Backup archive /tmp/rear.JAM8egDNTgZlexj/outputfs/rear/e205/20170117.1311/backup.tar.gz detected.
Backup archive /tmp/rear.JAM8egDNTgZlexj/outputfs/rear/e205/20170117.1324/backup.tar.gz detected.
Backup archive /tmp/rear.JAM8egDNTgZlexj/outputfs/rear/e205/20170117.1335/backup.tar.gz detected.
Select a backup archive.
1) 20170117.1311
2) 20170117.1324
3) 20170117.1335
#? 4
Invalid choice 4, try again (or press [Ctrl]+[C] to abort).
#? ^C
2017-01-18 09:22:29.979923804 Running exit tasks.
2017-01-18 …

Drop useless Abort choice in USB backup selection dialog

---

usr/share/rear/finalize/SUSE_LINUX/i386/170_rebuild_initramfs.sh

Typo in `rebuild_initramfs` for PPC64 arch which prevent bootloader and initrd creation during recovery.

BUG: Typo in rebuild_initramfs for PPC64

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/Debian/i386/170_rebuild_initramfs.sh
usr/share/rear/finalize/Fedora/i386/170_rebuild_initramfs.sh
usr/share/rear/finalize/SUSE_LINUX/i386/170_rebuild_initramfs.sh
usr/share/rear/verify/GNU/Linux/260_recovery_storage_drivers.sh

Warn if initrd cannot be created when udev is not there, see
https://github.com/rear/rear/pull/1171#issuecomment-274442700
and some more code cleanup, see
https://github.com/rear/rear/pull/1176#issuecomment-274785858

Warn if initrd cannot be created and code cleanup (issue 1171)

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/800_create_isofs.sh
usr/share/rear/output/ISO/Linux-ia64/300_create_bootimg.sh
usr/share/rear/output/ISO/Linux-ppc64/300_create_yaboot.sh
usr/share/rear/output/ISO/Linux-ppc64/310_create_grub2.sh
usr/share/rear/output/ISO/Linux-ppc64/800_create_isofs.sh
usr/share/rear/output/ISO/Linux-ppc64le/300_create_grub2.sh
usr/share/rear/output/ISO/Linux-ppc64le/800_create_isofs.sh
usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
usr/share/rear/output/RAMDISK/Linux-i386/900_copy_ramdisk.sh
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
usr/share/rear/output/USB/Linux-i386/830_copy_kernel_initrd.sh
usr/share/rear/output/default/940_grub2_rescue.sh
usr/share/rear/output/default/940_grub_rescue.sh
usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh

Now pack/GNU/Linux/900_create_initramfs.sh
first tries to create initrd.xz with the newer xz-lzma compression and
if that fails it falls back to creating initrd.cgz with gzip compression.
Because now two ReaR initrd filenames are used
initrd.xz versus initrd.cgz
the global variable REAR_INITRD_FILENAME is set
and used in various subsequent scripts where before
the filename initrd.cgz was hardcoded.
See https://github.com/rear/rear/issues/1142

New REAR_INITRD_COMPRESSION to specify the compression of the recovery system initrd

---

usr/share/rear/layout/save/GNU/Linux/280_multipath_layout.sh

If multipathed devices are detected, add the content of `/etc/multipath` directory
into the ramdisk. This avoids some crash during recovery when multipathed
devices were renamed in `/etc/multipath/bindings.`
If no `/etc/multipath/binding` file is present in the ramdisk during recovery, system will detect and named multipath disk as `/dev/mapper/multipaha`, while rear trying to find a disk named `/dev/mapper/rootdisk` (this disk was named `rootdisk` in `/etc/multipath/binding` during backup.)
**=> Tested successfully on redhat7.2 (ppc64le)**
example of cutomized `/etc/multipath/binding` file where `mpatha` were renamed in `rootdisk`:
```
#
#
rootdisk 3600507680c82004cf80000000000014c
```
Error message during restoration *when this patch is not applied* (note the `mpatha` device detected vs …

add /etc/multipath/* in rear ramdisk

---

usr/share/rear/conf/default.conf

100 MiB is too low. My first attempt to "rear -v mkrescue" an 64-bit kernel 4.9.11 fails with:
ERROR: Could not copy /tmp/rear.2wwzvo4iQ1W4LLK/tmp/initrd.cgz to /tmp/rear-efi.0sRzW//EFI/BOOT/initrd.cgz
Aborting due to an error, check /root/rear/var/log/rear/rear-d2.log for details.
The default 100 MiB is not a sensible value for an EFI boot partition nowadays:
total 100M
-rwx------ 1 root root  79K Feb 22 22:59 BOOTX64.efi
-rwx------ 1 root root  96M Feb 22 22:59 initrd.cgz
-rwx------ 1 root root 4.7M Feb 19 14:49 kernel

Increase default USB_UEFI_PART_SIZE from 100 to 200 MiB

---

usr/share/rear/prep/default/500_guess_bootloader.sh

NVME disks are not handled by gues_bootloader script, causing an error later.
This is a simple fix that should do the job.

support of nvme disks in guess_bootloader script

---

usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh

As seen on UEFI 64-bit Arch Linux distributions with efibootmgr package installed.
Upon "bootctl install" the .efi files are:
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
When system is booting withing having a listing in the UEFI boot menu (efivars) then the UEFI boot will most likely be booted using file /boot/EFI/BOOT/BOOTX64.EFI.

Enhancement: find 64-bit systemd UEFI bootloader

---

usr/share/rear/conf/default.conf
usr/share/rear/format/USB/default/300_format_usb_disk.sh
usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh

including rounding user UEFI size input to alignment values and enhancing with an option to insert parameters in the mkrescue mkfs.(ext3|ext4) phase for improved speed and lifetime of USB flash memory media; issue #1201

mkrescue partition alignment enhancement 

---

.gitignore

So /etc/rear/site.conf does not accidentally gets added and committed.

Add etc/rear/site.conf to .gitignore 

---

.gitignore
usr/share/rear/prep/default/310_include_uefi_tools.sh
usr/share/rear/prep/default/320_include_uefi_env.sh

and also allow `/boot` to be completely a VFAT file system, instead of just `/boot/efi` (rear/rear#1223)

320_include_uefi_env made less case sensitive

---

usr/share/rear/build/default/990_update_os_conf.sh
usr/share/rear/lib/config-functions.sh

Clean up the SetOSVendorAndVersion function a bit.
In particular set SUSE_LINUX as OS_VENDOR
on all SUSE systems but do not set OS_MASTER_VENDOR
same as OS_VENDOR because then scripts in
a .../$OS_VENDOR/... or .../$OS_MASTER_VENDOR/...
sub-directory would get sourced twice by
the (buggy?) SourceStage function.
This pull request is triggered by
https://github.com/rear/rear/pull/1171#issuecomment-273781272
and it is also related to
https://github.com/rear/rear/issues/1214#issuecomment-286056772

Use SUSE_LINUX as OS_VENDOR on all SUSE systems.

---

usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh

Otherwise the initrd file will not boot the kernel, instead returning a Kernel Panic and
> initramfs unpacking failed: junk in compressed archive
`lsinitcpio -a` was helpful in spotting this issue: 
> ==> ERROR: Newer lz4 stream format detected! This may not boot!
More details at https://github.com/rear/rear/issues/1218#issuecomment-285813885

lz4 legacy format (Linux kernel compression)

---

usr/share/rear/conf/default.conf

lz4 -l is necessary for Linux kernel boot compatibility, a separate branch and patch has already been pull request for that change in code. This patch also updates the documentation for that change. And it includes a table with an example to show the real life trade offs for extraction time, creation time and size based on an example.

doc lz4 -1 changed to lz4 -l

---

usr/share/rear/conf/GNU/Linux.conf

`mkrescue` on a source computer with both USB 2.0 and 3.0 port might run with the `xhci` module only.
When the (USB) boot device is used to start a USB 2.0 computer that requires the `ehci` module, both the `ehci_hcd` and `ehci_pci` modules, to boot with USB keyboard and mouse support. Tested with Arch Linux 4.9.11-1 on an Intel DE3815TYKHE (USB2+3 where `lsmod` only show the `xhci` module), then ReaR will not have keyboard support when booted on a machine with USB 2.0 only. After adding the 4 `(u|e|x|o)hci_pci` modules, the USB keyboard and mouse do function again with the USB 2.0 only mainboard. Also see https://github.com/rear/rear/issues/519#issuecomment-286579288

Add USB .hci_pci modules for broader hardware support

---

usr/sbin/rear

Treat missing additional config files (almost) same
as other missing config files which means that
missing additional config files do not let ReaR
abort with an Error but in contrast to other missing
config files missing additional config files are reported
to the user via 'LogPrint' so that the user is at least informed
if what he requested via the '-C' command line option cannot
be fulfilled.
An intended positive side-effect when missing additional
config files are no Error is that then it also works
(not relly cleanly but it works) for DRLM_MANAGED=y
which requires that missing local config files must
not let ReaR abort with an Error because the needed
config files get later downloaded from the DRLM server
and applied
(cf. the drlm_import_runtime_config function in …

treat missing additional config files same as other missing config files

---

usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/init/default/030_update_recovery_system.sh

Only added plain 'curl' to PROGS in conf/GNU/Linux.conf
but currently no special code for the https support libs.
Additionally enhanced init/default/030_update_recovery_system.sh
to error out if 'curl' is required but not there.

Added plain 'curl' to default PROGS (issue1156 and issue1229).

---

usr/share/rear/prep/default/320_include_uefi_env.sh

Today I've accidentally found a small regression that can basically avoid ReaR to correctly setting **USING_UEFI_BOOTLOADER=1**.
With old code:
```
if [[ -n $(find /boot -maxdepth 1 -iname efi -type d) ]]; then
return    # not found
fi
```
If _efi_ directory is found inside _/boot_  320_include_uefi_env.sh would prematurely return.

Corrected bad test for UEFI partition check inside /boot.

---

Makefile
packaging/debian/rules
packaging/rpm/rear.spec
usr/share/rear/conf/default.conf
usr/share/rear/init/default/010_set_drlm_env.sh
usr/share/rear/lib/drlm-functions.sh

This PR will improve DRLM and ReaR integration and solve a DRLM issue opened by @gdha (https://bugzilla.redhat.com/show_bug.cgi?id=1239003).
**brief description of changes:**
- add support for Multiple configs `rear -C confname` in DRLM (issue #1229)
- Solve issue https://github.com/brainupdaters/drlm/issues/42, now the connection is verified by default and properly documented in default.conf.
- Now ReaR logs will be sent in real time to DRLM.
- Improved error handling with DRLM RESTful API and keep backwards compatibility with previous versions of ReaR (since 1.17) on DRLM side.
- New default REAR_CAPATH="/etc/rear/cert" to store SSL certs used by ReaR. see default.conf
This code has been tested on RHEL/CentOS, SLES/OpenSUSE and Debian/Ubuntu.

DRLM management and security improvements

---

usr/share/rear/prep/default/500_guess_bootloader.sh

Currently onyl FYI so that you can have a look
my first attempt to implement BOOTLOADER support, cf.
https://github.com/rear/rear/issues/1242#issuecomment-288349895
Currently it is not tested.
I think there could be some missing alignment between
prep/default/500_guess_bootloader.sh
and
layout/save/default/450_check_bootloader_files.sh
When someone uses the grand new "FancyBoot" bootloader,
setting BOOTLOADER="FancyBoot" in default.conf won't help him
as long as there is no support for that in ReaR.
But setting BOOTLOADER is not meant this way.
Setting BOOTLOADER is only meant so that the user
can - if needed - (i.e. when autodetection fails for him)
enforce ReaR to set up during "rear recover" one of
the supported bootloaders i.e. one of what is listed in …

First attempt to implement BOOTLOADER support

---

usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/init/default/010_set_drlm_env.sh

This PR will add support for curl (HTTPS)
brief description of changes:
Added required LIBS and files to **/usr/share/rear/conf/GNU/Linux.conf** and remove them from **/usr/share/rear/init/default/010_set_drlm_env.sh**
This code has been tested on RHEL/CentOS, SLES/OpenSUSE and Debian/Ubuntu.

Added required libs and files for curl with HTTPs by default

---

usr/share/rear/conf/default.conf
usr/share/rear/format/USB/default/300_format_usb_disk.sh
usr/share/rear/format/USB/default/350_label_usb_disk.sh
usr/share/rear/lib/format-workflow.sh

Use parted with bytes 'B' as unit in the format workflow
to be compatible with older parted, cf.
https://github.com/rear/rear/issues/1270
and further cleanups and enhancements
in the format workflow.

Use parted with B unit to be compatible with older parted.

---

usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/prepare/default/400_autoresize_disks.sh

This patch corrects problems with mawk, which allowed maximum integer 0x7FFFFFFF (2147483647) when "%d" conversion specification format was used.
This caused that maximum allowed partition size was limited to ~2GB.

Patch for issue #1269 where mawk incorrectly calculated size of partition

---

usr/share/rear/conf/GNU/Linux.conf

brief description of changes:
Added excludes of SSL private keys in **/usr/share/rear/conf/GNU/Linux.conf** 
This code has been tested on RHEL/CentOS where curl has NSS support `/etc/pki/*`. SLES/opesSUSE and Debian/Ubuntu are ok with not including (/etc/ssl/private).

Excluded private keys from recovery for curl https (see: PR #1267)

---

usr/share/rear/conf/default.conf
usr/share/rear/prep/GNU/Linux/310_include_cap_utils.sh
usr/share/rear/rescue/NETFS/default/600_store_NETFS_variables.sh
usr/share/rear/rescue/NETFS/default/610_save_capabilities.sh
usr/share/rear/restore/NETFS/default/510_set_capabilities.sh

Changed NETFS_RESTORE_CAPABILITIES
from a binary variable to an array that contains
those directories where ReaR should save and
restore file capabilities, see
https://github.com/rear/rear/issues/1283
and the related issue
https://github.com/rear/rear/issues/1175
This change is not backward compatible because now
NETFS_RESTORE_CAPABILITIES="yes"
does no longer work as expected.
I cannot enhance it so that
NETFS_RESTORE_CAPABILITIES="yes"
works as before which would mean to
run 'getcap -r /' as generic fallback
because that command is the reason for
https://github.com/rear/rear/issues/1283
which this pull request intends to fix.

Make NETFS_RESTORE_CAPABILITIES more fail safe

---

usr/share/rear/rescue/default/100_hostname.sh

By storing the hostname in /etc/hostname (lowercase) Arch Linux will automatically set the host name in the recovery environment. See issue #1254

Fix no hostname set in Arch Linux #1254

---

usr/share/rear/conf/GNU/Linux.conf

The PROGS array contains a redundant/duplicate "pico" configuration. Remove it.

Remove duplicate pico from Linux.conf PROGS array

---

usr/share/rear/rescue/NETFS/default/600_store_NETFS_variables.sh

Error message when booting on recovery image:
```
ET: Registered protocol family 15
Registering the dns_resolver key type
registered taskstats version 1
Freeing unused kernel memory: 5376k freed
INIT: version 2.86 booting
Hostname set to sles11sap-144
/etc/rear/rescue.conf: line 9: syntax error near unexpected token `('
/etc/rear/rescue.conf: line 9: `All set NETFS_* variables (cf. rescue/NETFS/default/600_store_NETFS_variables.sh):'
Configuring Relax-and-Recover rescue system
Running 00-functions.sh...
Running 01-run-ldconfig.sh...
Running 10-console-setup.sh...
Loading /etc/dumpkeys.out
```
It seems "# " is missing in `usr/share/rear/rescue/NETFS/default/600_store_NETFS_variables.sh`

Typo in 600_store_NETFS_variables.sh ?

---

usr/share/rear/build/GNU/Linux/005_create_symlinks.sh

Only create LVM symlinks when the HOST system contains LVM

Add LVM check in 005_create_symlinks.sh

---

usr/share/rear/layout/save/GNU/Linux/510_current_disk_usage.sh

Gnu `df` at least since 2013 contains the -x option to "Exclude Certain File System Type":
`  -x, --exclude-type=TYPE   limit listing to file systems not of type TYPE`
There is no need to use `grep` to exclude file systems.
Also including `tmpfs` and `devtmpsfs` clutters the output. Exclude these file systems too.
Output before change:
```
Filesystem      Size  Used Avail Use% Mounted on
dev             3.9G     0  3.9G   0% /dev
run             3.9G  696K  3.9G   1% /run
/dev/sda2        20G  2.1G   18G  11% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           3.9G     0  3.9G   0% /tmp
/dev/sda3       9.3G   17M  9.3G   1% /home
/dev/sda1      1022M   44M  979M   5% /boot
tmpfs           789M     0  789M   0% /run/user/0 …
```

exclude tmpfs from df.txt and replace grep

---

usr/share/rear/lib/framework-functions.sh

Adding horizontal rulers around stage, so the human eye can quicker spot new stages in long output listings.

Make long SourceStage logging output better human scannable

---

usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh

-l is needed to make initramfs boot, this compresses using Legacy format (Linux kernel compression)

Lz4 -l (Legacy) is needed to make initramfs boot

---

usr/share/rear/build/GNU/Linux/130_create_dotfiles.sh

Some handy command the help me getting (debug) things done, in the Rear recovery environment.

Add nano, dhcp client, sshd start to bash history

---

usr/share/rear/rescue/default/100_hostname.sh

Since 201921869e228d301cff7b4500c84e8cc165c539, SLE12 losts its hostname in recovery mode.
The reason seems to be because `/etc/hostname` file exists in SLE12, but only `/etc/HOSTNAME` is used to set hostname.
I propose the following simple change to solve this issue.

Set hostname in both /etc/hostname and /etc/HOSTNAME.

---

usr/share/rear/layout/prepare/default/320_apply_mappings.sh

Related to issue #183 and #1301
eMMC and NVMe devices might need the partition separator `p`.
With this modification I was able to recover migrate from /dev/sda to /dev/nvme0n1 until patching etc/fstab phase.
Without this mod I wasn't even able to reach the partitioning of the target nvme device.

Add mmcblk and nvme devices to translation mappings

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

When using SLE12 with multipath, partition behind the multipath device are duplicated in disk layout file.
This break the layout recreation during recovery.
1) recovery will try to create twice the same partition
2) flags are wrong (twice "primary" instead of "primary" "flag")
extract of layout generated:
```
multipath /dev/mapper/3600507680c82004cf8000000000000d8 /dev/sda,/dev/sdb,/dev/sdc,/dev/sdd,/dev/sde,/dev/sdf,/dev/sdg,/dev/sdh
part /dev/mapper/3600507680c82004cf8000000000000d8 7340032 2097152 primary primary /dev/mapper/3600507680c82004cf8000000000000d8-part1
part /dev/mapper/3600507680c82004cf8000000000000d8 7340032 2097152 primary primary /dev/mapper/3600507680c82004cf8000000000000d8-part1
part /dev/mapper/3600507680c82004cf8000000000000d8 2154823680 9441280 primary primary …
```

Use "sort -un" to prevent duplicate entry in partitions file.

---

usr/share/rear/rescue/GNU/Linux/990_sysreqs.sh

When no DNS server is defined in _/etc/resolv.conf_, every call to `dig` in [990_sysreqs.sh](https://github.com/rear/rear/blob/master/usr/share/rear/rescue/GNU/Linux/990_sysreqs.sh#L107) takes ~18 s to timeout.
In summary, this caused on my SLES12 SP1 with two configured IP addresses to idle for 3 minutes:
```
...
2017-04-19 17:24:42 Including rescue/GNU/Linux/990_sysreqs.sh
2017-04-19 17:27:42 Finished running 'rescue' stage in 181 seconds
...
```
This fix skips call to `dig` if no DNS server is defined in _/etc/resolv.conf_
V.

Fix for long wait in dig, when DNS servers are not set.

---

usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
usr/share/rear/prep/GNU/Linux/240_include_multipath_tools.sh

Force Loading multipath modules when `BOOT_OVER_SAN` is True. (#1295 re-open)
Before this changes, multipath module was loaded only if multipath devices were present in `LAYOUT_FILE`.
So, if you migrate from virtual machine (non-multipath) to `BOOT_OVER_SAN` system (usually multipathed), multipath is not loaded during recover/migration.
I propose to automatically the load of multipath modules during recovery when `BOOT_OVER_SAN` is True.
I also add /lib*/multipath which where missing when creating rescue image with `BOOT_OVER_SAN=y`

Multipathing when BOOT_OVER_SAN=y 

---

usr/share/rear/layout/prepare/default/320_apply_mappings.sh

Creating a set of rules based on OS type (RedHat, Suse) to set the suffix used between multipath disk name and partition number:
- RHEL < 7 => p
- RHEL >= 7 => ""
- SUSE < 12 => _part
- SUSE > 12 => -part
Can easily be updated with other Linux distro

Multipath device mapping

---

usr/share/rear/prep/default/310_include_uefi_tools.sh

Replace find command with /boot/[eE][fF][iI]
Abort when having access to the UEFI binaries is mandatory (in case of USING_UEFI_BOOTLOADER=1) so that ReaR then
aborts with an Error message instead of proceeding, as requested by @jsmeix

Simplify case insensitive /boot/efi check in 310_include_uefi_tools

---

usr/share/rear/prep/GNU/Linux/240_include_multipath_tools.sh

- same issue than #852. multipath need libaio.
- Issue detected with Ubuntu.

Adding libaio for multipath if BOOT_OVER_SAN true

---

usr/share/rear/layout/prepare/default/320_apply_mappings.sh

- Like #1315, add "-part" as multipath prefix for ubuntu.

Add partition prefix "-part" for multipathed device in Ubuntu.

---

usr/share/rear/finalize/GNU/Linux/150_migrate_disk_devices_layout.sh
usr/share/rear/layout/save/default/450_check_bootloader_files.sh

`yaboot.conf` is used by RHEL < 7 in POWER system.
Like `lilo.conf`, the variable `boot=` must be updated in case of disk migration.
We should also add lilo.conf & yaboot.conf files to `CHECK_CONFIG_FILES`. What do you think ?

Add yaboot.conf to the list of file for disk migration.

---

usr/share/rear/conf/Linux-i386.conf

Flash memory, especially SD Cards and USB flash drives, often comes without decent (NAND memory IC) specifications. As a result you have to figure the optimal partition alignment value a.k.a. Allocation Unit, a.k.a erase block size. That value is the smallest unit that a NAND flash can erase. The values range from 128KB to 64MB, typically 2MB. More info at [https://wiki.linaro.org/WorkingGroups/KernelArchived/Projects/FlashCardSurvey](https://wiki.linaro.org/WorkingGroups/KernelArchived/Projects/FlashCardSurvey) The `flashbench` tool helps to identify the real world Allocation Unit size for flash memory.

Add (Linaro) flashbench to the list of PROGS

---

usr/sbin/rear
usr/share/rear/prep/default/950_check_missing_programs.sh

In
https://github.com/rear/rear/commit/463a2651af982723f843beccdf33f71a0352fa53
the fix for
usr/share/rear/prep/default/95_check_missing_programs.sh
made the REQUIRED_PROGS test therein work again
but the same code in usr/sbin/rear was not fixed
(with this pull request it gets fixed at both places).
But 'declare -a MISSING_PROGS' contradicted the intent
that is explained in the comment above in the code.
An empty array does not work witn 'set -u':
<pre>
-bash: arr: unbound variable
-bash: arr[*]: unbound variable
-bash: arr[@]: unbound variable
-bash: arr[@]: unbound variable
</pre>
'declare -a arr' is the same as 'arr=()'.
One must have an array with at least one (empty) member.

Fixed REQUIRED_PROGS tests (related to issue1233)

---

usr/share/rear/layout/prepare/GNU/Linux/130_include_filesystem_code.sh

Hereby I implemented basically my proposal
https://github.com/rear/rear/issues/1327#issuecomment-296672094
and additionally now dd is used as generic fallback in any case.
I tested it on SLE12 with wipefs in the recovery system
and also without wipefs in the recovery system
(i.e. for me also the dd fallback works).
Details:
With wipefs in the recovery system
I get in diskrestore.sh
<pre>
wipefs --all --force /dev/sda2 || wipefs --all /dev/sda2 || dd if=/dev/zero of=/dev/sda2 bs=512 count=1 || true
</pre>
and in the "rear -d -D recover" log file
<pre>
+ source /usr/share/rear/layout/recreate/default/200_run_script.sh
...
+++ echo -e 'Creating filesystem of type ext4 with mount point / on /dev/sda2.'
+++ wipefs --all --force /dev/sda2
+++ mkfs -t ext4 -b 4096 -i 16377 -U …

Try wipefs and use dd as fallback (issue1327 and related to issue799)

---

.editorconfig
usr/share/rear/lib/dump-workflow.sh

also show OUTPUT_* in rear dump, fixing #1337
(use Editorconfig to declare our coding style)

Show OUTPUT_* variables in rear dump

---

usr/share/rear/conf/default.conf
usr/share/rear/output/TSM/default/950_dsmc_save_result_files.sh

Should fix #1342
- No need to copy files if `TSM_RESULT_SAVE` is false
- When `$PXE_TFTP_URL` is defined, results files are deleted by
`800_copy_to_tftp.sh` ... So it produce an Error "No files to copy (RESULT_FILES is empty)"

Exit if TSM_RESULT_SAVE is false or PXE_TFTP_URL is defined.

---

usr/share/rear/conf/default.conf
usr/share/rear/conf/examples/RHEL7-PPC64LE-Mulitpath-PXE-GRUB.conf
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
usr/share/rear/output/PXE/default/810_create_pxelinux_cfg.sh

Some non x86 platform (like ppc64/ppc64le) does not support native PXE boot. Some document recommend  to use GRUB as a PXE alternative. (https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/chap-installation-server-setup.html#sect-network-boot-setup-ppc-grub2)
I would like to propose this possibility in ReaR as an addition to the standard PXE.
- This alternative way to use "Grub PXE" server will be controlled by a new boolean variable : `PXE_CONFIG_GRUB_STYLE` 
- a New `make_pxelinux_config_grub` function to create the grub compatible boot menu.
- Like PXE, when the client is looking at its MAC address or IP (in hex) on the config directory of the TFTP server. But file should be like this : `grub.cfg-<MAC or IP>`.
- `gethostip` is part of …

Allow "grub PXE style" for non x86 platform. 

---

usr/share/rear/layout/save/GNU/Linux/280_multipath_layout.sh

- BUG: reading `/sys/block/$name/size` gives nbr of blocks, not size. *(sorry my mistake)*
Using `get_disk_size` is better and gives the expected result.

Using get_disk_size to get size of multipath device.

---

usr/share/rear/finalize/Linux-ppc64/600_install_yaboot.sh

Exit from executing yaboot, if yaboot bootloader is managed by lilo (could be the case on sles11 ppc64 when not using LVM).
Here is the content of yaboot.conf (sles11 ppc64 no LVM)
```
partition = 3
timeout = 80
default = SLES11_SP4_1
image = /boot/vmlinux-3.0.101-71-ppc64
label = SLES11_SP4_1
root = /dev/vda3
append = "quiet sysrq=1 insmod=sym53c8xx insmod=ipr crashkernel=512M-:256M "
initrd = /boot/initrd-3.0.101-71-ppc64
initrd-size = 5817152
```

Don't run yaboot if yaboot.conf is managed by lilo.

---

usr/share/rear/conf/default.conf

Document incremental/differential backup timing granularity
(one day and the differentiating time is at 00:00) and
other shortcomings of BACKUP_TYPE=incremental
or BACKUP_TYPE=differential, see the related issue
https://github.com/rear/rear/issues/1285

document incremental/differential backup timing granularity

---

usr/share/rear/finalize/SUSE_LINUX/i386/550_rebuild_initramfs.sh

I just notice that initrd were not correctly created in sles11 since we change chroot usage (stop using loggin).
mkinitramfs call other tools (dirname, getent, perl ...) without a correctly configured $PATH, this operation failed.
Here is the way to reproduce it :
```
RESCUE sles11sap-144:~ # TARGET_FS_ROOT=/mnt/local
RESCUE sles11sap-144:~ # mount -t proc none $TARGET_FS_ROOT/proc
RESCUE sles11sap-144:~ # mount -t sysfs none $TARGET_FS_ROOT/sys
RESCUE sles11sap-144:~ # mkinitrd_binary=$( chroot $TARGET_FS_ROOT /bin/bash -c 'PATH=/sbin:/usr/sbin:/usr/bi
n:/bin type -P mkinitrd' )
RESCUE sles11sap-144:~ # chroot $TARGET_FS_ROOT $mkinitrd_binary 
Kernel image:   /boot/vmlinux-3.0.101-63-ppc64
Initrd image:   /boot/initrd-3.0.101-63-ppc64
/lib/mkinitrd/setup/01-prepare.sh: line 183: getent: …
```

Initramfs need $PATH when running in chroot on sles11

---

usr/share/rear/prep/GNU/Linux/280_include_systemd.sh

Some modern distros (like ubuntu16.04) use systemd to control inet naming. 
Those information are stored in `/lib/systemd/network` or `/usr/lib/systemd/network`.
For example, my system in Ubuntu16.04 uses Predictable interface name by default : **enp0s1**
*I'm not a big fan of Predictable interface name, but it seems to become the new standard (Fedora 25 / Ubuntu 16.04, CoreOS...)*
When I boot to the rescue image, the interface is renamed **eth0** => with **NO IP** because of name chaged.
I think we should add `/lib/systemd/network` or `/usr/lib/systemd/network` to the rescue image as we want to "replicate" network configuration from the original machine when booting on the rescue image.
If the user doesn't like the "Predictable naming", it could add `net.ifnames=0` or change the …

Include systemd/network to preserve Predictable Network Interface Names

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

Avoid to get devname and devsize if it is a multipath device.
- In this section of script we get information devname and devsize; but
those information will be dropped if the device is a multipath device.
=> test if it is a multipath device and get devname and devsize only when
needed.

Avoid to get devname & devsize when not needed (multipath)

---

usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/linux-functions.sh

cleanup linux-functions.sh and some related code
in 390_copy_binaries…_libraries.sh and
in _input-output-functions.sh as a preparation step
that is related to solve issue1202

cleanup linux-functions.sh as preparation for issue1202

---

usr/share/rear/layout/prepare/default/300_map_disks.sh

This prevent ReaR to propose disk with different size during recovery. (see #1353)

BUG #1353 Typo in 300_map_disks

---

usr/share/rear/build/GNU/Linux/400_copy_modules.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/linux-functions.sh
usr/share/rear/rescue/GNU/Linux/230_storage_and_network_modules.sh
usr/share/rear/rescue/GNU/Linux/240_kernel_modules.sh

Implemented support for additional meta values like
MODULES=( 'none' )
MODULES=( 'all' )
MODULES=( 'loaded' )
in build/GNU/Linux/400_copy_modules.sh
what MODULES get included in the recovery system
see https://github.com/rear/rear/issues/1202
and https://github.com/rear/rear/issues/1355

Enhancement what MODULES get included in the reovery system

---

usr/share/rear/build/GNU/Linux/400_copy_modules.sh

In 400_copy_modules.sh all redirections of stderr to /dev/null
were removed (only some '1>/dev/null' are left), cf.
https://github.com/rear/rear/pull/1359#discussion_r116239195
Furthermore duplicate module files in the 'modprobe --show-depends'
output are now removed only to avoid useless stderr warnings
from the subsequent 'cp' command like
"cp: warning: source file '/lib/modules/.../foo.ko' specified more than once"
regardless that nothing goes wrong when 'cp' gets duplicate source files
cf. http://blog.schlomo.schapiro.org/2015/04/warning-is-waste-of-my-time.html

Do not discard stderr needlessly (related to pull request 1359).

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/Debian/i386/550_rebuild_initramfs.sh
usr/share/rear/finalize/Fedora/i386/550_rebuild_initramfs.sh
usr/share/rear/finalize/SUSE_LINUX/i386/550_rebuild_initramfs.sh
usr/share/rear/lib/global-functions.sh
usr/share/rear/verify/GNU/Linux/260_recovery_storage_drivers.sh

This is a minor backward incompatible change:
The new default.conf setting
REBUILD_INITRAMFS="yes"
rebuilds the initramfs/initrd in any case during "rear recover"
in the recreated system to be on the safe side because
ReaR cannot check/verify all possible reasons why the
initramfs/initrd may have to be rebuild,
see https://github.com/rear/rear/issues/1321
With
REBUILD_INITRAMFS=""
the old behaviour where "rear recover" rebuilds the initrd/initramfs
only if some storage drivers changed can be still specified.
With
REBUILD_INITRAMFS="no"
the user can explicitly skip rebuilding the initramfs/initrd.

implemented REBUILD_INITRAMFS variable (issue1321)

---

usr/share/rear/finalize/Linux-ppc64le/620_install_grub2.sh

Patch to support grub2 installation with software RAID1 on Linux on POWER (ppc64/ppc64le)
- Need to loop over multiple PReP partition and install grub2 on it.
- Need to use chroot with set a proper PATH in order for grub2-install
to call additional  tool when `/boot` is set on md devices.
Tested with CentOS 7 LE pp64le 
```
RESCUE centos7-145:~ # rear -v recover
Relax-and-Recover 2.00-git201705171620 / 2017-05-17
Using log file: /var/log/rear/rear-centos7-145.log
Running workflow recover within the ReaR rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.statd if available.
Started RPC portmapper 'rpcbind'.
RPC portmapper 'rpcbind' available.
Started rpc.statd.
RPC status rpc.statd available.
Started rpc.idmapd.
Using backup archive …
```

Support for Grub2 + RAID1 on POWER

---

usr/share/rear/conf/default.conf
usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh

If server have Secure Boot enabled, ReaR should not try to create boot loader (BL) for recovery system (which is handy in other cases). As we are not able to sign it, it will be refused by Secure Boot.
This patch just skips ReaRs attempt to create BL and uses original shipped with OS.
c.f. https://github.com/rear/rear/issues/1374

Do not recreate BOOTX64.efi, if Secure boot is enabled.

---

usr/share/rear/layout/prepare/GNU/Linux/150_include_drbd_code.sh
usr/share/rear/layout/prepare/default/600_show_unprocessed.sh
usr/share/rear/lib/_input-output-functions.sh

Documented the UserInput function usage with some examples.

Enhanced the UserInput function and replaced example select and read calls by the UserInput function

---

usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/prep/DUPLICITY/default/050_prep_duplicity.sh

Add SSL cert directories so we can interact with Google Cloud Storage
I was using Duply/Duplicity with Google Cloud Storage and the SSL connections to Google where failing because the SSL certificates didn't get copied over into the image.
This fixes that and allows for restores to come straight from Google Cloud Storage.

Add SSL cert directories

---

usr/share/rear/finalize/GNU/Linux/430_create_multipath_config.sh

The previous code only copy /etc/multipath/bindings if it does not
exist on the TARGET_FS_ROOT. We need also to copy the /etc/mulitpath/bindings when it is updated during migration process.

Always copy /etc/multipath/bindings to the TARGET_FS_ROOT

---

usr/share/rear/lib/_input-output-functions.sh

Have an automated unique default user_input_ID
for the UserInput function so that each
UserInput function call has a user_input_ID
which is some kind of precondition for
https://github.com/rear/rear/issues/1366
Now (at least from my current point of view)
the UserInput function should be feature-complete.
It needs 'bc' to calculate huge numbers and (fortunately) since
https://github.com/rear/rear/pull/1332
'bc' is one of the REQUIRED_PROGS in default.conf
so that it is also available in the ReaR recovery system.
By the way I enhanced the CallerSource function
that now also outputs the line number (useful in bigger scripts)
because I learned how to use BASH_LINENO correctly
(there is an unexpected - but documented - "off by one"
for the BASH_LINENO array index).

Automated unique default user_input_ID for UserInput

---

usr/share/rear/output/ISO/Linux-ppc64/300_create_yaboot.sh

`ISO_FILE` variable must be updated to add `/yaboot` to the ISO image when running SUSE on ppc64.
This could be a side effect of the cleaning made in #1383
This should solve #1407 
@jsmeix @gdha @schlomo, can you review this one please ?

Add /yaboot to ISO_FILE when running SUSE ppc64

---

usr/share/rear/output/ISO/Linux-ppc64le/820_create_iso_image.sh

- xorrisofs use -chrp-boot-part option to generate PPC boot while
mkisofs use -chrp-boot
We need then to change the `-chrp-boot` by `-chrp-boot-part` when using with `xorrisofs`
- tested with SLE12 on ppc64le system

Adapt chrp-boot option when xorrisofs is used

---

usr/share/rear/prep/USB/Linux-i386/350_check_usb_disk.sh

@gozora can you please check if this would work? I think it will help the users if we explain them why ReaR aborts and to give them a chance to fix it.

Improve #1415 to also explain where the USB device is mounted

---

usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh

If you install SLES12 with btrfs support but without snapshots you should face some issue during recovery:
During layout creation, ReaR will fail to mount btrfs FS (because subvolumeID is empty)
```
+++ subvolumeID=
+++ btrfs subvolume set-default /mnt/local/
btrfs subvolume set-default: too few arguments
usage: btrfs subvolume set-default <subvolid> <path>
Set the default subvolume of a filesystem
2017-07-25 17:33:28.564682686 An error occurred during layout recreation.
```
Looking at `disklayout.conf` shows that **NO** `btrfsnormalsubvol` are present (=> no subvol creation)
```
disk /dev/sda 53687091200 msdos
part /dev/sda 7340032 1048576 primary boot,prep /dev/sda1
part /dev/sda 53678702592 8388608 primary lvm /dev/sda2
lvmdev /dev/system /dev/sda2 …
```

SLES12 with no snapshots failed to recreate/mount btrfs FS during recovery.

---

usr/share/rear/lib/recover-workflow.sh

Avoid the additional
<pre>
Run "rear recover" to restore your system !
</pre>
message that only makes sense as long
as 'rear recover' was not ever started, cf.
https://github.com/rear/rear/issues/1433#issuecomment-319084191

Adapt /etc/motd when 'rear recover' is running (issue 1433)

---

usr/share/rear/conf/Linux-ppc64.conf
usr/share/rear/conf/Linux-ppc64le.conf
usr/share/rear/prep/GNU/Linux/280_include_systemd.sh

I encounter an issue last time when trying to migrate a VM from oVirt on POWER to PowerVM.
After booting the LPAR (PowerVM guest) on the ReaR recue image, I can't log into the console.
To solve that issue I had to connect via SSH and start `agetty` on `hvc0` manually (or run again `/etc/scripts/system-setup`). 
oVirt VM use VNC console (`tty1`) while PowerVM partition need to use `hvc0` serial console.
Because backup was done on oVirt VM, `hvc0` was not present, but this means that hvc0 was not automatically detected by ReaR => `serial console detection` is not working.
(This was working in the past.... may be a possible regression ... #1398) 
Anyway, I dig a bit this and realized that this problem only exist on `systemd` based OS (RHEL7 or SLES12); and discover that …

Systemd automatic serial console detection

---

usr/share/rear/rescue/Linux-ppc64/410_use_hvc_console.sh
usr/share/rear/rescue/Linux-ppc64le/410_use_hvc_console.sh

removing 2 "POWER only" scripts that create hvc0 link to systemd.
- as `hvc0 tty` are now automatically detected and created by `systemd-generator` (#1442) we don't
need to create them manually.
- Having `agetty hvc0` started twice produce strange console behaviour (double character typing, echo, character missing.... )

removing duplicate hvc0 console creation.

---

usr/share/rear/finalize/Debian/ppc64le/550_rebuild_initramfs.sh

rebuild_mkinitrd is missing for Debian/Ubuntu on ppc64le arch.
Add a link to `finalize/i386/550_rebuild_initramfs.sh`

Add finalize/550_rebuild_initramfs.sh to ppc64le arch for Debian/Ubuntu

---

usr/share/rear/finalize/Linux-ppc64/540_check_lilo_path.sh
usr/share/rear/finalize/Linux-ppc64/540_check_yaboot_path.sh
usr/share/rear/finalize/Linux-ppc64/600_install_yaboot.sh
usr/share/rear/finalize/Linux-ppc64/610_install_lilo.sh

I currently facing a BUG with mkinitrd re-creation when : 
- restoration is made to a different system (migration)
- running with ppc64 with lilo or yaboot boot loader
- boot device is multipathed.
- and boot partition is defined with `/dev/disk/by-id` in `lilo.conf` or `yaboot.conf`
mkinitrd gets the boot device from `/etc/lilo.conf` or ` /etc/yaboot.conf` when they exists. 
This means those one need to be migrated BEFORE running mkinitrd.
`/etc/lilo.conf` and `/etc/yaboot.conf` are with migrated with (`250_migrate_disk_devices_layout.sh`) for non-diskbyid device (/dev/vda, /dev/sda, /dev/mapper/vg-lv) which is before `550_rebuild_initramfs.sh`.
But diskbyid devices which are multipathed are not migrated (`260_rename_diskbyid.sh`).
```
while read ID DEV_NAME; do
ID_NEW=""
if [[ $DEV_NAME …
```

Migrate lilo and yaboot before mkinitrd

---

usr/share/rear/finalize/Linux-ppc64/540_check_yaboot_path.sh

As requested by @jsmeix in #1446 (https://github.com/rear/rear/pull/1446#issuecomment-324345102), 
I remove the export variable in `540_check_yaboot_path.sh`.

Remove unecessary export variable

---

usr/share/rear/restore/default/900_create_missing_directories.sh

Create /var/tmp (if it doesn't exist) during recovery.

---

usr/share/rear/conf/default.conf
usr/share/rear/restore/default/900_create_missing_directories.sh
usr/share/rear/verify/TSM/default/400_verify_tsm.sh

Now restore/default/900_create_missing_directories.sh
recreates by default some generic directories in any case
if they do not exist, namely:
mnt proc run sys dev/pts dev/shm tmp var/tmp
and
MOUNTPOINTS_TO_RESTORE was renamed
into DIRECTORIES_TO_CREATE
but all should be fully backward compatible - in particular
if exists MOUNTPOINTS_TO_RESTORE is still also used.

Enhance MOUNTPOINTS_TO_RESTORE into DIRECTORIES_TO_CREATE

---

usr/share/rear/lib/_input-output-functions.sh

The UserInput return code is now simply 0 or 1:
The UserInput return code is the return code of
the 'read' bash builtin that is called to get user input.
When the UserInput function is called with right syntax
its return code is 0 for any actual user input and
in case of any (non empty) automated user input.
The return code is 1 when the 'read' call timed out
(i.e. when there was no actual user input)
so that one can distinguish between an explicitly
provided user input and no actual user input
even if the explicitly provided user input is the same
as the default so that it makes a difference
whether or not the user explicitly chose and confirmed
that the default is what he actually wants
or if he let things "just happen" inattentively via timeout
where it is important to have a big …

Simplified UserInput return codes to the 'read' return code

---

usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh

This patch fixes problem with hanging `cryptsetup luksOpen ...` when `dmestup` binary is missing in ReaR recovery system. (c.f. #1444).

cryptsetup hangs on `cryptsetup luksOpen ...`

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/save/default/400_check_backup_special_files.sh

New TSM version (since v8.1.2) needs to have additional file copy to Rescue media in order to work.
All those new files are located in /etc/adsm directory.
```
new files in /etc/adsm
-rw-rw-rw- 1 root root 80 Aug 23 09:41 spclicert.rdb
-rw-rw-rw- 1 root root 80 Aug 23 09:41 spclicert.crl
-rw------- 1 root root 193 Aug 23 09:41 spclicert.sth
-rw-rw-rw- 1 root root 5080 Aug 23 09:41 spclicert.kdb
-rw------- 1 root root 193 Aug 23 09:41 TSM.sth
-rw-rw-rw- 1 root root 645 Aug 23 09:41 TSM.IDX
-rw-rw-rw- 1 root root 3260 Aug 23 09:41 TSM.KDB
```
Currently :
<pre>
COPY_AS_IS_TSM=( /etc/adsm/TSM.PWD /opt/tivoli/tsm/client /usr/local/ibm/gsk8* )
</pre>
Proposed :
<pre>
COPY_AS_IS_TSM=( /etc/adsm /opt/tivoli/tsm/client /usr/local/ibm/gsk8* )
</pre>
This change should solve the issue in TSM 8.1.2 …

Add dir /etc/adsm dir to COPY_AS_IS_TSM (#1452)

---

usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh

Some Linux distribution (like sles11) has a version of multipath which return an error when `dm-multipath` kernel module is loaded but no multipath devices are detected.
This produce an exit to `rear_shell` waiting for UserInput. 
I propose to change it to a UserInput with 30s delay in order to avoid to block the recovery process when `BOOT_ON_SAN=yes` but no multipath device are found (in case of migration for example).

Add non blocking userprompt with timeout if no multipath device detected.

---

usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/lib/network-functions.sh

Grub2 `net_default_server_opt` variable must be a real IP not a hostname or fqdn.
=> if a user do not specify `PXE_TFTP_IP`, this one will be "guess" from the "PXE_TFTP_URL".
But we need to be sure it is a real numeric IP. if not we need to try to resolve the name to IP.
Creation of two new functions in `network-functions.sh`
- create is_ip() function
- create get_ip_from_fqdn() function

Resolve $PXE_TFTP_IP to IP if hostname or FQDN are used

---

usr/share/rear/conf/default.conf
usr/share/rear/rescue/default/900_clone_users_and_groups.sh

Some minor improvements of https://github.com/rear/rear/pull/1471
but still kept the behaviour of how it worked before
https://github.com/rear/rear/pull/1471
i.e. CLONE_ALL_USERS_GROUPS
replaces the CLONE_USERS and CLONE_GROUPS
If the behaviour of how it works should be changed
a separated issue or pull request is needed.
Personally I do not intend to change the behaviour
because it seems to work o.k. as is (no user complaints).

Improved overhauled 900_clone_users_and_groups.sh

---

usr/share/rear/restore/ZYPPER/default/980_initial_network_setup.sh

When 'set-e' is set one cannot 'simply return' from a script.
When 'set-e' is set one must always call
<pre>
apply_bash_flags_and_options_commands "$DEFAULT_BASH_FLAGS_AND_OPTIONS_COMMANDS"
</pre>
before returnig into other code where 'set-e' is not set.
Otherwise there happen arbitrary unexpected failures elsewhere
because "the rest of the ReaR code" is not at all ready to
run correctly when 'set -e' is set, see also
https://github.com/rear/rear/issues/700

Do not 'simply return' when 'set-eu' is set.

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/conf/default.conf
usr/share/rear/prep/NETFS/GNU/Linux/205_inspect_tar_capabilities.sh
usr/share/rear/prep/NETFS/default/040_inspect_configuration_files.sh
usr/share/rear/prep/RSYNC/GNU/Linux/200_selinux_in_use.sh
usr/share/rear/restore/NETFS/default/400_restore_backup.sh

BACKUP_PROG_OPTIONS used to be a string variable, turn it into an array (GD, 06/SEP/2017 - issue #1175)
added new script prep/NETFS/GNU/Linux/205_inspect_tar_capabilities.sh which will automatically add capabilities to the BACKUP_PROG_OPTIONS array

BACKUP_PROG_OPTIONS used to be a string variable, turn it into an array

---

usr/share/rear/prep/default/330_include_uefi_tools.sh

This change integrates UEFI tools on demand as determined by `320_include_uefi_env.sh`.
It avoids replicating UEFI tests already done in `320_include_uefi_env.sh` and just relies on a correctly set `$USING_UEFI_BOOTLOADER` variable. For such variable to be set correctly, `310_include_uefi_tools.sh` is renamed to `330_include_uefi_tools.sh`.

Fix UEFI tools integration (should address issues in #1477, #1478)

---

usr/share/rear/format/USB/default/200_check_usb_layout.sh
usr/share/rear/format/USB/default/300_format_usb_disk.sh
usr/share/rear/layout/prepare/GNU/Linux/150_include_drbd_code.sh
usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/layout/prepare/default/600_show_unprocessed.sh
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/restore/BORG/default/300_load_archives.sh
usr/share/rear/restore/FDRUPSTREAM/default/270_selinux_considerations.sh
usr/share/rear/restore/NBKDC/default/400_restore_backup.sh

Now each UserInput function call requires
a specified '-I user_input_ID' option and
the autogenerated user_input_ID is gone.
Now the user_input_ID option value can and must be
a valid bash variable name e.g. 'choose_replacement_disk'
so that the user can (if he wants) specify a variable named
UserInput_choose_replacement_disk
(i.e. the user_input_ID option value with prefix 'UserInput_')
where its value is used as automated input.
This way meaningful variable names for automated UserInput
are implemented in a generic way using plain bash syntax
without any restriction how the user needs to specify
his particular automated input settings.
The user can do this statically in his local.conf like
UserInput_choose_replacement_disk="/dev/sda"
or via whatever sophisticated scripting magic as he …

Use meaningful variable names for automated UserInput

---

usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
usr/share/rear/lib/layout-functions.sh

- @schlomo, The change made in d89623404c08cf8b4b485e35295fb4caf2a35232 can produce error in some Linux Distro (like Sles11). 
It is not directly link with the Linux version, but how scripts are dealing with `apply_layout_mappings()` function. In `250_migrate_disk_devices_layout.sh` a list of file to migrate is provided to the function. Depending to the configuration, some of them can e empty (or a link which point to an empty file.)
I think we just need to be sure that the function is called with 1 argument... 
But the fact to provide an empty file to the function should not produce an ERROR which kill the recovery process. After all, if the file is empty, no modification will be done.
- I also made some changes in `250_migrate_disk_devices_layout.sh` in order to modify link target when …

Avoid apply_layout_mappings Error if input file is empty

---

usr/share/rear/rescue/default/500_ssh.sh

This PR was originally included in my YUM PR, but I at the request of @jsmeix , I pulled it out and am submitting it separately.  
In my testing, I would see multiple passwd entries created if the string 'ssh' occurred in more than just the sshd daemon user's entry.  While this didn't actually break anything, these tweaks should make it cleaner.

Tweak how ssh user is copied in usr/share/rear/rescue/default/500_ssh.sh

---

usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/layout/prepare/default/600_show_unprocessed.sh
usr/share/rear/lib/_input-output-functions.sh

In 300_map_disks.sh use runtime generated UserInput-IDs
to support multiple same UserInput calls for different devices
that need to be mapped.
This one implements the missing part in
https://github.com/rear/rear/pull/1473#issuecomment-328832250
How it looks now compared to
https://github.com/rear/rear/pull/1473#issuecomment-328811035
<pre>
RESCUE e205:~ # export USER_INPUT_LAYOUT_MIGRATION_REPLACEMENT_SDA="1"
RESCUE e205:~ # export USER_INPUT_LAYOUT_MIGRATION_CONFIRM_MAPPINGS="yEs"
RESCUE e205:~ # rear recover
...
Comparing disks.
Device sda has size 22548578304, 21474836480 expected
Switching to manual disk layout configuration.
Original disk /dev/sda does not exist (with same size) in the target system
Choose an appropriate replacement for /dev/sda
1) /dev/sda
2) /dev/sdb
3) Do not map …

In 300_map_disks.sh use runtime generated UserInput-IDs

---

usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh

Original gpt disk partitions may be unnamed. As _parted_ requires a name for each gpt partition, ReaR currently supplies "rear-noname" for originally unnamed partitions. This leads to systemd log messages during `rear recover` and in boot logs:
```
Dev dev-disk-by\x2dpartlabel-rear\x2dnoname.device appeared twice with different sysfs paths
```
To supply unique names for unnamed partitions, just use the basename of the partition's device path, e.g. sda1, sda2, ...
The suggested change also strips unnecessary quotes from _parted_ invocations.
Tested on Ubuntu 16.04.3 LTS (gpt only).

Avoid log messages about multiple disk partitions with identical name

---

usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/lib/_input-output-functions.sh

Now any default input is what the user would enter.
In particular now a numeric default input is no longer
the index of a choices array element (starting at '0')
(that array is an implementation detail of the UserInput function)
but now a numeric default input is the choice number that is
shown to the user (starting at '1') which the user would type in.

Cleanup and simplified default input for the UserInput function.

---

usr/share/rear/conf/default.conf
usr/share/rear/rescue/GNU/Linux/290_kernel_cmdline.sh

I propose to check the current kernel parameters used (in `/proc/cmdline`) to detect some important parameter we should use when booting in rescue mode (means  add them in KERNEL_CMDLINE variable).
Based on the discussion with @gdha in #1400, I started to detect `net.ifnames` or `biosdevname` parameter in order to preserve interface naming between rescue mode and real system after migration.

Add automatically some important kernel parameters to KERNEL_CMDLINE

---

usr/share/rear/layout/save/default/330_remove_exclusions.sh
usr/share/rear/lib/layout-functions.sh

This PR closes the existing gap between 'fs'-type file systems and mounted btrfs subvolumes (type 'btrfsmountedsubvol').
- It allows mounted btrfs subvolumes to be excluded like other components, for example:
```
EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}" "btrfsmountedsubvol:/mnt/dir" )
```
- It enables dependency management for mounted btrfs subvolumes (making sure that file systems containing btrfs mount points are recreated as well).
Related: #1496
Tested on Ubuntu 16.04.3 LTS

Fix btrfsmountedsubvol exclusion and dependency management

---

Makefile
usr/share/rear/rescue/default/500_ssh.sh

Currently, usr/share/rear/rescue/default/500_ssh.sh can only detect if SSH_ROOT_PASSWORD is MD5 encrypted.  Any string other than those with a '$1$' prefix will be encrypted using MD5.  For instance, SHA-512 encrypted passwords are common and are identified with a '$6$' prefix... but would not be detected as an encrypted password and rear would re-encrypt the already encrypted string using MD5, breaking the ability to use intended password.
Per the discussion with @schlomo and @jsmeix in https://github.com/rear/rear/pull/1489#issuecomment-329745987 , this PR improves encrypted password detection.

Improve encrypted password detection in 500_ssh.sh

---

usr/share/rear/lib/_input-output-functions.sh

Now the UserInput function supports the 'read' options
'-r' for raw input and
'-s' to not echo input from a terminal on that terminal.

Support raw input and read without echoing for confidential UserInput

---

usr/sbin/rear
usr/share/rear/lib/_input-output-functions.sh

Now a failure message like
<pre>
rear mkrescue failed, check /root/rear.master/var/log/rear/rear-e205.log for details
</pre>
is shown when it exits in any unintended way,
e.g. when it exits because [Ctrl]+[C] was pressed or
when it exits at an arbitrary command because of 'set -e'.
For the latter case cf.
https://github.com/rear/rear/issues/700#issuecomment-327755633
That failure message is not show when it exits/aborts
intentionally via the Error function plus the USR1 trap
because in this case the Error function and the USR1 trap
show already appropriate messages.

Add an ExitTask to show a failure message if it exits unintendedly.

---

usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/global-functions.sh
usr/share/rear/lib/layout-functions.sh
usr/share/rear/prep/default/950_check_missing_programs.sh

The new contains_visible_char function tests
whether or not its arguments contain at least one 'real value'
where 'real value' means to be neither empty nor only blank
or control characters.
Currently it is already used in the UserInput function and in the
get_device_name UdevSymlinkName UdevQueryName
functions in lib/layout-functions.sh and
in 950_check_missing_programs.sh
@schabrolles 
the contains_visible_char function should be in particular
useful for you when you like to ensure a value is
neither empty nor blank.
Note that using plain
<pre>
test $var && echo "var is neither empty nor blank"
</pre>
without quoting $var only works when var contains
at most one single word because it fails for strings:
<pre>
-bash: test: foo: unary operator expected
</pre>
In contrast the …

Add function to test for 'real value'

---

doc/rear.8.adoc

The lintian is manpage-has-errors-from-man and the error is
rear.8.gz 525: warning [p 6, 7.0i]: can't break line
So I just shorten the original line to prevent this.
Author: Frédéric Bonnard <frediz@linuix.vnet.ibm.com>
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
=> 3th and last back-port patch for Debian (rear-2.2) - issue #1488

Fix lintian error (debian) on rear man-page

---

usr/share/rear/finalize/GNU/Linux/320_migrate_network_configuration_files.sh
usr/share/rear/lib/network-functions.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/00-functions.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh

The objective of this PR is to update the network migration process in ReaR.
Before this PR, network migration was based on udev rules files to detect and update mac or interface name.
A) The problem is that newer Linux distro (rhel7, ubuntu) does not automatically update anymore the udev network rule files.
This prevent ReaR :
- to propose new interface in case of migration
- to rename interface and properly activate network in recovery mode
- to perform Network Migration on the restored image.
=> Migration is also currently impossible with `biosdevname` network interface name format (which is the new default for ubuntu/redhat.)
B) Network parameter migration (ip/routes via `/etc/rear/mapping/ip_addresses` or  `/etc/rear/mapping/routes`) are only compatible with RedHat/Suse sysconfig …

Improve ReaR network migration

---

doc/user-guide/06-layout-configuration.adoc
usr/share/rear/conf/default.conf
usr/share/rear/finalize/GNU/Linux/240_reassign_luks_keyfiles.sh
usr/share/rear/layout/prepare/GNU/Linux/160_include_luks_code.sh
usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh

ReaR 2.2 with cryptsetup 1.6.6 (as on Ubuntu 16.04.3 LTS) uses compiled-in default values which are not up-to-date in terms of cryptographic security:
Option | cryptsetup 1.6.6 Default | More Secure | Auto-detectable
-------|--------------------------|-------------|----------------
Key size | --key-size 256 | --key-size 512 | Yes
Passphrase processing time (msecs) | --iter-time 1000 | --iter-time 2000 | No
Random number generation device | --use-urandom | --use-random | No
For details, see [Encryption options for LUKS mode](https://wiki.archlinux.org/index.php/Dm-crypt/Device_encryption#Encryption_options_for_LUKS_mode) in the ArchWiki.
In addition, ReaR can neither auto-detect nor use existing keyfiles for the automatic decryption of recreated LUKS volumes. A recovered system will ask …

Improve cryptographic security and user-friendliness for LUKS volumes

---

usr/share/rear/lib/network-functions.sh

Change in is_ip() function to be compatible with bash 3.1 (SLES10).
using variable to store regex seems to solve the problem of quoted regex (bash <3.2) and non-quoted regex (bash >= 3.2)
This should solve issue #1522 
(to be confirmed by @gdha and @jsmeix)

Use regex in variable for bash3.1 compatibility

---

usr/share/rear/conf/default.conf
usr/share/rear/restore/default/900_create_missing_directories.sh
usr/share/rear/verify/TSM/default/400_verify_tsm.sh

Renamed DIRECTORIES_TO_CREATE into
DIRECTORY_ENTRIES_TO_RECOVER according to
https://github.com/rear/rear/pull/1513#discussion_r141318652
Plus a fix for that in  400_verify_tsm.sh
and - by the way - some code cleanup therein.

Renamed DIRECTORIES_TO_CREATE into DIRECTORY_ENTRIES_TO_RECOVER

---

usr/share/rear/build/default/500_ssh_setup.sh
usr/share/rear/conf/default.conf
usr/share/rear/rescue/default/500_ssh.sh

This intends to implement what is described in
https://github.com/rear/rear/pull/1530#issuecomment-337526810
and subsequent comments.
This removes "out-of-the-box" support in ReaR for
other secure shell software like CentrifySSH
cf. https://github.com/rear/rear/issues/836
but it does not make OpenSSH mandatory for ReaR
so that the initial problem in
https://github.com/rear/rear/issues/836
should not re-appear.
In default.conf it is now described how to set up ReaR
with a secure shell software other than OpenSSH >= 3.1
basically via
<pre>
SSH_FILES='no'
COPY_AS_IS=( "${COPY_AS_IS[@]}" my secure shell software files )
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" my secure shell programs )
</pre>
Currently I have not yet tested it.

Only support OpenSSH 3.1 and later for SSH setup

---

usr/share/rear/restore/TSM/default/400_restore_with_tsm.sh
usr/share/rear/verify/TSM/default/400_verify_tsm.sh

The goal of this PR is to allow a user to use to provide TSM login information to the console if TSM password file is missing in the ReaR rescue image. (issue #1534)

Tsm ask password

---

usr/share/rear/rescue/NBU/default/450_prepare_netbackup.sh

When using NetBackup 7 for ReaR backup (BACKUP=NBU in /etc/rear/local.conf), the NetBackup initscript (/etc/init.d/netbackup) is automatically added to the ReaR rescue image as /etc/scripts/system-setup.d/90-netbackup.sh.
Upon recovery, the agent is *not* started automatically.
Also the /etc/scripts/system-setup aborts immediately after sourcing NetBackup initscript, causing auto-recovery to not work.
The root cause is /etc/scripts/system-setup **sourcing** initscripts, instead of executing them.
This is OK for other internal scripts, but not for 3rd-party initscripts ReaR doesn't control.
In particular, netbackup executes "exit XX" at its end, causing /etc/scripts/system-setup to exit.
Suggested fix is to modify /usr/share/rear/rescue/NBU/default/450_prepare_netbackup.sh so that the …

#1523 Netbackup agents not automatically started

---

usr/share/rear/lib/layout-functions.sh

`150_save_diskbyid_mappings.sh` creates `/var/lib/rear/recovery/diskbyid_mappings` which look like this:
```
dm-name-36005076802818058480000000000037b /dev/mapper/36005076802818058480000000000037b
dm-name-36005076802818058480000000000037b_part1 /dev/mapper/36005076802818058480000000000037b_part1
dm-name-36005076802818058480000000000037b_part2 /dev/mapper/36005076802818058480000000000037b_part2
dm-name-system-APPOlv /dev/mapper/system-APPOlv
dm-name-system-root /dev/mapper/system-root
dm-name-system-swap /dev/mapper/system-swap
dm-uuid-LVM-14gcW2jEBtAEVeSWDKsobrD0HkqVM3NGBpdCO7Seomr8qvBfefUUZZ2qGl3c665e /dev/mapper/system-root
dm-uuid-LVM-14gcW2jEBtAEVeSWDKsobrD0HkqVM3NGgL4XzRRtjTHbunSy0oLFtvAhCb50F01z /dev/mapper/system-swap
dm-uuid-LVM-14gcW2jEBtAEVeSWDKsobrD0HkqVM3NGjEZqIdr0yocYNog9hDJO5 …
```

Remove unecessary /dev prefix

---

usr/share/rear/build/default/980_verify_rootfs.sh
usr/share/rear/conf/default.conf
usr/share/rear/prep/TSM/default/400_prep_tsm.sh

As explain in #1533, `rear mkrescue` failed when using with TSM because of the need of additional libraries.
This error comes from the image rescue check made in `build/default/980_verify_rootfs.sh`.
Two solutions here:  
1- Update and export LD_LIBRARY_PATH in `prep/TSM/default/400_prep_tsm.sh`. When exported, LD_LIBRARY_PATH will be inherit into the chrooted environment used in  `build/default/980_verify_rootfs.sh`:
```
for binary in $( find $ROOTFS_DIR -type f -executable -printf '/%P\n' ) ; do
chroot $ROOTFS_DIR /bin/ldd $binary | grep -q 'not found' && broken_binaries="$broken_binaries $binary"
done
```
2- We don't need all the stuff provided by the TSM client in the rescue image (~300MB). Only `dsmc` (tsm client) binary, with some libraries and config files.
I usually use the …

Update and export LD_LIBRARY_PATH when using TSM

---

usr/share/rear/build/GNU/Linux/090_create_lib_directories_and_symlinks.sh

If symlink (in /usr) points to relative target on original system, it will be incorrectly
recreated in ReaR recovery system.
This applies to links in other than root (/)
c.f. Issue https://github.com/rear/rear/issues/1555
I've omitted use of `ln` and later "guesswork" and rather used `cp` to copy original symlink "as is".

This patch correct behavior during symlink creation process of /usr/lib*

---

usr/share/rear/conf/default.conf

Add an example of an optimized COPY_AS_IS_TSM.
This one will only copy `dsmc` binary, needed libraries, passwd and default configuration files.
All the other files generated by the user must be added manually.

COPY_AS_IS_TSM optimzed example

---

usr/share/rear/build/GNU/Linux/400_copy_modules.sh

ReaR fails to find kernel modules, where aliases are present. For example, the nVidia video driver modules on Ubuntu 16.04 LTS use aliases like this: `nvidia_uvm` -> `nvidia_384_uvm`, making `rear -v mkrescue` produce error messages like this:
```
Copying only currently loaded kernel modules (MODULES contains 'loaded_modules')
ERROR: nvidia_uvm loaded but no module file?
Aborting due to an error[...]
```
This PR fixes the module lookup code. It uses `modprobe` to check for aliased modules. If the modprobe version installed does not support alias resolution via `-R`, the new code will silently fall back to the old behavior (i.e. no alias resolution).

Fix copying kernel modules when module aliases are present

---

usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh

Currently, some bootloader configurations do not honor the $KERNEL_CMDLINE configuration variable. This PR aims to fix the situation.
Background: I am trying to integrate support for TCG Opal-encrypted disks in ReaR. To do so, ReaR has to honor a setting like `KERNEL_CMDLINE="$KERNEL_CMDLINE libata.allow_tpm=1"` on rescue systems.
I've tried to fix all affected spots in ReaR, but did not dare to touch the section beginning at line 175 in `usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh`:
```
Log "Creating /rear/syslinux.cfg"
{
syslinux_write <<EOF
label rear
say Relax-and-Recover - Recover $HOSTNAME from $time
menu hide
kernel $HOSTNAME-$time
EOF
```
I just did not do sufficient research do discover the motivation behind all the different syslinux configurations in that file. …

Honor $KERNEL_CMDLINE in bootloaders

---

usr/share/rear/prep/default/040_check_backup_and_output_scheme.sh

OUTPUT_URL=null conflicts with OUTPUT=USB
because for OUTPUT=USB the script
output/USB/Linux-i386/850_make_USB_bootable.sh
wants to make the USB device bootable
which cannot work with OUTPUT_URL=null, see
https://github.com/rear/rear/issues/1571#issuecomment-343467593

Error out for OUTPUT_URL=null together with OUTPUT=USB

---

doc/rear.8
doc/rear.8.adoc
usr/sbin/rear
usr/share/rear/lib/help-workflow.sh

Let the 'debugscript mode' ( '-D' ) automatically
also set 'debug mode' ( '-d' ) and 'verbose mode' ( '-v' ).
I never use '-D' alone.
When I need the debugscript mode I always also
need debug messages and verbose command output.
Or is there a reason why '-D' alone without
debug messages and verbose command output
actually makes sense?

Let usr/sbin/rear '-D' automatically also set '-d' and '-v'

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh

Enhanced
skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh
so that recovery system startup can run unattended
when only a single MAC has changed:
If there is only one old MAC and only one new MAC
then automatically map the old MAC to the new one, cf.
https://github.com/rear/rear/issues/1399#issuecomment-344656970
When there are more MACs the user can already predefine
in /etc/rear/mappings/mac what mapping should be done
during recovery system startup and a predefined mapping
is already done automatically without a user dialog.

Enhance user dialogs in recovery system startup towards running unattended

---

usr/share/rear/build/default/980_verify_rootfs.sh

This allows the "broken_binaries" code to properly detect *.so files that have relative paths.  Prior to this change, executables which had relative paths to their *.so files would result in "not found", thus adding those executables to the $broken_binaries array.  This caused problems for one executable in FDR/Upstream version 4.0.
I've tested that this works properly, but I'd appreciate it if somebody could take a look at the code change and let me know if you see any problems.  This is code that gets used by all ReaR users, not just FDR/Upstream customers.

Let /bin/ldd detect *.so with relative paths

---

usr/share/rear/conf/default.conf
usr/share/rear/output/NSR/default/950_nsr_save_result_files.sh
usr/share/rear/prep/NSR/default/450_check_nsr_client.sh
usr/share/rear/rescue/NSR/default/450_prepare_networker_startup.sh
usr/share/rear/rescue/NSR/default/470_safe_filesystems.sh
usr/share/rear/restore/NSR/default/400_restore_with_nsr.sh
usr/share/rear/verify/NSR/default/410_verify_nsr_paths.sh

The intention behind this mode/variable is to make it possible to use the EMC Legato networker in a client only mode during recovery. Such a use case is needed if the administrator of the to-be-recovered system is not the administrator of the EMC Legato networker server itself or allowed to access it. This appears for example in an environment in which the backup-and-restore-as-a-service infrastructure is operated elsewhere.
1. NSR_CLIENT_MODE is not set or set to "no": The NSR backup method is executed as before for backwards compatibility in ReaR.
2. NSR_CLIENT_MODE is set to "yes": Several NSR actions will be skipped and during the recovery a user prompt is displayed to trigger the recovery on the remote NSRSERVER.

Add a NSR_CLIENT_MODE to the backup method NSR.

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh

Trick for unattended recovery when we have more LAN interfaces in place - see also https://github.com/gdha/rear-automated-testing/issues/36

Trick for unattended recovery when we have more LAN interfaces

---

usr/share/rear/build/default/980_verify_rootfs.sh
usr/share/rear/conf/default.conf

With the new config variable
NON_FATAL_BINARIES_WITH_MISSING_LIBRARY
the user can specify an 'egrep' pattern what programs
(i.e. files in a /bin/ or /sbin/ directory) where the 'ldd' test in
build/default/980_verify_rootfs.sh reports 'not found' libraries
are non-fatal so that those programs in the recovery system
do not lead to an Error abort of "rear mkrescue/mkbackup".
This is a generic method so that the user can avoid issues
in particular with third-party backup tools that soemtimes
have unexpected ways to use their specific libraries like
https://github.com/rear/rear/issues/1533 (for TSM) and
https://github.com/rear/rear/pull/1560 (for FDR/Upstream).
I consider it as a "minor bug" when there is no generic method
in ReaR where the user can overrule an automatism in ReaR
and as an …

Addded NON_FATAL_BINARIES_WITH_MISSING_LIBRARY

---

usr/share/rear/conf/default.conf

Now the USER_INPUT variables are officially
documented in default.conf which means
now those variables and how they work
can no longer be easily changed.
The default values are the fallback values
in the UserInput() function.
This should be one of the final steps related to
https://github.com/rear/rear/issues/1399
before the ReaR 2.3 release.

Document USER_INPUT variables in default.conf

---

usr/share/rear/lib/framework-functions.sh

Now the SourceStage shows a (non fatal)
LogPrintError message to the user when a script
without leading 3-digit number 'NNN_' is sourced
because sripts without leading 3-digit number are
likely run in wrong order.
This is a further enhancement of
https://github.com/rear/rear/issues/1054
because scripts with the old 2-digit number could exist
as leftover as old/outdated user-specific addon scripts
that had been added during an older ReaR version.
Example how it looks now with two artificially added sripts
without leading 3-digit number 'NNN_':
<pre>
...
Script 'default/033update_recovery_system.sh' without leading 3-digit number 'NNN_' is likely run in wrong order
Source init/default/033update_recovery_system.sh
Script 'default/30_update_recovery_system.sh' without leading 3-digit number …

LogPrintError when sourcing unexpected named script (issue 1054)

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
usr/share/rear/layout/prepare/default/010_prepare_files.sh
usr/share/rear/layout/prepare/default/250_compare_disks.sh
usr/share/rear/layout/prepare/default/270_overrule_migration_mode.sh
usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/layout/prepare/default/320_apply_mappings.sh
usr/share/rear/layout/prepare/default/400_autoresize_disks.sh
usr/share/rear/layout/prepare/default/500_confirm_layout_file.sh
usr/share/rear/layout/recreate/default/100_confirm_layout_code.sh

When the user can (if needed) enforce MIGRATION_MODE
he can avoid a disastrous disaster recovery as in
https://github.com/rear/rear/issues/1271
By the way I found a bug in layout/prepare/default/300_map_disks.sh
because for same disk with same size it mapped
e.g. /dev/sda to /sys/block/sda but the latter is no
block device which lets "rear recover" BugError out with
<pre>
BUG in /usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh line 35:
'Disk /sys/block/sda is not a block device.'
</pre>

Let the user enforce MIGRATION_MODE

---

usr/share/rear/backup/BORG/default/500_make_backup.sh
usr/share/rear/backup/BORG/default/800_prune_old_backups.sh
usr/share/rear/prep/BORG/default/300_init_archive.sh

This PR fixes #1588.
Borg backup as back end now honors ReaR's verbose option.
V.

Borg backup as back end now displays progress, when ReaR is launched in verbose mode

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh

Without the 1s sleep time, I got the following error `Cannot find device "eth0"` during a network migration (sles12sp2).
```
Running 55-migrate-network-devices.sh...
The only original network interface eth0 00:1a:4a:16:01:cc is not available
and no mapping is specified in /etc/rear/mappings/mac
Mapping it to the only available eth1 1a:f4:ea:94:64:0c
Reloading udev ... done.
Running 58-start-dhclient.sh...
Running 60-network-devices.sh...
Cannot find device "eth0"
Cannot find device "eth0"
Cannot find device "eth0"
Running 62-routing.sh...
Cannot find device "eth0"
Running 63-teaming.sh...
Running 65-sysctl.sh...
Running 67-check-by-label-cdrom.sh...
Running 99-makedev.sh...
```
This is solve by adding a 1s delay before triggering udev.

Add 1s sleep time before udevtrigger

---

packaging/debian/control

For Debian and Ubuntu package building and installation we move the packages isolinux and xorriso from Depends to Recommends lines
See issue #1403
A word of warning: xorriso and isolinux will NOT install automatically - when not present if required rear will bail out.
And, also story https://github.com/gdha/rear-automated-testing/issues/26 as background

Move the packages isolinux and xorriso from Depends to Recommends lines

---

usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh

This should make function get_usb_syslinux_version to return a proper version number again.
For issue #1376

Fix the bad perl expression in grep to a normal expression

---

usr/share/rear/lib/filesystems-functions.sh

In xfsprogs >= 4.7 log section sunit=0 is considered invalid.
c.f. https://github.com/rear/rear/issues/1579

Fix for XFS file system recreation code.

---

usr/share/rear/skel/default/usr/lib/systemd/system/sysinit.service

This fixes Issue #1609.
Before patching:
- dhclient is killed after /etc/scripts/system-setup exited
After patching:
- dhclient is still alive after /etc/scripts/system-setup exited
Same applies to NetBackup daemons if applicable.

Issue #1609: keep daemons spawned by sysinit.service alive upon exit

---

usr/share/rear/rescue/default/500_ssh.sh
usr/share/rear/skel/default/etc/scripts/run-sshd

See
https://github.com/rear/rear/issues/1512#issuecomment-347912101
and subsequent comments, in particular see
https://github.com/rear/rear/issues/1512#issuecomment-347927227
but I decided to keep the
<pre>
if grep -q '^ssh:' /etc/inittab ; then
</pre>
in skel/default/etc/scripts/run-sshd
because as far as I understand it a
"ssh:23:respawn:..." entry in /etc/inittab is written by
rescue/default/500_ssh.sh only if sshd should be started.

Make ssh key generation in recovery system also work for SysVinit

---

usr/share/rear/lib/config-functions.sh

For issue #731 we tried to avoid the usage of `lsb_release`, therefore, we try to extract all required info from `/etc/os-release`, or `/etc/system-release`, or `/etc/issue` before falling back to `lsb_release`.
In later stadium we will also write the `/etc/rear/os.conf` file instead of being auto-created by installing the rpm. For Debian or Ubuntu that did not happen. So, that is one of the reasons to harmonize the creation of `/etc/os.conf`.
This PR is **not** complete, but I wanted to push it forward for your comments etc...

config-functions.sh - partial rewrite of SetOSVendorAndVersion

---

usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh

For details see my https://github.com/rear/rear/issues/1618#issuecomment-348712258

xfs_info (>= 4.12.0) does not accept device file as valid option, but mountpoint must be used instead.

---

usr/share/rear/layout/prepare/default/250_compare_disks.sh

@jsmeix, as explain directly in #1596, I got the following small bug ...
```
RESCUE rear-rhel-142:~ # rear -D recover
Relax-and-Recover 2.2 / Git
Using log file: /var/log/rear/rear-rear-rhel-142.log
Running workflow recover within the ReaR rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.statd if available.
Started RPC portmapper 'rpcbind'.
RPC portmapper 'rpcbind' available.
Started rpc.statd.
RPC status rpc.statd available.
Started rpc.idmapd.
Using backup archive '/tmp/rear.xAzGbMuWwaH3TfJ/outputfs/rear-rhel-142/backup.tar.gz'
Calculating backup archive size
Backup archive size is 1003M	/tmp/rear.xAzGbMuWwaH3TfJ/outputfs/rear-rhel-142/backup.tar.gz (compressed)
Setting up multipathing
Activating multipath
multipath activated
Listing …
```

Ignore disk size of multipath slave in 205_compare_disk.sh

---

usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
usr/share/rear/prep/GNU/Linux/280_include_systemd.sh
usr/share/rear/skel/default/etc/scripts/dhcp-setup-functions.sh

1. **Be aware the -`h` PR has been removed!**
2. commented out in `skel/default/etc/scripts/dhcp-setup-functions.sh`
the _localtime_ copy lines (as the `/usr/share/zoneinfo` is not
present anyway in the rescue environment)
3. added `systemd-tmpfiles` within the systemd frame-work to fix issue #1575

systemd-tmpfiles required for rpcbind and comment some unneeded code

---

usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh

The might be a typo in https://github.com/rear/rear/blob/master/usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh#L397
if test -n "btrfs_subvolume_path" ; then
if test -n "$btrfs_subvolume_path" ; then
Or not?

typo in: if test -n "btrfs_subvolume_path" ; then ?

---

usr/share/rear/layout/prepare/default/250_compare_disks.sh

I thought having already corrected this one ... (I may be forgot to push it).

BUG: must continue if device is a multipath slaves

---

usr/share/rear/prep/default/400_save_directories.sh

`: > $file` is equivalent (not identical) to `touch $file`
(Besides cat is a concatenation tool.)

cat /dev/null input shortened to :

---

usr/share/rear/backup/DUPLICITY/default/500_make_duplicity_backup.sh
usr/share/rear/conf/default.conf
usr/share/rear/prep/DUPLICITY/default/200_find_duply_profile.sh
usr/share/rear/prep/DUPLICITY/default/210_check_NETFS_URL_requirements.sh

…PR #1554 found some issues
(like issue #1668 and #1665). This is the first batch to correct this (and hopefuly the last one).
DUPLY_PROFILE and BACKUP_DUPLICITY_URL were running in each others way for one, had big trouble to
fix the BACKUP_DUPLICITY_GPG_OPTIONS variable interpretation, but has been fixed at last.
More test are required to be 100% sure the recovery is working as it is supposed to work. For next year (tomorrow?)
Greeting from 2017 - Gratien

After testing duplicity (and duply) with the latest commits #1554

---

usr/share/rear/prep/default/400_save_directories.sh

What is the definition of unwanted "noise" from the mount points?
https://github.com/karelzak/util-linux/blob/master/libmount/src/utils.c#L267
till
https://github.com/karelzak/util-linux/blob/master/libmount/src/utils.c#L299
contain more then 3 pseudo file systems "cgroup|fuse.*|nfsd".
Which of libmount/src/utils.c additional pseudo-FS are also "noise" in this context?
I have included them all here, with the goal to easily remove the file systems that are needed are.

mount noise in 400_save_directories excluded_fs_types?

---

usr/share/rear/lib/global-functions.sh
usr/share/rear/restore/DUPLICITY/default/110_check_temp_dir_with_duply.sh
usr/share/rear/restore/DUPLICITY/default/150_restore_duply.sh

- moved function to find duply conf file to global-functions.sh as it is used by the prep and restore phase 
- new script (110_check_temp_dir_with_duply.sh) to make sure the TEMP_DIR is /mnt/local/tmp instead of tmp (to avoid out of disk space) and it must be located in the restore dir and not in the verify as /mnt/local is not created yet at that time
- Be a bit more verbose in script 150_restore_duply.sh
**_This should fix all implementation issues with the `duply` wrapper for duplicity (issue #1664)_**

Make duply wrapper work again

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

Don't even read *.rpmb $blockd.
Error: Partition mmcblk0rpmb is numbered ''. More than 128 partitions is not supported.

FIXME comments for *rpmb block devices

---

usr/share/rear/layout/compare/default/500_compare_layout.sh
usr/share/rear/layout/precompare/default/110_check_layout_file.sh
usr/share/rear/lib/checklayout-workflow.sh

Sort layout entries before comparing
to avoid a falsely detected changed layout.
This should fix https://github.com/rear/rear/issues/1657
Tomorrow I try to also fix https://github.com/rear/rear/issues/1658
but that looks more complicated...

Avoid falsely detected changed layout (issues 1657 and 1658)

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

fix the bad `elif [[ ! ( = *rpmb || *[0-9]boot[0-9])` statement - PR #1667 (script /usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

FIX rpmb block devices check in 200_partition_layout.sh

---

usr/share/rear/finalize/AVA/default/990_copy_avagentlog.sh
usr/share/rear/rescue/AVA/default/450_prepare_avagent_startup.sh
usr/share/rear/restore/AVA/default/200_prompt_user_to_start_restore.sh

Starting of the avagent.bin used to be done at boot time by "restore\AVA\default\200_prompt_user_to_start_restore.sh", but as the AVA_ROOT_DIR variable declared in default.conf is not present resulted in error. Instead now a script is created during mkresuce (-> rescue\AVA\default\450_prepare_avagent_startup.sh), which does the same. Simialr NSR/EMC Networker script used as example.

Move EMC Avamar daemon starting to rescue step

---

usr/share/rear/layout/save/GNU/Linux/510_current_disk_usage.sh

There is no purpose of including the target device in df.txt
Removing that section makes the df.txt better human readable.
TODO#1: only for USB workflow?
TODO#2: make the EFI partition optional (only needed when the target (USB) device contains an EFI partition).
TODO#3: improve line breaking

exclude REAR-000 and ESP from df.txt

---

packaging/debian/control

As of ReaR version 2.3, a Debian installation pulls in packages which are only used in specific configurations: `nfs-client, portmap, xorriso, isolinux`. Along with indirect dependencies, this installs lots of unnecessary packages on systems not requiring the respective functionality.
This PR aims to reduce dependency bloat by default. Unlike recommended packages, suggested packages will not be installed by default, but can be pulled in on demand via the `apt` option `--install-suggests`.
The PR includes additional dependencies for #1659.
Maybe even some required dependencies could be relaxed to suggestions, for example: `syslinux[!ppc64el], syslinux-common[!ppc64el]`

Relax Debian dependencies (change 'Recommends' to 'Suggests')

---

usr/share/rear/verify/NETFS/default/550_check_backup_archive.sh

the md5sum command expects the file to reside in local directory

#1685 Cannot restore backup when BACKUP_INTEGRITY_CHECK=1

---

usr/share/rear/restore/TSM/default/400_restore_with_tsm.sh

Removed the overcomplicated way how
the "dsmc restore" command is called in
restore/TSM/default/400_restore_with_tsm.sh
and call it as
<pre>
dsmc restore ... 0<&6 1>&7 2>&8
</pre>
in compliance with "What to do with stdin, stdout, and stderr" in
https://github.com/rear/rear/wiki/Coding-Style

Simplified TSM dsmc restore (issue 1534)

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/AVA/default/990_append_avagentlog.sh
usr/share/rear/finalize/AVA/default/990_copy_avagentlog.sh
usr/share/rear/rescue/AVA/default/450_prepare_avagent_startup.sh
usr/share/rear/restore/AVA/default/200_prompt_user_to_start_restore.sh

Avamar agent has to be started via "systemctl start avagent" to function properly, otherwise the Avamar server does not recognize the client correctly and cannot restore with the function "Restore everything to a different location" (which is needed to restore to /mnt/local). This pull request includes the necessary patches, so that the necessary scripts are included into the ReaR image.

Complete EMC Avamar integration

---

usr/share/rear/backup/BORG/default/500_make_backup.sh
usr/share/rear/backup/BORG/default/800_prune_old_backups.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/borg-functions.sh
usr/share/rear/prep/BORG/default/300_init_archive.sh

Borg common options have possibility to set umask (--umask) for archive operations.
Until this commit, there was no way to adapt umask for Borg archives from within ReaR.
C.f. https://github.com/rear/rear/issues/1699

Added option BORGBACKUP_UMASK.

---

usr/share/rear/prep/BAREOS/default/570_check_bareos_plugin_dir.sh

New script 570_check_bareos_plugin_dir.sh is to copy the Bareos plugin directory to the rescue image - issue #1692

copy the Bareos plugin directory 

---

usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
usr/share/rear/lib/global-functions.sh
usr/share/rear/verify/default/040_validate_variables.sh

Implemeted two new general useful functions percent_encode() and percent_decode()
but currently percent_encode() fails for me on SLES11-SP4 with GNU bash version 3.2.57
in case of UTF-8 encoded strings (hopefully nobody uses a UTF-8 encoded GPT partition name)
cf. https://github.com/rear/rear/issues/1563#issuecomment-359797990
Those functions are used to again support GPT partition names with blanks and
re-implemented some quoting hell to provide what parted command line calls need
according to
https://github.com/rear/rear/issues/1563#issuecomment-359784102
By the way I additionally
replaced is_numeric() with hopefully new more generally usable functions
is_integer() and is_positive_integer() that also return a useful return code
and I better documented what read_and_strip_file() actually …

Again support partition names with blanks issues 212 and 1563

---

doc/user-guide/09-design-concepts.adoc

Doc seems to incorrectly state that the code would check for running from tmpfs or ramdisk. The actual check in code that I can find is much simpler: "test -e /etc/rear-release" at <https://github.com/rear/rear/blob/master/usr/sbin/rear>
Better reflect the actual behavior in documentation.

tmpfs/ramdrive -> test -e /etc/rear-release

---

usr/share/rear/backup/DUPLICITY/default/500_make_duplicity_backup.sh
usr/share/rear/prep/DUPLICITY/Debian/100_debian_lib.sh
usr/share/rear/prep/DUPLICITY/default/050_prep_duplicity.sh
usr/share/rear/restore/DUPLICITY/default/400_restore_duplicity.sh

This will stop the Duplicity restore from Erroring out if the Temporary Directory is on an Ramdisk. Also I've cleaned some things up and Fixed an Issue with the librsync library on Debian.

Fix Duplicity

---

usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf
usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf
usr/share/rear/conf/examples/SLE12-btrfs-example.conf

Simpler `findmnt` command example in comment
<pre>
findmnt -n -r -o TARGET -t btrfs | grep -v '^/$' | egrep -v 'snapshots|crash'
</pre>
and more fail-safe BACKUP_PROG_INCLUDE example array
that contains now plain directories `/dir` instead of `/dir/*`
so that now also the directory itself and dot-files `/dir/.file`
get included in the backup, see
https://github.com/rear/rear/issues/1714

Simpler and more fail-safe SLE btrfs example configs (issue 1714)

---

packaging/rpm/rear.spec
usr/share/rear/init/default/005_verify_os_conf.sh
usr/share/rear/lib/config-functions.sh

Remove the os.conf creation in the rear.spec file and fixed in function SetOSVendorAndVersion the proper detection of RedHatEnterpriseServer. Added new script usr/share/rear/init/default/005_verify_os_conf.sh to create the os.conf if it did not exist yet - issue #1639

Remove the os.conf creation in the rear.spec file

---

usr/share/rear/lib/_input-output-functions.sh

In lib/_input-output-functions.sh
there is now a new function descendants_pids()
that outputs PIDs of all descendant processes of a parent process PID
where the output lists latest descendants PIDs first and the initial parent PID last
(i.e. great-grandchildren PIDs, grandchildren PIDs, children PIDs, parent PID)
so that the output ordering is already the right ordering to cleanly terminate
a sub-tree of processes below a parent process and finally the parent process
and this termination functionality is used in the DoExitTasks() function
to do a clean termination of descendant processes that should fix
https://github.com/rear/rear/issues/1712

Clean termination of descendant processes (issue 1712)

---

usr/share/rear/rescue/GNU/Linux/310_network_devices.sh

Since some network drivers do not set the `operstate` value to `down` or `up`, we can fallback to using the `carrier` value:
- failing to read the value means interface is administratively down
- reading 0 means down
- reading 1 means up

Issue #1701: Use a fallback to get interface state using the 'carrier' status

---

usr/share/rear/layout/save/NSR/default/650_check_iso_recoverable.sh

* Type: Bug Fix
* Impact: Low
* Reference to related issue (URL): none.
I tested the pull request on a CentOS 6.9 VM and a RHEL6 and 7 based server.
The script `650_check_iso_recoverable.sh` exits with FALSE if it cannot find an ISO image stored on the NSR_SERVER.
In case the "NSR_CLIENT_MODE" is set to "yes" saving an ISO image to the NSR_SERVER is not allowed. Because of this `rear checklayout` (in the cronjob "rear") is always FALSE in this mode and a rescue image is created daily even if not required.
This pull request shall correct the behaviour with skipping the ISO check in the mode NSR_CLIENT_MODE=yes.

Correction to the 650_check_iso_recoverable.sh for NSR_CLIENT_MODE

---

usr/share/rear/conf/default.conf
usr/share/rear/rescue/default/430_prepare_timesync.sh

* Type:  **Enhancement** 
* Reference to related issue (URL): 
#1622 and #1623
Created CentOS 6 (init-based) and CentOS 7 (systemd-based) VMs in Virtualbox and tested rescue ISOs for all 4 TIMESYNC options on both systems.
Added chrony support so that newer systems that ship with chrony vs ntp, like RHEL/CentOS 7, are able to sync system time during rescue/restore.
430_prepare_timesync.sh will also not update ROOTFS_DIR/etc/inittab if the system is systemd-based.
While I was here, I updated the options for rdate to include -l (use syslog) and -p (print remote system time) so that rdate output is as close to the other 3 TIMESYNC options.

430 prepare timesync.sh chronyd support

---

usr/share/rear/conf/default.conf

Add `/usr/local/ibm/gsk8` to TSM_LD_LIBRARY_PATH in default.conf.
This solves issue #1688

Add /usr/local/ibm/gsk8 to TSM_LD_LIBRARY_PATH

---

usr/share/rear/finalize/Linux-ppc64le/620_install_grub2.sh

* Reference to related issue (URL):  https://github.com/rear/rear/issues/1710
https://www.suse.com/fr-fr/support/update/announcement/2017/suse-ru-20170617-1/
Tested on RHEL 7 BareMetal (PowerNV) [ReaR Backup + restore with NFS+PXE]
Tested on RHEL 7 KVM Guest for non-regression test [ReaR Backup + restore with NFS+PXE]
Tested on RHEL 7 LPAR (PowerVM) for non-regression test [ReaR Backup + restore with NFS+PXE]
**Problem description:** grub2-install failed on PowerNV (BareMetal System).
grub2-install for power (ppc64le) always try to update firmware boot order during grub2-install by …

use grub2-install --no-nvram on PowerNV system

---

usr/share/rear/conf/default.conf
usr/share/rear/prep/TSM/default/400_prep_tsm.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1688
tested on RHEL7.4 ppc64le with TSM 8.1
detect gsk lib PATH and add it into `TSM_LD_LIBRARY_PATH` (in `usr/share/rear/prep/TSM/default/400_prep_tsm.sh`)

Add gsk libs to TSM_LD_LIBRARY_PATH

---

usr/share/rear/conf/GNU/Linux.conf

* Reference to related issue (URL): https://github.com/rear/rear/issues/1710
Tested on RHEL 7 BareMetal (PowerNV) [ReaR Backup + restore with NFS+PXE]
Tested on RHEL 7 KVM Guest for non-regression test [ReaR Backup + restore with NFS+PXE]
Tested on RHEL 7 LPAR (PowerVM) for non-regression test [ReaR Backup + restore with NFS+PXE]
Add by default dbus user and group in the rescue image.
dbus is used by systemd to startup some services (like serial console detection)

Add dbus user and group by default

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/prepare/default/010_prepare_files.sh
usr/share/rear/layout/prepare/default/420_autoresize_last_partitions.sh
usr/share/rear/layout/prepare/default/430_autoresize_all_partitions.sh
usr/share/rear/layout/prepare/default/540_generate_device_code.sh
usr/share/rear/layout/recreate/default/200_run_layout_code.sh
usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
usr/share/rear/layout/save/GNU/Linux/510_current_disk_usage.sh
usr/share/rear/lib/layout-functions.sh

https://github.com/rear/rear/issues/1731
Currently this is in a "submit early" state
where subsequent "submit often" commits will follow
that is currently mainly intended for others to see what I have up to now
which is currently only a little bit tested by me
Renamed 400_autoresize_disks.sh into 430_autoresize_all_partitions.sh
to keep full backward compatible old weird behaviour but now that
needs to be explicity wanted by the user via the new config variable
AUTORESIZE_PARTITIONS=true
and
implemented new default 420_autoresize_last_partitions.sh
that only resizes the last partition on each disk (if at …

Replace 400_autoresize_disks by 420_autoresize_last_partitions and 430_autoresize_all_partitions

---

usr/share/rear/lib/_input-output-functions.sh

https://github.com/rear/rear/issues/1747#issuecomment-371055121
https://github.com/rear/rear/issues/700#issuecomment-327755633
In usr/share/rear/layout/prepare/default/420_autoresize_last_partitions.sh
use an unbound variable for testing e.g. as follows
<pre>
set -e -u -o pipefail
echo "$DOESNOTEXIST"
</pre>
which lets that script abort.
Without the fix it looks during "rear recover"
<pre>
RESCUE d57:~ # rear -D recover
...
Confirm or edit the disk mapping
1) Confirm disk mapping and continue 'rear recover'
2) Edit disk mapping (/var/lib/rear/layout/disk_mappings)
3) Use Relax-and-Recover shell and return back to here
4) Abort 'rear recover'
(default '1' timeout 300 seconds) …

Run exit tasks code with default bash flags and options (issues #700 and #1747)

---

usr/share/rear/restore/NBU/default/400_restore_with_nbu.sh

When NetBackup restoration fails, the error code printed was always `0`, due to a bad use of the `$?` variable.

Fixed invalid reported return code (always 0) upon NBU restoration failure

---

usr/share/rear/layout/save/default/445_guess_bootloader.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1752
* How was this pull request tested? on AWS system
* Brief description of the changes in this pull request: AWS system uses GRUB as bootloader, but the boot disk was identified as EFI

additional check for Hah!IdontNeedEFI #1752

---

usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/lib/_input-output-functions.sh

https://github.com/rear/rear/issues/1755
On my SLES11 and SLES12 systems.
Show descendant processes PIDs with their commands in the log
so that later the plain PIDs in the log get more comprehensible.
What works sufficiently on all systems is "pstree -Aplau $MASTER_PID"
but the pstree command is not available in the ReaR recovery system
so that the ps command is used as fallback.

Replace pstree by ps command (issue#1755)

---

usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1749
* How was this pull request tested? on AWS docker system
* Brief description of the changes in this pull request: The file systems used by the docker images should not be saved in the `diskalyout.conf` file

exclude docker FS from layout #1749

---

usr/share/rear/layout/save/GNU/Linux/270_hpraid_layout.sh
usr/share/rear/lib/hp_raid-functions.sh

Tested with ReaR 2.3 under RHEL7.4 on a HP DL360 Gen9 with SPP 2017.10 installed.
This change is required because in HP's SPP (Service Pack for Proliant) the hpacucli/hpssacli is now (recognised with Version 3.10) called "ssacli" and the installation directory's name has been renamed as well.

Update hp_raid-functions.sh and 270_hpraid_layout.sh

---

usr/share/rear/backup/TSM/default/400_create_include_exclude_files.sh
usr/share/rear/backup/TSM/default/500_make_TSM_backup.sh

This is the first draft of TSM backup.
Now, a TSM incremental backup is started when the command `rear mkbackup` or `rear mkbackuponly` is executed.
- TSM client must be installed and properly configured
- file exclusion is managed by TSM in configuration files.

First draft of TSM backup

---

usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
usr/share/rear/lib/layout-functions.sh

* Impact:  **Normal**
Tested in PowerVM environment, with RHEL7.4, with a disk Migration.
RedHat use to add **no** prefix between multipath device name a partition number (ex: `/dev/mapper/mpatha1"). In that case, multipath option `user_friendly_name` is activated (which is RedHat default).
When `user_friendly_name` is disabled, RedHat adds a **"p"** prefix between multipath device name (WWID in that case) and partition number. (ex: `/dev/mapper/3600507680c82004cf8000000000000d8p1`).
I propose the following:
- During the 1st replacement change, replace **ALL** known …

Fix partition replacement

---

usr/share/rear/layout/save/default/445_guess_bootloader.sh

https://github.com/rear/rear/pull/1754
https://github.com/rear/rear/pull/1752
I cannot test the 'Hah!IdontNeedEFI' case because
I do not have a system with a GPT BIOS boot partition.
When in the 'Hah!IdontNeedEFI' case no known non-EFI bootloader is found
continue guessing the used bootloader by inspecting the first bytes on the next disk
because otherwise the default code below would falsely guess that 'EFI' is used
cf. https://github.com/rear/rear/pull/1754#issuecomment-383531597
and subsequent comments.

Fix 'Hah.IdontNeedEFI' case.

---

usr/share/rear/conf/default.conf
usr/share/rear/rescue/GNU/Linux/500_clone_keyboard_mappings.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/10-console-setup.sh

Also include other keyboard mappings to also support users with a non-US keyboard
because without the right keyboard mapping it could become an awful annoyance
to work in the recovery system.
Actually this provides a workaround when in
etc/scripts/system-setup.d/10-console-setup.sh
the `loadkeys /etc/dumpkeys.out` fails.
* Impact: **Low** and **High**
For US-keyboard users the impact is at most low,
for non-US-keyboard users the impact could be even critical.
It works for me on a SUSE system.
I don't know where on other systems the other keyboard mapping files are stored.
But it is now at least a starting point that can be easily enhanced for other systems. …

Also include other keyboard mappings to support non-US keyboards

---

usr/share/rear/lib/drlm-functions.sh

* Reference to related issue (URL): https://github.com/brainupdaters/drlm/issues/68
Tested on RHEL and Debian based systems.
With source instead of eval makes more sense ans solves the issue. 
Before latest changes on DRLM API was necessary to eval the received config but now we are downloading config to file and source is more convenient and solves the issue.

Solve problem with some variables loading config from DRLM drlm issue  brainupdaters/drlm#68

---

usr/share/rear/layout/save/default/320_autoexclude.sh

https://github.com/rear/rear/issues/1767
SLES12SP2 on POWER with multipath devices
The actual code without this patch just exclude "real disk" which doesn't have fs mounted, not mutlipath devices.
This path check if fs has parent device in disk AND multipath, then exclude disk and multipath with no fs mounted.

exclude multipath device that does not have mounted fs

---

usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh

tested on POWER with sles11sp4 
Having multipathd daemon started when not needed could bring some side-effect on some linux distribution (like sles11sp4). 
This could happen if you recover a system that previously used mutlipathed (with BOOT_ON_SAN=y) 
The purpose of the PR is to unload dm-multipath module (when user confirm that multipath is not needed) and only start multipath deamon if needed.

Do not start multipathd when not needed

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

https://github.com/rear/rear/issues/1766
https://github.com/rear/rear/issues/1796
- SLES12SP2 (ppc64le) with multipath devices
- RHEL7 (ppc64le) with multiapth devices
This patch use `/sys/block/dm-X/holders` directory of the multipathed device to get `dm-` name of its partions.

Better way to get multiapth partion name.

---

usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
usr/share/rear/lib/layout-functions.sh
usr/share/rear/prep/GNU/Linux/220_include_lvm_tools.sh

Using 'vgcfgrestore' to restore Thin LVs doesn't work, because there
isn't the metadata in the configuration file.
To be able to use Thin LVs, upon failure of 'vgcfgrestore' (or migration),
traditional 'vgcreate/lvcreate' are used instead.
This approach is sub-optimal because it requires to know all the
possible options to 'lvcreate', which is hard/impossible to do.
Nonetheless, this is better than nothing since the issue with 'lvcreate'
options was already there in case of migration.
The code using 'lvcreate' only runs upon 'vgcfgrestore' failure, which
typically happens only with Thin LVs (IMHO). Hence, on most setups, the
optimized code will still run, preventing any regression to happen.
Signed-off-by: Renaud Métrich <rmetrich@redhat.com>
PLEASE TEST MORE.
I tested as follows:
- …

Issue #1380 - ReaR recovery fails when the OS contains a Thin Pool/Volume

---

usr/share/rear/build/default/980_verify_rootfs.sh
usr/share/rear/lib/sesam-functions.sh

* Impact:  **Normal** /
*
On some systems (for example centos6 and/or ubuntu) REAR backup with Backup type SESAM
fails during verify of the rootfs due to missing libraries:
```
/opt/sesam/bin/sesam/Crypto.Hash._SHA256.so requires additional libraries (fatal error)
libpython2.7.so.1.0 => not found
/opt/sesam/bin/sesam/cPickle.so requires additional libraries (fatal error)
libpython2.7.so.1.0 => not found
ERROR: ReaR recovery system in '/tmp/rear.LyKD3Rt2V4XgYs2/rootfs' not usable
```
these libraries are part of the Sesam client integration itself but unfortunately are not found
due to the sesam installation directory not beeing part of LD_LIBRARY_PATH.
For TSM an alike issue has already been fixed as TSM sets the LD_LIBRARY_PATH:
``` …
```

Sesam integration: add sesam bin directory to LD_LIBRARY_PATH

---

usr/share/rear/conf/default.conf
usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
usr/share/rear/restore/NETFS/default/400_restore_backup.sh
usr/share/rear/restore/TSM/default/400_restore_with_tsm.sh
usr/share/rear/wrapup/default/990_copy_logfile.sh

https://github.com/rear/rear/pull/1797
Works for me with BACKUP=NETFS.
Not tested BACKUP=TSM but also changed for that
@schabrolles please have a look regarding TSM
in particular related to https://github.com/rear/rear/pull/1799
Have backup restore log in the new separated directory $VAR_DIR/restore/
and copy that directory contents into the recreated system a the end of
"rear recover" via usr/share/rear/wrapup/default/990_copy_logfile.sh

Copy backup restore log into recreated system (related to pull request 1797)

---

usr/share/rear/build/GNU/Linux/110_touch_empty_files.sh
usr/share/rear/build/default/502_include_mdadm_conf.sh
usr/share/rear/prep/GNU/Linux/230_include_md_tools.sh

Trying to restore a backup of a system booting with multipath + software
raid, at the rescue prompt, after starting multipathd or executing "rear
recover", the multipath devices are not found.
This is due to mdadm building the array at boot, preventing multipath
from grabbing the disks later.
Solution: Disable automatic building of software raids (mdadm) by
ignoring the corresponding udev rule.
Tested on RHEL7 and RHEL6.
**Requires additional testing on Ubuntu and SLES (sorry I don't have
these).**
Signed-off-by: Renaud Métrich <rmetrich@redhat.com>
Enhancement
Normal
* Reference …

Issue #1722 - Cannot restore disk built on multipath + md

---

usr/sbin/rear
usr/share/rear/conf/default.conf
usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
usr/share/rear/finalize/GNU/Linux/250_migrate_lun_wwid.sh
usr/share/rear/finalize/GNU/Linux/260_rename_diskbyid.sh
usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
usr/share/rear/finalize/Linux-i386/620_install_grub2.sh
usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/layout/prepare/default/320_apply_mappings.sh
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/layout-functions.sh
usr/share/rear/output/ISO/Linux-ia64/800_create_isofs.sh
usr/share/rear/wrapup/default/990_copy_logfile.sh

Fixed, simplified and enhanced GRUB2 installation
plus fixed typos 'whereto' -> 'where to'
https://github.com/rear/rear/issues/1828
Currently tested only on SLES12 to keep backward compatibility
(as far as I can test it with reasonable effort for me).
I need to also test it on SLES15 (tomorrow).
Fixed finalize/Linux-i386/620_install_grub2.sh according to
https://github.com/rear/rear/issues/1828#issuecomment-398717889
Enhanced GRUB2 installation by the new config variable
GRUB2_INSTALL_DEVICES so that now the user can specify
what he wants if needed.
Cleaned up finalize/Linux-i386/620_install_grub2.sh …

Fixed, simplified and enhanced GRUB2 installation

---

usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
usr/share/rear/pack/Linux-i386/300_copy_kernel.sh

Tested on laptop running Slackware 14.2 with grub upgraded to v2.02.
Used "rear -d -D mkbackup" to successfully create a bootable USB drive.  Booted ReaR rescue image but did not run recover.  The backup tar was available on the USB.
Changed two files to add support for Slackware 14.2 distro.

add support for Slackware UEFI/USB

---

usr/share/rear/output/PXE/default/800_copy_to_tftp.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1861
* How was this pull request tested? Still need to test it out via ReaR Automated Testing
* Brief description of the changes in this pull request: add ldlinux.c32 to the PXE boot area

fedora28: missing ldlinux.c32 prevents PXE booting

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
usr/share/rear/finalize/Linux-i386/620_install_grub2.sh
usr/share/rear/finalize/Linux-ppc64le/620_install_grub2.sh
usr/share/rear/lib/layout-functions.sh

Fixed, simplified and enhanced GRUB2 installation for PPC64/PPC64LE
https://github.com/rear/rear/pull/1843
and
https://github.com/rear/rear/issues/1828
Not at all by me because I have no PPC64/PPC64LE system.
Fixed finalize/Linux-ppc64le/620_install_grub2.sh according to
https://github.com/rear/rear/issues/1828#issuecomment-398717889
Enhanced GRUB2 installation by the new config variable
GRUB2_INSTALL_DEVICES so that now the user can specify
what he wants if needed.
Aligned code in finalize/Linux-ppc64le/620_install_grub2.sh
with the code in finalize/Linux-i386/620_install_grub2.sh
as far as I could from …

Fixed, simplified and enhanced GRUB2 installation for PPC64/PPC64LE

---

usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh

Tested on laptop running Slackware 14.2 with grub upgraded to v2.02.
Used "rear -d -D mkrescue" to successfully create a bootable ISO image burned to DVD. Booted ReaR rescue image but did not run recover. 
Changed 3 files to add support for Slackware ISO rescue image.

mods to allow slackware ISO image and udev sda fix

---

usr/share/rear/output/PXE/default/800_copy_to_tftp.sh

* Reference to related issue (URL):https://github.com/rear/rear/issues/1866
* How was this pull request tested?yes, via ReaR Automated Testing
* Brief description of the changes in this pull request: fixes PXE HD discovery

fedora28: syslinux needs libcom32.c32 to boot from HD

---

usr/share/rear/build/default/995_md5sums_rootfs.sh
usr/share/rear/conf/default.conf
usr/share/rear/skel/default/etc/scripts/system-setup

I think the impact is `high` regardless that in practice it should be rarely needed
but when files in the recovery system are corrupt it is basically a must to detect them.
https://github.com/rear/rear/issues/1859
and
https://github.com/rear/rear/issues/1724
By me on my usual simple SLES12 QEMU/KVM test system.
I expect some more false positives where it fails to verify the md5sum of certain files
on other systems and in particular in more complicated environments.
During "rear mkrescue/mkbackup" the new script
build/default/995_md5sums_rootfs.sh
creates md5sums for all regular files in in the recovery system
and stores …

Verify md5sums of files in recovery system (issue #1859)

---

usr/share/rear/lib/bootloader-functions.sh

https://github.com/rear/rear/issues/1871
not yet tested
Use `grep ' on / '` with explicitly specified spaces as separators instead of `grep -w 'on /'`
because on SLES with btrfs and snapper the latter results two matches that result
two same UUIDs (with newline) that end up (with newline) in the boot menuentry

Aviod duplicate UUID in boot menuentry when snapper is used (issue #1871)

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh

https://github.com/rear/rear/issues/1832
by me on my SLES12 test system
with `debug` kernel command line parameter
when booting the ReaR recovery system
and the `set -x` output of system-setup.d/40-start-udev-or-load-modules.sh
looks good to me.
Now system-setup.d/40-start-udev-or-load-modules.sh
waits up to 10 seconds for systemd-udevd to ensure
this needed deamon has sufficient time to start up
which by the way avoids an broken pipe error
of the too fast test that was done before.

Wait for systemd-udevd to avoid broken pipe error in 40-start-udev-or-load-modules.sh

---

usr/share/rear/restore/DUPLICITY/default/400_restore_duplicity.sh

https://github.com/rear/rear/issues/1879
Via partial restore
This removes the overwriting of $HOSTNAME in 400_restore_duplicity.sh.
Just removing the Line should be enough especially because $HOSTNAME isn't overwritten on Duplicity Backup.

Remove overwrite of $HOSTNAME in 400_restore_duplicity.sh

---

usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/output/default/200_make_prefix_dir.sh
usr/share/rear/skel/default/etc/scripts/system-setup
usr/share/rear/verify/USB/NETFS/default/540_choose_backup_archive.sh

https://github.com/rear/rear/issues/1875#issuecomment-407039065
and subsequent comment
By me as in https://github.com/rear/rear/issues/1875#issuecomment-406987662
Now the `Error` function shows the last 5 lines of stdout and stderr messages
of the called programs on the user's terminal that should hopefully
make the root cause of an eooro exit more obvious to the user
without the need to analyze the log file in any case.
Additionally I adapted output/default/200_make_prefix_dir.sh
to provide a better Error function text that now talks about
`Failed to create ... directory under the mounted network filesystem share`.
How …

Show last programs messages in Error function (related to issue1875)

---

usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1883
tested with SLES12SP3
When loading multipath devices in rescue mode, ReaR rescue print to the user the name / UUID / size of the discovered multipath device.
if multipath is used with "friendly_name" option, the output of the command `multipath -l` is 
```
<friendly_mpath_name> (<mpath UUID>) <dm-name> <Vendor, type>
rootvg (3600507680c82004cf800000000000306) dm-2 IBM     ,2145 
```
while it is a bit different when "friendly_name" is disabled
```
<mpath UUID> <dm-name> <Vendor, type> …
```

Print multipath device name during rescue  when firendly_name is off

---

usr/share/rear/finalize/Linux-ppc64le/680_install_PPC_bootlist.sh

* Reference to related issue (URL): [https://github.com/rear/rear/issues/1886](#1886)
Tested on AIX/LPAR/PPC64le with 2 prep partitions, but no multipath on older ReaR 2.00 version
- Added handling of multiple *prep* partitions
- Enhanced handling of multiple *prep* partitions and multipath

#1886 - LPAR/PPC64 bootlist is incorrectly set when having multiple 'prep' partitions

---

usr/share/rear/build/default/995_md5sums_rootfs.sh
usr/share/rear/skel/default/etc/scripts/system-setup

Technically the impact is zero (only false alarm)
but to the user the impact is 'normal' because false alarm confuses the user.
I think essentially false alarm is like a WARNING message, cf.
https://blog.schlomo.schapiro.org/2015/04/warning-is-waste-of-my-time.html
https://github.com/rear/rear/issues/1883#issuecomment-409875733
By me on my SLES12 KVM system.
Now also exclude all regular files in /dev/
(device nodes get already excluded by 'find -type f')
because sometimes it could happen that there are
regular files in /dev/ in ROOTFS_DIR
which won't get copied into the recovery system
so that those regular files in …

Avoid false alarm during md5sum verification (related to issue1883)

---

usr/share/rear/finalize/Linux-i386/610_install_grub.sh
usr/share/rear/finalize/Linux-i386/620_install_grub2.sh

* Impact: **High** 
* Reference to related issue (URL): #1902 
* How was this pull request tested? yes via https://github.com/gdha/rear-automated-testing/issues/65
Recovery fails during grub-config with GRUB2_INSTALL_DEVICES empty
See script 620_install_grub2.sh
@schabrolles could you review this in the absence of Johannes?

change the logic of the continue with function is_disk_a_pv during grub2 config

---

packaging/rpm/rear.spec

* Type: *Enhancement** 
* Reference to related issue (URL): #1855 
* How was this pull request tested? on local laptop
* Brief description of the changes in this pull request: To be compliant with RPM specs we need to remove the BuildRoot and clean section.

remove BuildRoot and clean section from rear.spec 

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh

The ReaR code is making the assumption that the $BACKUP_PROG return value is returned from the child process. This is true for **rsync** and unsupported methods, but not for **tar** because **tar** uses the following pipes:
~~~
tar ... | <encrypt> ... | <splitter>
~~~
which ends up for basic case with the following pipes:
~~~
tar ... | cat | dd of=backup.tar.gz
~~~
In fact, the return code is hence the one for **dd**.
When there is an error, e.g. ENOSPC, **dd** returns 1, causing ReaR to believe **tar** returned 1, which is non-critical (1 means there was file modifications while reading them).
Also, if **tar** suffered an issue, e.g. an invalid parameter was passed to **tar**, then **dd** would return 0, causing a fake success to be returned.
This code fixes all these issues by returning …

Issue #1913 - NETFS+tar backup exit code testing insufficient (may fail to catch real backup errors)

---

usr/share/rear/conf/default.conf

Signed-off-by: Renaud Métrich <rmetrich@redhat.com>
by default zram devices (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/blockdev/zram.txt) are not to be mapped, exactly as it is done for ramdisk and loop devices.

Added exclusion of zram devices from device mapping

---

usr/share/rear/lib/filesystems-functions.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1915
Full backup restore of:
Centos6 (xfsprogs-3.1)
Fedora26 (xfsprogs-4.10)
This patch will help to avoid messages like:
`"[: -eq: unary operator expected"` when using with older versions of xfsprogs.

Added default value (0) for crc variable (XFS).

---

usr/sbin/rear

* Type: **Enhancement** 
* Reference to related issue (URL): #1815 
* How was this pull request tested? via the CLI `sudo ./rear -D -c /etc/rear/local.conf mkrescue`
* Brief description of the changes in this pull request: added a test for CONFIG_DIR

Check if CONFIG_DIR is not a file #1815

---

usr/share/rear/rescue/GNU/Linux/500_clone_keyboard_mappings.sh

https://github.com/rear/rear/issues/1906
Via "rear mkrescue" on my openSUSE Leap 15.0 system.
In rescue/GNU/Linux/500_clone_keyboard_mappings.sh
avoid running `find` in the whole tree of filesystems which takes ages, cf.
https://github.com/rear/rear/issues/1906#issuecomment-416058041

Avoid find in whole fstree in 500 clone keyboard mappings issue1906

---

usr/share/rear/init/default/050_check_rear_recover_mode.sh
usr/share/rear/lib/dump-workflow.sh
usr/share/rear/lib/finalizeonly-workflow.sh
usr/share/rear/lib/help-workflow.sh
usr/share/rear/lib/opaladmin-workflow.sh
usr/share/rear/lib/udev-workflow.sh

https://github.com/rear/rear/issues/1901
https://github.com/rear/rear/issues/1939
By me on my openSUSE Leap 15.0 system.
The behaviour in the recovery system was simulated and tested via
<pre>
</pre>
Now `rear -s dump` and `rear -s help` work and
the help workflow is supported in the running recovery system.

Support simulation mode for dump and help workflows plus better help workflow

---

usr/share/rear/lib/linux-functions.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1941
Patch has been tested on a system with a kernel without module support.
Permits ReaR to work on systems which do not support kernel modules. It still requires setting `MODULES=( 'no_modules' )`in the config.

properly handle module-less kernels (fixes #1941)

---

usr/share/rear/finalize/Linux-i386/610_install_lilo.sh
usr/share/rear/lib/config-functions.sh
usr/share/rear/pack/Linux-i386/300_copy_kernel.sh

1. Added automatic OS vendor and version detection.
2. Added logic to search for kernel files in using default /boot/vmlinuz-`uname -r` pattern in the event that the standard ELILO kernel install paths come up empty.
Added legacy LILO bootloader support.
Enhancement
Normal.
On a Slackware 14.2 OS, performed a full backup to and recover from a USB device. Was able to boot with coldstarted disk using basic LILO bootloader. Should not conflict with other bootloader types (GRUB and ELILO).
* Brief description of …

For Slackware Linux:

---

usr/share/rear/rescue/GNU/Linux/310_network_devices.sh

* How was this pull request tested? Unit tested + Recovery in migration mode
When a physical device is enslaved in a bond, its MAC address is modified to the first network interface's MAC address of the bond. This makes `/etc/mac-addresses` record an invalid information, e.g.:
**Broken**
~~~
eth1-bond0 52:54:00:31:e0:b9
eth2-bond0 52:54:00:31:e0:b9
eth0 52:54:00:a3:97:5b
~~~
**Expected**
~~~
eth1-bond0 52:54:00:31:e0:b9
eth2-bond0 52:54:00:86:ec:a8
eth0 52:54:00:a3:97:5b
~~~

network: Record permanent mac address when device is enslaved in a bond, or else /etc/mac-addresses will record broken information

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh
usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
usr/share/rear/layout/save/GNU/Linux/240_swaps_layout.sh
usr/share/rear/layout/save/GNU/Linux/250_drbd_layout.sh
usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh
usr/share/rear/layout/save/GNU/Linux/270_hpraid_layout.sh
usr/share/rear/layout/save/GNU/Linux/280_multipath_layout.sh

Basically no impact on usual systems where all those tools are installed
but high impact on systems where such tools are missing because
when specific required programs are missing on a system
better safe than sorry and error out during "rear mkrescue/mkbackup"
than "successfully" provide the user a recovery system that is useless.
https://github.com/rear/rear/issues/1963
By me on my system with an ext4 root filesystem as in
https://github.com/rear/rear/issues/1963#issue-380602044
Currently this is only a first step where I only added specific
required `parted` and `mkfs.*` programs to REQUIRED_PROGS
in …

Add specific required programs to REQUIRED_PROGS (issue 1963)

---

etc/rear/local.conf
usr/sbin/rear

* Reference to related issue (URL): #1965 
* How was this pull request tested? locally
````
$ sudo usr/sbin/rear -v mkrescue
Relax-and-Recover 2.4 / Git
Running rear mkrescue (PID 15205)
Using log file: /projects/rear/myforks/rear/var/log/rear/rear-okido.log
ERROR: Carriage return character in /projects/rear/myforks/rear/etc/rear/local.conf (perhaps DOS or Mac format)
````
* Brief description of the changes in this pull request: If configuration files contain hidden carriage returns this often runs into an error (which is sometimes not obvious to understand where the issue came from). With this patch we will bail out and tell the user to fix his config file

check for carriage return in {local|site|rescue}.conf files

---

usr/share/rear/build/GNU/Linux/100_copy_as_is.sh

When including files in the ISO using COPY_AS_IS functionality and some of these are libraries with same name as standard system libraries, the standard system libraries are not included if an executable included through COPY_AS_IS requires a library.
This does not happen for executables specified through PROG.
Example: copy /lib64/libglib-2.0.so.0 into /non-standard-dir/lib64/ and include /non-standard-dir/lib64 in the ISO (COPY_AS_IS+=( /non-standard-dir/lib64 ))
- /usr/lib/udev/rename_device which is also included as COPY_AS_IS (in /usr/share/rear/rescue/GNU/Linux/250_udev.sh) requires /lib64/libglib-2.0.so.0 but /lib64/libglib-2.0.so.0 is not included, only /non-standard-dir/lib64/libglib-2.0.so.0 will be
- /usr/lib/udev/rename_device will not be usable in rescue due to missing …

Issue #1975 - Missing libraries in Rescue ISO causing executables to fail

---

usr/share/rear/conf/Arch/i386.conf
usr/share/rear/conf/GNU/Linux.conf

By running `rear mkrescue` on Arch Linux.
On current Arch (rolling release), SSL certificates are symlinked from /etc/ssl/certs to /etc/ca-certificates/extracted/cadir.
This is causing ReaR to complaint about broken symlinks when running `rear mkrescue/mkbackup`:
```
Broken symlink './etc/ssl/certs/QuoVadis_Root_CA_1_G3.pem' in recovery system because 'readlink' cannot determine its link target
Broken symlink './etc/ssl/certs/1e09d511.0' in recovery system because 'readlink' cannot determine its link target
Broken symlink './etc/ssl/certs/Staat_der_Nederlanden_Root_CA_-_G2.pem' in recovery system because 'readlink' …
```

Add /etc/ca-certificates directory to ReaR recovery system for Arch Linux

---

Makefile
packaging/arch/PKGBUILD.local

I built and installed rear on my own Arch system using these 2 patches.
First change modifies the makefile to refer to dist/$(name)-$(distversion).tar.gz instead of $(name)-$(distversion).tar.gz.
Second change renames /usr/sbin to /usr/bin before assembly of Pacman package.

Fix broken 'make pacman'

---

usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
usr/share/rear/build/OPALPBA/Linux-i386/391_list_executable_dependencies.sh
usr/share/rear/build/default/980_verify_rootfs.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/linux-functions.sh
usr/share/rear/prep/NBU/default/450_check_nbu_client_configured.sh

* Type: **Bug Fix** + **Enhancement**
* Reference to related issue (URL): #1974 
* How was this pull request tested? **Tested by a Red Hat customer on rear-2.4.2**
With ReaR 2.4, a verification of the binaries included in the ISO is
performed. When using `COPY_AS_IS` with **NetBackup**, too many binaries were
included, causing the verification to fail or print error messages.
This fix defines a new `NBU_LD_LIBRARY_PATH` variable used during
verification and also excludes unused **NetBackup** binaries from the ISO.
Additionally, the `RequiredSharedObjects()` function has been fixed to not
list the left part of the ldd mapping when there is a …

Fix for #1974 - NBU (Netbackup) not working since ReaR 2.4

---

usr/share/rear/prep/GNU/Linux/400_guess_kernel.sh

* Type: **Regression Fix**
https://github.com/rear/rear/pull/1985#issuecomment-443157197
On my openSUSE Leap 15.0 (SLES12-like) system
Basically I reverted the main part of
https://github.com/rear/rear/pull/1985/commits/8b39c585c502be19d41b64d9530f661fcc6bf6c2
i.e. we do no longer call `file` to verify if the KERNEL_FILE
variable actually contains a 'kernel' file so that now e.g.
<pre>
KERNEL_FILE="/etc/os-release"
</pre>
"just works" again (ReaR obeys user's commandments) as it did in
https://github.com/rear/rear/pull/1985#discussion_r237451729
see there for the reasoning why.

Removed file command usage in 400_guess_kernel.sh because it is not reliably working to test if a file is actually a kernel

---

usr/share/rear/conf/default.conf
usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
usr/share/rear/output/ISO/Linux-ia64/800_create_isofs.sh
usr/share/rear/output/ISO/Linux-ppc64le/820_create_iso_image.sh
usr/share/rear/prep/ISO/GNU/Linux/320_verify_mkisofs.sh

Tested on x86_64 with xorrisofs (no change) and mkisofs:
- no change when backup is not embedded
- **udf** included + mkisofs option when backup is embedded
When using **BACKUP_URL=iso:///backup** and ISO generator is **mkisofs** or **genisoimage**, include the **udf** module and enable creating an hybrid **iso9660/udf** DVD.
This is necessary if the backup archive is >= 4GiB, otherwise the following error occurs:
~~~
File ./backup/backup.tar.gz is larger than 4GiB-1.
-allow-limited-size was not specified. There is no way do represent this file size. Aborting.
~~~
*xorrisoifs* doesn't require this.

Include UDF support in rescue ISO when backup is stored on the ISO itself

---

usr/sbin/rear
usr/share/rear/conf/default.conf

- Tested without `export TMPDIR=xxx` variable
- Tested with `export TMPDIR=xxx` variable
Usually **$BUILD_DIR** hosted on `/tmp` and hence automatically excluded from the backup.
When specifying **$TMPDIR**, **$BUILD_DIR** was not excluded from the backup.

Automatically exclude $BUILD_DIR from the backup

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/58-start-dhclient.sh

https://github.com/rear/rear/issues/1986
I created a new ISO file on a laptop that had multiple interfaces and the issue was resolved by this diff.
The DHCP client during recovery does not iterate correctly over all network interfaces that are found. It incorrectly takes the first found interface time and again. If the interface that is intended for recovery is not the first one then the automatic recovery will fail. The user can only work around the situation by running "dhclient" manually on the correct interface.

Fix for issue https://github.com/rear/rear/issues/1986

---

usr/share/rear/output/ISO/Linux-ppc64le/800_create_isofs.sh

- Tested on rhel7 on ppc64le with Boot on ISO
Fix an error due to missing `$TMP_DIR/` before `$REAR_INITRD_FILENAME`.
This prevents the ISO to be generated because of `initrd` cannot be found.
```
Testing that the recovery system in /tmp/rear.hDXOoQTdilZRyyA/rootfs contains a usable system
Creating recovery/rescue system initramfs/initrd initrd.xz with xz lzma compression
Created initrd.xz with xz lzma compression (42387961 bytes) in 113 seconds
ERROR: No initrd 'initrd.xz'
Some latest log messages since the last called script 800_create_isofs.sh: …
```

$TMP_DIR parent directory was missing before initrd filename variable.

---

usr/share/rear/output/ISO/Linux-ppc64/310_create_grub2.sh
usr/share/rear/output/ISO/Linux-ppc64le/300_create_grub2.sh

* Reference to related issue (URL): No issue created
* How was this pull request tested? Not tested, I don't have the hardware for now, please may someone with hardware test.
~~~
Issue is caused by incorrect, according to PAPR specification,
bootinfo entity parsing code in grub2.
In PAPR spec "B.4.1.6.1 Bootinfo Entities" partition and path
separator (,) is optional and if not present bootinfo may be
treated as directory and filename components unless it begins
with number:
&device;:[&partition;][,]&directory;&filename;
If (,) is missing and directory begins with a hexadecimal number
GRUB2 treats this as partition number …

Fix for 'error:unrecognized number' when booting ISO on PPC

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh

* How was this pull request tested? Tested on RHEL7
Prior to this change, when a network interface had a custom name set instead of `ethX`, the network configuration was not applied. Typical usage is the `ifcfg` file sets up a `DEVICE` name and `HWADDR` mapping.
The new code fixes this issue by running the network interface migration code in an unattended manner.
Example (tested on a RHEL 7 box):
~~~
/etc/sysconfig/network-scripts/ifcfg-first:
TYPE="Ethernet"
BOOTPROTO="dhcp"
DEFROUTE="yes"
IPV6INIT="no"
DEVICE="first"
HWADDR="52:54:00:eb:6c:bf"
ONBOOT="yes"
~~~
/etc/rear/site.conf:
~~~
USE_STATIC_NETWORKING=y
~~~
Prior …

network: Automatically map device to its new name when device is found on the system with same MAC address but different name

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/prepare/GNU/Linux/130_include_filesystem_code.sh

Usually this is not needed but if the worst comes to the worst
an easy way to specify mkfs.xfs options it is likely highly appreciated.
https://github.com/rear/rear/issues/1998
Currently it is not at all tested by me.
Currently it is meant so that @gozora can have a first look, cf.
https://github.com/rear/rear/issues/1998#issuecomment-447325672
Via the new optional global MKFS_XFS_OPTIONS config variable
the user can specify mkfs.xfs options for all mkfs.xfs calls
and/or via optional device specific config variables like
MKFS_XFS_OPTIONS_SDA2
the user can specify mkfs.xfs options only for the mkfs.xfs call
for that …

Provide final power to the user for mkfs.xfs options if needed (issue 1998)

---

usr/share/rear/lib/uefi-functions.sh

* Reference to related issue (URL): #1996 
* How was this pull request tested? not tested yet
* Brief description of the changes in this pull request: See https://github.com/rear/rear/issues/1996#issuecomment-445201012

fedora29 grub2-efi-x64-modules does not contain linuxefi module

---

usr/share/rear/lib/uefi-functions.sh

https://github.com/rear/rear/issues/1193
On my openSUSE Leap 15.0 system with UEFI boot:
Without /usr/lib/grub2/x86_64-efi/moddep.lst (excerpts):
<pre>
...
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
...
Trying to find what to use as UEFI bootloader...
Trying to find a 'well known file' to be used as UEFI bootloader...
Using '/boot/efi/EFI/opensuse/grubx64.efi' as UEFI bootloader file
...
Created initrd.cgz with gzip default compression (69492491 bytes) in 9 seconds
ERROR: grub2-mkimage would not make bootable EFI image of GRUB2 (no /usr/lib/grub*/x86_64-efi/moddep.lst file)
Some latest log messages since the last called script 250_populate_efibootimg.sh: …

Error out when we cannot make a bootable EFI image of GRUB2 (issue 1193)

---

usr/sbin/rear
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/dump-workflow.sh

* Type: **Minor Bug Fix** **Enhancement**
https://github.com/rear/rear/pull/2011#issuecomment-453085678
By me on my openSUSE Leap 15.0 system.
Now `rear dump` shows array variable elements separated by `'` characters as
```
ARRAY_VARIABLE_NAME = 'first element' 'second element'
```
for example with `BACKUP_RSYNC_OPTIONS=( this that 'something else' )`
(excerpts):
```
...
BACKUP_RSYNC_OPTIONS = 'this' 'that' 'something else' 
...
BACKUP_PROG_EXCLUDE = '/tmp/*' '/dev/shm/*' '/root/rear.github.master/var/lib/rear/output/*' '/nfs/*' '/tmp/rear.Prkdrs6sR9pybOv' 
```
Before it would have been e.g.
```
BACKUP_RSYNC_OPTIONS = this that something else …
```

Improve rear dump output to clearly distinguish array elements

---

usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh

High impact only when docker is used.
https://github.com/rear/rear/issues/1989#issuecomment-456054278
I do not use docker and I get exactly the same
var/lib/rear/layout/disklayout.conf as before
so I assume there are no regressions.
In usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
ensure docker_root_dir is not empty because otherwise any
mountpoint string matches "^" which would skip all mountpoints

Be safe against empty docker_root_dir (issue 1989)

---

usr/sbin/rear

By me on my openSUSE Leap 15.0 system.
Before:
```
rear: invalid option -- 'Q'
...
```
(i.e. the 'dump' workflow is run).
With the fix here:
```
rear: invalid option -- 'Q'
Use 'rear --help' or 'man rear' for more information.
```
In the code before in usr/sbin/rear
```
readonly OPTS="$( getopt -n $PROGRAM -o "c:C:dDhsSvVr:" -l "help,version,debugscripts:" -- "$@" )"
if test $? -ne 0 ; then
echo "$help_note_text"
exit 1
fi
```
the `$?` does not contain the `getopt` exit code
but the `readonly` return code which is always zero.
The new code
```
if ! OPTS="$( getopt -n $PROGRAM -o "c:C:dDhsSvVr:" -l "help,version,debugscripts:" -- "$@" )" ; then
echo …
```

Fixed exit in usr/sbin/rear when getopt failed

---

usr/sbin/rear
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/array-functions.sh

Intent:
Improve readability of the ReaR log file by suppressing
particular `set -x` debug output that is usually of no interest
so that it gets easier for our users and for us to analyze an issue
by inspecting the log file when rear was called in debugscripts mode.
By me on my openSUSE Leap 15.0 system
I think a noticeable part of the `set -x` debugscripts output
(that part is about 25% for my initial test, see below)
is usually of no interest and therefore dispensable by default.
This pull request is a proposal how we could suppress dispensable
debug output by default (in particular when rear is called with '-D')
unless rear is called with '--debugscripts …

Suppress dispensable 'set -x' debug output unless called with '--debugscripts x'

---

usr/share/rear/lib/layout-functions.sh
usr/share/rear/rescue/GNU/Linux/270_fc_transport_info.sh

* Reference to related issue (URL): #2020 
* How was this pull request tested? Tested by customer
When a system has many multipath devices (547 disks, 272 x 2 paths), creating the ReaR rescue takes several hours. This is due to:
- the `get_device_name()` function to scan all multipath devices multiple times without caching the information (legacy code, when kernel has no `/sys/block/<dev>/dm/name` node)
- the `get_device_name()` function to scan the multipath devices even if there is no need for that
- the collect of unused `/sys/class/fc_transport` information
With these optimizations, the ReaR rescue takes a few …

Multipath optimizations

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/Linux-i386/100_EFISTUB_run_efibootmgr.sh
usr/share/rear/finalize/Linux-i386/630_run_efibootmgr.sh
usr/share/rear/finalize/default/050_prepare_checks.sh
usr/share/rear/init/default/010_EFISTUB_check.sh
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/260_EFISTUB_populate.sh
usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
usr/share/rear/output/ISO/Linux-i386/830_create_iso_image_EFISTUB.sh
usr/share/rear/output/default/940_grub2_rescue.sh
usr/share/rear/output/default/940_grub_rescue.sh
usr/share/rear/prep/GNU/Linux/500_EFISTUB_check_kernel.sh
usr/share/rear/prep/ISO/GNU/Linux/360_EFISTUB_prechecks.sh
usr/share/rear/prep/default/321_EFISTUB_check_uefi_env.sh
usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh
usr/share/rear/restore/NETFS/Linux-i386/510_selinux_fixfiles_exclude_dirs.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1942
Full backup restore on Arch Linux configured for EFISTUB booting.
Migration from GRUB2 to EFISTUB on SLES2 SP2.
This patch enables basic support in ReaR for systems setup to boot using EFISTUB.

Basic support for EFISTUB booting.

---

usr/share/rear/lib/uefi-functions.sh

* Type: Bug Fix
* Reference to related issue (URL): https://github.com/rear/rear/commit/f9e53a331c226fa305145866492bb978a1e66a2a
Created and UEFI booted ReaR recovery system on RHEL 7.6, SLES12 SP2 and Fedora29
It looks like https://github.com/rear/rear/commit/f9e53a331c226fa305145866492bb978a1e66a2a introduced a regression for Linux distributions that ships Grub2 EFI modules (grub2-efi-x64-modules) only in _/usr/lib/grub*/x86_64-efi_ but does not copy them to _/boot_ when installed (observed on RHEL7.6 and Fedora29 so far, but there might be more ...).
Missing modules in _/boot_ combined with code from https://github.com/rear/rear/commit/f9e53a331c226fa305145866492bb978a1e66a2a …

Fix for commit f9e53a33

---

usr/share/rear/skel/default/etc/scripts/system-setup.d/58-start-dhclient.sh

* Reference to related issue (URL): #1274 
* How was this pull request tested? not tested yet
* Brief description of the changes in this pull request: with multiple lan interface it might fail to acquire an IP address, with this little fix it should work.

small fix to the 58-start-dhclient.sh script

---

usr/share/rear/finalize/GNU/Linux/310_migrate_udev_rules.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh

* Reference to related issue (URL): #2046 
* How was this pull request tested? at the customer site with success
* Brief description of the changes in this pull request: See #2046 for the full problem description.
> What we found is that Red Hat Enterprise Linux 7 virtual guests using the vmxnet3 driver on VMware hypervisors have names such as eno16780032 instead of an expected name such as ens192 (scheme 2). Unfortunately, this can lead to not only inconsistent network device names but sometimes network loss when the virtual guest machine or the hypervisor was rebooted.

add eno-fix.rules to the RULE_FILES array #2046

---

usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
usr/share/rear/finalize/GNU/Linux/250_migrate_lun_wwid.sh
usr/share/rear/finalize/GNU/Linux/260_rename_diskbyid.sh
usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
usr/share/rear/finalize/GNU/Linux/310_migrate_udev_rules.sh
usr/share/rear/finalize/GNU/Linux/320_migrate_network_configuration_files.sh
usr/share/rear/finalize/default/520_confirm_finalize.sh

* Type: **Bug Fix** **Enhancement** **Cleanup**
skip patching absolute symlinks during finalize stage
is only a first step towards actually fixing
https://github.com/rear/rear/issues/1338
Not yet tested and not yet complete - some more commits are needed...
All finalize scripts that patch restored files within TARGET_FS_ROOT
should do the same symlink handling which means
1. Skip patching symlink targets that are not within TARGET_FS_ROOT
(i.e. when it is an absolute symlink)
2. Skip patching if the symlink target contains /proc/ /sys/ /dev/ or /run/
3. Skip patching dead symlinks
Skip patching symlink targets that are not within …

skip patching absolute symlinks during finalize stage (related to issue 1338)

---

usr/share/rear/rescue/NSR/default/470_safe_filesystems.sh

* Type: **Improvement/Others?**
* Reference to related issue (URL): None.
* How was this pull request tested? On a HP DL360 G9 / RHEL7.4
During the time working with the EMC Networker recovery I determined it is of additional use to not skip the retrieval of the filesystems in NSR_CLIENT_MODE I introduced with f09c3d3. It does not harm to do so since gathering this information is "read-only" for the client. 
Due to saving the save sets filesystem information in $VAR_DIR/recovery/nsr_paths within the recovery image one is able to retrieve/read this stored information during a recovery process i.e. for advising the EMC networker server team to …

Update 470_safe_filesystems.sh for NSR

---

usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh

https://github.com/rear/rear/issues/2016
https://github.com/rear/rear/issues/2002
sles12sp3 / rhel 7 with disk migration and multipath
refresh udev with trigger before activating multipath
Ensure that all information from multipath devices are updated by udev
into /sys before activating multipath. This is one of the root cause
of issues rear#2002 and rear#2016

Udev before multipath

---

usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh

* Reference to related issue (URL): #1363 
* How was this pull request tested? at the customer side
* Brief description of the changes in this pull request: when the WORKFLOW=mkrescue we immediately return from script `prep/NETFS/default/070_set_backup_archive.sh`

to avoid confusing in mkrescue run we do not print using archive #1363

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/save/default/950_verify_disklayout_file.sh
usr/share/rear/lib/global-functions.sh

* Type: **Enhancement** and **AvoidErrorsDuringRecovery**
* Impact: **Low** and **High**
Low impact when all is fine but hight (useful) impact when things
look fishy when disklayout.conf is created during "rear mkrescue"
to avoid that "rear recover" fails when it is too late to fix things.
https://github.com/rear/rear/issues/1681
https://github.com/rear/rear/issues/2006#issuecomment-460646685
"rear mkrescue" still works for me on my openSUSE Leap 15.0 sytem
with that partitioning:
```
Model: ATA WDC WD10EZEX-75M (scsi)
Disk /dev/sda: 953870MiB
Sector size (logical/physical): 512B/4096B
Partition Table: gpt
Disk Flags: 
Number  Start      End        Size       File system     Name  Flags
1      1.00MiB    501MiB …
```

New verify disklayout file script 950_verify_disklayout_file.sh

---

packaging/debian/control

ReaR works in configurations not using syslinux, so `Depends` is too strong. Additionally, not using syslinux is not unusual per se, so `Recommends` would still be too strong. Per Debian Policy [7.2. Binary Dependencies](https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends), `Suggests` would be the right level here.

Debian packaging: downgrade syslinux from Depends to Suggests

---

usr/share/rear/build/GNU/Linux/400_copy_modules.sh
usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/conf/default.conf

Hopefully low impact because this change should only
make things work better by default in the recovery system
without really bad side effects.
The somewhat bigger default recovery system should
not be a really bad side effect.
There is one backward incompatible change:
Before the user had to specify in local.conf
```
MODULES=( "${MODULES[@]}" 'moduleX' 'moduleY' )
```
to get additional kernel modules included
but now the user must specify
```
MODULES=( 'moduleX' 'moduleY' )
```
for that because with `"${MODULES[@]}"`
the default value `all_modules` would be kept
which triggers to get all modules included.
https://github.com/rear/rear/issues/2041
By me on my openSUSE Leap 15.0 …

Have MODULES all_modules by default plus needed adaptions for that

---

usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh

* Impact: **Low** (excessive PBA size)
A TCG Opal pre-boot authentication (PBA) system is a minimal operating system constructed by ReaR to unlock self-encrpyting disks before the regular OS takes over. Before this PR, it could happen that a previously created PBA was included in a subsequently created PBA, causing it to be unnecessarily large.

OPALPBA output fix: Do not include any PBA into another PBA

---

usr/share/rear/output/RAWDISK/Linux-i386/280_create_bootable_disk_image.sh

* Impact: **Normal** (creating RAWDISK output fails with "no space left on device")
On Ubuntu 18.04, it has been observed that after creating a loop device
and creating a properly sized VFAT file system >250 MB on it, after
mounting the file system size was actually just 30 MB. Reason: The
partition detection did not pick up the correct partition sizes of the
associated image file. This change uses losetup's --partscan option
(supported by util-linux v2.21 and above) to offer one additional
opportunity to detect partitions. If the option is not available, a
traditional losetup call will be used as a fallback.

RAWDISK output: improve device partition detection (e.g. Ubuntu 18.04)

---

usr/share/rear/skel/default/etc/scripts/run-sshd

* Supercedes: https://github.com/rear/rear/pull/2068
* Impact: **High** (cannot log in via SSH on rescue system)
On Ubuntu 18.04 with OpenSSH 7.6, /etc/ssh/sshd_config contains
commented-out lines for 'PermitRootLogin' and other options. This fix
makes sure that settings changed for ReaR will be real, not comments.

Fix SSH root login on the recovery system with some configurations

---

usr/share/rear/skel/default/etc/scripts/system-setup

This fix avoids a false alarm
> Possibly corrupted Relax-and-Recover rescue system
which occurs as `run-sshd` modifies `/etc/ssh/sshd_config`.

system-setup: Exclude /etc/ssh/sshd_config from md5sums verification

---

usr/share/rear/layout/prepare/GNU/Linux/131_include_new_btrfs_subvolumes_code.sh

* Impact: **High** (in specific Btrfs use cases, ReaR recover would fail)
* Reference to related issue (URL): https://github.com/rear/rear/issues/2067
* How was this pull request tested? On Ubuntu 18.04.2 LTS with different combinations of Btrfs file systems and subvolume hierarchies.
This PR aims to recreate all Btrfs file systems which have been mounted on the original system. It is a re-write of the original Btrfs subvolume code.
Although this code is simpler and focuses on mounted subvolumes only, its effects are intended to be entirely compatible with Btrfs scenarios addressed previously (e.g. using `snapper`). The assumptions are:
1. _All_ Btrfs subvolumes, which were actually mounted on the original …

Add new implementation to recreate all mounted Btrfs subvolumes

---

packaging/debian/control

* Impact: **Normal** (rear fails startup)
* How was this pull request tested? By manually installing the 'net-tools' package on Ubuntu 18.04.2 LTS
On a Ubuntu 18.04.2 LTS desktop system, `rear -h` fails with:
```
ERROR: Cannot find required programs:  route
```
Route is required by `usr/share/rear/conf/GNU/Linux.conf` (line 8).
Running `apt install net-tools` fixed the situation.

Add 'net-tools' to Debian dependencies as required for 'route' command

---

usr/share/rear/rescue/GNU/Linux/310_network_devices.sh

* Reference to related issue (URL): See PR https://github.com/rear/rear/pull/1954
* How was this pull request tested? Tested on RHEL7 with a Team on eth0 and eth1
Use "ethtool -P" as the preferred method to retrieve the MAC address.
Otherwise fall back to other methods, which may lead to some invalid MAC address when using Teams.

network: Record permanent mac address when device is enslaved in a Team, or else /etc/mac-addresses will record broken information

---

usr/share/rear/layout/prepare/GNU/Linux/131_include_filesystem_code.sh
usr/share/rear/layout/prepare/GNU/Linux/133_include_mount_filesystem_code.sh
usr/share/rear/layout/prepare/GNU/Linux/135_include_btrfs_subvolumes_generic_code.sh
usr/share/rear/layout/prepare/GNU/Linux/136_include_btrfs_subvolumes_SLES_code.sh

https://github.com/rear/rear/pull/2080
By looking at the new commets and messages ;-)
The new layout/prepare/GNU/Linux/133_include_... script names are
```
layout/prepare/GNU/Linux/131_include_filesystem_code.sh
layout/prepare/GNU/Linux/133_include_mount_filesystem_code.sh
layout/prepare/GNU/Linux/135_include_btrfs_subvolumes_generic_code.sh
layout/prepare/GNU/Linux/136_include_btrfs_subvolumes_SLES_code.sh
```
and the new btrfs_subvolumes_setup_... function names are
```
btrfs_subvolumes_setup_generic
btrfs_subvolumes_setup_SLES
```
Those new names are now used in comments and messages.

Fixed comments and messages about '13X_include_...' scripts that had been renamed via issue 2080

---

usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
usr/share/rear/skel/default/usr/lib/systemd/system/plymouth-start.service

https://github.com/rear/rear/pull/1947
https://github.com/rear/rear/pull/2018
This PR updates the OPALPBA workflow in light of recent changes:
* It sets `USE_RESOLV_CONF='no'` as networking is not required/available in the PBA
* It avoids copying in the entire `/etc/alternatives` directory as since d97cfbe74477e7849ccee9880c57ba4d6a31ee25 its links could pull in lots of unwanted stuff, which is not required in rescue systems (i.e. graphical editors).

Update OPALPBA workflow

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

* Type: **Enhancement** 
* Reference to related issue (URL): https://github.com/rear/rear/issues/2087
* How was this pull request tested? Manually on PC with eMMC disk device (Z83-F).
* Brief description of the changes in this pull request: sysfs for (some?) eMMC disks recognises partitions, which are actually no usual partitions, but special areas on the eMMC. When trying to get the partition layout for such disks, ReaR exits with an error. This pull request contains enhancements to silently ignore these special partitions, so that ReaR no longer fails.

Ignore invalid partitions on eMMC devices of type *rpmb and *boot*

---

usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
usr/share/rear/lib/_input-output-functions.sh

* Type: **Critical Bug Fix**
https://github.com/rear/rear/issues/2089
https://github.com/rear/rear/issues/2089#issuecomment-474240386
For the history how this issue became known see
https://github.com/rear/rear/issues/2087#issue-421604286
https://github.com/rear/rear/pull/2080/commits/f4a7d22f0dc07e518b750f445159320cac397952
By me on openSUSE Leap 15.0 with artificial Error calls
in a script directly as
```
Error "Test error"
```
and in a subshell as
```
( Error "Test error" )
```
The Error function must not return to its caller
because then the caller could continue with the code
after its Error function call, see …

Error function must immediately exit (issue #2089)

---

usr/share/rear/finalize/Linux-ppc64le/680_install_PPC_bootlist.sh

Correction to #1886 - LPAR/PPC64 bootlist is incorrectly set when having multiple 'prep' partitions

fixed bootlist (special thanks to pcahyna++)

---

usr/share/rear/finalize/Linux-ppc64le/680_install_PPC_bootlist.sh

* Type: **Style Cleanup**
* Reference to related issue (URL): 
https://github.com/rear/rear/pull/1887/files#r268264260
Code analysis and experimenting with analogous snippets of bash code.
Array expansion inside strings like `"aaa ${boot_list[@]} bbb"` splits the string into several strings:
```
boot_list=( foo bar )
"aaa ${boot_list[@]} bbb"
```
-> `"aaa foo" "bar bbb"` instead of `"aaa foo bar bbb"`. This is probably unintended, although harmless in this case.
Change `[@]` to a more intuitive `[*]`, which keeps the result of expansion as one string.
See https://github.com/koalaman/shellcheck/wiki/SC2145

Use [*] instead of [@] for array expansion inside a string

---

usr/share/rear/lib/_input-output-functions.sh

https://github.com/rear/rear/issues/2089#issuecomment-476590268
By me on my openSUSE Leap 15.0 system as in
https://github.com/rear/rear/pull/2088#issuecomment-474446764
and subsequent comments.
A SUSE colleague found the simplest way to get the current PID
without using bsh 4.x $BASHPID:
```
read current_pid junk </proc/self/stat
```
This also works even in nested subshells in a sourced script
and it is simpler than what I had used before
```
tmpfile=$( mktemp )
cat /proc/self/stat >$tmpfile
current_pid=$( cut -d ' ' -f4 $tmpfile )
rm $tmpfile
```
because `read` is a shell builtin (so no parent PID stuff is needed)
and the …

Use simplest way to get current PID in bash 3 (related to issue 2089)

---

usr/share/rear/build/GNU/Linux/630_verify_resolv_conf_file.sh

* Impact: ***Normal**
* Reference to related issue (URL): #2015 and #2018 
* How was this pull request tested? via rea-automated-testing
* Brief description of the changes in this pull request: 
https://github.com/gdha/rear-automated-testing/issues/75 - I did not like to current behaviour and agree with @OliverO2 that ReaR pretends to just work out of the box, which was not correct IMHO in this particular case. I agree with @schlomo too that we should adopt systemd more (not less), but this was a quick-win.
For the next release we can have systemd-resolved incorporated (no rush as systemd is a moving duck anyhow)

quick hack to copy the real resolv.conf file on ubuntu18.x

---

usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh

Enhancement
Low
https://github.com/rear/rear/issues/2103
Manually on corresponding hardware (Z83-F Mini PC)
For eMMC devices strip the trailing "p" in the disk device name,
so that during recovery the efibootmgr call will not fail, but create an UEFI boot entry.

Fix disk device name in efibootmgr call for eMMC devices

---

usr/share/rear/build/GNU/Linux/640_verify_lvm_conf.sh

* Reference to related issue (URL): #2044 
* How was this pull request tested? via automated testing

adding 640_verify_lvm_conf.sh script

---

usr/share/rear/finalize/Linux-i386/660_install_grub2.sh
usr/share/rear/layout/prepare/default/250_compare_disks.sh

Found "by the way" while testing https://github.com/rear/rear/pull/2081
By me on SLES12 and SLES15 while testing https://github.com/rear/rear/pull/2081
1.)
The changes in layout/prepare/default/250_compare_disks.sh
avoid that it goes into MIGRATION_MODE with
```
Ambiguous possible target disks need manual configuration (more than one with same size found)
```
in any case when there is more than one disk.
Before it compared for all disks how often any original disk size
matches any possible target disk size and when there are
more disks e.g. both on the original system and on the target system
there are /dev/sda with 10 …

Fixes for more than one disk

---

usr/share/rear/build/default/985_fix_broken_links.sh

https://github.com/rear/rear/issues/2111
Not yet tested at all
Never copy symlink targets in /proc/ /sys/ /dev/ or /run/
into the ReaR recovery system

Do not copy symlink targets in proc sys dev run (issue#2111)

---

usr/share/rear/finalize/default/110_bind_mount_proc_sys_dev_run.sh

https://github.com/rear/rear/issues/2045#issuecomment-481195463
Works for me on SLES11
Dirty hack to keep things still working on SLES11:
On SLES11 it does not work to bind-mount /dev into TARGET_FS_ROOT
see https://github.com/rear/rear/issues/2045#issuecomment-481195463
because within the recovery system /dev is no mountpoint
(in a running SLES11 system 'udev' is mounted on /dev) and
within the recovery system bind-mounting of the /dev directory fails.
It seems the root cause is that within the recovery system / is no mountpoint
like in a normal running system where e.g. /dev/sda2 is mounted on /
but within the recovery …

Revive old 100_populate_dev.sh code for SLES11 (follow up of issue 2045)

---

usr/share/rear/prep/default/320_include_uefi_env.sh

https://github.com/rear/rear/issues/2095
Seems to work well for me on openSUSE Leap 15.0
```
...
Found EFI system partition /dev/sda1 on /boot/efi type vfat
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
```
The - from my point of view - needlessly overcomplicated
local variables (sometimes uppercased) and their `awk` constructs
are simplified into using plain `grep` and a bash array
to avoid inexplicable wrong behaviour is some cases
that is somehow related to the `nullglob` bash option, cf.
https://github.com/rear/rear/issues/2095#issuecomment-481833946
together with different kind of `awk`, cf. …

Simplify awk constructs in 320_include_uefi_env.sh (issue #2095)

---

usr/share/rear/build/default/990_verify_rootfs.sh

* Reference to related issue (URL): #2120
* How was this pull request tested? Ran `rear mkrescue` on Ubuntu 18.04.2 LTS server before and after patching. Verifying log output changes as intended. Also tested a full restore successfully.
This PR intends to fix #2120, avoiding unwanted "Welcome to" messages in the log file from `rear mkrescue`.
These invocations of `bash --login` in `usr/share/rear/build/default/990_verify_rootfs.sh` were affected as follows:
1. Motd message does not appear in log file, as output is filtered by _grep_. But if someone would change the welcome message text to something containing the phrase "not found", the grep expression would always match and subsequent code …

Fix #2120: avoid unwanted "Welcome to" messages in log file

---

usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/layout/save/default/330_remove_exclusions.sh
usr/share/rear/lib/layout-functions.sh

* Reference to related issue (URL): none
* How was this pull request tested? Ran `rear mkrescue` and `rear recover` on Ubuntu 18.04.2 LTS server before and after patching. Verified fix works as intended.
This PR corrects a mapping error when TCG Opal 2 self-encrypting disks were present but had to be excluded due to a non-existent disk during recovery. This exclusion was not handled properly.
(Edit: dropped second change)

Fix layout mapping

---

usr/share/rear/conf/default.conf

* How was this pull request tested? Tested on RHEL7
When using the NetBackup method, the files in the logs directory are excluded because they are useless. However, if, for some reason `/usr/openv/netbackup/logs` is a symlink to some other directory (a user customization), then ReaR will fail to create the ISO, due to having a skeleton directory for NBU in ReaR, causing the 'tar | untar' of `COPY_AS_IS` items to fail.

NBU: exclude '/usr/openv/netbackup/logs' directory instead of files in directory only

---

usr/share/rear/layout/prepare/GNU/Linux/135_include_btrfs_subvolumes_generic_code.sh

* Reference to related issue (URL): https://github.com/rear/rear/pull/2080#issuecomment-472448686
* How was this pull request tested? On Ubuntu 16.04 and 18.04

btrfs subvolumes generic: fix 'subvolume set-default' for older versions

---

usr/share/rear/build/default/985_fix_broken_links.sh

* Reference to related issue (URL): #2129, #2130
* How was this pull request tested? On Ubuntu 18.04.2 LTS: Compared `$ROOTFS_DIR` contents before and after code changes, verified everything works as intended.
1. Relative symbolic links are now properly resolved before checking the link's target.
2. Directories, which are link targets, no longer fail when trying to copy them. Instead, a meaningful hint is printed for the user to decide.
**Note:** On the test system, there is a relative symbolic link `/etc/ssh/sshd_config` -> `sshd_config.company`, which points to a customized configuration.
```
$ sudo usr/sbin/rear -v mkrescue
Relax-and-Recover 2.4 / Git
[...]
Copying all files in …
```

Improve handling of broken symlinks (fix #2129, fix #2130)

---

.packit.yaml

This PR adds support for packit https://github.com/packit-service/packit, which syncs upstream releases into downstream automatically. See docu on packit side https://github.com/packit-service/packit/blob/master/README.md.

On-board packit.yaml

---

usr/share/rear/output/default/950_copy_result_files.sh

https://github.com/rear/rear/pull/2142#issuecomment-494426331
https://github.com/rear/rear/pull/2142#issuecomment-495010023
https://github.com/rear/rear/issues/2137
By me via
https://github.com/rear/rear/pull/2142#issuecomment-494426331
Before output/default/950_copy_result_files.sh falsely errors out with
```
Could not copy '/usr/share/rear/conf/templates/RESULT_usage_FOO.txt'
```
cf. https://github.com/rear/rear/pull/2142#issuecomment-495010023
when `OUTPUT=FOO` is used where no
usr/share/rear/conf/templates/RESULT_usage_FOO.txt
exists.
Currently only
usr/share/rear/conf/templates/RESULT_usage_PXE.txt …

Improvements and fixes for 950_copy_result_files (related to issue2137)

---

usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/save/default/950_verify_disklayout_file.sh
usr/share/rear/lib/layout-functions.sh

https://github.com/rear/rear/issues/1681
https://github.com/rear/rear/issues/1771
Tested with 4 disks:
- Disk 1: GPT with consecutive partitions
- Disk 2: MSDOS with consecutive partitions
- Disk 3: GPT with non-consecutive partitions (1, 3, 4, 6)
- Disk 4: MSDOS with non-consecutive partitions (1, 3 (extended), 5 (logical), 6 (logical))
`parted` is not capable of creating non-consecutive partitions. To still  be able to do so, the trick consists in creating dummy partitions to fill the gaps between partition numbers.
Allocation of these dummy …

Enable creation of non consecutive partitions

---

usr/share/rear/finalize/SUSE_LINUX/s390/660_install_grub2_and_zipl.sh
usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

In general see
https://github.com/rear/rear/issues/2137
in particular
for generic enhancements to support s390 dasd disks see
https://github.com/rear/rear/pull/2142#issuecomment-496178838
and for SUSE specific enhancements to install
the GRUB2 plus ZIPL bootloader on SLES on s390 see
https://github.com/rear/rear/pull/2142#issuecomment-496194073
By me on s390, see
https://github.com/rear/rear/pull/2142#issuecomment-496194073
Generic enhancements to support s390 dasd disks
and SUSE specific enhancements to install
the GRUB2 plus ZIPL bootloader on SLES on s390

Enhancements for dasd disks and GRUB2 plus ZIPL bootloader on SLES on s390

---

doc/user-guide/04-scenarios.adoc
usr/sbin/rear
usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/build/default/960_remove_encryption_keys.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/framework-functions.sh
usr/share/rear/restore/NETFS/default/400_restore_backup.sh
usr/share/rear/restore/YUM/default/405_recreate_users_and_groups.sh
usr/share/rear/restore/YUM/default/410_restore_backup.sh
usr/share/rear/verify/NETFS/default/600_check_encryption_key.sh

This is a critical security issue only if BACKUP_PROG_CRYPT_ENABLED
with a BACKUP_PROG_CRYPT_KEY is used.
https://github.com/rear/rear/issues/2155
therein in particular
https://github.com/rear/rear/issues/2155#issuecomment-499376750
This is an early submit so that you can have an early look
that is not yet tested at all by me because I never used
BACKUP_PROG_CRYPT_ENABLED myself.
Separate the special case when BACKUP_PROG_CRYPT_ENABLED
with a BACKUP_PROG_CRYPT_KEY is used
from the usual case when it is not used.
Only when BACKUP_PROG_CRYPT_ENABLED with
a BACKUP_PROG_CRYPT_KEY is used do special stuff
(in particular …

Do not log BACKUP_PROG_CRYPT_KEY value (issue 2155)

---

usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/1564
* How was this pull request tested? Making a recover on Baremetal server with SSD Samsung EVO NVMe disk
* Brief description of the changes in this pull request: for NVMe devices the trailing 'p' in the Disk value (as in /dev/nvme0n1p that is derived from /dev/nvme0n1p1) needs to be stripped (to get /dev/nvme0n1), otherwise the efibootmgr call fails because of a wrong disk device name.

Fix 4 issue 1564

---

usr/share/rear/restore/BACULA/default/400_restore_backup.sh

* How was this pull request tested? Tested a recovery with bacula until `bconsole` is executed
With this change, the bconsole output is sent to FD 7, which is stdout. Previously the output was sent to FD 1 which is redirected to the ReaR log.

bacula: Fixed 'bconsole' prompt not displaying at all when doing a recover

---

doc/user-guide/04-scenarios.adoc
usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/build/default/960_remove_encryption_keys.sh
usr/share/rear/conf/default.conf
usr/share/rear/restore/NETFS/default/400_restore_backup.sh
usr/share/rear/restore/YUM/default/405_recreate_users_and_groups.sh
usr/share/rear/restore/YUM/default/410_restore_backup.sh

https://github.com/rear/rear/issues/2157
Not yet tested at all by me - I will do that later...
Make the code that deals with BACKUP_PROG_CRYPT_KEY more fail safe:
1. Use double quotes `"$BACKUP_PROG_CRYPT_KEY"` so that
the BACKUP_PROG_CRYPT_KEY value can contain spaces.
2. Escape special regexp characters in the BACKUP_PROG_CRYPT_KEY value
when it is used as a regexp in `grep` or `sed`.
3. Use single quotes `BACKUP_PROG_CRYPT_KEY='my_secret_passphrase'`
in the documentation examples so that the BACKUP_PROG_CRYPT_KEY value
can contain special characters like `$`,
cf. …

More fail safe BACKUP_PROG_CRYPT_KEY handling (issue 2157)

---

usr/share/rear/prep/GNU/Linux/210_include_dhclient.sh

https://github.com/rear/rear/issues/2184
Not yet tested - will test it tomorrow...
Added test to prep/GNU/Linux/210_include_dhclient.sh
to Error out when DHCLIENT_BIN and DHCLIENT6_BIN are empty
and USE_DHCLIENT is set.

Error out when DHCLIENT_BIN and DHCLIENT6_BIN are empty and USE_DHCLIENT is set

---

usr/share/rear/layout/prepare/default/420_autoresize_last_partitions.sh

https://github.com/rear/rear/issues/2182
Not yet tested by me - will do that later today or tomorrow.
When 420_autoresize_last_partitions.sh resizes the last partition
on a GPT disk it leaves 33 LBA blocks at the end of the disk
so that 420_autoresize_last_partitions.sh produces a fully correct
disklayout.conf file where no further automated adjustments by
a subsequent script like 100_include_partition_code.sh are done.

Let 420_autoresize_last_partitions.sh leave 33 blocks at end of GPT disks (issue #2182)

---

usr/share/rear/layout/prepare/default/420_autoresize_last_partitions.sh
usr/share/rear/lib/layout-functions.sh

https://github.com/rear/rear/issues/2183
By me, see
https://github.com/rear/rear/issues/2183#issuecomment-512791873
In the function apply_layout_mappings (therein in its "step 3")
only treat leftover temporary replacement words as an error
if they are in a non-comment line (comments have '#' as first non-space character),
see https://github.com/rear/rear/issues/2183#issuecomment-511394129
Additionally I added in 420_autoresize_last_partitions.sh
the missing word 'bytes' to DebugPrint messages
so that the output changes e.g. from
```
New /dev/vda is 21474836480 smaller than old disk
```
to
```
New /dev/vda is 21474836480 …
```

In apply_layout_mappings it is no error when there are leftover replacement strings in comments

---

usr/share/rear/layout/prepare/default/320_apply_mappings.sh

https://github.com/rear/rear/issues/2181
By me in migration mode as described at
https://github.com/rear/rear/issues/2181#issue-468078812
and
https://github.com/rear/rear/issues/2181#issuecomment-512255821
With the changes here things "just work" for me.
In migration mode apply the disk layout mappings not only to disklayout.conf
but also to other files that are also used to migrate the disk layout, namely
$VAR_DIR/layout/config/df.txt and /etc/rear/rescue.conf
Additionally re-read the BTRFS_SUBVOLUME_SLES_SETUP variable
from /etc/rear/rescue.conf

Apply layout mappings also to other relevant files

---

usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh

#1356 ## Relax-and-Recover (ReaR) Pull Request Template
* Reference to related issue (URL): #2187 
* How was this pull request tested? Tested on RHEL8 with multiple segments
Create the 'lvmvol' lines commented out when multiple segments exist for a given LV.
This is not an issue unless Migration Mode is used.
In such case, using 'lvcreate' commands already does best effort and loses LV information.
**Reproducer**:
1. Add 2 disks to an existing system
2. Create a VG with the disks
~~~
~~~
3. Create 2 LVs with segments
~~~
~~~
4. Format and mount the LVs
~~~
~~~
5. Create rescue ISO
6. Check …

Issue #2187 - disklayout.conf file contains duplicate lines

---

usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh

* Reference to related issue (URL): #2187
Comparing disklayout generated before and after. Here is the difference:
```diff
-lvmvol /dev/rhel_ibm-p9wr-08 home 3941727207424b linear segmentsize:2000393601024b
-#lvmvol /dev/rhel_ibm-p9wr-08 home 3941727207424b linear segmentsize:1941333606400b
+lvmvol /dev/rhel_ibm-p9wr-08 home 3941727207424b linear 
+# extra parameters for the line above not taken into account when restoring using 'lvcreate': segmentsize:2000393601024b
+#lvmvol /dev/rhel_ibm-p9wr-08 home 3941727207424b linear 
+# extra parameters for the line above not taken into account when restoring using 'lvcreate': …
```

Minor adjustments to #2194

---

doc/user-guide/13-tcg-opal-support.adoc
usr/share/rear/output/RAWDISK/Linux-i386/260_create_syslinux_efi_bootloader.sh
usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh
usr/share/rear/output/RAWDISK/Linux-i386/280_create_bootable_disk_image.sh

* Tests were based on current ReaR master (d7b587cb5b7a14432e7c4f9e5f4d94e50abea740) on Ubuntu 18.04.2 LTS:
* Tested booting recovery systems in these configurations:
1. Legacy Boot
1. EFI Boot via syslinux (Secure Boot disabled)
1. EFI Boot via Grub 2 (Secure Boot disabled)
1. EFI Boot via Grub 2 (Secure Boot enabled)
* Tested TCG Opal 2 PBA disk unlocking with Secure Boot enabled.
This PR adds Secure Boot support to the RAWDISK output format.
This in turn enables Secure Boot in conjunction with the PBA (pre-boot authentication) system required to unlock TCG Opal 2-compatible self-encrypting disks. (BTW: AFAIK there is no other solution available …

RAWDISK and TCG Opal 2 Self-Encrypting Disks: add Secure Boot support

---

usr/share/rear/lib/uefi-functions.sh

* Reference to related issue (URL): #2001 
Tested on RHEL7 UEFI, RHEL8 UEFI + SLES12SP3 UEFI
On Fedora and RHEL systems, Grub2 UEFI modules live in /usr/lib/grub*/x86_64-efi, not /boot, unless grub2-install is executed, but executing this tool is not needed with UEFI at all.
On SuSE systems, Grub2 UEFI modules also live in /usr/lib/grub*/x86_64-efi, but there is also a copy in /boot, so it's not needed searching in /boot at all.
Additionally, only UEFI modules should be looked for, so /boot cannot be
searched but only /boot/grub2/x86_64-efi (similarly /usr/lib/grub*/x86_64-efi), …

uefi: Search for Grub2 modules in /usr/lib/grub*/x86_64-efi and not in /boot

---

usr/share/rear/prep/GNU/Linux/400_guess_kernel.sh

As it is, rear does not detect the kernel on ppc64el as it looks for
something like vmlinuz whether vmlinux is used on that arch.
* Reference to related issue (URL): No issue opened, just I just fixed it
* How was this pull request tested? I tested it on a Debian VM with rear mkbackup and recover afterwards.
* Brief description of the changes in this pull request: I added case for the specific ppc64el kernel naming in /boot

Handle ppc64el kernel naming

---

usr/share/rear/conf/GNU/Linux.conf

#2220
Running rear mkrescue, the new code logs:
```
Cloning users: daemon rpc usbmuxd usbmux vcsa nobody dbus sshd
Cloning groups: disk cdrom floppy tape audio video lp tty dialout kmem uucp ssh_keys plugdev tty usbmuxd usbmux fuse kvm oinstall dbus input daemon rpc nobody sshd
```
the old code logs:
```
Cloning users:  daemon rpc usbmuxd usbmux vcsa nobody dbus sshd
Cloning groups: disk cdrom floppy tape audio video lp tty dialout kmem uucp ssh_keys plugdev tty usbmuxd usbmux fuse kvm oinstall dbus input root
```
(note the extra space which should not be there).
Difference in /etc/passwd:
```diff
--- …
```

Append to CLONE_USERS and CLONE_GROUPS by using +=

---

usr/share/rear/lib/framework-functions.sh
usr/share/rear/verify/DUPLICITY/default/200_check_tmpfs.sh

* Type: Cleanup
* Reference to related issue (URL):  #1390
* How was this pull request tested? Rhel7 (rear -d -v mkrescue)
* Brief description of the changes in this pull request: Instead of using 'mount | grep "$BUILD_DIR/outputfs"' the command 'mountpoint -q "$BUILD_DIR/outputfs"'  is used.

Use mountpoint instead of mount|grep

---

usr/share/rear/build/default/990_verify_rootfs.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/framework-functions.sh

Print helpful messages about keeping/not keeping the build directory in case of errors.
#2121, https://bugzilla.redhat.com/show_bug.cgi?id=1693608
```
yum -y install rear
echo 'COPY_AS_IS+=( /usr/bin/xterm )' >> /etc/rear/local.conf
yum -y install xterm
rpm  -e --nodeps libXaw.x86_64 # don't do it on a workstation
```
This makes ReaR complain about broken xterm and abort. To test it interactively:
```
rear mkrescue
```
Result:
```
Broken symlink '/usr/lib/modules/3.10.0-1077.el7.x86_64/build' in recovery system because 'readlink' cannot determine its link target
Broken symlink …
```

Do not keep the build dir when used noninteractively

---

doc/user-guide/06-layout-configuration.adoc
usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
usr/share/rear/layout/prepare/default/520_exclude_components.sh
usr/share/rear/layout/save/GNU/Linux/280_multipath_layout.sh
usr/share/rear/layout/save/default/320_autoexclude.sh
usr/share/rear/lib/layout-functions.sh

**Bug Fix.**
**Normal.**
https://github.com/rear/rear/issues/2234.
Locally tested under KVM. Multipath configuration:
0QEMU_QEMU_HARDDISK_0001 dm-0 QEMU,QEMU HARDDISK
size=2.0G features='1 retain_attached_hw_handler' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=1 status=active
| `- 2:0:0:1 sdb 8:16 active ready running
`-+- policy='service-time 0' prio=1 status=enabled
`- 2:0:0:2 sda 8:0  active ready running
Model: Linux device-mapper (multipath) (dm)
Disk /dev/mapper/0QEMU_QEMU_HARDDISK_0001: 2147MB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk …

Improve handling of partition label type for multipath disks

---

usr/share/rear/lib/layout-functions.sh

**Bug Fix**.
**Normal**.
https://github.com/rear/rear/issues/2236.
Locally tested under KVM. Multipath configuration:
0QEMU_QEMU_HARDDISK_0001 dm-0 QEMU,QEMU HARDDISK
size=2.0G features='1 retain_attached_hw_handler' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=1 status=active
| `- 2:0:0:1 sdb 8:16 active ready running
`-+- policy='service-time 0' prio=1 status=enabled
`- 2:0:0:2 sda 8:0  active ready running
Model: Linux device-mapper (multipath) (dm)
Disk /dev/mapper/0QEMU_QEMU_HARDDISK_0001: 2147MB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk …

Fix including of multipath disks in backup

---

usr/share/rear/backup/RSYNC/GNU/Linux/610_start_selinux.sh
usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh
usr/share/rear/backup/RSYNC/default/450_calculate_req_space.sh
usr/share/rear/backup/RSYNC/default/500_make_rsync_backup.sh
usr/share/rear/backup/RSYNC/default/700_copy_backup_log.sh
usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
usr/share/rear/output/RSYNC/default/900_copy_result_files.sh
usr/share/rear/prep/NETFS/default/400_automatic_exclude_recreate.sh
usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh
usr/share/rear/verify/TSM/default/390_request_point_in_time_restore_parameters.sh
usr/share/rear/verify/default/020_cciss_scsi_engage.sh

https://github.com/rear/rear/issues/1395
Not yet tested by me in any way and
I cannot test all those affected code parts,
in particulart not the changes for TSM and NBU.
Some general cleanup for ReaR 2.6. in all scripts
by removing '2>/dev/null' where it makes sense
and replacing '&>/dev/null' by '1>/dev/null' where it makes sense
or also removing '&>/dev/null' where that seems to be better, see
https://github.com/rear/rear/issues/1395#issuecomment-541083321

Remove dev null redirection where possible issue1395

---

usr/share/rear/conf/default.conf
usr/share/rear/restore/DP/default/460_press_y_to_continue.sh
usr/share/rear/verify/GALAXY10/default/550_request_point_in_time_restore_parameters.sh
usr/share/rear/verify/NBU/default/380_request_client_destination.sh
usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh
usr/share/rear/verify/TSM/default/390_request_point_in_time_restore_parameters.sh
usr/share/rear/verify/default/040_validate_variables.sh

https://github.com/rear/rear/issues/2253
I tested the plain code by running it as a separated script
and for me the input seems to work o.k.
but I cannot actually test it with TSM or NBU
because I have neither of them.
Let the user enter date and time again and again until the input is valid
or the user pressed only ENTER to restore the most recent available backup.
Replaced 'LogPrint' with 'UserOutput' because
the former shows messsages only in verbose mode
while the latter shows messages always to the user
(this does not matter in practice during 'rear recover'
but 'UserOutput' is the ceaner code for user output
and I …

Do not abort in case of invalid user input but retry

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/save/default/320_autoexclude.sh
usr/share/rear/layout/save/default/335_remove_excluded_multipath_vgs.sh
usr/share/rear/lib/layout-functions.sh
usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
usr/share/rear/prep/YUM/default/070_set_backup_archive.sh
usr/share/rear/verify/YUM/default/070_set_backup_archive.sh

https://github.com/rear/rear/issues/2245
Not tested because I cannot test multipath.
Using `is_true "$AUTOEXCLUDE_MULTIPATH"`
instead of `[[ "$AUTOEXCLUDE_MULTIPATH" =~ ^[yY1] ]]`
according to "Relax-and-Recover functions" in
https://github.com/rear/rear/wiki/Coding-Style
Additionally a cleanup of the `get_partition_number` function:
When the comments talk about `bug` then `BugError` should be called.
Plus hopefully more comprehensible comments,
cf. "Code must be easy to understand" in
https://github.com/rear/rear/wiki/Coding-Style

Use is_true() for AUTOEXCLUDE_MULTIPATH and cleanup of get_partition_number()

---

usr/share/rear/conf/default.conf

This pull request supersedes https://github.com/rear/rear/pull/2244
https://github.com/rear/rear/issues/2239
I used a test system with a separated ext2 filesystem on /tmp
cf. https://github.com/rear/rear/issues/2239#issuecomment-538647867
With `AUTOEXCLUDE_PATH=( /media /run /mnt /tmp )`
I still got in disklayout.conf the ext2 filesystem on /tmp
which is the intended behaviour.
Enhanced AUTOEXCLUDE_PATH in default.conf
from only `AUTOEXCLUDE_PATH=( /media )`
to `AUTOEXCLUDE_PATH=( /media /run /mnt /tmp )`
plus explanatory comment in default.conf
how AUTOEXCLUDE_PATH works.

Enhanced AUTOEXCLUDE_PATH /media /run /mnt and /tmp

---

usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh

* How was this pull request tested? Tested on RHEL7 (poweroff.com) and RHEL8 (poweroff.c32)
RHEL8 (syslinux-6.04) is shipping `poweroff.c32`, not `poweroff.com`.

Add alternative for 'poweroff.com' ('poweroff.c32' on RHEL8)

---

usr/share/rear/restore/FDRUPSTREAM/default/260_copy_log_and_report.sh

* Impact:  **Normal**
Tested on CentOS 7, running 7 FDR/Upstream services.  Temporarily set $countmax=3 to verify that the infinite loop detection works properly.
Users may run multiple FDR/Upstream services on a single machine.  This code change allows ReaR to copy FDR/Upstream logs from the recovery environment to the restored system for all running services.  Previously the code was expecting to find only one set of logs and reports in the FDR/Upstream installation directory.  For several years now, logs and reports have been stored in a new location ($FDRUPSTREAM_DATA_PATH), so we check here instead.

Accommodate logs from multiple FDR/Upstream services.  Improve logging.

---

usr/share/rear/build/default/990_verify_rootfs.sh
usr/share/rear/conf/default.conf

* Impact: **Normal** (sometimes even **High**)
https://github.com/rear/rear/issues/2279
On my openSUSE Leap 15.0 system:
```
...
Copying all kernel modules in /lib/modules/4.12.14-lp150.12.79-default (MODULES contains 'all_modules')
Copying all files in /lib*/firmware/
...
Testing that the recovery system in /tmp/rear.SrlUTo4b7fvtlHL/rootfs contains a usable system
...
Exiting rear mkrescue (PID 13565) and its descendant processes
real    1m2.146s
user    0m49.257s
sys     0m8.092s
```
See
https://github.com/rear/rear/issues/2279#issuecomment-555562821
plus skip the `ldd` test for firmware files.
and redirected stderr of `ldd` avoids tons …

Improved check for missing libraries in 990_verify_rootfs.sh (issue 2279)

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
usr/share/rear/output/default/940_grub2_rescue.sh

Full backup && restore
Currently, ReaR is using hard-coded set of Grub2 modules for UEFI
boot-loader. This patch introduces global GRUB2_MODULES variable, so
that user can add or remove modules according his needs.
**Rationale:**
If one uses  `GRUB_RESCUE=y` in `UEFI mode` (yet another nice combination :-)), _rear.efi_ will be created with [different set of modules](https://github.com/rear/rear/blob/4e2a1819d54e0e1a9800a9405907c17253cec7f2/usr/share/rear/output/default/940_grub2_rescue.sh#L152) compared to _BOOTX64.efi_.
It is not so important for user to have possibility to add/remove Grub2 modules to _BOOTX64.efi_ …

Currently, ReaR is using hard-coded set of Grub2 modules for UEFI

---

usr/share/rear/conf/GNU/Linux.conf

https://github.com/rear/rear/pull/1961/files#r356220735
https://github.com/rear/rear/issues/1652
Backup to ISO and restore on RHEL 7.6 vagrant box with UEFI and CentOS 7 vagrant box without UEFI.
Revert part of #1961 : move `route` back from REQUIRED_PROGS to PROGS. `route` is actually not required, ReaR uses `ip route` everywhere. As it is not always installed nowadays (e.g. on CentOS 7 Vagrant images), having it in REQUIRED_PROGS breaks ReaR on those installs where it would work just fine.

Revert part of #1961 : move route back from REQUIRED_PROGS to PROGS

---

usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh
usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh

Issue 2281(missing delete_dummy_partitions_and_resize_real_ones calls)

---

doc/user-guide/06-layout-configuration.adoc
usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
usr/share/rear/layout/save/default/950_verify_disklayout_file.sh

* Type: **Minor Bug Fix** / **Enhancement**
* Impact: **Low** / **High**
Normally (i.e. on SLES and RHEL) nothing should be noticed
but when there are insufficient LVM tools used
(as in https://github.com/rear/rear/issues/2259)
the impact is high because without the check the error is unnoticed
so that things fail when it is too late during "rear recover".
https://github.com/rear/rear/issues/2259
Works for me on SLES12-SP4 with its default LVM(+btrfs) setup.
My disklayout.conf is identical compared to before the changes here.
According to
https://github.com/rear/rear/issues/2259#issuecomment-557019729
there is now a check before the longer `lvs` calls
to ensure …

Error out in case of insufficient LVM tools (issue 2259)

---

usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/layout/prepare/default/010_prepare_files.sh
usr/share/rear/layout/save/GNU/Linux/100_create_layout_file.sh
usr/share/rear/lib/layout-functions.sh

* Type: **Bug Fix** / **Cleanup**
In my case disklayout.conf became totally useless.
If the '/dev/sda' entries were only commented out
the bad disklayout.conf could still be manually adapted
but without any '/dev/sda' entries it is useless in practice
(I cannot guess during "rear recover" what right values could be).
https://github.com/rear/rear/issues/2298
Currently untested preliminary initial state.
"rear mkrescue" looks goot to me with that changes
but I need to test "rear recover" (hopefully tomorrow).
Better (i.e. hopefully more fail safe) `is_multipath_path` function, cf.
https://github.com/rear/rear/issues/2298#issuecomment-564590474 …

Better is_multipath_path function (issue #2298) plus some other stuff

---

usr/share/rear/wrapup/default/990_copy_logfile.sh

* Type: **Minor Bug Fix** / **Cleanup**
https://github.com/rear/rear/issues/2301
On my laptop as in
https://github.com/rear/rear/issues/2301#issue-537544483
I did a third "rear -D recover" and now I have in the log
```
+ source /usr/share/rear/wrapup/default/990_copy_logfile.sh
...
++ for log_file_symlink in $recovery_system_roots_home_dir/rear-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]*.log
++ test -L /mnt/local/root/rear-2019-12-11T17:26:13+01:00.log
+++ readlink -m /mnt/local/root/rear-2019-12-11T17:26:13+01:00.log
++ test /var/log/rear/recover/rear-linux-88cr.log = /var/log/rear/recover/rear-linux-88cr.log
++ rm --verbose …
```

Remove outdated /root/rear-DATE-TIMESTAMP.log symlinks (issue#2301)

---

usr/share/rear/conf/default.conf
usr/share/rear/conf/templates/rear.help
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh

https://github.com/rear/rear/issues/2276#issuecomment-554316041
Currently I had only tested the USB case.
I need to test the ISO case.
For `OUTPUT=ISO` the user can now explicitly specify
what to boot by default when booting the ISO on BIOS systems via
`ISO_DEFAULT="boothd0"` to boot from the first disk and
`ISO_DEFAULT="boothd1"` to boot from the second disk.
For `OUTPUT=USB` the user can now explicitly specify
what to boot by default when booting the disk on BIOS systems via
`USB_BIOS_BOOT_DEFAULT="boothd0"` to boot from the first disk.
The default `USB_BIOS_BOOT_DEFAULT=""` boots the second disk.
Those things are now …

Enhanced recovery system BIOS boot default settings for USB and ISO (related to issue 2276

---

doc/user-guide/16-Rubrik-CDM.adoc

#2266 
Ran `rear mkrecover` and `rear recover` on CentOS 7.7 and 8.0 virtual systems. Errors from missing libraries were not displayed and system recovery was successful.
Added instructions for using `LD_LIBRARY_PATH` in `/etc/rear/local.conf` to capture point to libraries not being found by `ldd`.

Added support for CentOS 7.7 and 8.0 for Rubrik-CDM

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
usr/share/rear/output/default/940_grub2_rescue.sh

* Type: **Bug Fix** / **Cleanup**
#2199 #2283  #2001 https://github.com/rear/rear/issues/1996#issuecomment-445201012 
the two cases that use the code touched by this PR:
- creating a rescue ISO on a RHEL 8.1 UEFI system and booting it
- creating a rescue system using GRUB_RESCUE and booting it using the EFI boot menu
- repeating both with GRUB2_MODULES=(part_gpt part_msdos fat ext2 normal chain boot configfile linux jfs iso9660 usb usbms usb_keyboard video udf ntfs all_video gzio efi_gop reboot search test echo btrfs lvm)
There have been several cases recently where ReaR on UEFI was broken due to either a wrong assumption about what Grub2 …

Use grub-mkstandalone instead of grub-mkimage for UEFI

---

usr/share/rear/layout/save/FDRUPSTREAM/Linux-s390/990_copy_disklayout_file.sh
usr/share/rear/output/default/950_copy_result_files.sh
usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh

if the path for $FDRUPSTREAM_DATA_PATH does not exist, then create it.
This change is FDR specific for s390 and is only in effect if ZVM_NAMING is "Y"
* Type: Bug Fix
* Impact:  Normal
Description:
If the data destination dir does not exist, then create it

create data path for s390 FDR backups if !exists

---

doc/user-guide/04-scenarios.adoc
usr/share/rear/build/GNU/Linux/130_create_dotfiles.sh
usr/share/rear/build/default/501_check_ssh_keys.sh
usr/share/rear/conf/default.conf
usr/share/rear/conf/examples/borg-example.conf
usr/share/rear/finalize/GNU/Linux/310_migrate_udev_rules.sh
usr/share/rear/finalize/NBU/default/990_copy_bplogrestorelog.sh
usr/share/rear/prep/DUPLICITY/default/050_prep_duplicity.sh
usr/share/rear/prep/DUPLICITY/default/200_find_duply_profile.sh
usr/share/rear/rescue/default/300_patch_root_home.sh
usr/share/rear/rescue/default/500_ssh.sh
usr/share/rear/restore/DUPLICITY/default/110_check_temp_dir_with_duply.sh
usr/share/rear/restore/RSYNC/default/800_copy_restore_log.sh
usr/share/rear/setup/default/005_ssh_agent_start.sh
usr/share/rear/wrapup/default/990_copy_logfile.sh

* Reference to related issue (URL): #2331
Full backup/restore with:
- root home directory set to _/root_
- root home directory set to _/root/home/root_
This patch removes hard-coded location of root home directory (/root) from ReaR code, and replaces it with global configuration variable **ROOT_HOME_DIR**. This allows to correctly track home directory of root user even when a non-default location is used.

Home directory of root user is not hard-coded any more.

---

usr/share/rear/finalize/GNU/Linux/320_migrate_network_configuration_files.sh

* Type: **Bug Fix**  / **Enhancement** / **Cleanup**
https://github.com/rear/rear/issues/2310
Just an initial "submit early submit often" part of today.
More will come tomorrow.
Not yet tested at all (only `bash -n` does not show a syntax error).
Currently it is an incomplete first part up to the line
```
```
of a general cleanup as first step which I do primarily
to get some basic understanding of the code.
Not yet any actual enhancement (that will be the second step).
Overhaul 320_migrate_network_configuration_files.sh
to make it working sufficiently with nowadays network ifcfg file syntax, cf. …

Cleanup and enhance 320_migrate_network_configuration_files.sh (issue 2310)

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
usr/share/rear/output/default/940_grub2_rescue.sh
usr/share/rear/rescue/default/860_set_uefi_vars.sh

* Type: **New Feature** / **Enhancement**
* Reference to related issue (URL): #2276 
ReaR rescue system boot with:
OUTPUT=USB and OUTPUT=NETFS
on
\- SLES12-SP2
\- Fedora29
\- Centos 7
**This patch adds following:**
\- Possibility to boot original system for UEFI boot with OUTPUT=NETFS
and OUTPUT=USB (similarly to non UEFI ReaR rescue system).
\- Introduces couple of new variables that could be later beneficial for other UEFI code:
- esp_mpt - mount-point of ESP (e.g. /boot/efi)
- esp_disk - disk device holding ESP (e.g. /dev/sda1)
- esp_relative_bootloader - relative path to UEFI_BOOTLOADER (e.g. /EFI/BOOT/BOOTX64.EFI)
- esp_disk_uuid - UUID of disk holding ESP
\- Replaces …

Allow to boot original system from Grub menu (UEFI)

---

usr/share/rear/prep/NETFS/default/100_check_nfs_version.sh

**Bug Fix**
**Low**
#2341 and #2250 
- Under RHEL7.6: On a  HPE DL360 Gen10.
- Under Debian 10: -
This pull request adds the missing but required NFS users for RHEL7.x and Debian 10 to let `rpcbind `start successfully during recovery.

Add missing but required NFS users for proper rpcbind startup

---

usr/share/rear/output/ISO/Linux-ppc64le/820_create_iso_image.sh

https://github.com/rear/rear/issues/2344#issuecomment-601949828
By @mmetts in https://github.com/rear/rear/issues/2344
Have a hardcoded '-iso-level 3' option
in output/ISO/Linux-ppc64le/820_create_iso_image.sh
because it is also hardcoded
in output/ISO/Linux-i386/820_create_iso_image.sh
and it seems to also work in general on PPC64LE architecture.

Have '-iso-level 3' option also for ppc64le

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh

https://github.com/rear/rear/issues/2344#issuecomment-602550299
https://github.com/rear/rear/commit/77773964633e8b6fcfc03841f8fb6770f7c453f7
By me one openSUSE Leap 15.1 using
various ISO_MAX_SIZE values (100, 200, 400, 600)
with and without `FIRMWARE_FILES=( 'no' )`
Cleaned up and enhanced the ISO_MAX_SIZE implementation
in backup/NETFS/default/500_make_backup.sh
to make it in particular more safe against erroneous settings
of the ISO_MAX_SIZE variable.

Overhauled ISO_MAX_SIZE implementation in 500_make_backup.sh

---

usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh

* Reference to related issue (URL): #2365 
* How was this pull request tested? on k8s worker nodes using Longhorn
* Brief description of the changes in this pull request: To avoid file system traces in the disklayout.conf file we need to skip these pseudo-devices (build via iscsi). See https://longhorn.io/ for more in-depth details about longhorn itself.

Skip Longhorn Engine replica devices

---

usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh

It is a minor bug when "rear mkrescue/mkbackup" does not error out
when things have actually failed.
In this case when gathering crypt information was not successful
the code blindly proceeds resulting wrong (incomplete) entries
in disklayout.conf that let later (when it is too late) "rear recover" fail.
https://github.com/rear/rear/issues/2204
By me on my current homeoffice laptop that uses LUKS 1.
I get still same 'crypt' entries in disklayout conf.
Error out during "rear mkrescue/mkbackup" when LUKS version 2 is used
because currently LUKS version 2 is not suppported.
When LUKS version 2 is used it fails at least …

Error out when LUKS version 2 is used (issue #2204)

---

usr/share/rear/build/GNU/Linux/100_copy_as_is.sh

* Type: **Enhancement** / **Cleanup**
https://github.com/rear/rear/issues/2377
With
```
```
and in etc/rear/local.conf
```
COPY_AS_IS+=( /usr/local/bin /usr/local/bin /usr/share/man/man8/partprobe.8.gz /usr/share/man/man8/partprobe.8.gz )
```
I get same files in /tmp/rear.XXXX/rootfs
with and without deduplication.
Filter out duplicate entries in COPY_AS_IS
but keep the ordering of the elements
i.e. only the first occurrence of an element is kept.
Also remove duplicates in the copy_as_is_filelist_file
with 'sort -u' because here the ordering does not matter.
Duplicates in the copy_as_is_filelist_file can happen
even if there are no duplicates …

Filter out duplicates in COPY_AS_IS and copy_as_is_filelist_file

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh

https://github.com/rear/rear/issues/2369
By ReaR user @dsamx
In backup/NETFS/default/500_make_backup.sh add "bs=1M" to
`SPLIT_COMMAND="dd of=$backuparchive bs=1M"`
to let 'dd' read and write up to 1MiB at a time to speed up things
for example from only 500KiB/s (with the 'dd' default of 512 bytes)
via a 100MBit network connection to about its full capacity

Use "dd ... bs=1M" in backup/NETFS/default/500_make_backup.sh

---

usr/share/rear/lib/bootloader-functions.sh

https://github.com/rear/rear/issues/2388
the change in this pull request was tested by the affected user, see
https://github.com/rear/rear/issues/2388#issuecomment-625147460
In the `create_grub2_cfg` function in usr/share/rear/lib/bootloader-functions.sh
that is used in case of UEFI to set up GRUB2 as bootloader for the recovery system
do no longer let GRUB2 load the modules `video_bochs` and `video_cirrus`
because those are not available as GRUB2 modules in case of UEFI (`x86_64-efi`)
and the generic `insmod all_video` that is still there should be sufficient for GRUB2
cf. …

No longer load video_bochs and video_cirrus by the create_grub2_cfg function

---

usr/share/rear/init/default/050_check_rear_recover_mode.sh

https://github.com/rear/rear/issues/2387#issuecomment-626303944
Tested by me on my SLES15 test system
Before init/default/050_check_rear_recover_mode.sh did only error out
when in the recovery system an unsupported workflow should be run.
Now it also errors out when on the normal/original system
an unsupported workflow should be run.
Rear 2.6 should not be released without that critical bug fix => "blocker".

Error out for unsupported workflow in any case

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/uefi-functions.sh

Renamed GRUB2_MODULES and GRUB2_MODULES_LOAD
for installing GRUB2 as recovery system UEFI bootloader into
GRUB2_MODULES_UEFI and GRUB2_MODULES_UEFI_LOAD
cf. https://github.com/rear/rear/issues/2392

Make GRUB2_MODULES variables having UEFI specific names (issue 2392)

---

usr/share/rear/output/PXE/default/820_copy_to_net.sh
usr/share/rear/output/default/950_copy_result_files.sh

* Reference to related issue (URL): **N/A**
Run `rear mkrescue` with and without destination directory schema created.
When transferring ReaR recovery system ISO, create also destination directory structure (including parents). This is useful because when destination directory structure does not exist (or is incomplete), Lftp puts files into last available directory in OUTPUT_URL scheme.

Create destination directory schema when using lftp

---

usr/share/rear/lib/borg-functions.sh
usr/share/rear/prep/BORG/default/200_prep_borg.sh

* Reference to related issue (URL): **N/A**
Full backup/restore
During restore with `BACKUP=BORG` messages as follow could be observed:
```
=== Borg archives list ===
Location:   backup
Repository: /mnt/rear/borg/node1
[1] HAEnode1_1 	Thu, 2020-05-21 10:40:15
[2] Exit
Choose archive to recover from
(timeout 300 seconds)
1
Recovering from backup archive /mnt/rear/borg/node1::HAEnode1_1 on backup
Remote: bash: warning: setlocale: LC_ALL: cannot change locale (rear.UTF-8)
...
```
`Remote: bash: warning: setlocale: LC_ALL: cannot change locale (rear.UTF-8)` message is shown when server site does not have `rear.UTF-8` available.
Changing locale name to standard …

Updated generated locale filename from "rear.UTF-8" to "en_US.UTF-8" (BACKUP=BORG)

---

usr/share/rear/output/PXE/default/820_copy_to_net.sh
usr/share/rear/output/default/950_copy_result_files.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/2406
With executing `rear mkbackup` with configured lftp. 
Currently OUTPUT_LFTP_OPTIONS are evaluated after connection to
destination host is established. This avoids using of
OUTPUT_LFTP_OPTIONS for connection specific settings.
This patch moves OUTPUT_LFTP_OPTIONS to the beginning of lftp command
before any other command is executed.

Evaluate OUTPUT_LFTP_OPTIONS at the beginning of lftp operations.

---

usr/share/rear/build/default/501_check_ssh_keys.sh

* Type: **Enhancement** **Cleanup**
At most "normal" impact because the
SSH_UNPROTECTED_PRIVATE_KEYS
functionality is only meant to work to some usual extent
but not for each and every special cases,
see its description in default.conf
```
SSH_UNPROTECTED_PRIVATE_KEYS='no'
```
https://github.com/rear/rear/issues/2421
A quick "rear mkrescue" test on my openSUSE Leap 15.1 system
with this in /etc/ssh/ssh_config
```
IdentityFile    ~/.ssh/id_dsa
IdentityFile = ~/.ssh/id_ecdsa
identityfile "~/.ssh/id_ed25519"
```
and that (dummy stuff) in /root/.ssh/config
```
IdentityFile    ~/.ssh/id_dsaqq
IdentityFile = ~/.ssh/id_ecdsaqq
identityfile "~/.ssh/id_ed25519qq"
```
* Brief description of the changes in …

Also parse SSH Include files in 501_check_ssh_keys.sh

---

usr/share/rear/prep/default/380_include_opal_tools.sh
usr/share/rear/skel/default/etc/scripts/unlock-opal-disks

* Reference to related issue (URL): #2425
* How was this pull request tested? On Ubuntu 20.04 LTS on two UEFI systems (one HPE ML10Gen9 server with problematic firmware, one other)
* OPALPBA: Add and remove a UEFI 'next boot' entry (essentially a no-op)

Fix #2425: OPALPBA: Reboot after SED-unlocking may hang on UEFI systems

---

usr/share/rear/prep/GNU/Linux/210_include_dhclient.sh

Personally I ( @jsmeix ) consider such kind of additional auto-detection
functionality in ReaR as **Low** impact - provided there is a config variable
where the user can specify what he wants and ReaR obeys.
* How was this pull request tested? On Ubuntu 20.04 LTS Desktop,
cf. https://github.com/rear/rear/issues/2368#issuecomment-644663685
While ReaR already does DHCP auto-detection during `mkrescue` for a number of configurations, the Network Manager flavor on Ubuntu 20.04 Desktop is not supported. This leads to DHCP not being auto-enabled and usually a rescue system which is not accessible remotely.
This patch adds the required Network Manager auto-detection:
```
2020-06-16 …
```

Add DHCP auto-configuration for Network Manager (Ubuntu 20.04 Desktop)

---

usr/share/rear/layout/prepare/GNU/Linux/131_include_filesystem_code.sh
usr/share/rear/layout/prepare/default/010_prepare_files.sh
usr/share/rear/layout/prepare/default/319_rename_xfs_configs.sh
usr/share/rear/layout/save/GNU/Linux/100_create_layout_file.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/2333
Successfully restored VM with following disk layout from VirtualBox to Qemu. (migration from /dev/sd* to /dev/vd*)
```
NAME                        KNAME     PKNAME    TRAN   TYPE  FSTYPE             SIZE MOUNTPOINT
/dev/sda                    /dev/sda            sata   disk                       8G 
|-/dev/sda1                 /dev/sda1 /dev/sda         part  vfat               200M /boot/efi
|-/dev/sda2                 /dev/sda2 /dev/sda         part  xfs                  1G /boot
`-/dev/sda3                 /dev/sda3 /dev/sda         part  LVM2_member        6.8G 
|-/dev/mapper/centos-root /dev/dm-0 /dev/sda3 …
```

Migrate XFS configuration files.

---

usr/share/rear/conf/default.conf

https://github.com/rear/rear/issues/2432
See https://github.com/rear/rear/issues/2432#issuecomment-648115634
Add "--type luks1" to the default LUKS_CRYPTSETUP_OPTIONS

Add "--type luks1" to the default LUKS_CRYPTSETUP_OPTIONS

---

doc/user-guide/13-tcg-opal-support.adoc
usr/share/rear/build/OPALPBA/Linux-i386/095_exclude_non_essential_files.sh
usr/share/rear/build/OPALPBA/Linux-i386/106_remove_files_copied_unconditionally.sh
usr/share/rear/conf/Ubuntu.conf
usr/share/rear/layout/save/GNU/Linux/190_opaldisk_layout.sh
usr/share/rear/lib/opal-functions.sh
usr/share/rear/lib/opaladmin-workflow.sh
usr/share/rear/prep/default/380_include_opal_tools.sh
usr/share/rear/skel/default/etc/scripts/unlock-opal-disks

* Reference to related issue (URL): #2436
* How was this pull request tested? On Ubuntu 20.04 LTS
* OPALPBA, Ubuntu: Fix incomplete file exclusions
* Fixes omissions reported in #2436.
* Uses COPY_AS_IS_EXCLUDE where possible.
* Removes files from the PBA system's staging directory where _not copying_ could not be configured.
* OPALPBA: Improve boot splash on Ubuntu 20.04
* Takes into account a change from VT1 to VT7 to hide log messages during the boot process.
* Improves Plymouth boot splash usage to hide log messages during the reboot after unlocking disks.
* opaladmin: Add sub-commands 'deactivate', 'reactivate'
* Makes turning on and off hardware encryption easier on provisioned …

TCG Opal Improvements

---

usr/sbin/rear
usr/share/rear/layout/save/GNU/Linux/100_create_layout_file.sh
usr/share/rear/lib/framework-functions.sh
usr/share/rear/lib/layout-functions.sh

Replacing somewhat obscure $DATE usage
with fixed and consistent variables.

Cleanup using $DATE

---

usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh

Fixes #2434. (problem introduced in PR #2293).
Success was reported by @yontalcar in #2434 (for RHEL 7 and RHEL 8 only though).
Sometimes the search command in GRUB2 used in UEFI ISO does not find the root device. This was seen at least in Debian Buster running in Qemu (VirtualBox works fine, RHEL/CentOS in Qemu works fine as well).
To make ReaR work in this case, set $root to a sensible value before trying `search`. The GRUB2 image created by grub-mkstandalone has $root set to memdisk, which can't work.
This essentially matches how it used to work before PR #2293.

Supply default value for root in grub in UEFI ISO

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/DP/default/500_restore_ssc.sh
usr/share/rear/output/DP/default/950_dp_save_result_files.sh
usr/share/rear/prep/DP/default/400_prep_dp.sh
usr/share/rear/prep/DP/default/450_check_dp_client_configured.sh
usr/share/rear/rescue/DP/default/450_prepare_omni_systemd.sh
usr/share/rear/rescue/DP/default/450_prepare_omni_xinetd.sh
usr/share/rear/restore/DP/default/300_create_dp_restore_fs_list.sh
usr/share/rear/restore/DP/default/400_restore_with_dp.sh
usr/share/rear/restore/DP/default/450_restore_via_gui.sh
usr/share/rear/restore/DP/default/460_press_y_to_continue.sh
usr/share/rear/verify/DP/default/400_verify_dp.sh
usr/share/rear/verify/DP/default/450_request_gui_restore.sh
usr/share/rear/verify/DP/default/500_select_dp_restore.sh

Type: Bug Fix and Enhancement
Impact: High
Without those changes the Data Protector 10.70 and later won't be able to use systemd (over xinetd). Restore performance from BACKUP=DP has been increased by doing parallel restores now.
Reference to related issue (URL):
none
How was this pull request tested?
Applied the changes to a SLES15 SP1 system running rear 2.6.1. Created a new ISO, booted the system and ran through various test cases.
Brief description of the changes in this pull request:
Additional changes to Data Protector branding and general script cleanup
Adjustment required to support systemd-only with Data Protector 10.70 and later in addition to xinetd-only deployments
Parallel restore support from BACKUP=DP

Support for systemd and parallel restore with Data Protector (BACKUP=DP)

---

usr/share/rear/conf/default.conf

* Type: **Enhancement** / **Possibly backward incompatible change**
High impact because of possibly backward incompatible change,
cf. https://github.com/rear/rear/issues/1565#issuecomment-342449263
https://github.com/rear/rear/issues/1565
and
https://github.com/rear/rear/issues/2456
in particular
https://github.com/rear/rear/issues/1565#issuecomment-342449263
Not at all tested by me.
In default.conf change `ISO_VOLID="RELAXRECOVER"` to
```
ISO_VOLID="REAR-ISO"
```
so the first ISO has the label REAR-ISO (8 characters) and subsequent ISOs
get the labels REAR-ISO_01 REAR-ISO_02 ... respectively
that have 11 characters which is the maximum length …

default.conf change ISO_VOLID="RELAXRECOVER" to ISO_VOLID="REAR-ISO"

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh

* Reference to related issue (URL): https://github.com/rear/rear/pull/2466#issuecomment-669168386
Ran a backup ensuring that there is not enough space in the destination to write backup.tar.gz.
Commit 2674807 removed the BACKUP_PROG_CRYPT_OPTIONS="cat" which breaks
the exit code logic because pipes_rc and backup_prog_shortnames does no
longer match.
Ensure that the number of elements in both variables are alwas the same.
Signed-off-by: Carlos Santos <casantos@redhat.com>

500_make_backup.sh: fix exit code logic

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh

* Reference to related issue (URL): #2465
* How was this pull request tested? See steps to reproduce in issue #2465 
```
When tar exits with status greater than zero rear copies the last three
tar messages from backup.log to its own log. Those lines are also shown
to the user when rear is invoked with the "-v" option.
Some tar messages, however, are purely informational, e.g.
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
tar: /var/spool/postfix/private/discard: socket ignored
Strip the informational messages and show only actual errors, e.g.
tar: /etc/grub.d/README: file changed as we read it
Fixes: issue #2465
Fixes: …
```

500_make_backup.sh: filter informational tar messages from output

---

usr/share/rear/build/GNU/Linux/400_copy_modules.sh

https://github.com/rear/rear/issues/2414
cf. https://github.com/rear/rear/issues/2414#issuecomment-668632798
In 400_copy_modules.s skip kernel modules that are builtin modules

In 400_copy_modules.sh skip copying kernel modules that are builtin modules (issue 2414)

---

usr/sbin/rear
usr/share/rear/lib/framework-functions.sh

https://github.com/rear/rear/issues/2461
Both "rear mkbackup" and "!rear recover" worked well for me
with BACKUP=NETFS on SLES12-SP5
The current working directory when usr/sbin/rear is launched
is also the working directory of all the other scripts and config files
that get sourced via the Source() function in lib/framework-functions.sh

Have 'cd WORKING_DIR' in Source() function

---

Makefile

N/A
The issue occurred when creating a gentoo ebuild for the 2.6 release
when running "make install" make throws warnings
`make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.`
Fix: do not call "make" inside a Makefile, use "$(MAKE)" instead
For reference, see
https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html

Makefile: fix warning "jobserver unavailable: using -j1"

---

usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh

https://github.com/rear/rear/issues/2491
On my home-office laptop I have both LUKS1 and LUKS2 volumes.
`luks2test` is the only LUKS2 volume.
With this changes I get (excerpts):
```
...
Creating disk layout
Overwriting existing disk layout file /root/rear.github.master/var/lib/rear/layout/disklayout.conf
Error: Incomplete values for LUKS device 'luks2test' at '/dev/sda8' (only LUKS version 1 is supported) see /root/rear.github.master/var/lib/rear/layout/disklayout.conf
Excluding component fs:/other
...
```
(The component `fs:/other` gets automatically excluded
because I use `OUTPUT_URL=file:///other` for my tests.)
This is the resulting …

Inform the user about unsupported LUKS2 volumes but do not error out

---

usr/share/rear/layout/save/default/310_include_exclude.sh
usr/share/rear/layout/save/default/320_autoexclude.sh
usr/share/rear/layout/save/default/330_remove_exclusions.sh
usr/share/rear/layout/save/default/335_remove_excluded_multipath_vgs.sh
usr/share/rear/layout/save/default/950_verify_disklayout_file.sh
usr/share/rear/lib/layout-functions.sh
usr/share/rear/prep/NETFS/default/400_automatic_exclude_recreate.sh

Tested on my home-office laptop while working on
https://github.com/rear/rear/pull/2493
More verbose messages when components are excluded
so that is is easier for the user to see what the actual results are
when he specified to exclude components in his etc/rear/local.conf
and what components are automatically excluded by ReaR.
There is a (perhaps oversophisticated?) distinction what messages should appear
- only in the log file in debug '-d' mode via 'Debug'
- in the log file and on the user's terminal in debug '-d' mode via 'DebugPrint'
- in the log file and on the user's terminal in verbose '-v' mode via 'LogPrint'
so that the info that is shown on …

More verbose messages when components are excluded

---

doc/rear-presentation.adoc
doc/rear.8
doc/rear.8.adoc
usr/sbin/rear
usr/share/rear/lib/help-workflow.sh

https://github.com/rear/rear/issues/2416
I tested `rear mkrescue` `rear -v mkrescue` `rear -d mkrescue` `rear -D mkrescue`
on my homeoffice laptop and I think the content in the log is now less confusing
for the user in particular in normal modes (i.e. `rear mkrescue` `rear -v mkrescue`).
Normally stdout and stderr are redirected to /dev/null.
Only in debug modes stdout and stderr are redirected to the log.
Cf. https://github.com/rear/rear/issues/2416#issuecomment-702142588

Redirect stdout and stderr to the log only in debug mode - normally they go to /dev/null (issue 2416)

---

usr/share/rear/prep/default/036_valid_output_methods.sh

https://github.com/rear/rear/issues/2501
Tested with `OUTPUT=iso` versus `OUTPUT=ISO` on my homeoffice laptop.
For "rear mkbackup/mkrescue/mkbackuponly/mkopalpba"
(i.e. for all workflows that run the 'prep' stage)
check that the OUTPUT method is actually implemented
i.e. check that a usr/share/rear/output/$OUTPUT directory exists
and error out when an OUTPUT method seems to be not supported
to ensure that the user cannot specify a non-working OUTPUT in /etc/rear/local.conf
cf. usr/share/rear/prep/default/035_valid_backup_methods.sh

New 036_valid_output_methods.sh to error out for unsupported OUTPUT methods

---

doc/user-guide/06-layout-configuration.adoc
usr/share/rear/conf/default.conf
usr/share/rear/layout/prepare/GNU/Linux/160_include_luks_code.sh
usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh

Enhancement.
Normal.
https://github.com/rear/rear/issues/2204
Quite thoroughly. I've run many backup followed by recover tests on Fedora 32, RHEL 8.2 and Fedora 25 (because there is LUKS1 by default on f25). I didn't notice any issues when I used default encryption during install of the system. I've also tried various ciphers/key-sizes/hash variants to ensure that values given by luksDump parsing on LUKS2 are meaningful and to recreating LUKS1 on system where LUKS2 is default and vice versa.
* Brief …

Add initial LUKS2 support

---

usr/share/rear/lib/layout-functions.sh
usr/share/rear/lib/opal-functions.sh
usr/share/rear/skel/default/etc/scripts/unlock-opal-disks

This patch enables support for OPAL 2 self-encrypting NVMe disk drives.
I will amend this PR and/or propose merging it as soon as testing results come in (cf. progress in #2475).

Support OPAL 2 self-encrypting NVMe disk drives (fix #2475)

---

usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/conf/default.conf
usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh

* Reference to related issue (URL): #2474
As AMD graphics hardware was not available on the test system, tests were run by mocking as follows:
* Add these lines in `usr/share/rear/lib/mkopalpba-workflow.sh` after `SourceStage "prep"`:
```bash
LogPrintError "FIRMWARE_FILES=<${FIRMWARE_FILES[*]}>"
exit
```
* Run `usr/sbin/rear mkopalpba` with default configuration (Intel graphics), expect result: `FIRMWARE_FILES=<no>`.
* In `default.conf` use these single-line configuration changes:
* `FIRMWARE_FILES=( yes )`, expect result: `FIRMWARE_FILES=<no>`.
* `FIRMWARE_FILES=( a b c )`, expect result: `FIRMWARE_FILES=<a b c>`.
* `OPAL_PBA_FIRMWARE_FILES=( one two )`, expect result: `FIRMWARE_FILES=<one two>`.
* In …

Fix #2474: add AMD firmware to OPAL PBA if necessary

---

doc/user-guide/06-layout-configuration.adoc
usr/share/rear/layout/prepare/GNU/Linux/160_include_luks_code.sh
usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh

https://github.com/rear/rear/pull/2504
Not yet tested by me.
The "cryptseup luksFormat" command does not require
any of the cipher, key-size, hash option values
because if omitted a cryptseup default value is used, cf.
https://github.com/rear/rear/pull/2504#issuecomment-720341023

Make recreating LUKS volumes work with optional cryptsetup options

---

usr/share/rear/build/default/990_verify_rootfs.sh

https://github.com/rear/rear/issues/2508#issuecomment-725914211
Of course things still work for me on my openSUSE Leap 15.1 system
but I do not use any special LD_LIBRARY_PATH so my test is rather meaningless.
I have to wait for @dcz01 feedback on
https://github.com/rear/rear/issues/2508#issuecomment-725921174
In 990_verify_rootfs.sh restore the LD_LIBRARY_PATH
after reporting binaries with 'not found' shared object dependencies
so that results are the same for the first 'ldd' run that finds binaries
with 'not found' shared objects dependencies and the second 'ldd' run
that reports those 'not found' shared objects …

Restore the LD_LIBRARY_PATH after reporting binaries with 'not found' shared objects

---

usr/share/rear/rescue/GNU/Linux/500_clone_keyboard_mappings.sh

https://github.com/rear/rear/issues/2519
Works well for me.
On my openSUSE Laep 15.1 system I get during "rear -D mkrescue"
```
Included current keyboard mapping (via 'dumpkeys -f')
Included fallback US keyboard mapping /usr/share/kbd/keymaps/legacy/i386/qwerty/defkeymap.map.gz
Included other keyboard mappings in /usr/share/kbd/keymaps
```
But I did not test the various failure cases.
Inform the user about possible issues with keyboard usage in the recovery system
but use neutral wording for those user messages to avoid false alarm
except when it fails to include the current keyboard mapping
(which is no fatal Error …

Better wording in user messages about keyboard issues

---

usr/share/rear/build/default/990_verify_rootfs.sh

* Type: **Bug Fix** / **Enhancement** / **Cleanup**
* Impact: **Low** / **High**
Low for normal use cases with 'tar' as backup tool.
Probably high for users with third-party backup tools
that require special LD_LIBRARY_PATH settings.
https://github.com/rear/rear/issues/2508#issuecomment-726711801
"rear mkrescue" still works well for me with backup tool 'tar'
The whole ldd testing code in 990_verify_rootfs.sh was completely overhauled:
Now a special LD_LIBRARY_PATH is only set directly before the "chroot ... ldd" test
and afterwards it is restored to what it was before.
Now each binary is first tested without any LD_LIBRARY_PATH set (which is the normal case)
and …

Completely overhauled ldd test in 990_verify_rootfs.sh

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/output-functions.sh
usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
usr/share/rear/output/ISO/Linux-i386/830_create_iso_image_EFISTUB.sh
usr/share/rear/output/ISO/Linux-ia64/800_create_isofs.sh
usr/share/rear/output/ISO/Linux-ppc64le/820_create_iso_image.sh
usr/share/rear/prep/ISO/GNU/Linux/320_verify_mkisofs.sh

* Type: **Bug Fix**  / **Enhancement**
* Impact: **Low** / **Critical**
Low impact (actually there should be no impact) under normal circumstances.
In contrast critical when the backup is included in the ISO with BACKUP_URL=iso://
where the backup archive file (e.g. backup.tar.gz) could be greater or equal 2GiB.
When there is a 2GiB file size limit a backup.tar.gz that is greater than 2GiB
will get corrupted in the ISO so backup restore via "rear recover" would fail
but then it is too late and the backup in the ISO is unusable.
Therefore such a test is critical because without such a test
for the user it appears af if everything went OK during "rear mkbackup"
until he finds out later during "rear recover" that his backup got corrupted. …

Error out when files greater or equal ISO_FILE_SIZE_LIMIT should be included in the ISO

---

doc/rear-release-notes.txt
doc/rear.8
doc/rear.8.adoc
usr/share/rear/conf/default.conf
usr/share/rear/prep/NBKDC/default/400_prep_nbkdc.sh
usr/share/rear/restore/NBKDC/default/400_restore_backup.sh

* Type: Bug Fix
Fixes #2518 
* Impact: Normal
* Reference to related issue (URL): https://github.com/rear/rear/issues/2518
+ NovaStor development team internal code Review.
+ Developer (me) tested backup and restore of Fedora Workstation 32 and Ubuntu 20.04 VM.
+ NovaStor QA team tested backup and restore of CentOS 7 VM.
This PR allows ReaR restore with NovaStor DataCenter 8.0 or higher. The NBKDC scripts before, are working only with DataCenter 7.x.
The commit messages contain brief description, what they change.

NBKDC: Fix ReaR backup and restore with NovaStor DataCenter 8.0 and higher

---

usr/share/rear/prep/DP/default/450_check_dp_client_configured.sh
usr/share/rear/restore/DP/default/450_restore_via_gui.sh
usr/share/rear/verify/DP/default/400_verify_dp.sh
usr/share/rear/verify/DP/default/450_request_gui_restore.sh

Type: Enhancement
Impact: High
Other platforms supporting the Data Protector Disk Agent, but not the Cell Console (GUI), will be supported with REAR and BACKUP=DP. This includes ppc64.
Reference to related issue (URL):
none
How was this pull request tested?
Applied the changes to a SLES15 SP1 system running rear 2.6.1. Created a new ISO, booted the system and ran through various test cases.
Brief description of the changes in this pull request:
Relevant checks unavailable on clients without the Data Protector Cell Console (GUI) are skipped. Restore defaults to external Data Protector GUI restore.

ppc64 support for BACKUP=DP

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/output-functions.sh
usr/share/rear/prep/ISO/GNU/Linux/320_verify_mkisofs.sh

https://github.com/rear/rear/pull/2525
See https://github.com/rear/rear/pull/2533#issuecomment-738034862
Skip the assert_ISO_FILE_SIZE_LIMIT function
when there is no usable ISO_FILE_SIZE_LIMIT set
so the user could specify `ISO_FILE_SIZE_LIMIT=0`
or `ISO_FILE_SIZE_LIMIT="no"` in his etc/rear/local.conf
if he wants to skip the ISO_FILE_SIZE_LIMIT test.

ISO_FILE_SIZE_LIMIT: provide final power to the user to skip the ISO_FILE_SIZE_LIMIT test

---

usr/sbin/rear
usr/share/rear/prep/USB/default/380_copy_usb_fs_module.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh

I noticed the false alarm `modprobe: FATAL: ...` error message during my tests with
https://github.com/rear/rear/issues/2534
See https://github.com/rear/rear/pull/2537#issuecomment-741819477
and https://github.com/rear/rear/pull/2537#issuecomment-741825046
Completely overhauled USB filesystem related kernel module handling:
In prep/USB/default/380_copy_usb_fs_module.sh do no longer unconditionally
add the USB filesystem to the MODULES and MODULES_LOAD arrays
because there are systems where the USB filesystem (e.g. 'ext3')
is no kernel module (e.g. on openSUSE Leap 15.2) and then via
MODULES_LOAD "modprobe ext3" fails …

Completely overhauled USB filesystem kernel module handling

---

usr/share/rear/build/default/990_verify_rootfs.sh
usr/share/rear/conf/default.conf
usr/share/rear/finalize/DP/default/500_restore_ssc.sh

Type: Enhancement
Impact: Medium
Add DP_LD_LIBRARY_PATH to include shared libraries used by BACKUP=DP and make ReaR compatible with changes in recent versions of Micro Focus Data Protector
Reference to related issue (URL):
none
How was this pull request tested?
Applied the changes to a SLES15 SP2 system running rear 2.6.1. Created a new ISO, booted the system and ran through various test cases.
Brief description of the changes in this pull request:
- Add DP_LD_LIBRARY_PATH to include shared libraries used by BACKUP=DP
- Handle new encrypted client certificates in Data Protector 10.80 and later
- Excludes files only used by Data Protector Reporting Server to reduce image footprint

Add DP_LD_LIBRARY_PATH to include shared libraries used by BACKUP=DP

---

usr/share/rear/layout/prepare/GNU/Linux/131_include_filesystem_code.sh

* How was this pull request tested? **manually by me - only the no label but uuid path**
* Issue #2548 related to this PR but it is not the same
mkfs.vfat (used for e.g. uefi partition) did not honor the uuid from the layout so "boot original system" was failing (by id/no label) after a recover. It also adds new boot menu entries and changes boot order on HP machines when a efi partition with new id is detected. The change tries to use -i option to set the uuid on creation and falls back to not using it when it fails (like done in the script for ext and others). This fixes the issues.

fixed vfat mkfs using uuid from layout if possible

---

usr/share/rear/conf/default.conf
usr/share/rear/prep/BACULA/default/400_prep_bacula.sh
usr/share/rear/prep/BACULA/default/450_check_BACULA_client_configured.sh
usr/share/rear/prep/BACULA/default/500_check_BACULA_bconsole_results.sh
usr/share/rear/prep/OBDR/BACULA/default/030_bextract_tape_device.sh
usr/share/rear/verify/BACULA/default/050_check_requirements.sh
usr/share/rear/verify/BACULA/default/100_start_bacula-fd.sh

Signed-off-by: Gratien Dhaese <gratien.dhaese@gmail.com>
* Reference to related issue (URL): #2152 
* How was this pull request tested? Not yet tested - waiting on Bacula user to do that for us
* Brief description of the changes in this pull request: The Enterprise Bacula uses different locations for keeping the configuration files than the community version of Bacula, hence, the enhancement to detect the correct location via preparation flow.

#2152: make bacula aware of different location of config files

---

usr/share/rear/conf/default.conf
usr/share/rear/output/RAWDISK/Linux-i386/280_create_bootable_disk_image.sh
usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh

* How was this pull request tested? On Ubuntu 20.04 LTS Server
This PR enables `rear mkrescue` when used with the **RAWDISK** output method to install the rescue/recovery system directly to one or more local disk partitions.
This is particularly useful on systems with redundant disks where a malfunction of one disk can be recovered via a rescue system available on another disk. It is also useful for testing as a separate rescue/recovery medium is no longer necessary.
1. Enable `RAWDISK` output.
1. Prepare one or more rescue partitions on local disk(s)
* with an appropriate size …

RAWDISK: Add local rescue partition installation capability

---

usr/share/rear/conf/default.conf
usr/share/rear/rescue/NBU/default/450_prepare_netbackup.sh
usr/share/rear/skel/NBU/usr/openv/tmp/.gitignore

Tested by a customer using ReaR (2.4 version in RHEL 8) with NetBackup 8.2
It was found by our customer that when attempting to restore from NetBackup, bprestore is unable to restore data from NetBackup server:
```
EXIT STATUS 25: cannot connect on socket
bprestore failed (return code = 25)
```
The fix is to copy the NetBackup PBX (vxpbx_exchanged) service to the rescue system and start it on boot before starting NetBackup. Additionally, it was needed to add the /usr/openv/tmp directory.
The problem was reported for NetBackup 8.2, but the service is apparently needed even in older versions of NetBackup …

Changes for NetBackup (NBU) support

---

usr/share/rear/build/default/503_store_tty_root_password.sh
usr/share/rear/conf/default.conf
usr/share/rear/prep/default/340_include_password_tools.sh
usr/share/rear/skel/default/bin/login

* How was this pull request tested? On Ubuntu 20.04 LTS Server
Currently, ReaR allows a password check on SSH sessions only (via `SSH_ROOT_PASSWORD`).
This PR enables the rescue/recovery system to enforce a password check also on terminal connections (the system console and/or serial terminals).
This prevents unauthenticated local root access
* while the rescue/recovery system is being run via a remote SSH session, or
* when a system reboot has inadvertently started the recovery system installed on a local disk partition (e.g. where a buggy firmware has inadvertently reshuffled the boot order).
1. Configure `TTY_ROOT_PASSWORD` in the same way as …

Add terminal password check via 'TTY_ROOT_PASSWORD'

---

usr/share/rear/output/ISO/Linux-i386/700_create_efibootimg.sh

https://github.com/rear/rear/issues/2552
Not at all tested by me (I don't use EFI).
Add 2 more 32MiB blocks to be on the safe side against inexplicaple failures like
"cp: error writing '/tmp/rear.XXX/tmp/efi_virt/./EFI/BOOT/elilo.conf': No space left on device"
where the above calculated $efi_img_sz is a bit too small in practice.

Add 2 more 32MiB blocks to efi_img_sz (issue 2552)

---

usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh

* How was this pull request tested? Test on RHEL7 with a LVM Raid
Make sure we delete the volume group before re-creating it.
The issue happens in Migration mode when ReaR is not trying to use vgcfgrestore.
1. Install a system
2. Add 2 additional disks that will be used to host a LVM VG
- /dev/vdb
- /dev/vdc
3. Create a Raid volume
~~~
~~~
4. Build a rescue image and perform a recovery
Error is shown below:
~~~
Start system layout restoration.
Disk '/dev/vda': creating 'msdos' partition table
Disk '/dev/vda': creating partition number 1 with name 'primary'
Disk '/dev/vda': creating partition number 2 with name 'primary'
Creating LVM PV /dev/vdb
Creating LVM PV /dev/vdc
Creating LVM PV …

Update 110_include_lvm_code.sh to make sure vgremove is called before recreating the VG

---

usr/share/rear/format/USB/default/300_format_usb_disk.sh

I've created usb disk images using 
```
fallocate -l 8G /var/lib/rear/output/rear-hostname.img
losetup -P /dev/loop0 /var/lib/rear/output/rear-hostname.img
YES=true rear -v format -- --efi /dev/loop0
rear -v -c mkbackup
losetup -d /dev/loop0
```
With a local.conf
```
OUTPUT=USB
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
USB_UEFI_PART_SIZE=200
```
and tested them as usb disk image in libvirt/kvm
Support loop devices to create usb disk images without having a physical usb stick plugged in in to the server. The problem is loop devices is that the first partition is names **loop0p1** instead of **loop01** …

Support loop devices in format_usb_disk

---

usr/share/rear/conf/default.conf
usr/share/rear/format/USB/default/300_format_usb_disk.sh
usr/share/rear/output/ISO/Linux-i386/700_create_efibootimg.sh
usr/share/rear/output/ISO/Linux-ia64/200_mount_bootimg.sh

* Type: **Minor Bug Fix** / **Enhancement** / **Cleanup**
https://github.com/rear/rear/issues/2575
Not tested by me but SUSE user reported that it is ok, see
https://github.com/rear/rear/issues/2575
Do no longer specify '-o fat=16' when loop mounting efiboot.img file
but rely on the automatic FAT type detection when mounting
cf. https://github.com/rear/rear/issues/2575
plus some general generic code cleanup in
output/ISO/Linux-i386/700_create_efibootimg.sh

Do not specify '-F 16'  for mkfs.vfat and also no '-o fat=16' when mounting it

---

usr/share/rear/format/USB/default/200_check_usb_layout.sh
usr/share/rear/layout/save/default/320_autoexclude.sh
usr/share/rear/lib/format-workflow.sh
usr/share/rear/lib/output-functions.sh
usr/share/rear/lib/udev-workflow.sh
usr/share/rear/prep/USB/Linux-i386/350_check_usb_disk.sh

* Type: **Minor Bug Fix** / **Enhancement**
https://github.com/rear/rear/issues/2588
Not tested - basically only message text changes.
Replace possibly misleading "USB device" by generic "USB or disk device" wording

Replace possibly misleading "USB device" by generic "USB or disk device" wording

---

usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh

This enables to run "rear recover" with automated LVM LVs shrinking as needed
on a bit smaller replacement disk (e.g. when a nominally same sized replacement disk
is actually a bit smaller than the original disk).
The automated LVs shrinking is not intended when replacement disk(s) are substantially smaller.
To migrate onto a substantially smaller replacement disk the user must in advance
manually adapt his disklayout.conf file before he runs "rear recover".
On my SLES 15 SP 3 system with the YaST default LVM setup as in
"SLES 15 SP 1 with default LVM and btrfs structure" in
https://github.com/rear/rear/wiki/Test-Matrix-rear-2.6
where "rear recover" runs on a 1GiB smaller disk
i.e. 19GiB on the replacement VM …

Automatically shrink LVs if needed during "rear recover"

---

usr/share/rear/prep/RSYNC/default/050_prep_rsync.sh

* Reference to related issue (URL): #2594 
* How was this pull request tested? by end-user of #2594 (@cvijayvinoth)
* Brief description of the changes in this pull request: adding sleep period to give the rsync daemon some extra time to wake up before accepting connections

#2594 adding sleep period to give rsync daemon time to wake up

---

usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh

* Reference to related issue (URL): #2596 
* How was this pull request tested? manually via savelayout
* Brief description of the changes in this pull request: Do not stop with an Error during the savelayout when we discover a PV that is not part of a VG

#2596 Have unused LVM PV devices only as comment in disklayout.conf file

---

usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh
usr/share/rear/lib/layout-functions.sh

* Reference to related issue (URL): #2595
Backup & restore on a RHEL 8 host with UEFI but without RAID and on a CentOS 7 host with UEFI and RAID (ESP on RAID). Examination of logs to check that correct efibootmgr commands were executed.
Use dependencies when determining partitions for UEFI
The ESP may be located on a RAID device. In this case, we need to determine the physical RAID components and call efibootmgr on them (after restoring - during the finalize step), because efibootmgr does not know how to tell the firmware to boot from RAID. Moreover, the current code tries to parse a device like `/dev/md125` into a disk called `/dev/md` and partition `125`. …

Fix setting boot path in case of UEFI partition (ESP) on MD RAID

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/default/940_grub2_rescue.sh

https://github.com/rear/rear/issues/2545
Not at all tested by me - currently I don't have a UEFI test system
Improved user messages during GRUB_RESCUE setup in particular for the UEFI case
plus some error checking in the UEFI case and some minor code simplifications.

Better description and error checking for GRUB_RESCUE with UEFI plus some alignment with create_grub2_cfg function

---

usr/share/rear/prep/default/400_save_directories.sh

https://github.com/rear/rear/issues/2610
Right now only a preliminary proposal
that is not yet at all tested by me.
In prep/default/400_save_directories.sh
also exclude mountpoints that are below mountpoints of "type autofs".
Such mountpoints are below an ancestor mountpoint that is owned/created by the automounter.
It is possible to create a sub-mountpoint below an automounted mountpoint
but the fact that the sub-mountpoint is not local means it should be excluded
(i.e. there is no need to recreate the non-local sub-mountpoint directory).
Furthermore automounted NFS filesystems can cause this script to hang up if NFS …

In 400_save_directories.sh also exclude mountpoints below mountpoints of "type autofs"

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/backup/RSYNC/GNU/Linux/610_start_selinux.sh
usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh
usr/share/rear/backup/RSYNC/default/200_check_rsync_relative_option.sh
usr/share/rear/backup/RSYNC/default/500_make_rsync_backup.sh
usr/share/rear/backup/RSYNC/default/700_copy_backup_log.sh
usr/share/rear/conf/default.conf
usr/share/rear/output/RSYNC/default/200_make_prefix_dir.sh
usr/share/rear/output/RSYNC/default/900_copy_result_files.sh
usr/share/rear/prep/NETFS/default/400_automatic_exclude_recreate.sh
usr/share/rear/prep/RSYNC/GNU/Linux/200_selinux_in_use.sh
usr/share/rear/prep/RSYNC/default/100_check_rsync.sh
usr/share/rear/prep/RSYNC/default/150_check_rsync_protocol_version.sh
usr/share/rear/restore/DUPLICITY/default/400_restore_duplicity.sh
usr/share/rear/restore/RBME/default/400_restore_backup.sh
usr/share/rear/restore/RSYNC/default/200_remove_relative_rsync_option.sh
usr/share/rear/restore/RSYNC/default/400_restore_rsync_backup.sh
usr/share/rear/verify/RSYNC/GNU/Linux/600_check_rsync_xattr.sh
usr/share/rear/verify/RSYNC/default/550_check_remote_backup_archive.sh

* Type: **Bug Fix** / **Cleanup**
* Reference to related issue (URL): #2612, #2577
Against CentOS 7:
1. full backup and restore using rsync over ssh
2. added nonsensical rsync option `BACKUP_RSYNC_OPTIONS+=( -M--nonsense )`, verified that ReaR aborts mkbackup instead of displaying a warning message and continuing
3.  added nonsensical rsync option `BACKUP_RSYNC_OPTIONS+=( -M--nonsense )` in the rescue system, verified that ReaR displays a prominent warning during mkrescue before continuing and aborting later at a different place
4. added  `BACKUP_INTEGRITY_CHECK=1` and a nonsensical rsync option `BACKUP_RSYNC_OPTIONS+=( -M--nonsense )` in the rescue system, verified that ReaR displays a rsync error and aborts during mkrescue instead …

Cleanup rsync and fix error reporting

---

usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh

Having `PROGS+=( lvcreate )` in etc/rear/local.conf causes
false Error() exit in copy_binaries() in 390_copy_binaries_libraries.sh
```
...
Copying binaries and libraries
ERROR: Failed to copy '/sbin/lvcreate' to '/tmp/rear.hM0nwyMqPDhiprd/rootfs/bin'
```
The change in this pull request avoids this false Error() exit.
Avoid false Error() exit in copy_binaries()
in build/GNU/Linux/390_copy_binaries_libraries.sh
```
ERROR: Failed to copy '/sbin/lvcreate' to '/tmp/rear.XXX/rootfs/bin'
```
when there is e.g. `PROGS+=( lvcreate )` in etc/rear/local.conf
by skipping 'cp' errors in copy_binaries()
(regardless what the reason was why 'cp' failed)
but add the affected …

Avoid false Error() exit in copy_binaries() in 390_copy_binaries_libraries.sh

---

usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh

https://github.com/rear/rear/issues/2616
Not at all tested by me.
In layout/save/GNU/Linux/210_raid_layout.sh
treat the RAID layout value '-unknown-' same as an empty value
to avoid that layout/prepare/GNU/Linux/120_include_raid_code.sh
will create a 'mdadm' command in diskrestore.sh like
"mdadm ... --layout=-unknown- ..."
which would fail during "rear recover" with something like
"mdadm: layout -unknown- not understood for raid0"

Treat RAID layout value '-unknown-' same as an empty value

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/_input-output-functions.sh

With the default USER_INPUT_MAX_CHARS=0 input is not truncated and it
also makes correcting the input possible (before [Enter] is pressed)
cf. https://github.com/rear/rear/issues/2622
https://github.com/rear/rear/issues/2622
By me on Leap 15.2
With the default USER_INPUT_MAX_CHARS=0 input is not truncated
and it also makes correcting the input possible (before [Enter] is pressed)

Better default USER_INPUT_MAX_CHARS=0 makes correcting the input possible

---

usr/share/rear/conf/default.conf
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
usr/share/rear/output/USB/Linux-i386/300_create_grub.sh
usr/share/rear/output/USB/Linux-i386/830_copy_kernel_initrd.sh
usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh

* Type: **New Feature** / **Enhancement**
* Reference to related issue (URL): partially #2648
tested output usb with:
1. USB_BOOTLOADER=
2. USB_BOOTLOADER=grub
on apu2 board (coreboot/seabios) - no efi
added option to write grub bootloader to usb (no efi)
it may not be perfect but a good starting point

added grub bootloader for USB

---

usr/share/rear/format/USB/default/300_format_usb_disk.sh

* Impact:  **High**
* Reference to related issue (URL): most parts of #2648 
output usb on apu1 and apu2 boards - with msdos and gpt using extlinux/syslinux boot.
this PR fixes all blocking bugs for output usb on none efi devices.
** fixing boot by adding gpt boot partition (ef02)
** adding boot partition to get it closer to how efi formatting works
** adding option for gpt boot flag on separate boot partition
Additional note:
you may need to set OUTPUT_URL=usb:///dev/disk/by-label/REAR-BOOT

fixed output usb format script for none efi cases

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
usr/share/rear/output/USB/Linux-i386/300_create_grub.sh
usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh

https://github.com/rear/rear/pull/2655
Not at all tested by me
Simplifications for USB_BOOTLOADER="grub"

Simplifications for USB_BOOTLOADER="grub"

---

usr/share/rear/lib/bootloader-functions.sh

* Type: **Bug Fix** / **Enhancement** 
with output=usb, partitioned gpt, bootloader grub, no efi/legacy boot on apu2 hardware with firmware 4.13.0.6
This PR fixes two bugs in grub config while improving readability of config write function a bit.
1) it fixes all the none efi cases for the boot menu in the grub config
2) it fixes or actually adds serial configuration to the config

Fix grub config

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh

* Reference to related issue (URL): kind of related #2644
* Relax-and-Recover 2.6 / 2020-06-17
* syslinux 6.04  Copyright 1994-2015 H. Peter Anvin et al
* extlinux 6.04  Copyright 1994-2015 H. Peter Anvin et al
using output=usb I created a bootable USB stick with working serial on a apu board based machine. (ex6linux)
I can not find any statement in syslinux documentation if multiple `serial` lines are allowed. The docs just state the line must be the first one in the config file. On my apu board based machine I have two serial interfaces (and nothing else) but as soon as I have `serial` config lines for two different devices/ports it is not working for any …

fixed serial console for syslinux

---

usr/share/rear/conf/default.conf
usr/share/rear/rescue/GNU/Linux/600_unset_TMPDIR_in_rescue_conf.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/2654#issuecomment-881609874
Running `rear mkrescue` on a system with /tmp on tmpfs. Before, it has failed with the message `cp: error copying '/tmp/rear.ZLTj0NcVqlr4fiH/tmp/initrd.cgz' to '/tmp/rear.ZLTj0NcVqlr4fiH/tmp/isofs/isolinux/initrd.cgz': No space left on device`. After the change it succeeds.
The default temporary directory ( /tmp ) is not suited for ReaR, because ReaR needs lots of space. file-hierarchy(7) recommends to use /var/tmp as default for such programs.
If the user sets TMPDIR explicitly, it still takes precedence.
See the discussion in issue #2654 .

Default TMPDIR should be /var/tmp

---

usr/share/rear/conf/Linux-ppc64.conf
usr/share/rear/conf/Linux-ppc64le.conf

* Reference to related issue (URL): https://bugzilla.redhat.com/show_bug.cgi?id=1983008 https://bugzilla.redhat.com/show_bug.cgi?id=1983000
* Run `rear mkrescue` in a KVM virtual machine on RHEL 8 without `powerpc-utils-core` (which contains those two utilities) and checked that it immediately aborts with `ERROR: Cannot find required programs: ofpathname`. With `powerpc-utils-core` installed and `/usr/sbin/bootlist` manually removed it succeeds and the initrd contains `ofpathname`. With `powerpc-utils-core` installed normally it succeeds and the initrd contains both `ofpathname` and `bootlist`.
* Run `rear mkrescue` in a PowerVM LPAR on RHEL 8 without `powerpc-utils-core` (which contains those two utilities) and …

On POWER require bootlist & ofpathname if needed

---

usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/global-functions.sh

Use double quotes to get the variable evaluated in
remove_temporary_mountpoint "$BUILD_DIR/outputfs"
and
remove_temporary_mountpoint "$mountpoint"
to fix https://github.com/rear/rear/issues/2667
https://github.com/rear/rear/issues/2667
Before see  https://github.com/rear/rear/issues/2667#issuecomment-912442380
but with the change here it works now for me:
```
++ remove_temporary_mountpoint /var/tmp/rear.LEl5cQbfB1jzo68/outputfs
++ test -d /var/tmp/rear.LEl5cQbfB1jzo68/outputfs
++ rmdir -v /var/tmp/rear.LEl5cQbfB1jzo68/outputfs
rmdir: removing directory, '/var/tmp/rear.LEl5cQbfB1jzo68/outputfs'
```
Use double quotes to get …

Use double quotes for remove_temporary_mountpoint "$BUILD_DIR/..."

---

usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh

* Type: **Bug Fix** / **Enhancement** / **Cleanup**
https://github.com/rear/rear/issues/2683
Not at all tested by me because I don't use UEFI
Completely overhauled output/USB/Linux-i386/100_create_efiboot.sh
that should in particular fix https://github.com/rear/rear/issues/2683
by no longer using `cp -p` but always and only `cp -L`
to ensure the real content gets copied
but no longer preserve mode,ownership,timestamps because that may fail like
```
cp: failed to preserve ownership for '/tmp/rear-efi.XXXXXXXXXX/EFI/BOOT/kernel': Operation not permitted
```
because it copies to a VFAT filesystem on the EFI partition
(see …

Overhauled output/USB/Linux-i386/100_create_efiboot.sh

---

usr/sbin/rear
usr/share/rear/lib/_input-output-functions.sh

Normally there should be no difference when things are OK
but for users with e.g. broken config files the impact is high
because now they see that their config files are broken.
https://github.com/rear/rear/issues/2686
I did some quick "rear -D mkrescue" tests with artificial syntax errors
in default.conf, _input-output-functions.sh, and local.conf
Error out or BugError in sbin/rear when
it failed to source or Source mandatory files

Error out in sbin/rear when it failed to source or Source mandatory files

---

usr/share/rear/format/USB/default/300_format_usb_disk.sh
usr/share/rear/format/USB/default/350_label_usb_disk.sh
usr/share/rear/lib/format-workflow.sh
usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh

* Type: **New Feature** / **Enhancement**
* Reference to related issue (URL): #2698
created with the following config on a BIOS machine:
```
OUTPUT=USB
BACKUP=BORG
USB_DEVICE=/dev/disk/by-label/REAR-000
USB_DEVICE_FILESYSTEM_LABEL=REAR-000
USB_DEVICE_PARTED_LABEL=gpt
USB_DEVICE_FILESYSTEM=ext4
USB_UEFI_PART_SIZE="512"
CLONE_USERS=(root)
CLONE_GROUPS=(root)
CLONE_ALL_USERS_GROUPS="false"
BORGBACKUP_REPO="/borg"
BORGBACKUP_UMASK="0002"
BORGBACKUP_ENC_TYPE="repokey"
export BORG_RELOCATED_REPO_ACCESS_IS_OK="yes"
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK="yes"
export TMPDIR="/wsp_var/tmp/"
USE_RESOLV_CONF="no"
USE_DHCLIENT=no
USE_STATIC_NETWORKING=1
USE_SERIAL_CONSOLE=y
COPY_KERNEL_PARAMETERS=( 'net.ifnames' 'biosdevname', …
```

minimal changes needed for hybrid boot (bios+uefi)

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/lib/write-protect-functions.sh
usr/share/rear/prep/RAWDISK/Linux-i386/480_initialize_write_protect_settings.sh
usr/share/rear/prep/USB/default/480_initialize_write_protect_settings.sh
usr/share/rear/prep/default/490_store_write_protect_settings.sh

https://github.com/rear/rear/pull/2626
Not yet tested by me - will test soon...
The specific WRITE_PROTECTED_PARTITION_TABLE_UUIDS
is replaced by WRITE_PROTECTED_UUIDS with generic functionality
cf. https://github.com/rear/rear/pull/2626#issuecomment-950953826
WRITE_PROTECTED_FILE_SYSTEM_LABEL_PATTERNS
is shortened to WRITE_PROTECTED_FS_LABEL_PATTERNS

Enhanced disk write-protection

---

doc/user-guide/06-layout-configuration.adoc
usr/share/rear/conf/default.conf
usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh
usr/share/rear/layout/recreate/default/120_confirm_wipedisk_disks.sh
usr/share/rear/layout/recreate/default/150_wipe_disks.sh
usr/share/rear/layout/recreate/default/220_verify_layout.sh
usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh

That old code drives me nuts.
In particular its confusing variable names, cf. the "By the way" part in
https://github.com/rear/rear/pull/2702#issuecomment-968934959
https://github.com/rear/rear/pull/2702
With a simple RAID1 array (two component devices /dev/sda and /dev/sdb)
I got same `raid` line values in disklayout.conf after "rear mkrescue".
But I could have made mistakes for other types of RAID arrays.
Overhauled layout/save/GNU/Linux/210_raid_layout.sh
based on https://github.com/rear/rear/pull/2702
i.e. with the changes in https://github.com/rear/rear/pull/2702

Overhauled RAID code

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/recreate/default/120_confirm_wipedisk_disks.sh
usr/share/rear/layout/recreate/default/150_wipe_disks.sh

* Type: **Minor Bug Fix** / **Enhancement**
https://github.com/rear/rear/issues/2715
https://github.com/rear/rear/pull/2703#issuecomment-979928423
https://github.com/rear/rear/pull/2514#issuecomment-743483945
I tested some "rear mkbackup" / "rear recover"
with the same two VMs as in
https://github.com/rear/rear/pull/2714
In layout/recreate/default/120_confirm_wipedisk_disks.sh
skip disks that do not exist on the bare hardware in the recovery system
cf. https://github.com/rear/rear/issues/2715
and exclude disks that are write-protected and
cf. https://github.com/rear/rear/pull/2703#issuecomment-979928423
show what disks will be wiped in any …

Improved wiping disks

---

usr/share/rear/output/PXE/default/800_copy_to_tftp.sh

```
OUTPUT=PXE
OUTPUT_PREFIX_PXE=$HOSTNAME
PXE_TFTP_PREFIX=$HOSTNAME.
PXE_TFTP_URL=sshfs://wingcon@172.200.200.1/tmp/test
PXE_CONFIG_URL=sshfs://wingcon@172.200.200.1/tmp/test/
PXE_RECOVER_MODE="manual"
PXE_CREATE_LINKS="IP"
BACKUP=BORG
USB_DEVICE=/dev/disk/by-label/REAR-000
USB_DEVICE_FILESYSTEM_LABEL=REAR-000
USB_DEVICE_PARTED_LABEL=gpt
USB_DEVICE_FILESYSTEM=ext4
USB_UEFI_PART_SIZE="512"
CLONE_USERS=(root)
CLONE_GROUPS=(root)
CLONE_ALL_USERS_GROUPS="false"
BORGBACKUP_REPO="/borg"
BORGBACKUP_UMASK="0002"
BORGBACKUP_ENC_TYPE="repokey"
export BORG_RELOCATED_REPO_ACCESS_IS_OK="yes"
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK="yes"
export TMPDIR="/wsp_var/tmp/"
USE_RESOLV_CONF="no"
USE_DHCLIENT=no …
```

fixed pxe file cp and permissions for sshfs target

---

usr/share/rear/build/GNU/Linux/400_copy_modules.sh

https://github.com/rear/rear/issues/2677
https://github.com/rear/rear/issues/2615
Not yet tested by me.
Fix function modinfo_filename:
Output the original module_filename also when it is a symlink
because in the code below 'cp -L' copies the symlink taget content
as a new regular file with file name as the name of the symlink
so the copied content can be still found under its original name,
cf. https://github.com/rear/rear/issues/2677#issuecomment-997859219
Additionally in case of MODULES=( 'all_modules' ) also use 'cp -L' to
copy the actual content to avoid dangling symlinks in the recovery system.

Fix function modinfo_filename in 400_copy_modules.sh

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/bootloader-functions.sh

* Type: Enhancement
* Impact: Normal
* Reference to related issue (URL): https://github.com/rear/rear/issues/2733
* How was this pull request tested? yes in my own environment with 2 different virtual machines.
Due to the performance issues involved when using TFTP for file transfer modern PXE server support HTTP(s) downloads as well.
Since it is necessary for rear to mount the upload target during creating of the rescue information HTTP targets are not supported. Hence the url specified via $PXE_TFTP_URL used for nfs, sshfs upload and TFTP download may differ from the HTTP source offered by the same PXE server.
Therefore the change introduces a new config …

Support for http sources when using PXE

---

doc/user-guide/16-Rubrik-CDM.adoc
usr/share/rear/conf/default.conf

* Type: **Enhancement** 
#2685
#2266
#2700
#2314 
Deployed a RHEL 7.9 system on vSphere, ran `rear mkrescue` with no errors. Performed BMR on using the created ISO image on a 2nd empty vSphere VM and was able to recover the original system successfully.
Removed the need to include /usr/lib64 with the Rubrik CDM image. Rubrik CDM v6 and higher does not seem to need the libraries in this directory anymore. This will also reduce the image size when CDM is being used and fix boot problems due to an image that is too large.

Removed need for /usr/lib64

---

usr/share/rear/conf/GNU/Linux.conf

https://github.com/rear/rear/issues/2743
See https://github.com/rear/rear/issues/2743#issue-1110167131
Do no longer copy all in `/usr/lib*/syslog-ng/*`
but only copy `*.so` files `/usr/lib*/syslog-ng/*so`
and skip things in `/usr/lib*/syslog-ng/loggen/`
because 'loggen' is not included in the recovery system.

Skip unneeded /usr/lib*/syslog-ng/loggen/ from the recovery system

---

usr/share/rear/lib/serial-functions.sh

* Reference to related issue (URL): None
* How was this pull request tested? RHEL 8.5 VM with a serial console
Changes `usr/share/rear/lib/serial-functions.sh`.
Without this change `console=tty0` would be added whenever the last
device returned by `get_serial_console_devices` was not classified
as a real serial device even though the previous ones were.
Thus, the `cmdline` on a machine with `ttyS[0-3]` where only `ttyS0`
is real was changed to
```
console=ttyS0,115200 console=tty0
```
In such case, only kernel messages would appear on `ttyS0` [1].
[1] https://www.kernel.org/doc/html/latest/admin-guide/serial-console.html

Add `console=tty0` to cmdline only if no real serial device was found

---

usr/share/rear/conf/GNU/Linux.conf

* Reference to related issue (URL): None
Successful recovery of a RHEL 8.5 VM with BIOS without encryption, LVM
or multipath with this patch applied and unsuccessful recovery of the same
machine without it.  RHEL 8.5 has `os-prober` 1.74 and does not ship
`grub-mount` binary.
Changes usr/share/rear/conf/GNU/Linux.conf
Older releases of `os-prober` (1.74 and below) use `dmsetup` as a fallback
solution for mounting when `grub-mount` is missing.
However, `dmsetup` was included in the rescue image if and only if LVM,
multipath or encryption were detected.  Thus, BIOS machines that do
not use these but still have `dmsetup` present, would block indefinitely
on the …

Include `dmsetup` and `dmeventd` unconditionally

---

usr/share/rear/layout/save/default/335_remove_excluded_multipath_vgs.sh

* How was this pull request tested? On RHEL8 with Upstream ReaR
The current code excluding multipath devices is broken when a device being excluded matches other devices.
This leads to excluding wanted devices.
This happens when having custom alias for multipath devices *or* there are more than 26 multipath devices and 'mpatha' is getting excluded, which leads to excluding all 'mpathaX' devices are well.
See example below:
- have /boot on a dedicated multipath device 'mpathba'
- have / on a dedicated multipath device 'mpatha' and LVM vg 'rhel'
- have a dedicated multipath device 'mpathb' and LVM vg 'data'
- tell ReaR to …

multipath: fix exclusion of still wanted devices

---

usr/share/rear/conf/default.conf
usr/share/rear/rescue/GNU/Linux/310_network_devices.sh

* How was this pull request tested? Manually
These new array variables enable to ignore specific IP addresses or network interfaces when building the network configuration used in the rescue environment.
This is typically useful when floating IP addresses are used. Not ignoring these may lead to outage if the floating IP address is used by another system at time the system is getting recovered.

New EXCLUDE_IP_ADDRESSES and EXCLUDE_NETWORK_INTERFACES directives

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
usr/share/rear/output/USB/Linux-i386/300_create_grub.sh

* Reference to related issue (URL): #2500 
* How was this pull request tested? With an EFI USB disk
* Brief description of the changes in this pull request: The GRUB2_SET_USB_ROOT variable was used locally in script 100_create_efiboot.sh. However, by adding it to the default.conf we are able to overrule the setting which was defined in the 100_create_efiboot.sh script. Now, it can be added to the local.conf file with a more precise setting according the end-user requirements.
Furthermore, we also introduced the `insmod xzio` in the grub.conf file in case we were using the `REAR_INITRD_COMPRESSION=lzma` setting in …

GRUB2_SEARCH_ROOT_COMMAND variable to overrule Grub2 search string

---

usr/share/rear/conf/default.conf

https://github.com/rear/rear/pull/1205
https://github.com/rear/rear/issues/2770#issuecomment-1068935688
In default.conf increase USB_UEFI_PART_SIZE to 1024 MiB
cf. https://github.com/rear/rear/pull/1205
in particular to also make things work by default when additional
third-party kernel modules and firmware (e.g. from Nvidia) are used,
cf. https://github.com/rear/rear/issues/2770#issuecomment-1068935688

increase USB_UEFI_PART_SIZE to 1024 MiB

---

usr/share/rear/finalize/Fedora/i386/550_rebuild_initramfs.sh

https://github.com/rear/rear/issues/1040
I don't use Fedora so cannot test it.
@pcahyna @rmetrich 
please have a look if my changes make sense.
In finalize/Fedora/i386/550_rebuild_initramfs.sh
avoid ShellCheck
SC2068: Double quote array expansions to avoid re-splitting elements
https://github.com/koalaman/shellcheck/wiki/SC2068
and avoid
SC2145: Argument mixes string and array. Use * or separate argument
https://github.com/koalaman/shellcheck/wiki/SC2145
cf. https://github.com/rear/rear/issues/1040#issuecomment-1062945160

Avoid SC2068 and SC2145 in finalize/Fedora/i386/550_rebuild_initramfs.sh

---

usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh

https://github.com/rear/rear/commit/4dbbb288057189076d82cb8e477cd994a4ce1851
https://github.com/rear/rear/issues/1040#issuecomment-1034870262
Not at all tested - I don't have a RAID10 test system right now
In layout/save/GNU/Linux/210_raid_layout.sh
fixed the RAID10 layout support code as far as possible for now.
Currently only 'near=...' support is (and was) implemented initially via
https://github.com/rear/rear/commit/4dbbb288057189076d82cb8e477cd994a4ce1851
This fix was triggered by ShellCheck
SC2034: param appears unused. Verify use (or export if used externally)
https://github.com/koalaman/shellcheck/wiki/SC2034 …

Fixed the RAID10 layout support code

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
usr/share/rear/finalize/default/060_compare_files.sh
usr/share/rear/layout/save/default/490_check_files_to_patch.sh
usr/share/rear/layout/save/default/600_snapshot_files.sh

* Reference to related issue (URL): #2785
On RHEL 8.5: `rear mkbackuponly`, change of UUID of `/boot` and remount, `rear mkrescue` and recovery.
After recovery, the system does not boot, as it can not mount `/boot`. After manual fixing of `/etc/fstab`, checked the recovery log - it contains
```
2022-04-26 10:17:49.073321433 Including finalize/default/060_compare_files.sh
2022-04-26 10:17:49.082885638 Some configuration files in the restored system do not match the saved layout!
```
Configuration files can get out-of-sync with the recreated layout. This leads to inconsistent configuration, e.g. filesystem not mountable at boot, if they are mounted by …

Verify file hashes at the end of recover after file restore from backup     

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

https://github.com/rear/rear/issues/2801#issuecomment-1122015129
I got the same disklayout.conf on my homeoffice laptop
with the changes of this pull request here.
In layout/save/GNU/Linux/200_partition_layout.sh
ensure $disk_label is one of the supported partition tables, cf.
https://github.com/rear/rear/issues/2801#issuecomment-1122015129

Ensure supported partition tables

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

https://github.com/rear/rear/issues/2801#issuecomment-1122015129
I got the same disklayout.conf on my homeoffice laptop
with the changes of this pull request here.
In layout/save/GNU/Linux/200_partition_layout.sh
ensure syntactically correct 'disk' and 'part' entries

Ensure syntactically correct 'disk' and 'part' entries in disklayout.conf

---

usr/share/rear/build/GNU/Linux/400_copy_modules.sh

https://github.com/rear/rear/issues/2727
Seems to work OK for me - but I can only do a few generic tests.
In particular with `MODULES=( 'loaded_modules' 'wireguard' )`
I get exactly only the loaded kernel modules but no 'wireguard'.
In build/GNU/Linux/400_copy_modules.sh also
for MODULES=() or MODULES=( 'moduleX' 'moduleY' )
include the currently loaded kernel modules.

Always include loaded kernel modules

---

usr/share/rear/output/default/940_grub2_rescue.sh

* Reference to related issue (URL): No issue opened right now
* How was this pull request tested?: Local VM
On RHEL8.5, if you simply add the line `GRUB_RESCUE=y` at `/etc/rear/site.conf` and run `rear -v mkbackup`, you'll see the new entry at the Grub2 menu, but that new boot option will end up with a Panic like the following one:
The original Grub2 entry looks like the following:
```
menuentry 'Relax-and-Recover' --class os {
search --no-floppy --fs-uuid --set=root 1c0c73ea-169c-4ed5-a6d0-d0e6501fc0b6
echo 'Loading kernel /boot/rear-kernel ...'
linux /rear-kernel selinux=0 unattended console=ttyS0,9600 console=tty0
echo …
```

For GRUB_RESCUE set 'root=/dev/ram0 vga=normal rw' as for other boot media

---

usr/share/rear/conf/default.conf

("critical" because it is related to system crash in some cases)
https://github.com/rear/rear/issues/2798
See https://github.com/rear/rear/issues/2798#issuecomment-1126145771
and https://github.com/rear/rear/issues/2798#issuecomment-1127721378
In default.conf add dev/watchdog\* to COPY_AS_IS_EXCLUDE
because /dev/watchdog /dev/watchdog\* functionality
is not wanted in the ReaR rescue/recovery system
because we do not want any automated reboot
while disaster recovery happens via "rear recover".
Furthermore having dev/watchdog* during "rear mkrescue"
may even trigger a system "crash" that is caused by
TrendMicro ds_am …

Exclude dev/watchdog* from recovery system

---

usr/share/rear/lib/global-functions.sh
usr/share/rear/restore/NETFS/default/400_restore_backup.sh
usr/share/rear/restore/YUM/default/410_restore_backup.sh

* Type: **Code comment fix**
* Reference to related issue (URL): #2457
Code analysis only - I checked that the changes in the diff are all in lines that are commented out.
In PR #2457, the default ISO_VOLID value "RELAXRECOVER" got changed to "REAR-ISO", but some code comments have the old value. Update them.

Update the ISO volume label in comments

---

usr/share/rear/conf/default.conf

* Type: **Documentation**
https://github.com/rear/rear/pull/2660
In default.conf describe
USB_BOOT_PART_SIZE and USB_DEVICE_BOOT_LABEL
In particular see
https://github.com/rear/rear/pull/2660#issuecomment-885582656
I do not change the currently
implemented user config variable names
USB_BOOT_PART_SIZE and USB_DEVICE_BOOT_LABEL
By the way:
Regarding where by default the recovery system and backup
get stored for OUTPUT=USB and BACKUP=NETFS see
https://github.com/rear/rear/pull/2660#issuecomment-885622061
and how they can be stored separated
with an optional boot partition see
https://github.com/rear/rear/pull/2660#issuecomment-885643937

Describe USB_BOOT_PART_SIZE and USB_DEVICE_BOOT_LABEL

---

packaging/rpm/rear.spec

* Reference to related issue (URL): https://github.com/rear/rear/issues/2757
Test with correct filenames and a little change with no impact:
https://github.com/antonvoznia/rear/pull/51
As result the packit build has been passed
https://dashboard.packit.dev/results/copr-builds/362145
Test with incorrect filename:
https://github.com/antonvoznia/rear/pull/52
As result the Packit build has been failed:
https://dashboard.packit.dev/results/copr-builds/362146
Adding make validate for building stage to check the correctness of the filenames of the scripts.
It is instead of travis CI solution …

RPM spec: update build requirement for Fedora to unblock Packit build and run make validate after build

---

.packit.yaml

Packit will test it, see the Checks tab.
Update build targets for Packit (the Fedora ones were obsolete). Add Koji scratch builds (Koji is the Fedora build system) as an alternative to the usual Copr builds, and EPEL and CentOS Stream build targets in order to produce packages for CentOS / RHEL. Add openSUSE Leap and Tumbleweed build targets (using Copr).
This will greatly increase the diversity of systems that we perform test RPM builds for.

Update and extend Packit build targets

---

usr/share/rear/build/GNU/Linux/005_create_symlinks.sh
usr/share/rear/build/OPALPBA/Linux-i386/106_remove_files_copied_unconditionally.sh
usr/share/rear/conf/GNU/Linux.conf

* Reference to related issue (URL): https://bugzilla.redhat.com/show_bug.cgi?id=2097437
without the change:
```
...
Testing that the recovery system in /var/tmp/rear.sewWahfi7dNgMlf/rootfs contains a usable system
...
124
```
with the change, the return code is 0 and manually executing vi in the chroot works properly.
In recent Fedora and RHEL 9, `vi` is a shell script that executes `vim` if found, so linking `vim` to `vi` leads to an infinite loop. Fix by removing the symlink (I find it more confusing than helpful anyway, and it is good to reduce the amount of special handling) and adding `/usr/libexec/vi` (the real executable, executed by `vi` if `vim` is …

Fix vi in the rescue system on Fedora and RHEL 9

---

usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh

https://github.com/rear/rear/issues/513
https://github.com/rear/rear/issues/2820
Works for me on SLES11 SP4 and SLES15 SP3
In layout/prepare/GNU/Linux/110_include_lvm_code.sh
pipe as many 'y' as asked for into "lvm lvcreate"

Use fail-safe 'yes' pipe for "lvm lvcreate"

---

usr/share/rear/lib/format-workflow.sh

* How was this pull request tested? Directly by invoking `rear format -- -b/--bios <device>`.
Found while testing #2825.
According to `rear format -- --help`, this workflow should recognise both `-b` and `--bios` options. This PR fixes the following error message:
```console
Use 'rear format -- --help' for more information.
rear format failed, check /var/log/rear/rear-<redacted>.log for details
```

Recognise `-b`/`--bios` options in `format` workflow

---

usr/share/rear/conf/default.conf
usr/share/rear/format/USB/default/300_format_usb_disk.sh
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
usr/share/rear/prep/USB/Linux-i386/340_find_mbr_bin.sh

https://github.com/rear/rear/pull/2828#issuecomment-1164590100
Tested on openSUSE Leap 15.3 laptop with BIOS, see
https://github.com/rear/rear/pull/2829#issuecomment-1165460982
and on Red Hat with BIOS, see
https://github.com/rear/rear/pull/2829#issuecomment-1165470884
and on on RHEL 8 with UEFI, see
https://github.com/rear/rear/pull/2829#issuecomment-1165570472
and on openSUSE Leap 15.3 laptop with UEFI, see
https://github.com/rear/rear/pull/2829#issuecomment-1166925033
and subsequent comments
In format/USB/default/300_format_usb_disk.sh
set USB_DEVICE_PARTED_LABEL to match format-workflow.sh
which means when a format …

Set USB_DEVICE_PARTED_LABEL to match format-workflow.sh

---

usr/share/rear/conf/GNU/Linux.conf

#2827 
Created LVM on an empty disk (`mpatha`) and mounted it
```bash
parted --script -a optimal /dev/mapper/mpatha -- mklabel gpt mkpart extra ext2 1M -1M set 1 lvm on
pvcreate --yes /dev/mapper/mpatha1
vgcreate sigvg  /dev/mapper/mpatha1
lvcreate -y -n  sig_lv  sigvg -L 1G
mkfs.xfs /dev/sigvg/sig_lv
mkdir /home/foo
echo "/dev/sigvg/sig_lv                             /home/foo                   xfs     defaults        0 0" >> /etc/fstab
mount /home/foo
```
ran `rear mkbackup`
and then filled the disk with signatures 
```bash
EXTRADISK=/dev/mapper/mpatha1
EXTRAFS=( $(lsblk -ln -o mountpoint $EXTRADISK) )
for f in "${EXTRAFS[@]}"; do
umount $f
done
EXTRADEVS=( $(lsblk -lnp -o name …
```

Add yes to REQUIRED_PROGS

---

usr/share/rear/format/USB/default/300_format_usb_disk.sh

This PR is based on #2829 so let's keep it a draft until that's resolved and properly rebased.
* Reference to related issue (URL): https://github.com/rear/rear/pull/2828#issuecomment-1164134153
* How was this pull request tested? RHEL 7 with BIOS and EFI (both hybrid and native disk layouts)
`parted` 3.2 added the support for `esp` keyword.  Thus, `parted` 3.1 on RHEL 7 does not support it yet so try a fallback that sets the corresponding partition type using `sgdisk`.

Support creation of EFI system partition on systems with older `parted`

---

usr/share/rear/backup/NETFS/default/200_check_rsync_relative_option.sh
usr/share/rear/backup/NETFS/default/210_check_rsync_relative_option.sh
usr/share/rear/backup/RSYNC/GNU/Linux/610_start_selinux.sh
usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh
usr/share/rear/backup/RSYNC/default/200_make_prefix_dir.sh
usr/share/rear/backup/RSYNC/default/210_check_rsync_relative_option.sh
usr/share/rear/backup/RSYNC/default/450_calculate_req_space.sh
usr/share/rear/backup/RSYNC/default/500_make_rsync_backup.sh
usr/share/rear/backup/RSYNC/default/700_copy_backup_log.sh
usr/share/rear/lib/global-functions.sh
usr/share/rear/lib/rsync-functions.sh
usr/share/rear/output/RSYNC/default/200_make_prefix_dir.sh
usr/share/rear/output/RSYNC/default/900_copy_result_files.sh
usr/share/rear/prep/RSYNC/GNU/Linux/200_selinux_in_use.sh
usr/share/rear/prep/RSYNC/default/100_check_rsync.sh
usr/share/rear/prep/RSYNC/default/150_check_rsync_protocol_version.sh
usr/share/rear/restore/RSYNC/default/400_restore_rsync_backup.sh
usr/share/rear/verify/RSYNC/default/550_check_remote_backup_archive.sh

* Reference to related issue (URL): closes #2781 
- recovery using `OUTPUT=USB` `BACKUP=RSYNC` with a `rsync://...:/...` (rsync over ssh) and `rsync://...::/...` (rsyncd) `BACKUP_URL`
- recovery using `OUTPUT=ISO` `BACKUP=RSYNC` with a `rsync://...:/...` (rsync over ssh) `BACKUP_URL` and three values of `OUTPUT_URL`:  `rsync://...:/...` (rsync over ssh) but different from `BACKUP_URL`, `rsync://...::/...` (rsyncd), and undefined (to inherit  `BACKUP_URL`). Verified that the output ISO is found at the right places on the rsync server.
- mkrescue and mkbackuponly to localhost with a `rsync://...:/...` (rsync over ssh) `BACKUP_URL` and `OUTPUT_URL`, the latter pointing to a different directory than the former. …

Refactor rsync URL support, fixes rsync OUTPUT_URL

---

usr/share/rear/conf/GNU/Linux.conf
usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh

* Reference to related issue (URL): #2834 #2827 
In the same way as #2834
Revert "Use fail-safe 'yes' pipe for "lvm lvcreate"" - PR #2827 and pass `-y` to `lvcreate` to stop asking for input instead.
The `-y` option is much simpler and less error-prone than a 'yes' pipe (no error termination because of SIGPIPE, for instance). But we lose support for SLES11, where `lvcreate` does not know the `-y` option.
`yes` remains among `REQUIRED_PROGS`, it can be useful in the rescue system. (It could be theoretically moved to PROGS, because it is not required anymore. This could be done separately if really desired, but for now we prefer to keep it in REQUIRED_PROGS, …

Pass -y to lvcreate instead of piping the output of yes

---

usr/share/rear/rescue/GNU/Linux/290_kernel_cmdline.sh

https://github.com/rear/rear/pull/2749#issuecomment-1197843273
I simulated that proc/cmdline contains
```
console=ttyS0,9600 console=tty0
```
and then `COPY_KERNEL_PARAMETERS+=( console )`
results
```
...
Adding console=ttyS0,9600 to KERNEL_CMDLINE
Adding console=tty0 to KERNEL_CMDLINE
```
for me.
Overhauled rescue/GNU/Linux/290_kernel_cmdline.sh
in particular to make it possible
to add several kernel options by this script
with same kernel option keyword like
```
console=ttyS0,9600 console=tty0
```

Overhauled rescue/GNU/Linux/290_kernel_cmdline.sh

---

usr/share/rear/backup/BORG/default/500_make_backup.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/borg-functions.sh

Tested with rear release `2.6` on Debian Bullseye (patched `usr/share/rear/lib/borg-functions.sh` file with this changes)
This PR implements a new variable `BORGBACKUP_IGNORE_WARNING` which ignores borg warnings.
Borg warnings can happen if a file changed while backing it up described here: https://borgbackup.readthedocs.io/en/stable/usage/general.html#return-codes. Because borg return code is 1 in such case `rear mkbackup` fails.

implement  BORGBACKUP_IGNORE_WARNING

---

usr/share/rear/conf/default.conf

https://github.com/rear/rear/pull/2514
https://github.com/rear/rear/issues/799
I used `DISKS_TO_BE_WIPED=""` a lot on my openSUSE test VMs
In ReaR 2.7 default.conf has DISKS_TO_BE_WIPED='false'
so no disk is wiped to avoid possible regressions
until this new feature was more tested by interested users, see
https://github.com/rear/rear/blob/master/doc/rear-release-notes.txt
Now after ReaR 2.7 release I like to have this feature tested
by default by users who use our GitHub master code.

By default let "rear recover" wipe disks that get completely recreated

---

usr/share/rear/output/PXE/default/810_create_pxelinux_cfg.sh

https://github.com/rear/rear/pull/2851
Not at all tested by me because I do not use PXE
In output/PXE/default/810_create_pxelinux_cfg.sh
insert missing '$pxe_link_prefix' for the IP case
also for the "if has_binary gethostip" part, see
https://github.com/rear/rear/pull/2851#issuecomment-1237939248

Insert '$pxe_link_prefix' also "if has_binary gethostip" in the IP case

---

.github/workflows/stale.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

usr/share/rear/lib/_input-output-functions.sh

https://github.com/rear/rear/issues/2866
Works sufficiently well for me
during "rear recover" with MIGRATION_MODE="true"
(where several user dialogs appear).
In the UserInput function
in lib/_input-output-functions.sh
drain stdin if stdin is a terminal (i.e. in interactive mode).

In the UserInput function drain stdin if stdin is a terminal

---

usr/share/rear/conf/default.conf

https://github.com/rear/rear/issues/2870#issuecomment-1261045942
In default.conf better description
of the BACKUP=EXTERNAL config variables, see
https://github.com/rear/rear/issues/2870#issuecomment-1261045942
and some general improvements of the comments
e.g. removed the colloquial word 'stuff' where not useful
and in particular make blocks of config variables
that belong together more clear by using
```
####
.
.
.
####
```
as indicators where a block begins and ends.

Improved comments in default.conf

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/recreate/default/120_confirm_wipedisk_disks.sh
usr/share/rear/layout/recreate/default/150_wipe_disks.sh
usr/share/rear/layout/recreate/default/200_run_layout_code.sh
usr/share/rear/layout/save/default/550_barrel_devicegraph.sh

High impact only on systems where 'barrel' exists.
There should be no change (and no impact) on other systems
regarding the actual disk layout recreation via diskrestore.sh
(i.e. nothing of the actual disk layout recreation
via diskrestore.sh is changed).
There are visible changes on all systems
regarding the choices in the user dialogs
during "rear recover" that are improved
so that users have now more options what to do
and what should happen during "rear recover".
There was no change what the default choice is
so the default behaviour of "rear recover" is same as before
unless BARREL_DEVICEGRAPH is explicitly set to true by the user.
In particular users can now additionally choose:
"Skip wiping disks"
Before there was no way to do that without …

Implement basic 'barrel' support

---

usr/share/rear/lib/sesam-functions.sh

hi,
we are evaluating shipping REAR 2.7 with the next sesam release. It appears that with REAR 2.7, mkrescue
step will fail bcs of missing libraries during functionality check:
```
2022-12-04 12:00:57.066647656 /opt/sesam/bin/sesam/python3/libhogweed.so.6 requires additional libraries (fatal error)
2022-12-04 12:00:57.075641526   linux-vdso.so.1 (0x00007ffc7a5ca000)
libnettle.so.8 => not found
```
adding two more directories to the backup module related LD_LIBRARY_PATH fixes this issue.

fix rear mkrescue with sesam 5.x

---

usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh

* Reference to related issue (URL): fixes #1958
* full back-up and recovery on RHEL 8.7 / x86_64 (BIOS) with SATA disk, LVM in default configuration
* full back-up and recovery on RHEL 8.7 / x86_64 (BIOS) with SATA disk, LVM configured to show `/dev/disk/by-path` device symlinks instead of the usual `/dev/sd*` device nodes by using this line in /etc/lvm/lvm.conf:
`filter = [ "r|/dev/disk/by-path/.*-usb-|", "a|/dev/disk/by-path/pci-.*-nvme-|", "a|/dev/disk/by-path/pci-.*-scsi-|", "a|/dev/disk/by-path/pci-.*-ata-|", "a|/dev/disk/by-path/pci-.*-sas-|", "a|loop|", "r|.*|" ]`.
This case breaks with the original code already during `rear savelayout` and is fixed by this change.
* Brief description of the changes in …

Protect against colons in pvdisplay output

---

usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh

https://github.com/rear/rear/issues/2884
Not tested by me but see
https://github.com/rear/rear/issues/2884#issuecomment-1369830593
Installing extlinux should also be working
for a mounted vfat boot partition see
https://wiki.archlinux.org/title/syslinux
which reads (excerpt):
```
For FAT, ext2/3/4, or btrfs boot partition use extlinux,
where the device has been mounted:
Alternatively, for a FAT boot partition use syslinux,
where the device is unmounted
```

Install extlinux for OUTPUT=USB for a vfat boot partition

---

usr/share/rear/output/USB/Linux-i386/300_create_grub.sh

https://github.com/rear/rear/issues/2883
not tested by me but see
https://github.com/rear/rear/issues/2883#issuecomment-1302006263
grub-install defaults to --target x86_64-efi
if the system is booted with EFI
so one cannot install a legacy-bios (or 32bit) grub
without setting the --target parameter

OUTPUT=USB: Use target=i386-pc for legacy BIOS GRUB2 install on EFI systems

---

usr/share/rear/finalize/Linux-ppc64le/660_install_grub2.sh

https://github.com/rear/rear/issues/2045
I cannot test it because I don't have PPC hardware.
In finalize/Linux-ppc64le/660_install_grub2.sh
remove the
"mount --bind <proc|sys|dev> at TARGET_FS_ROOT"
section because that is meanwhile done generically in
finalize/default/110_bind_mount_proc_sys_dev_run.sh
since https://github.com/rear/rear/issues/2045
But there the file
finalize/Linux-ppc64le/..._install_grub2.sh
was accidentally forgotten
(see its initial description).
See
https://github.com/rear/rear/pull/2047
therein see in particular
https://github.com/rear/rear/pull/2047/commits/dd9977f727b4a3a6573361cfafff833f3431f99f …

Addendum for issue 2045 for Linux-ppc64le/660_install_grub2.sh

---

usr/share/rear/lib/serial-functions.sh

https://github.com/rear/rear/issues/2914
Seems to work well as far as I could test it
on my QEMU/KVM virtual machine.
In lib/serial-functions.sh make the
get_serial_console_devices() function
fail-safe if no serial device node exists.

Make get_serial_console_devices() fail-safe if no serial device node exists

---

usr/share/rear/lib/validated/Debian/10/i386.txt
usr/share/rear/lib/validated/Debian/11/i386.txt
usr/share/rear/lib/validated/RedHatEnterpriseServer/8/i386.txt
usr/share/rear/lib/validated/SUSE_LINUX/15.3/i386.txt
usr/share/rear/lib/validated/SUSE_LINUX/15.4/i386.txt
usr/share/rear/lib/validated/SUSE_LINUX/15/i386.txt
usr/share/rear/lib/validated/Ubuntu/20.04/i386.txt
usr/share/rear/lib/validated/Ubuntu/22.04/i386.txt
usr/share/rear/lib/validated/Ubuntu/22.10/i386.txt

We actually got some great feedback

Adding all ReaR validations I got in the last 2 years

---

.gitignore
usr/sbin/rear
usr/share/rear/init/default/001_verify_config_arrays.sh
usr/share/rear/lib/help-workflow.sh

fixes #2930 
I wrote something that has this effect:
```
rear-sle15sp4:/src/rear # cat /etc/rear/local.conf 
BACKUP_PROG_INCLUDE=( $(findmnt -n -r -o TARGET -t btrfs | grep -v '^/$' | egrep -v 'snapshots|crash') )
COPY_AS_IS=foobar
rear-sle15sp4:/src/rear # rear help
ERROR: Missing array assignment like +=(...) for COPY_AS_IS in /etc/rear/local.conf:
COPY_AS_IS=foobar
Use debug mode '-d' for some debug messages or debugscript mode '-D' for full debug messages with 'set -x' output
Aborting due to an error, check /var/log/rear/rear-rear-sle15sp4.log.lockless for details
Terminated
```
What do you think?

check for wrong array assignment in user configs

---

packaging/rpm/rear.spec
usr/share/rear/conf/default.conf
usr/share/rear/layout/prep-for-mount/Linux-s390/205_s390_enable_disk.sh
usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
usr/share/rear/layout/prepare/Linux-s390/090_include_dasd_code.sh
usr/share/rear/layout/prepare/Linux-s390/205_s390_enable_disk.sh
usr/share/rear/layout/prepare/Linux-s390/360_generate_dasd_format_code.sh
usr/share/rear/layout/prepare/Linux-s390/370_confirm_dasd_format_code.sh
usr/share/rear/layout/prepare/Linux-s390/400_run_dasd_format_code.sh
usr/share/rear/layout/prepare/default/010_prepare_files.sh
usr/share/rear/layout/prepare/default/250_compare_disks.sh
usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
usr/share/rear/lib/layout-functions.sh

Full backup and recovery on RHEL 8 s390x VM with 4 DASDs: 2 in the root VG, one for storing the backup and one that was not included in the backup (`ONLY_INCLUDE_VG=( rootvg )` was set). Verified that the extra VG and the disk with the backup survived recovery and that DASDs were properly mapped during recovery (in a situation where the correct disk mapping is not an identity map).
The s390x architecture needs some unique handling of disks (called DASDs - Direct Access Storage Devices) during layout restoration. The DASDs need to be enabled, otherwise they are not recognized as block devices, and then to get formatted (at …

s390x (IBM Z) disk formatting fixes

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
usr/share/rear/layout/save/GNU/Linux/240_swaps_layout.sh

* Type: **Bug Fix** / **Cleanup**
https://github.com/rear/rear/issues/2927#issuecomment-1440044143
not yet tested by me
In layout/save/GNU/Linux/230_filesystem_layout.sh
and layout/save/GNU/Linux/200_partition_layout
and layout/save/GNU/Linux/240_swaps_layout.sh
replaced the subshell that appends its stdout to DISKLAYOUT_FILE
by a group command with redirection
```
{
...
} 1>>$DISKLAYOUT_FILE
```
cf. usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
https://github.com/rear/rear/blob/rear-2.7/usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh#L375

Replace subshell redirection by group command redirection

---

Makefile
packaging/debian/rear.dsc
packaging/gentoo/rear.ebuild
packaging/rpm/rear.spec

* Reference to related issue (URL):  closes #2945
`spectool -g packaging/rpm/rear.spec` downloads the correct tarball
Change the URL in the Source tag in the RPM spec file to point to the tarball on GitHub instead of SourceForge (where the tarball is not updated anymore).
AFAIK GitHub creates the tarballs automatically from tags.

Uptodate Source pointing to GitHub in RPM spec

---

usr/share/rear/prep/README
usr/share/rear/prep/default/990_verify_empty_rootfs.sh

https://github.com/rear/rear/issues/2951
Only a quick test by me:
https://github.com/rear/rear/pull/2953#issuecomment-1456253142
New prep/default/990_verify_empty_rootfs.sh
to verify that at the end of the 'prep' stage
the ReaR recovery system area (i.e. ROOTFS_DIR) is still empty.

New 990_verify_empty_rootfs.sh to verify untouched ROOTFS_DIR at the end of 'prep'

---

usr/share/rear/conf/default.conf
usr/share/rear/finalize/default/060_compare_files.sh

https://github.com/rear/rear/issues/2952#issuecomment-1458094671
see https://github.com/rear/rear/pull/2954#issuecomment-1463864769
In finalize/default/060_compare_files.sh show what will be done so the user understands what possibly subsequent error messages mean

Better user messages for finalize/default/060_compare_files.sh

---

usr/share/rear/output/OBDR/Linux-i386/820_create_iso_image.sh
usr/share/rear/output/OBDR/default/840_write_image.sh
usr/share/rear/prep/TAPE/default/400_check_tape_drive.sh
usr/share/rear/skel/OBDR/etc/scripts/system-setup.d/43-init-cciss.sh

https://github.com/rear/rear/issues/2637
Successful restore on DL380 Gen8 with LTO5 via OUTPUT=OBDR method.
OBDR was not creating new ISO recover enviroment files
consider in scripts 'hpsa' driver along with obsolete 'cciss' driver 
parse output from lsscsi also for cases when there is more Host/Channel/Id/Lun than 10

OBDR fixes

---

usr/share/rear/conf/default.conf

Added 2 exclusions to avoid errors when Veritas sw is installed
On our servers
Excluded 2 special paths under /dev

Exclusions for Veritas

---

.github/dependabot.yml
.github/workflows/differential-shellcheck.yml

Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on files changed via PR and reports results directly in PR.
Since this repository contains a lot of shell scripts I think you might find it useful.
Documentation is available at: [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always happy to extend functionality.
Examples - [screenshots](https://github.com/redhat-plumbers-in-action/differential-shellcheck/tree/main/docs/images)
---
* Reference to related issue (URL): #1040
> Manually, status should be showed below.
>
> It is deployed …

Add Shell linter - Differential-ShellCheck

---

usr/share/rear/.shellcheckrc
usr/share/rear/lib/.shellcheckrc

- enable/disable SC2168 (local is only valid in functions) because scripts under lib/ are always sourced from functions, so "local" is valid inside them.
- set shell=bash because ReaR uses bash but the scripts don't have shebangs.
As a part of my master's thesis, I made a "research" about the Differential shellcheck usage.
I solved 2 problems in this PR:
* unnecessary output of shellcheck "Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive."
Since the ReaR is written in bash and that is specified in the following …

Add .shellcheckrc adapted for ReaR

---

usr/share/rear/conf/default.conf

In current GitHub master code since DISKS_TO_BE_WIPED="" cf.
https://github.com/rear/rear/pull/2859
there is in layout/recreate/default/120_confirm_wipedisk_disks.sh
a UserInput() dialog like
```
Disks to be wiped: /dev/sda /dev/sdb /dev/sdd
...
Confirm disks to be wiped and continue 'rear recover'
```
which has usually (i.e. when not in MIGRATION_MODE)
a timeout of USER_INPUT_INTERRUPT_TIMEOUT.
During my tests with current GitHub master code
I learned that 10 seconds is far too little time
to read and understand that UserInput message and
then some more time to make a decision whether or not
the automated action is actually the right one.
I.e. 10 seconds was far too little time even for me
where I expected …

Increase USER_INPUT_INTERRUPT_TIMEOUT default from 10 to 30 seconds

---

usr/share/rear/verify/GALAXY11/default/420_login_to_galaxy_and_setup_environment.sh

https://github.com/rear/rear/pull/2156
I cannot test it because I do not have the needed backup software
In
verify/GALAXY11/default/420_login_to_galaxy_and_setup_environment.sh
run commands that deal with GALAXY11_PASSWORD
in a confidential way via
```
{ confidential_command ; } 2>/dev/null
```
to not leak the GALAXY11_PASSWORD value into the log file

Do not leak the GALAXY11_PASSWORD value into the log file

---

usr/share/rear/build/default/500_ssh_setup.sh
usr/share/rear/rescue/default/500_ssh.sh
usr/share/rear/restore/YUM/default/970_set_root_password.sh
usr/share/rear/restore/ZYPPER/default/970_set_root_password.sh

Do not leak the SSH_ROOT_PASSWORD value into the log file:
In build/default/500_ssh_setup.sh
rescue/default/500_ssh.sh
restore/YUM/default/970_set_root_password.sh
restore/ZYPPER/default/970_set_root_password.sh
run commands that deal with SSH_ROOT_PASSWORD
in a confidential way via
```
{ confidential_command ; } 2>/dev/null
```
see https://github.com/rear/rear/issues/2967
This fixes by the way also ZYPPER_ROOT_PASSWORD and YUM_ROOT_PASSWORD, see
https://github.com/rear/rear/issues/2967#issuecomment-1545593787

Do not leak the SSH_ROOT_PASSWORD value into the log file

---

README.adoc
doc/rear.8.adoc
usr/sbin/rear
usr/share/rear/format/USB/default/300_format_usb_disk.sh
usr/share/rear/layout/prep-for-mount/default/600_show_unprocessed.sh
usr/share/rear/layout/prepare/GNU/Linux/150_include_drbd_code.sh
usr/share/rear/layout/prepare/default/200_recreate_hpraid.sh
usr/share/rear/layout/prepare/default/300_map_disks.sh
usr/share/rear/layout/prepare/default/600_show_unprocessed.sh
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/lib/help-workflow.sh
usr/share/rear/prep/default/040_check_backup_and_output_scheme.sh
usr/share/rear/restore/BORG/default/300_load_archives.sh
usr/share/rear/skel/default/etc/scripts/system-setup
usr/share/rear/verify/CDM/default/430_gen_rbs_uuid_for_cdm.sh
usr/share/rear/verify/GALAXY11/default/420_login_to_galaxy_and_setup_environment.sh
usr/share/rear/verify/GALAXY11/default/500_select_backupset.sh

supersedes #2979 and should solve everything discussed there. Code is based on the work by @codefritzel and adapted by me.
My considerations and decisions:
* the non-interactive mode is marked *experimental* because it only changes the way how `UserInput` works and there might be some scenarios where it won't work as advertised. I don't want to put a lengthy explanation about the technical details in the help text, hence *experimental* to indicate the current status.
* Without `--non-interactive` nothing should have changed (but I fixed a few places that seemed like they could cause problems)
* With `--non-interactive` the `UserInput` timeouts are hard coded to 3 seconds (short, but not too short) and every `UserInput -I FOO` call can happen only once. If it happens again then it will …

Implement non-interactive mode

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/filesystems-functions.sh
usr/share/rear/restore/NFS4SERVER/default/400_restore_with_nfs_server.sh
usr/share/rear/restore/REQUESTRESTORE/default/200_prompt_user_to_start_restore.sh

Manually on Ubuntu 22.04
Add an automated restore feature to `REQUESTRESTORE`, similar to how `NFS4SERVER` works.
Example:
```
Confirm the recreated disk layout or go back one step
1) Confirm recreated disk layout and continue 'rear recover'
2) Go back one step to redo disk layout recreation
3) Use Relax-and-Recover shell and return back to here
4) Abort 'rear recover'
(default '1' timeout 300 seconds)
User confirmed recreated disk layout
Now you must manually restore your backup.
Ensure the backup data gets restored into /mnt/local (instead of '/')
because the disks and filesystems of the target system are mounted there.
Waiting for /mnt/local/ok file to …
```

Add fully automated restore to REQUESTRESTORE

---

usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh

https://github.com/rear/rear/issues/2990
On a Ubuntu desktop machine using mdadm RAID 1.
`rear recover` fails during disk layout recreation on my machine unless `wipefs` is called with the `-f` ( or `--force`) option.
rear may currently be a bit over-zealous with its use of `wipefs` when recreating md RAID arrays but if we are going to use `wipefs` then we should be consistent because wipefs uses the force option elsewhere in `rear` and recover failed to work at all for me without this extra -f.

Add -f (force) option to wipefs command in 120_include_raid_code.sh

---

usr/sbin/rear
usr/share/rear/lib/_input-output-functions.sh

* Type: **Critical Fix** / **Enhancement**
https://github.com/rear/rear/issues/2967
In sbin/rear added --expose-secrets option
and SECRET_OUTPUT_DEV

New --expose-secrets option plus SECRET_OUTPUT_DEV

---

usr/share/rear/prep/SESAM/default/400_prep_sesam.sh

Follow up fix for issue #3018 
After the excludes have been fixed tests with more recent sesam client verisons have shown that the service fails to startup during recovery image boot due to missing semaphore files. Removing the sesam work directory where those information is stored from the excludes solves this problem.

issue: #3018: remove $SESAM_WORK_DIR from excludes

---

usr/share/rear/build/GNU/Linux/100_copy_as_is.sh

Using an automated reproducer implemented using *systemtap*
1. Create a file in `/dev` which will be embedded in the rescue environment
~~~
3+0 records in
3+0 records out
30720 bytes (31 kB, 30 KiB) copied, 0.000689566 s, 44.5 MB/s
~~~
2. Execute the systemtap script in charge of shrinking the file while being copied
~~~
[...]
Pass 5: starting run.
~~~
3. Execute `rear mkrescue` from another terminal
The files copied as-is in the rescue are copied using a `tar -c | tar -x` command.
It may happen that inodes are shrinking during the copy (e.g. …

Make sure rescue contains all COPY_AS_IS files

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/build/default/500_ssh_setup.sh
usr/share/rear/build/default/503_store_tty_root_password.sh
usr/share/rear/build/default/960_remove_encryption_keys.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/_input-output-functions.sh
usr/share/rear/output/default/950_copy_result_files.sh
usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
usr/share/rear/prep/default/340_include_password_tools.sh
usr/share/rear/rescue/default/500_ssh.sh
usr/share/rear/restore/NETFS/default/400_restore_backup.sh
usr/share/rear/restore/YUM/default/405_recreate_users_and_groups.sh
usr/share/rear/restore/YUM/default/410_restore_backup.sh
usr/share/rear/restore/YUM/default/970_set_root_password.sh
usr/share/rear/restore/ZYPPER/default/970_set_root_password.sh
usr/share/rear/verify/GALAXY11/default/420_login_to_galaxy_and_setup_environment.sh
usr/share/rear/verify/NETFS/default/600_check_encryption_key.sh

See
https://github.com/rear/rear/issues/2967
and
https://github.com/rear/rear/pull/3006
therein in particular
https://github.com/rear/rear/pull/3006#issuecomment-1590775360
See
https://github.com/rear/rear/pull/3006#issuecomment-1578565338
Use
```
{ SECRET COMMAND ; } 2>>/dev/$SECRET_OUTPUT_DEV
```
instead of
```
{ SECRET COMMAND ; } 2>/dev/null
```
Reasoning:
See
https://github.com/rear/rear/issues/2967#issuecomment-1562732484
that reads (excerpt):
```
the
{ ... ; } 2>>/dev/$SECRET_OUTPUT_DEV
syntax makes it clear which redirections are
explicitly meant to hide secrets to distinguish them
from usual unwanted output …
```

Use '2>>/dev/$SECRET_OUTPUT_DEV'

---

usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh

https://github.com/rear/rear/pull/3025#issuecomment-1643774477
I tested it same (on same VMs) as I did in
https://github.com/rear/rear/pull/3025#issuecomment-1643774477
but now with the changes here
Secure Boot with OUTPUT=USB works for me.
In output/USB/Linux-i386/100_create_efiboot.sh
add Secure Boot support for OUTPUT=USB by using
SECURE_BOOT_BOOTLOADER as first stage Secure Boot bootloader BOOTX64.efi
and using grub*.efi as second stage Secure Boot bootloader files
in the same way as already done for OUTPUT=ISO
in output/ISO/Linux-i386/250_populate_efibootimg.sh
see …

Secure Boot support for OUTPUT=USB

---

doc/rear.8.adoc

* Type: **Documentation**
https://github.com/rear/rear/issues/2967
At https://github.com/rear/rear/pull/3039/files
in the `doc/rear.8.adoc` header line click on '...'
and then choose "View file" which currently leads to
https://github.com/rear/rear/blob/9fac32a35de3ec90156766ace42f6dc2f7f65f52/doc/rear.8.adoc
and therein see the `GLOBAL OPTIONS` part
In doc/rear.8.adoc
describe the new -e/--expose-secrets option
and a more exact description what the
non-interactive mode actually does
and some general simplifications
of other GLOBAL OPTIONS texts

Describe expose-secrets in rear.8.adoc

---

usr/share/rear/lib/_input-output-functions.sh

Before:
```
...
Use 'rear -v help' for more advanced commands.
[here nothing happens for 3 seconds]
real    0m3.690s
user    0m0.629s
sys     0m0.254s
```
With the change of this pull request:
```
...
Use 'rear -v help' for more advanced commands.
real    0m0.686s
user    0m0.644s
sys     0m0.234s
```
In the DoExitTasks function skip 'sleep 3'
when all went well and DoExitTasks is called at normal exit
to avoid needless 3 seconds delay of normal end of program.

In DoExitTasks() skip 'sleep 3' when all went well

---

usr/share/rear/finalize/GNU/Linux/230_remove_lvmdevices.sh

* Reference to related issue (URL):  closes #2917, closes #3042 
Full backup and recovery on a KVM virtual machine (x86_64) with virtio disk (vda) and a PowerVM LPAR (ppc64le) withs SCSI disk (sda), both with RHEL 9 (where the LVM default is `use_devicesfile=1`).
Before backup and recovery:
```
VERSION=1.1.4
IDTYPE=sys_serial IDNAME=00fac60100004c000000017bead7ca41.10 DEVNAME=/dev/sda3 PVID=3NFhwAW1RAQzJz8uOsZqkcqasKhlZt9b PART=3
Device /dev/sda3 IDTYPE=sys_serial IDNAME=00fac60100004c000000017bead7ca41.10 DEVNAME=/dev/sda3 PVID=3NFhwAW1RAQzJz8uOsZqkcqasKhlZt9b PART=3
```
After recovery:
```
Devices file does not exist.
VERSION=1.1.4 …
```

Remove the lvmdevices file at the end of recovery

---

usr/share/rear/finalize/GNU/Linux/260_rename_diskbyid.sh

Backup and recovery on RHEL 9: the log contains
```
2023-09-07 09:16:51.683209039 Including finalize/GNU/Linux/260_rename_diskbyid.sh
2023-09-07 09:16:51.751526112 Migrating disk-by-id mappings in certain restored files in /mnt/local to current disk-by-id mappings ...
```
and the recovered system has backup files:
```
/etc/lvm/devices/system.devices.rearbak
/etc/lvm/lvm.conf.rearbak
/etc/fstab.rearbak
```
showing that the creation of backups still works.
Respect coding style in finalize/GNU/Linux/260_rename_diskbyid.sh: https://github.com/rear/rear/wiki/Coding-Style#variables
Inspired by discussion of PR #3043 : …

Remove unnecessary curly braces in var expansion

---

usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
usr/share/rear/lib/layout-functions.sh

* Type:  **Enhancement**
* Reference to related issue (URL): fixes #2958
* `rear savelayout` on Fedora 36 with empty USB SD card reader
I show the relevant log excerpt and the corresponding part of `disklayout.conf`, if any.
* original code:
```
No partition label type for 'disk /dev/sdb' (may cause 'rear recover' failure)
```
```
#disk /dev/sdb 0 
```
* new code:
```
Ignoring sdb: blockdev: cannot open /dev/sdb: No medium found
```
No sdb in disklayout
* new code without reverting 0a1d634ed15500bb21f37ac1bbb11c8a4bb11545
same result
* original code only with 0a1d634ed15500bb21f37ac1bbb11c8a4bb11545 reverted
This reproduces https://github.com/rear/rear/issues/2810
```
ERROR: Invalid 'disk /dev/sdb' entry (no partition table type for …
```

Skip invalid disk drives (zero sized, no media) when saving layout

---

usr/share/rear/output/USB/Linux-i386/300_create_grub.sh

Found by chance while testing
https://github.com/rear/rear/pull/2961#issuecomment-1754987492
with
```
OUTPUT=USB
USB_BOOTLOADER="grub"
USB_DEVICE_PARTED_LABEL=gpt
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
```
See below how "rear mkrescue" looks now.
I tested that GRUB in the recovery system boots now without error message.
Before it had also booted but via some GRUB fallback with an error message.
In output/USB/Linux-i386/300_create_grub.sh
check with "lsblk -no LABEL" if something with USB_DEVICE_BOOT_LABEL exists
and if not try to use USB_DEVICE_FILESYSTEM_LABEL if something with it exists …

Fail safe USB_DEVICE_BOOT_LABEL setting and fallback

---

usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh

* Installed RHEL 9 system to a thin pool
* Extended the thin pool to another disk, while artificially keeping its metadata volume size unchanged, and using 100% of the VG (no free space in the VG left).
* Backed up and recovered
With ReaR version before this change, recovery fails with:
```
+++ lvm lvcreate -y -L 1073741824b -n swap rhel_kvm-08-guest06
Volume group "rhel_kvm-08-guest06" has insufficient free space (250 extents): 256 required.
```
swap is not part of the thin pool and is created after the thin pool. Without the change, the thin pool consumes too much space in the VG due to the metadata volume being too large, and there is not enough space for the swap volume, …

Save LVM pool metadata volume size in disk layout

---

usr/share/rear/conf/default.conf
usr/share/rear/lib/_input-output-functions.sh

While testing
https://github.com/rear/rear/pull/3070
I noticed that UserInput() timeout is 3 seconds
but I had no idea where that came from
(default UserInput() timeout is 300 or 30 seconds)
until I found out that in unattended recovery mode
skel/default/etc/scripts/system-setup
calls `rear --non-interactive recover`
and in non-interactive mode UserInput() does
```
timeout=3
automated_input_interrupt_timeout=3
```
with a hardcoded '3' that I could not find easily
in the whole ReaR code (without knowing where to look for).
I think having it hardcoded is wrong because for example
why should UserInput() wait at all when there is no user
who could see any input request or ever respond to it
so it should be possible …

Add USER_INPUT_UNATTENDED_TIMEOUT config variable

---

usr/share/rear/build/GNU/Linux/100_copy_as_is.sh

* Reference to related issue (URL): fixes #3064
`yum erase rsync` and `yum install chkconfig` followed by `rear mkrescue` on RHEL 9
Do not skip symbolic links when adding libraries required by executables in COPY_AS_IS. The symlink targets will be copied later by build/default/490_fix_broken_links.sh.  We thus need library dependencies for symlinked executables just like for normal executables and build/default/490_fix_broken_links.sh does not perform library dependency scan, so we need to do it at the same place as for normal executables (in build/GNU/Linux/100_copy_as_is.sh). Otherwise it can happen that we add a (broken) symlink via COPY_AS_IS, the actual …

Resolve libs for executable links in COPY_AS_IS

---

usr/share/rear/prep/ISO/GNU/Linux/320_verify_mkisofs.sh

`rear mkrescue` on a RHEL 9 system without any ISO image tool installed
xorrisofs is supposed to be the preferred method, so mention it first among the suggested tools that the user can install to produce an ISO image if none is found.

Mention xorrisofs when no ISO image tool is found

---

.packit.yaml
usr/share/rear/skel/default/etc/scripts/boot

* Reference to related issue (URL): fixes #3017 
CI tested it - I enabled tests on Fedora 39 and Fedora Rawhide
Newer versions of systemd (starting with Fedora 39) seem to mount /sys themselves. Mounting it again leads to errors on the recovery system startup (startup scripts failing with status=219/CGROUP ), see https://github.com/rear/rear/issues/3017.
Check if /sys is already mounted using the `mountpoint` tool and mount it only if it is not.
Do the same for the other system mountpoints like /proc, /dev, /dev/pts. Not sure if they suffer from the same problem, but they probably could.
N.B. the `mountpoint` command is already among REQUIRED_PROGS.

Don't mount /sys and other directories if already mounted

---

usr/share/rear/conf/default.conf
usr/share/rear/skel/default/etc/scripts/system-setup

https://github.com/rear/rear/issues/3068
See https://github.com/rear/rear/pull/3070#issuecomment-1801948014
In skel/default/etc/scripts/system-setup
replaced the hardcoded 'reboot'
by using a `REBOOT_COMMANDS` array
(plus REBOOT_COMMANDS_LABEL string)
so the user could specify a alternative command
like 'shutdown' or 'poweroff'
(see https://github.com/rear/rear/issues/3068)
or a sequence of commands if needed
(plus a label that is shown to the user).
Use USER_INPUT_INTERRUPT_TIMEOUT
and USER_INPUT_UNATTENDED_TIMEOUT
instead of hardcoded 'sleep' timeout values
to speed up things in unattended_recovery mode.
Show non-zero …

Add REBOOT_COMMANDS (issue 3068)

---

usr/share/rear/conf/examples/SLE11-SLE12-SAP-HANA-UEFI-example.conf
usr/share/rear/conf/examples/SLE11-ext3-example.conf
usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf
usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf
usr/share/rear/conf/examples/SLE12-btrfs-example.conf

In example.conf files use
```
{ SSH_ROOT_PASSWORD='...' ; } 2>>/dev/$SECRET_OUTPUT_DEV
```
(i.e. with SECRET_OUTPUT_DEV)

Update SSH_ROOT_PASSWORD in example.conf files

---

usr/share/rear/output/USB/Linux-i386/105_check_mounted_usb.sh

* Reference to related issue (URL): closes #3098
* full backup and recovery with OUTPUT=USB on RHEL 8
* `rear mkrescue` with
```
OUTPUT=USB
BACKUP=NETFS
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
OUTPUT_URL=file:///srv
```
fails with
```
file:// OUTPUT_URL is currently unsupported for OUTPUT=USB, use usb://
ERROR: OUTPUT_URL 'file:///srv' is not mounted at /var/tmp/rear.9WxhsNfKKQjmgsP/outputfs
Some latest log messages since the last called script 105_check_mounted_usb.sh:
2023-12-08 13:31:11.869249473 file:// OUTPUT_URL is currently unsupported for OUTPUT=USB, use usb://
Some messages from /var/tmp/rear.9WxhsNfKKQjmgsP/tmp/rear.mkrescue.stdout_stderr since the last called script 105_check_mounted_usb.sh: …
```

OUTPUT=USB: add a check that OUTPUT_URL is mounted

---

usr/share/rear/restore/NETFS/default/400_restore_backup.sh

with original code, `OUTPUT=ISO` and
`POST_RECOVERY_COMMANDS=( 'cp $STDOUT_STDERR_FILE /mnt/local/root' )`,
`/root/rear.recover.stdout_stderr` contains:
```
Including restore/NETFS/default/400_restore_backup.sh
mkdir: cannot create directory '/var/tmp/rear.pUTNJoLWHyPL5wP/outputfs/kvm-03-guest18': Read-only file system
```
In ReaR 2.6, when stdout and stderr of commands used to appear in the recover log, this was printed to the recover log.
With the changed code, this does not appear.
Remove a forgotten
`mkdir -p $BUILD_DIR/outputfs/$NETFS_PREFIX`
command in restore/NETFS/default/400_restore_backup.sh.
Should have been deleted in …

Do not touch $BUILD_DIR/outputfs (the backup location) during restore

---

usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh

https://github.com/rear/rear/issues/1571
and
https://github.com/rear/rear/issues/3098
i.e. false BUG Error in
output/USB/Linux-i386/850_make_USB_bootable.sh
because of unsupported OUTPUT_URL for OUTPUT=USB
Not tested.
Those code changes should not cause any issue.
In output/USB/Linux-i386/850_make_USB_bootable.sh replaced the
```
BugError "Filesystem where the booting related files are on $RAW_USB_DEVICE could not be found"
```
with more explanatory LogPrintError plus Error what the actual reason is,
similar as in the related
https://github.com/rear/rear/pull/3102
because in most cases it is not a bug in ReaR
but an error …

Error() instead of BugError() in 850_make_USB_bootable.sh

---

usr/share/rear/skel/default/etc/scripts/boot

https://github.com/rear/rear/issues/3107
I tested various 'dmesg -n [1-7]' during "rear recover"
and up to 'dmesg -n 5' i.e. up to warning messages
there are almost no kernel messages so that level 5
does not "pollute" the usual ReaR messages.
In contrast level 6 (notice messages) shows some more
kernel messages which could be considered as disturbing
and with level 7 (info messages) it really gets too much.
In [skel/default]/etc/scripts/boot set
```
dmesg -n 5
```
to limit console logging for 'dmesg' messages to level 5
so that kernel error and warning messages appear
(intermixed with ReaR messages) on the console
so that …

Set 'dmesg -n 5' in etc/scripts/boot

---

usr/share/rear/build/USB/default/800_enforce_usb_output.sh

https://github.com/rear/rear/pull/3103
and
https://github.com/rear/rear/issues/1571#issuecomment-343461088
and
https://github.com/rear/rear/issues/1571#issuecomment-343516020
see https://github.com/rear/rear/pull/3110#issuecomment-1860611433
Overhauled build/USB/default/800_enforce_usb_output.sh
Now BugError when OUTPUT=USB got somehow modified
in $ROOTFS_DIR/etc/rear/local.conf
plus explanatory comments.
Triggered by https://github.com/rear/rear/pull/3103
and replacing it by this new pull request.

Fixed 800_enforce_usb_output.sh

---

usr/share/rear/lib/_input-output-functions.sh

Triggered by the BugError output in
https://github.com/rear/rear/pull/3110#issuecomment-1862408735
See below at
"With the change here that output gets simpler and easier to read"
In the BugError function in lib/_input-output-functions.sh
do no longer show the BugError function message arguments '$*'
within single quotes as
```
Error "
...
'$*'
... "
```
because the message arguments are shown
on a separated line where the additional single quotes
do not make the output easier to read or understand.
For an example see
https://github.com/rear/rear/pull/3110#issuecomment-1862408735
where
```
BugError "'rear $WORKFLOW' uses OUTPUT=USB …
```

Show BugError message arguments without single quotes

---

usr/share/rear/setup/default/007_set_dmesg_level.sh

https://github.com/rear/rear/pull/3108
I tested it and it works well for me.
The new 'setup' stage script setup/default/007_set_dmesg_level.sh
sets 'dmesg -n [4-6]' for the worksflows
recover layoutonly restoreonly finalizeonly mountonly
depending on verbose and debug modes for ReaR.
This pull request obsoletes
https://github.com/rear/rear/pull/3112

Set 'dmesg -n [4-6]' in new 'setup' script 007_set_dmesg_level.sh

---

doc/user-guide/06-layout-configuration.adoc

Triggred by PR #2261. Found while working on #2997.
```
pvcreate /dev/vdc
vgcreate testvg /dev/vdc
lvcreate -L 1G testvg -n testlv 
mkfs.xfs /dev/testvg/testlv
lvcreate -L 1G testvg -n testlv2
mkfs.xfs /dev/testvg/testlv2
mkdir /media/testfs
mkdir /media/testfs/testfs2
mount /dev/testvg/testlv /media/testfs
mount /dev/testvg/testlv2 /media/testfs/testfs2
```
Observe that everything related to the storage created above is commented out in disklayout.conf:
```
#disk /dev/vdc 10737418240 unknown
#lvmdev /dev/testvg /dev/vdc noCtfr-i5N5-y03V-lw4W-0axd-TAk0-KqWlG4 10733223936
#lvmgrp /dev/testvg 4096 2559 10481664 …
```

Take AUTOEXCLUDE_PATH into account in layout doc

---

usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh

* Impact: **Normal** / **Critical**
Normally (i.e. by default) the ReaR recovery system
does not contain secrets but when it contains secrets
and when e.g. GRUB_RESCUE=Y is used then it is critical
that only root is allowed to access the initrd.
https://github.com/rear/rear/issues/3122
Not yet tested.
In pack/GNU/Linux/900_create_initramfs.sh call
chmod 0600 "$TMP_DIR/$REAR_INITRD_FILENAME"
to let only root access the initrd because
the ReaR recovery system can contain secrets

Make initrd accessible only by root

---

usr/share/rear/conf/default.conf

* Reference to related issue (URL): #2261
```sh
pvcreate /dev/vdb
vgcreate testvg /dev/vdc
vgcreate testvg /dev/vdb
lvcreate -L 1G testvg -n testlv 
mkfs.xfs /dev/testvg/testlv
lvcreate -L 1G testvg -n testlv2
mkfs.xfs /dev/testvg/testlv2
mount /dev/testvg/testlv /mnt
mkdir /mnt/test
mount  /dev/testvg/testlv2 /mnt/test
```
now `rear savelayout` creates disklayout.conf with this:
```
fs /dev/mapper/testvg-testlv /mnt xfs uuid=9f9a9874-0325-43e0-9979-6849109c44a9 label=  options=rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota
#fs /dev/mapper/testvg-testlv2 /mnt/test xfs uuid=b6dd2e35-2e7a-495a-a219-4e38b41a3530 label=  options=rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota
```
* Description of …

Improve the description of AUTOEXCLUDE_PATH

---

usr/share/rear/lib/write-protect-functions.sh

https://github.com/rear/rear/issues/3085
I don't know how I could test it.
I cannot reproduce the matching issue
because I don't have a system with /sys/block/nvme0c0n1
or something similar - i.e. where a /sys/block/device
does not have a matching /dev/device.
Let the is_write_protected function
report candidate devices without device node
as not write protected
because not all /sys/block devices have a "dev" file
e.g. /sys/block/nvme0c0n1 has no /dev/nvme0c0n1 device node, see
https://github.com/rear/rear/issues/3085
Because the is_write_protected function is meant
to identify write-protected disks and …

Let is_write_protected() report devices without device node as not write protected

---

usr/share/rear/prep/GNU/Linux/300_include_grub_tools.sh
usr/share/rear/prep/Linux-s390/305_include_s390_tools.sh
usr/share/rear/prep/default/320_include_uefi_env.sh

* Reference to related issue (URL): see discussion in commit ccae513d8362078c5d4bcffe9b1167835e6449b8
* `touch /boot/grub2FAIL` full backup and recovery. Original code fails to recover: "Installing GRUB Legacy boot loader: 
ERROR: Cannot install GRUB Legacy boot loader because there is no 'grub' program." New code works.
* `touch /boot/grub2FAIL && shopt -s nullglob && rear -d mkrescue && find /*/tmp/rear.*/rootfs /tmp/rear.*/rootfs -name grub\*-\* -executable`
original code: nothing
new code:
```
/usr/tmp/rear.noYr1PET9AefVbz/rootfs/bin/grub2-mkimage
/usr/tmp/rear.noYr1PET9AefVbz/rootfs/bin/grub2-mkpasswd-pbkdf2
/usr/tmp/rear.noYr1PET9AefVbz/rootfs/bin/grub2-mkrelpath …
```

Include GRUB tools unconditionally and don't create $VAR_DIR/recovery/bootdisk in prep

---

usr/share/rear/finalize/Linux-i386/630_install_grub.sh
usr/share/rear/finalize/Linux-i386/660_install_grub2.sh
usr/share/rear/finalize/default/050_prepare_checks.sh
usr/share/rear/layout/save/default/445_guess_bootloader.sh
usr/share/rear/lib/bootloader-functions.sh
usr/share/rear/lib/layout-functions.sh
usr/share/rear/lib/savelayout-workflow.sh

* Reference to related issue (URL): also helps with the problem in #3128
Full backup and recovery on a hybrid UEFI/BIOS bootloader setup, with UEFI firmware.
* Fixes a bug where a system with hybrid BIOS/UEFI boot was restored without the BIOS bootloader (`GRUB2`) and on subsequent `mkrescue` it will abort because it can't detect the bootloader - the BIOS bootloader was not found in the boot sector and the presence of the BIOS boot partition confused the EFI bootloader detection. In detail:
* Support BOOTLOADER=GRUB/GRUB2 with UEFI. This will happen with hybrid boot: BOOTLOADER=GRUB2 indicates that there is the BIOS version of GRUB2 installed and …

Support saving and restoring hybrid BIOS/UEFI bootloader setup and clean up bootloader detection

---

usr/share/rear/lib/_input-output-functions.sh

New TextPrefix function to
remove leading space and tab characters from input lines
and prefix each line with the argument string if specified.
The intent is to be able to properly indent multi-line message strings
in the code and output the message without the code indentation
but prefixed as needed for example like
```
message="first line
second line
last line"
LogPrint "Message text:$LF$( TextPrefix ' | ' <<<"$message" )"
```
which results the following output
```
Message text:
| first line
| second line
| last line
```

New TextPrefix function

---

usr/sbin/rear

* Reference to related issue (URL): #2654
`export TMPDIR=/tmp` in `etc/rear/local.conf` and calling `rear help` (the error appears even with `help`).
Error out early if TMPDIR is set in user config - setting TMPDIR in {site,local}.conf has not worked since 0022063 (PR #2633), as discussed in #2654.

Error out if TMPDIR is set in user config

---

usr/share/rear/output/IPL/Linux-s390/800_create_ipl.sh
usr/share/rear/prep/Linux-s390/034_check_config.sh

* Type: **Enhancement** / **Clean-up**
* Reference to related issue (URL): https://github.com/rear/rear/issues/3149#issuecomment-1941620475
* How was this pull request tested? I was able to successfully boot the generated kernel and initrd on s390x Fedora Rawhide machine with both `OUTPUT=IPL` and `OUTPUT=RAMDISK` options.
The initial PR with s390 support in ReaR introduced an s390-only `OUTPUT=IPL` undocumented option.  However, the `OUTPUT=IPL` option is completely redundant because it does the exact same thing as the already existing and documented OUTPUT=RAMDISK option.
This commit removes the whole `IPL` directory sub-tree and introduces a …

Replace the `OUTPUT=IPL` with equivalent `OUTPUT=RAMDISK`

---

usr/share/rear/init/default/050_check_rear_recover_mode.sh

High impact for special cases (i.e. when really needed).
No impact when not needed.
https://github.com/rear/rear/issues/3170#issuecomment-1981222992
See
https://github.com/rear/rear/issues/3170#issuecomment-1981222992
Add 'shell' to the workflows that are allowed
to be run from within the ReaR recovery system
because it can be useful for special cases

Allow 'shell' workflow in recovery system

---

doc/user-guide/04-scenarios.adoc

https://github.com/rear/rear/issues/3149#issuecomment-1943375764
All steps described in the new documentation were tried on a Fedora Rawhide s390x VM running under the z/VM hypervisor.
Document booting of ReaR rescue initramfs on s390/s390x.

docs: document booting of ReaR rescue initramfs on z/VM

---

usr/share/rear/lib/uefi-functions.sh
usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
usr/share/rear/output/ISO/Linux-i386/260_EFISTUB_populate.sh
usr/share/rear/output/RAWDISK/Linux-i386/260_create_syslinux_efi_bootloader.sh
usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
usr/share/rear/output/default/940_grub2_rescue.sh
usr/share/rear/prep/Linux-arm/330_set_efi_arch.sh
usr/share/rear/prep/Linux-i386/330_set_efi_arch.sh
usr/share/rear/prep/Linux-ia64/330_set_efi_arch.sh
usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh

Introduce variables EFI_ARCH{_UPPER} and GRUB2_IMAGE_FORMAT. Use them for various EFI bootloader suffixes, parameters and paths instead of hardcoding strings like BOOTX64.EFI. EFI_ARCH is "x64" and EFI_ARCH_UPPER is "X64" and GRUB2_IMAGE_FORMAT is "x86_64-efi" on x86_64 architecture.
Should make it easier to port the code to e.g. Arm.
See e.g.
https://github.com/rhboot/shim/blob/main/Make.defaults
for possible values.

Remove hardcoded architecture-dependend strings from EFI code

---

usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh

* How was this pull request tested? Recovery of Fedora Rawhide UEFI machine.
The idea is to find all direct partitions that contain the ESP mount point and to skip all other transitive `fs:` dependencies.
The `diskdeps.conf` file contains following entries on default Fedora installations (the list was shortened to only the relevant ones):
```
/dev/vda1 /dev/vda
/dev/vda4 /dev/vda
/dev/vda5 /dev/vda
fs:/boot/efi /dev/vda1
fs:/boot/efi fs:/boot
fs:/boot/efi fs:/
fs:/boot/efi btrfsmountedsubvol:/
fs:/boot /dev/vda4
fs:/boot fs:/
fs:/boot btrfsmountedsubvol:/
fs:/ /dev/vda5
btrfsmountedsubvol:/ /dev/vda5
```
The ESP partition is only on `/dev/vda1`.  However, the …

Skip btrfs subvolumes when detecting ESP partitions

---

usr/sbin/rear
usr/share/rear/conf/default.conf
usr/share/rear/prep/default/990_verify_empty_rootfs.sh

Hopefully a high positive impact
because of improved default confidentiality and
because of improved careful and complete cleanup of temporary leftovers
https://github.com/rear/rear/issues/3167
A simple "rear mkbackup"
and "rear recover" work for me.
In usr/sbin/rear set TMPDIR to TMP_DIR (within BUILD_DIR)
to ensure
that also for programs that are called by ReaR
ReaR will clean up all temporary stuff carefully and completely
via the function cleanup_build_area_and_end_program()
AND
that temporary files from programs that are called by ReaR
are sufficiently safe against unwanted access by non-root users
via  'mktemp -d' where …

Set TMPDIR to ReaR's TMP_DIR=$BUILD_DIR/tmp for programs that are called by ReaR

---

usr/share/rear/backup/NETFS/default/500_make_backup.sh
usr/share/rear/lib/global-functions.sh

High impact where needed.
No impact esewhere.
Triggred by my experiments in
https://github.com/rear/rear/pull/3175
how 'tar' behaves when exact same files or directories
are provided as 'tar' arguments to be archived.
See
https://github.com/rear/rear/pull/3175#issuecomment-1985907542
But I did not yet test "rear recover".
In lib/global-functions.sh added a
new unique_unsorted() function
that outputs lines in STDIN or in a file
without subsequent duplicate lines
which keeps the ordering of the lines.

New unique_unsorted() function

---

Makefile
README.adoc
doc/rear.8
doc/rear.8.adoc
doc/user-guide/17-Portable-Mode.adoc
usr/sbin/rear
usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
usr/share/rear/init/default/002_check_rear_recover_mode.sh
usr/share/rear/lib/help-workflow.sh
usr/share/rear/output/PORTABLE/default/450_create_portable_archive.sh
usr/share/rear/prep/default/100_init_workflow_conf.sh
usr/share/rear/skel/default/etc/scripts/system-setup

Add `OUTPUT=PORTABLE` and `--portable` command line option to faciliate using ReaR in truly portable mode.
The portable archive contains **only** ReaR, nothing else.
Tested with an OL9 restore via SystemRescueCD
I'll do some more testing both of portable usage and regular usage to ensure that this change doesn't hurt us.
Implements #3190 and should be merged after #3205, where I extracted the unrelated fixes. To review you can simply look at the last commit here.

Portable recovery

---

usr/share/rear/conf/default.conf

* Impact: **None**
No default should change.
No GitHub issue.
A colleague asked me how to get backup.tar.gz
and the ISO and all other RESULT_FILES
in the same directory that is not $HOSTNAME.
I had to somewhat reverse engineer things to find out how
because this is basically not described in default.conf.
I did not yet test that this pull request
does not change anything.
I had only tested that with
```
OUTPUT=ISO
OUTPUT_PREFIX="my_prefix"
NETFS_PREFIX="$OUTPUT_PREFIX"
BACKUP=NETFS
BACKUP_URL=file:///other/
```
backup.tar.gz and the ISO and all other RESULT_FILES
get stored in the same "my_prefix" directory.
In default.conf better descriptions …

Better describe OUTPUT_PREFIX and NETFS_PREFIX

---

usr/share/rear/prep/BACULA/default/500_check_BACULA_bconsole_results.sh

#3067 
#3082
* How was this pull request tested? Not yet - requested it via issue #3067 
`ERROR: Bacula director debian11-DR6 is not responding` - purpose is to have a simple test to verify to Bacula connector is responsive or not.

#3067 use exit code of nc to check BACULA directory availability

---

usr/share/rear/conf/examples/RHEL7-PPC64LE-Multipath-PXE-GRUB.conf
usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh

* Type: **Typo Fix**
https://github.com/rear/rear/pull/1449
https://github.com/rear/rear/issues/1899#issuecomment-2084552662
Not tested.
Only typo fixes in a LogPrint message
and in a example config file comment.
In layout/prepare/GNU/Linux/210_load_multipath.sh
fixed typo BOOT_ON_SAN -> BOOT_OVER_SAN
in LogPrint message and simplified the message.
In conf/examples/RHEL7-PPC64LE-Multipath-PXE-GRUB.conf
fixed typo BOOT_ON_SAN -> BOOT_OVER_SAN
in comment and used the wording "boot over SAN"
(i.e. with "over" instead of "on") consistently.

Typo fixes: BOOT_ON_SAN -> BOOT_OVER_SAN

---

usr/share/rear/conf/default.conf

* Type: **Documentation**
High impact when needed, cf.
https://github.com/rear/rear/issues/3189
how long it could take until one finds out
that booting fails because the initrd is too big.
https://github.com/rear/rear/issues/3189
https://github.com/rear/rear/pull/1566
Only descriptions.
See also
https://github.com/rear/rear/issues/3189#issuecomment-2079794186
In default.conf explain how one could reduce
the size of the ReaR recovery system initrd
in particular on POWER architecture
via COPY_AS_IS_TSM and alternatively
via COPY_AS_IS_EXCLUDE_TSM and additionally
via MODULES=( 'loaded_modules' ),
see https://github.com/rear/rear/issues/3189

default.conf example for COPY_AS_IS_EXCLUDE_TSM

---

usr/share/rear/prep/VEEAM/default/400_prep_veeam.sh

Closes #3213
* Type: **Enhancement** 
Manually on RHEL8. Tests with other distributions will follow.
enable default ramdisk if not set to satisfy Veeam 12.1ff requirements to check for sufficient free disk space

enable default ramdisk if not set to satisfy Veeam 12.1 requirements

---

usr/share/rear/restore/VEEAM/default/450_find_backup.sh

On every Veeam supported Linux distribution
RHEL 9.x
RHEL 8.x
Debian 10.13
Debian 11.9
Debian 12.5
Ubuntu 18.04
Ubuntu 20.04
Ubuntu 22.04
SLES 12 SP5
SLES 15 SP5
changed list backup option, to enable recovery do a different system

change find backup procedure for Veeam V12.1 and later

---

usr/share/rear/backup/NETFS/default/400_create_include_exclude_files.sh
usr/share/rear/backup/NETFS/default/500_make_backup.sh

Overhauled 400_create_include_exclude_files.sh
* Type: **Cleanup** / **Enhancement**
https://github.com/rear/rear/issues/3217
https://github.com/rear/rear/pull/3175#issuecomment-2111776529
In backup/NETFS/default/400_create_include_exclude_files.sh
Now do first backup the mounted filesystems
to backup '/' first so the basic system files
get stored first in the backup and
then backup what is specified in BACKUP_PROG_INCLUDE
see https://github.com/rear/rear/pull/3177#issuecomment-1985926458
and https://github.com/rear/rear/issues/3217#issue-2277985295
Report suspicious cases as LogPrintError
to have the user at least informed.
Remove duplicates but …

Overhauled 400_create_include_exclude_files.sh

---

usr/share/rear/conf/default.conf

see at the end of
https://github.com/rear/rear/pull/3175#issuecomment-2114478980
see
https://github.com/rear/rear/pull/3175#issuecomment-2114478980
In default.conf add `/var/tmp/rear.*` to BACKUP_PROG_EXCLUDE
because since ReaR uses `/var/tmp/rear.*` as BUILD_DIR
one would get at least the whole BUILD_DIR
of the current "rear mkbackup" run
in the backup by default.
Additionally describe why ReaR's VAR_DIR/output is excluded.
Also describe why the `'/directory/*'` form is used, cf.
https://github.com/rear/rear/pull/3175#issuecomment-2114478980

default.conf add '/var/tmp/rear.*' to BACKUP_PROG_EXCLUDE

---

usr/sbin/rear

https://github.com/rear/rear/pull/3175#issuecomment-2112594449
and
https://github.com/rear/rear/pull/3223#issuecomment-2114294271
https://github.com/rear/rear/pull/3175#issuecomment-2114420830
In usr/sbin/rear make it more clear
in a comment and in DebugPrint messages
when ReaR's TMP_DIR gets used
(in contrast to the system's TMPDIR)
Details - from
https://github.com/rear/rear/pull/3223#issuecomment-2114294271
While debugging things in
https://github.com/rear/rear/pull/3175#issuecomment-2112594449
I got a bit confused because it was not clear to me
if ReaR's TMP_DIR was used versus the system's TMPDIR
so I inspected the code …

In sbin/rear make it clear when ReaR's TMP_DIR is used

---

.github/workflows/build-packages.yml
tools/run-in-docker

Update Docker image list to currently working images, removing old and obsolete distros
Add missing dependencies to Archlinux
Adding `rear dump` as a very basic check before publishing snapshot packages

Fix & improve snapshot release building & testing

---

usr/share/rear/conf/default.conf

https://github.com/rear/rear/pull/3224
I manually reverted the actual change in
https://github.com/rear/rear/pull/3224
and then the current ReaR BUILD_DIR is not included
in the backup but a leftover ReaR BUILD_DIR from
a previous "rear -D mkbackup" gets correctly included
in the backup because it is my task to remove
my intentionally kept BUILD_DIR (via '-D').
Revert the actual change in
https://github.com/rear/rear/pull/3224
and have BACKUP_PROG_EXCLUDE in default.conf same as before
because the current BUILD_DIR gets automatically
excluded in usr/sbin/rear via
```
BACKUP_PROG_EXCLUDE+=( "$BUILD_DIR" )
```
It is not ReaR's …

Do not exclude '/var/tmp/rear.*' in default.conf

---

usr/sbin/rear

https://github.com/rear/rear/pull/3206#issuecomment-2122159018
https://github.com/rear/rear/pull/3206#issuecomment-2122173021
Not tested by me.
See also
https://github.com/rear/rear/pull/3206#issuecomment-2122373343
In sbin/rear set RECOVERY_MODE also in PORTABLE mode
because the PORTABLE mode is meant to be used only
to run 'rear recover' within a foreign rescue system.

Set RECOVERY_MODE also in PORTABLE mode

---

.packit.yaml
usr/share/rear/build/GNU/Linux/600_verify_and_adjust_udev.sh
usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh

* Reference to related issue (URL): #3175
Together with the changes in #3175 , the backup&recovery test make-backup-and-restore-iso passes when executed locally on Fedora rawhide.
/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh in the rescue system examines systemd version in order to know whether it should use udev or load modules manually.
Unfortunately, at least on Fedora, the systemd version can contain a tilde (the systemd version is equal to the systemd package version, which conforms to the Fedora conventions: https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_handling_non_sorting_versions_with_tilde_dot_and_caret ) and the …

Fix version test in udev start by desupporting systemd < 190

---

.packit.yaml

* Reference to related issue (URL): #3239
See the testing-farm:centos-stream-8-x86_64 check.
Looks like CentOS Stream 8 repo locations are fixed: https://gitlab.com/testing-farm/infrastructure/-/merge_requests/610/diffs so we can reenable the build and test.

Reenable CentOS Stream 8 CI builds and tests

---

usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
usr/share/rear/conf/default.conf
usr/share/rear/layout/compare/default/500_compare_layout.sh
usr/share/rear/output/ISO/Linux-i386/700_create_efibootimg.sh
usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
usr/share/rear/output/default/950_copy_result_files.sh
usr/share/rear/restore/NETFS/default/400_restore_backup.sh

Replace '/tmp/rear.XXX...' by '/var/tmp/rear.XXX...' in comments:
Current master code:
```
usr/share/rear/conf/default.conf:
usr/share/rear/restore/NETFS/default/400_restore_backup.sh:
usr/share/rear/layout/compare/default/500_compare_layout.sh:
usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh:
usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh:
usr/share/rear/output/default/950_copy_result_files.sh:
usr/share/rear/output/ISO/Linux-i386/700_create_efibootimg.sh:
```

Replace '/tmp/rear.XXX...' by '/var/tmp/rear.XXX...' in comments

---

usr/share/rear/build/default/990_verify_rootfs.sh

* Type: **Minor Bug Fix** / **Enhancement**
Only avoid a "false positive" check message.
https://github.com/rear/rear/issues/3021
By me on my Fedora 40 system
In build/default/990_verify_rootfs.sh
for each 'not found' shared object
(i.e. a shared object that was 'not found' by 'ldd')
check whether or not the shared object
may exist nevertheless in the recovery system
and if yes, we may sufficiently safely assume
things are OK in the ReaR recovery system
so we do not report it as missing to the user
(for debugging we have all in the log), see
https://github.com/rear/rear/issues/3021#issuecomment-2165453757

In 990_verify_rootfs.sh fix issue #3021

---

.packit.yaml

* Reference to related issue (URL): #3251 
See CI results
* Disable some builds and tests to reduce false positives and clutter:
* openSUSE Copr builds from Packit. The opensuse-leap-15.3-x86_64 was obsolete and opensuse-tumbleweed-x86_64 is not considered very useful: https://github.com/rear/rear/pull/3239#issuecomment-2173594371 . In the past, the builds were failing several times due to some breakage in Copr unrelated to ReaR or openSUSE. Disabling them may reduce false alarms from CI.
* Koji scratch builds from Packit. They are unlikely to uncover any other issues than the Copr builds do and the resulting RPMs have not been very useful.
* Fedora rawhide and …

Reduce the matrix of CI runs: disable the Fedora rawhide and 40 tests, Koji scratch builds, openSUSE Copr builds

---

usr/share/rear/finalize/GNU/Linux/320_migrate_network_configuration_files.sh

Migration of Fedora Linux system to different hardware (different NICs). With this patch, the network connections are preserved and functional after recovery, even though the NICs have different names and different MAC adresses.
Migrate NM keyfiles during network conf migration. See https://fedoramagazine.org/converting-networkmanager-from-ifcfg-to-keyfiles/ for more details on NetworkManager keyfiles.
Only MAC addresses and interface names are migrated for now.
TODO: migrate also IP addresses and routes.

Migrate MAC addresses and interface names in NetworkManager keyfiles during network configuration migration

---

usr/share/rear/layout/prepare/default/610_exclude_from_restore.sh
usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
usr/share/rear/layout/save/default/340_generate_mountpoint_device.sh
usr/share/rear/lib/filesystems-functions.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/2928
* How was this pull request tested? `rear savelayout` and manual inspection of generated files and backup/restore of a Fedora Rawhide machine
* automatically include mounted btrfs subvolumes in NETFS backups
* improve generation of `$RESTORE_EXCLUDE_FILE`

Automatically include mounted btrfs subvolumes in NETFS backups 

---

usr/share/rear/output/ISO/Linux-i386/850_check_for_errors.sh

CI has tested it - the message does not appear in the log https://artifacts.dev.testing-farm.io/54b1e241-c626-4dfb-92d4-bb369ae023db/work-backup-and-restoretjfz53h9/tests/plans/backup-and-restore/execute/data/guest/default-0/make-backup-and-restore-iso-1/data/rear-mkbackup.log anymore
If an error is not found in log, return 0. Not finding an error is good, so don't return 1 from the output/ISO/Linux-i386/850_check_for_errors.sh script.
Avoids the message
`Source function: 'source /usr/share/rear/output/ISO/Linux-i386/850_check_for_errors.sh' returns 1`
in the log.

Avoid returning 1 from a script if all is OK

---

usr/share/rear/conf/default.conf
usr/share/rear/prep/Linux-i386/370_detect_secure_boot.sh

Fixes #3276
#3276 
Manually on OL9u3 with secure boot and on Ubuntu 22 and openSUSE Leap 15.4 without secure boot
use `mokutil` to check for secure boot and guess the shim file - failing back to the previous behaviour if this doesn't work.
probably #3277 is a better or more complete implementation, however this one just adds a single file to automate the configuration that I had to add manually so far.

Autodetect secure boot via mokutil and guess the secure boot shim

---

.codespellignore

In .codespellignore the word 'für'
is likely no longer needed, see
https://github.com/rear/rear/commit/765c389ad97b7976b1a686a00e2323e74bd9137d#r146036920

Make .codespellignore ASCII

---

usr/share/rear/conf/examples/SLE11-SLE12-SAP-HANA-UEFI-example.conf

https://github.com/rear/rear/issues/3084
https://github.com/rear/rear/issues/3300
Not tested - only an example config change.
But the example values have been tested in
https://github.com/rear/rear/issues/3084#issuecomment-1833496190
and
https://github.com/rear/rear/issues/3084#issuecomment-1835840904
and
https://github.com/rear/rear/issues/3084#issuecomment-1835773844
In conf/examples/SLE11-SLE12-SAP-HANA-UEFI-example.conf
removed the meanwhile outdated and
obsolete information about ebiso, see
https://github.com/rear/rear/issues/3084#issuecomment-1833496190 so with /usr/bin/xorrisofs it "just works"
to make a UEFI …

Overhauled SLE11-SLE12-SAP-HANA-UEFI-example.conf

---

usr/share/rear/layout/save/NSR/default/650_check_iso_recoverable.sh

High impact only for those who use BACKUP=NSR
https://github.com/rear/rear/issues/3069
Cannot test it, see
https://github.com/rear/rear/issues/3069#issuecomment-2330860840
Deprecate
layout/save/NSR/default/650_check_iso_recoverable.sh
because it conflicts with "rear checklayout", see
https://github.com/rear/rear/issues/3069

BACKUP=NSR: Deprecate 650_check_iso_recoverable.sh

---

tests/plans/backup-and-restore/main.fmf

* Reference to related issue (URL):  #3313 
Not at all as it uses a feature that is not yet implemented in the Testing Farm infrastructure.
Request BIOS for backup and restore tests, they are very BIOS-specific due to the way the boot ISO is loaded via syslinux/memdisk. This change uses the documented syntax: https://tmt.readthedocs.io/en/stable/spec/hardware.html#boot , but it currently does not do anything as the Testing Farm infrastructure does not use the information yet to select the appropriate test VM. It thus merely prepares us for this feature when it gets implemented in Testing Farm and serves as a declaration of what the test needs.

Request BIOS for backup and restore tests

---

usr/share/rear/lib/config-functions.sh

* Reference to related issue (URL): https://github.com/rear/rear/issues/3149#issuecomment-1966068640
Contrary to its name, the OS_MASTER_VERSION variable was already used for this purpose for some versions, e.g. RHEL 7.  This fixes version comparison on RHEL 10 and newer.
Related: https://github.com/rear/rear/issues/3149#issuecomment-1966068640
Fixes: f4932c1cfe13d4a855bec93c1d3aa0b2b9128c6a ("Add OS version mappings for RHEL 8 and RHEL 9")
This commit has been split from #3171.

Use `OS_MASTER_VERSION` for major releases

---

usr/share/rear/lib/layout-functions.sh

* How was this pull request tested? Code tested in the following cases.
With QEMU SCSI disk ID "0000a":
~~~
rear> lsblk
NAME                           MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sda                              8:0    0    20G  0 disk
|-sda1                           8:1    0     1G  0 part
|-sda2                           8:2    0    19G  0 part
`-0QEMU_QEMU_HARDDISK_0000a    253:0    0    20G  0 mpath
|-0QEMU_QEMU_HARDDISK_0000a1 253:1    0     1G  0 part
`-0QEMU_QEMU_HARDDISK_0000a2 253:2    0    19G  0 part
sdb                              8:16   0    20G  0 disk
|-sdb1                           8:17   0     1G  0 part
|-sdb2 …

Fix partition naming on RHEL when migrating devices

---

usr/share/rear/lib/layout-functions.sh

Tested on RHEL9 with a QEMU/KVM system having the disks in multipath:
~~~
$ virsh dumpxml multipath9
[...]
<disk type='file' device='disk'>
<driver name='qemu' type='raw' cache='none' discard='unmap'/>
<source file='/var/lib/libvirt/images/multipath9.img' index='2'/>
<backingStore/>
<target dev='sdb' bus='scsi'/>
<shareable/>
<serial>OSDISK</serial>
<alias name='scsi0-0-0-1'/>
<address type='drive' controller='0' bus='0' target='0' unit='1'/>
</disk>
<disk type='file' device='disk'>
<driver name='qemu' type='raw' cache='none' discard='unmap'/>
<source file='/var/lib/libvirt/images/multipath9.img' index='1'/>
<backingStore/>
<target dev='sdc' …

Fix get_disklabel_type() not returning anything for multipath devices

---

usr/share/rear/backup/DUPLICITY/default/500_make_duplicity_backup.sh
usr/share/rear/conf/default.conf
usr/share/rear/lib/global-functions.sh
usr/share/rear/prep/DUPLICITY/default/200_find_duply_profile.sh
usr/share/rear/prep/DUPLICITY/default/220_define_backup_prog.sh
usr/share/rear/restore/DUPLICITY/default/110_check_temp_dir_with_duply.sh
usr/share/rear/verify/DUPLICITY/default/250_check_duply_profile.sh

* Type: **Bug Fix** / **Security Enhancement**
"Relatively" critical impact for two reasons:
It is a required security enhancement and
it is a backward incompatible change.
It is only "relatively" critical because
it is only when BACKUP=DUPLICITY is used
so it is not a backward incompatible change
that hits all or a lot of users.
https://github.com/rear/rear/issues/3293
https://github.com/rear/rear/issues/3259
Cannot test it because I neither use duplicity nor duply.
Overhauled prep/DUPLICITY/default/200_find_duply_profile.sh
so that now only an explicitly user specified DUPLY_PROFILE
will get sourced to avoid that some automatism
finds and …

Make sourcing DUPLY_PROFILE reasonably secure

---

usr/share/rear/lib/config-functions.sh
usr/share/rear/lib/framework-functions.sh

* Reference to related issue (URL):  https://github.com/rear/rear/issues/3149
* How was this pull request tested? `rear dump` and then rescue on x86_64 Fedora Rawhide and RHEL 9.4
* Description of the changes in this pull request - Notable changes:
1. Search for `rhel` when detecting RHEL\
\
The `redhat` substring is present only in auxiliary variables and URLs in `/etc/os-release` both on Fedora and RHEL.  Therefore, the `grep` worked only by accident on RHEL and was broken on Fedora because it wrongly classified Fedora as RHEL because its `BUG_REPORT_URL` refers to Red Hat's Bugzilla.\
\
On the other hand, `rhel` is the actual `ID` of RHEL and this string is
not present in …

 Make OS detection from `/etc/os-release` more robust

---

usr/share/rear/backup/NETFS/default/400_create_include_exclude_files.sh

High impact (i.e. "highly needed") only on SLES with btrfs.
https://github.com/rear/rear/issues/3346
see below
In backup/NETFS/default/400_create_include_exclude_files.sh
skip to add /.snapshots by default to the backup include list
because btrfs snapshots cannot be recreated

Skip to add /.snapshots by default to the backup include list

---

usr/share/rear/layout/save/GNU/Linux/100_create_layout_file.sh

Tested "by the way" in
https://github.com/rear/rear/pull/3347
In layout/save/GNU/Linux/100_create_layout_file.sh
call 'lsblk' with 'MOUNTPOINTS' with plural 'S'
to show all mounted btrfs subvolumes
in contrast to 'MOUNTPOINT' that shows only
a random one of the mounted btrfs subvolumes.

Call 'lsblk' with 'MOUNTPOINTS' to show all mounted btrfs subvolumes

---

usr/share/rear/lib/bootloader-functions.sh

* Reference to related issue (URL): #3350 
* How was this pull request tested? On  system that was impacted.
* Description of the changes in this pull request: To avoid that ReaR hangs on NFS mount points when performing a `find /usr` searh.

fix: add -xdev option to find to avoid hanging NFS (#3350)

---

usr/share/rear/build/GNU/Linux/100_copy_as_is.sh

coreutils 8.16 was released in 2012 so the '-r' option
should be supported since more than 10 years
so it is unlikely that someone is actually hit by it
BUT
some older Linux distributions with rather old coreutils
may still be in use somewhere so it is good to care about
this possible error because when 'ln' fails here, the
consequence is severe (recovery system startup fails)
and it shows up (too) late (at "rear recover" time)
AND
this issue is introduced in ReaR 2.8 by
https://github.com/rear/rear/pull/3206
so it could be considered as a regression in ReaR 2.8
https://github.com/rear/rear/pull/3206
therein
https://github.com/rear/rear/pull/3206#discussion_r1868998080
and subsequent comments
* How was this pull …

In 100_copy_as_is.sh error out if symlinking VAR_DIR SHARE_DIR fails

---

packaging/rpm/rear.spec

* How was this pull request tested?  See CI results below.
This fixes the build failure on Fedora 42+ related to the following Fedora change: https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin

Specify path to sbindir during RPM build

---

usr/share/rear/conf/default.conf

https://github.com/rear/rear/issues/3386#issuecomment-2609546695
"rear mkbackup" and "rear recover" worked for me
in particular with a mounted NFS share before "rear recover"
Added 'timeout' to REQUIRED_PROGS in default.conf

Add 'timeout' to default REQUIRED_PROGS

---

usr/share/rear/finalize/default/880_check_for_mount_by_id.sh

https://github.com/rear/rear/issues/3383#issuecomment-2652966699
See below
In finalize/default/880_check_for_mount_by_id.sh
only when what is mounded 'by-id' does not exist
as block device on the replacement hardware,
then alert the user because then he may have to
adapt his TARGET_FS_ROOT/etc/fstab, see
https://github.com/rear/rear/issues/3383#issuecomment-2652966699

Further enhance 880_check_for_mount_by_id.sh

---

.github/workflows/differential-shellcheck.yml

This will resolve issues similar to this:
`git: base SHA1 (0000000000000000000000000000000000000000) doesn't exist. Make sure that the base branch is up-to-date.`
Related to https://github.com/rear/rear/pull/3416

ci: run Differential ShellCheck only on push to master

---

usr/share/rear/lib/global-functions.sh
usr/share/rear/output/ISO/Linux-i386/700_create_efibootimg.sh
usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh

https://github.com/rear/rear/pull/2909
https://github.com/rear/rear/issues/2908
https://github.com/rear/rear/issues/3397
see below: https://github.com/rear/rear/pull/3408#issuecomment-2687620899
In lib/global-functions.sh added a new
umount_mountpoint_retry_lazy function
which is basically a copy of the code in
output/ISO/Linux-i386/700_create_efibootimg.sh
which had been added there
via https://github.com/rear/rear/pull/2909
Use the umount_mountpoint_retry_lazy function
in output/ISO/Linux-i386/700_create_efibootimg.sh
and also
in output/USB/Linux-i386/100_create_efiboot.sh
see https://github.com/rear/rear/issues/3397

New umount_mountpoint_retry_lazy function

---

usr/share/rear/layout/prepare/default/300_map_disks.sh

* Reference to related issue (URL): #3411 
* How was this pull request tested? In a real DR test
* Description of the changes in this pull request: The sizes of the disks will now also be saved in the ReaR log file which makes it easier to link the original disk with the new mapped one.
Furthermore, a new script `960_save_disk_and_vgs_mappings.sh` was added to assist further in the disk mapping process (even before we execute the recovery itself).

enhance 300_map_disks.sh script to also print the disk sizes

---

usr/share/rear/layout/save/default/445_guess_bootloader.sh

* Reference to related issue (URL): N/A, found when playing with #3406
* How was this pull request tested? `rear -d savelayout` on RHEL 9 (MSDOS) and RHEL 10 (GPT)
In general, `file` output is not stable and is purely informational.  This manifested in PReP Boot partitions on GPT formatted block devices being classified as missing (apparently, `file` detects the Protective MBR instead):
```console
/dev/sdb: DOS/MBR boot sector; partition 1 : ID=0xee, active, start-CHS (0x0,0,2), end-CHS (0x3ff,255,63), startsector 1, 10485759 sectors
Model: AIX VDASD (scsi)
Disk /dev/sdb: 5369MB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: pmbr_boot
Number  Start   End     Size    File …
```

ppc64le: Fix PReP Boot detection on GPT layouts

---

usr/share/rear/skel/default/etc/scripts/run-sshd

* Reference to related issue (URL): #3413 
* How was this pull request tested? Manually in recovery mode
* Description of the changes in this pull request: EL9 requires the ed25519 SSH key and the directory `/usr/share/empty.sshd` to be present.

On EL9 sshd will not start anymore #3413

---

usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh
usr/share/rear/layout/save/default/305_uniq_disktodo.sh
usr/share/rear/lib/layout-functions.sh

* Reference to related issue (URL): #3400 
* How was this pull request tested? on a Kubernetes system (on AWS)
* Description of the changes in this pull request: Disks that were mounted on a filesystem as a whole disk (no partition) were excluded in the disklayout.conf file.

#3400 to avoid disks mounted without partition getting excluded

---

usr/sbin/rear
usr/share/rear/lib/_framework-setup-and-functions.sh

Fix the current regression since
https://github.com/rear/rear/pull/3434
that using the POSIX compliant '.' is forbidden.
https://github.com/rear/rear/pull/3434#issuecomment-2742598092
reads (excerpts):
```
Because '.' is the POSIX standard command
POSIX compliant third party software rightfully uses '.'
so ReaR must not enforce an environment where '.' is
forbidden in general.
...
The right solution is a '.' wrapper function which enforces
that '.' is not used in a ReaR script or in a ReaR config file
but which allows '.' in any non-ReaR files.
What ReaR still can enforce is an environment
where all what is executed via 'source' or '.'
is checked to be trustworthy, i.e. for each
file that is executed via 'source' …
```

Allow sourcing via dot in non-ReaR files

---

usr/share/rear/layout/save/GNU/Linux/240_swaps_layout.sh

* Reference to related issue (URL): #3343
* How was this pull request tested? via `rear savelayout` on a Fedora Silverblue system
* Description of the changes in this pull request: Avoid having zram swap entry in the disklayout.conf file as it is memory based and not disk based swap.

remove zram swap from disklayout.conf 

---

usr/share/rear/verify/OBDR/NETFS/default/540_set_backup_compression.sh

This might be even a rather severe issue because
scripts in usr/share/rear/verify/ are run for "rear recover"
so the syntactically false setting of BACKUP_PROG_COMPRESS_OPTIONS
in verify/OBDR/NETFS/default/540_set_backup_compression.sh
may let "rear recover" inexplicably fail for example as in
https://github.com/rear/rear/issues/2911#issuecomment-1385563456
https://github.com/rear/rear/issues/2911#issuecomment-1386862853
* Related issues:
https://github.com/rear/rear/issues/3448#issuecomment-2785472035
https://github.com/rear/rear/pull/2963
https://github.com/rear/rear/issues/2637
https://github.com/rear/rear/issues/2911
I cannot test OBDR, see
https://github.com/rear/rear/issues/3448#issuecomment-2785428051
* …

Set BACKUP_PROG_COMPRESS_OPTIONS as an empty array

---

usr/share/rear/init/default/001_verify_config_arrays.sh

https://github.com/rear/rear/issues/3443
As in
https://github.com/rear/rear/issues/3443#issue-2969329614
I have in default.conf
```
{ MY_PASSWORDS=( my_default_password ) ; } 2>>/dev/$SECRET_OUTPUT_DEV
```
and in the bash where I later run 'rear -D help' I did
```
```
Then (with the changes in this pull request) I get:
```
...
...
2025-04-07 15:39:55.021382207 Including init/default/001_verify_config_arrays.sh
2025-04-07 15:39:55.663217781 Including init/default/002_check_rear_recover_mode.sh
...
...
...
2025-04-07 15:41:19.796992543 Including init/default/001_verify_config_arrays.sh
2025-04-07 15:41:20.415675839 Including init/default/002_check_rear_recover_mode.sh
```
When I …

Avoid that 001_verify_config_arrays.sh leaks secrets

---

tools/run-in-docker

* Reference to related issue (URL): n/a
```bash
$ ./run-in-docker
Hardware architecture not supported, removing incompatible Docker images matching centos:stream10
********** ubuntu:20.04                             **********
Bash is 5.0.17(1)-release
********** Copying dist to dist-all/ubuntu-20-04
********** ubuntu:22.04                             **********
Bash is 5.1.16(1)-release
********** Copying dist to dist-all/ubuntu-22-04
********** ubuntu:24.04                             **********
Bash is 5.2.21(1)-release
********** Copying dist to dist-all/ubuntu-24-04
********** debian:10                                **********
Bash is 5.0.3(1)-release
********** Copying dist to dist-all/debian-10 …
```

run-in-docker: Use /lib64/ld-linux-x86-64.so.2 to detect HW architecture

---

usr/share/rear/lib/global-functions.sh

https://github.com/rear/rear/issues/3454
See https://github.com/rear/rear/issues/3454
I am not a cifs user so I cannot test it.
In lib/global-functions.sh in mount_url()
therein in the cifs case added explicit '-t cifs'
to mount_cmd because that seems to be needed
with a Windows 11 cifs share at least in some cases
(with Windows 10 it had worked without '-t cifs').

Add '-t cifs' in mount_url() in global-functions.sh

---

usr/share/rear/conf/default.conf
usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh

The intent is to provide a feasible way out for the user
in particular for exceptional cases when there is
an unwanted and unneeded disk in his system
which causes trouble for ReaR - for example as in
https://github.com/rear/rear/issues/2995 and
https://github.com/rear/rear/issues/3433
where parted failed because of incorrect partitioning
which as a consequence makes ReaR fail.
* Reference to related issues (URLs):
https://github.com/rear/rear/issues/2995
https://github.com/rear/rear/issues/3433
My current changes are described below starting at
https://github.com/rear/rear/pull/3455#issuecomment-2821188937
My initial and meanwhile outdated changes
caused a regression which I described below in …

EXCLUDE_COMPONENTS in 200_partition_layout.sh

---

usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh

https://github.com/rear/rear/issues/3461#issuecomment-2830111347
On my test VM with LVM and
'use_lvmlockd = 1' in /etc/lvm/lvm.conf
```
...
Running 'layout/save' stage ======================
Creating disk layout
Overwriting existing disk layout file /root/rear.github.master/var/lib/rear/layout/disklayout.conf
Recreating LVM needs 'use_lvmlockd = 0' (there is 'use_lvmlockd = 1' in /etc/lvm/lvm.conf)
...
```
In layout/save/GNU/Linux/220_lvm_layout.sh
show LogPrintError message to inform the user
when 'use_lvmlockd = 1' was found in /etc/lvm/lvm.conf
but recreating LVM things needs 'use_lvmlockd = 0'

Tell if 'use_lvmlockd = 1' in /etc/lvm/lvm.conf

---

usr/share/rear/rescue/GNU/Linux/310_network_devices.sh

On my SLES15-SP6 test VM:
```
...
Skipping network interface 'lo': not bound to any physical interface.
...
```
```
...
Handling network interface 'eth0'
eth0 is a physical device
Handled network interface 'eth0'
Skipping network interface 'lo': not bound to any physical interface.
...
```
In rescue/GNU/Linux/310_network_devices.sh
show more consistent texts in user messages
in particular to avoid during "rear -v mkrescue"
the "lonely" message
```
Skipping 'lo': not bound to any physical interface.
```
without any context
in contrast to "rear -d mkrescue"
```
Handling network interface 'eth0'
eth0 is a physical device
Handled network interface 'eth0'
Skipping …
```

More consistent user messages in 310_network_devices.sh

---

usr/share/rear/lib/global-functions.sh

In lib/global-functions.sh
for the umount_mountpoint_retry_lazy function
add a comment that shows an example
why enforced umount raises its own specific troubles:
Enforced umount may corrupt data
when it disrupts a writing process, e.g. see
https://stackoverflow.com/questions/7878707/how-to-unmount-a-busy-device
which reads (excerpts)
```
umount -l /PATH/OF/BUSY-DEVICE
umount -f /PATH/OF/BUSY-NFS
...
NOTE/CAUTION
These commands can disrupt a running process,
cause data loss OR corrupt open files.
Programs accessing target DEVICE/NFS files
may throw errors OR could not work properly
after force unmount.
```

Describe enforced umount problem in umount_mountpoint_retry_lazy function

---

usr/share/rear/layout/recreate/default/150_wipe_disks.sh

On some platforms like Debian 12
command `lsblk -dbnlpo SIZE /dev/sda2`
can return the string that starts with space.
For example, " 1024".
As the result command
```
dd if=/dev/zero of=/dev/sda2 count= 1024 iflag=count_bytes
```
will be failed.
Strips non-digit characters with tr to return a clean numeric value.

BCF-5527: [Rear] Space in the variable device_to_be_wiped_size_bytes

---

usr/share/rear/prep/Linux-s390/034_check_config.sh

* Type: **Clean-up**
* Reference to related issue (URL): https://github.com/rear/rear/commit/32fe8dd7b0eac35534b28b10dd1b541397aa8bbf
* How was this pull request tested? N/A
Let's remove the deprecated s390-only `OUTPUT=IPL` value.  The deprecation warning has been in place for the last two releases and a change like this should be fine for ReaR 3.0.

s390: remove the deprecated `OUTPUT=IPL` value

---

usr/share/rear/lib/_framework-setup-and-functions.sh

https://github.com/rear/rear/pull/3490#issuecomment-3049047773
see
https://github.com/rear/rear/pull/3490#issuecomment-3053147895
In lib/_framework-setup-and-functions.sh
BugError when the functions
`AddExitTask` `QuietAddExitTask` `RemoveExitTask`
are called in a subshell because
changing the EXIT_TASKS array in a subshell
has no effect in the main shell (i.e. the process with $MASTER_PID)
where the EXIT_TASKS array will be used to run the exit tasks.

BugError when AddExitTask QuietAddExitTask RemoveExitTask are called in subshell

---

doc/rear.8
doc/rear.8.adoc
usr/sbin/rear
usr/share/rear/lib/help-workflow.sh

https://github.com/rear/rear/issues/2942#issuecomment-3132425914
https://github.com/rear/rear/issues/512#issuecomment-68051604
I tested it on my SLES15-SP6 test VM in a Git clone.
On the original test system VM:
```
ERROR: The '-c' option argument '/foor/bar' is not a directory
'etc/rear/local.conf' -> '/etc/myrear/local.conf'
Relax-and-Recover 2.9 / 2025-01-31
Running rear mkbackup (PID 3681 date 2025-07-30 16:43:01)
Command line options: usr/sbin/rear -D -c /etc/myrear mkbackup
Using config directory '/etc/myrear'
...
```
In the ReaR recovery system on a replacement VM:
```
RESCUE localhost:~ # rear -D -c /etc/myrear recover
ERROR: The '-c' option is not supported within …
```

In sbin/rear error out if '-c' is used in recovery system

---

usr/share/rear/lib/filesystems-functions.sh

RHEL 7, 8 and 9 systems were recovered and checked via `xfs_db`  that `features_ro_copmat` and 
`features_incompat` are left the same as on the original systems. Additionally, checked via `xfs_info` that new features keep original enablement status.
Recognize the following XFS features from the `xfs_info` output: `rmapbt`, `reflink`, `bigtime`, `inobtcount`, `nrext64` and `sparse`, and preserve their original enablement status. In newer version of `mkfs.xfs`, these options are enabled by default, which is not the desired behaviour if they were …

Support some XFS features

---

Makefile

`make srpm` on Fedora 41.
rpmbuild started to generate cleanup code for SRPM builds that assumes existence of a directory that it does not create, causing the build to fail and thus failing the srpm Makefile target.
The error message is like
```
Executing(rmbuild): /bin/sh -e /var/tmp/rpm-tmp.BFfEcM
+ umask 022
+ cd /var/tmp/build-rear-2.9-git.5699.8831a249.fixautomaticrearmismerge.changed/rpmbuild/BUILD/rear-2.9-build
/var/tmp/rpm-tmp.BFfEcM: line 33: cd: /var/tmp/build-rear-2.9-git.5699.8831a249.fixautomaticrearmismerge.changed/rpmbuild/BUILD/rear-2.9-build: No such file or directory
error: Bad exit status from …
```

Unbreak the srpm build with recent rpmbuild
