- usr/share/rear/backup/NETFS/default/50_make_backup.sh
Rear topic:
Backup log contains the BACKUP_PROG_CRYPT_KEY
Issue:
#568
> Backup log contains the BACKUP_PROG_CRYPT_KEY #568 

- usr/share/rear/finalize/SUSE_LINUX/ppc64/20_install_yaboot.sh
- usr/share/rear/layout/save/GNU/Linux/20_partition_layout.sh
- usr/share/rear/output/ISO/Linux-ppc64/30_create_yaboot.sh
This series of commits. Brings fixes for SLES 11 for IBM Power systems
> SLES 11 ppc64 fixes

- packaging/debian/control
> Change deb package control for multi arch support

- usr/share/rear/conf/examples/SLE11-SLE12-SAP-HANA-UEFI-example.conf
- usr/share/rear/conf/examples/SLE11-ext3-example.conf
- usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf
- usr/share/rear/conf/examples/SLE12-btrfs-example.conf
New SLE11-SLE12-SAP-HANA-UEFI-example.conf
see https://github.com/rear/rear/issues/229
Additionally (by the way) I fixed a wording
in my existing example.conf files for SLE.
> Add sap hana uefi example conf

- README.adoc
- doc/rear-presentation.adoc
- doc/rear.8
- doc/rear.8.adoc
See https://github.com/rear/rear/issues/688#issuecomment-158407780
> Added documentation for the new debugscripts option

- usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh
Have wipefs automatically available in recovery system
see https://github.com/rear/rear/issues/540
> Have wipefs automatically available in recovery system

- usr/share/rear/lib/_input-output-functions.sh
Use "type -P" instead of "type -p" for get_path(),
see https://github.com/rear/rear/issues/729
> Use "type -P" instead of "type -p" for get_path(),

- COPYING
Signed-off-by: Petr Hracek <phracek@redhat.com>
On the base of our discussion, this is PR for changing GPLv2 to GPLv3.
License was taken from https://www.gnu.org/licenses/gpl-3.0.txt
> Changing GPLv2 to GPLv3.

- usr/share/rear/output/ISO/Linux-i386/25_populate_efibootimg.sh
see https://github.com/rear/rear/issues/758
> Fixed the first first bash 3.x error (in 25_populate_efibootimg.sh)

- usr/share/rear/rescue/GNU/Linux/31_network_devices.sh
plus some syntax cleanup
see https://github.com/rear/rear/issues/758
> fixed second bash 3.x error in 31_network_devices.sh

- usr/share/rear/lib/framework-functions.sh
- usr/share/rear/output/default/10_mount_output_path.sh
- usr/share/rear/output/default/98_umount_output_dir.sh
Signed-off-by: Petr Hracek <phracek@redhat.com>
> Fixes #781 Fix for removing directory in case that they are not empty

- usr/share/rear/rescue/GNU/Linux/99_sysreqs.sh
cleaned up and partially fixed 99_sysreqs.sh (as good as I could - see the FIXME comments what is left from my point of view) see https://github.com/rear/rear/issues/795
> cleaned up and partially fixed 99_sysreqs.sh

- usr/share/rear/layout/prepare/GNU/Linux/10_include_partition_code.sh
in 10_include_partition_code.sh call partprobe in a backward compatible and fail safe way, see https://github.com/rear/rear/issues/793
Tested on SLES12-SP1 where it still works for me.
After recovery I have in the recovered system in /var/log/rear/recover/rear-f197.log (excerpts):
<pre>
++ . /var/lib/rear/layout/diskrestore.sh
...
+++ udevadm settle
+++ sleep 1
+++ partprobe -s /dev/sda
/dev/sda: msdos partitions 1 2
+++ my_udevtrigger
</pre>
I.e. for me partprobe "just works" (as it always did) so that I cannot actually verify if my fail safe way really works (but at least it seems
it is still really backward compatible).
> call partprobe in a backward compatible and fail safe way

- doc/user-guide/10-integrating-external-backup.adoc
probably the silliest patch in my F/OSS life, but it makes the docs look a lot better :)
> let GitHub properly render the list by adding an empty line in front

- usr/share/rear/format/USB/default/30_format_usb_disk.sh
- usr/share/rear/output/USB/Linux-i386/10_create_efiboot.sh
Hi guys,
I've created first draft as discussed in #831. Currently works only with elilo and manual intervention in EFI shell is needed to boot rear rescue (this will of course change in the future).
Please comment about possible changes and improvements.
> USB EFI boot support

- usr/share/rear/output/USB/Linux-i386/10_create_efiboot.sh
Should be working fine with grub2-install & grub2-mkimage.
> Corrected issue #849 (grub-install vs grub2-install)

- usr/share/rear/lib/global-functions.sh
see https://github.com/rear/rear/issues/856#issuecomment-222940800
@gdha
could you please have a look whether or not
it is o.k. for you when I merge that.
> clean up url_* functions in global-functions.sh (issue#856)

- usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh
check if findmnt supports FSROOT (issue883)
and use 'findmnt -m' to make 'fs' entries (issue882)
> findmnt fixes: check for FSROOT issue883 and use '-m' for 'fs' issue882

- usr/share/rear/finalize/Linux-ppc64/20_install_yaboot.sh
I'm not sure, but it looks like a typo. Could you check and confirm ?
> Typo in install_yaboot.sh with sfdisk command (2>&8 instead of 2>&1) ????

- usr/share/rear/layout/save/GNU/Linux/23_filesystem_layout.sh
Solved findmnt problems with BOOT from SAN (findmnt -m). Also added chattr & lsattr to PROGS array if no BTRFS CoW
> Solved findmnt problems with BOOT from SAN issue #822 (findmnt -m). 

- usr/share/rear/lib/global-functions.sh
automatically load fuse kernel module also for sshfs
in the same way as it is already done for ftpfs
cf. issue845
> automatically load fuse kernel module for sshfs

- usr/share/rear/output/default/94_grub2_rescue.sh
- usr/share/rear/output/default/94_grub_rescue.sh
see https://github.com/rear/rear/issues/913
> error out if not enough disk space for GRUB and GRUB2 rescue image

- usr/share/rear/prep/GNU/Linux/30_check_backup_and_output_url.sh
Use generic wording in error messages
because prep/default/02_translate_url.sh
may translate a BACKUP_URL into an OUTPUT_URL
so that errors in a BACKUP_URL may appear when
testing the translated/derived OUTPUT_URL
see https://github.com/rear/rear/issues/925
First steps to be prepared for 'se -e' which means
replacing COMMAND ; StopIfError ...
with COMMAND || Error ...
> use generic wording in 30_check_backup_and_output_url (issue925)

- usr/share/rear/conf/default.conf
see https://github.com/rear/rear/issues/938
> document GRUB_RESCUE meaning more clearly

- usr/share/rear/output/default/94_grub2_rescue.sh
see https://github.com/rear/rear/pull/948
and https://github.com/rear/rear/issues/946
and https://github.com/rear/rear/pull/942
> better ordering of what is done in 94_grub2_rescue

- .github/CONTRIBUTING.md
- doc/rear.8.adoc
- usr/share/rear/backup/default/01_pre_backup_script.sh
- usr/share/rear/backup/default/99_post_backup_script.sh
- usr/share/rear/conf/default.conf
- usr/share/rear/skel/default/etc/scripts/system-setup.d/67-check-by-label-cdrom.sh
> synchronize dev and master branch

- Makefile
- doc/rear-release-notes.txt
- doc/rear.8
- doc/rear.8.adoc
- doc/user-guide/02-getting-started.adoc
- packaging/rpm/rear.spec
- usr/share/rear/build/SUSE_LINUX/61_link_systemd_lib.sh
- usr/share/rear/conf/default.conf
- usr/share/rear/layout/save/default/45_check_network_files.sh
- usr/share/rear/lib/config-functions.sh
- usr/share/rear/lib/linux-functions.sh
- usr/share/rear/prep/default/50_guess_bootloader.sh
- usr/share/rear/rescue/GNU/Linux/96_collect_MC_serviceguard_infos.sh
@gdha 
if you do not object I will merge it tomorrow
> fixed suse spelling typos

- doc/rear-presentation.adoc
- doc/user-guide/09-design-concepts.adoc
Fixed non ASCII characters in
doc/rear-presentation.adoc and
doc/user-guide/09-design-concepts.adoc see
https://github.com/rear/rear/issues/1018#issuecomment-251385721
> Fixed non ASCII characters in documentation (except rear-release-notes).

- usr/share/rear/conf/default.conf
- usr/share/rear/lib/borg-functions.sh
- usr/share/rear/prep/BORG/default/30_init_archive.sh
New ReaR variables for controlling Borg behaviour:
- BORGBACKUP_KEYS_DIR
- BORGBACKUP_CACHE_DIR
- BORGBACKUP_RELOCATED_REPO_ACCESS_IS_OK
- BORGBACKUP_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK
> New Borg variables introduced

- README.adoc
- doc/user-guide/04-scenarios.adoc
- usr/share/rear/conf/default.conf
- usr/share/rear/lib/borg-functions.sh
Applied changes discussed in #1052.
> Correction in behavior of Borg environment variables

- usr/share/rear/conf/default.conf
- usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
- usr/share/rear/restore/NETFS/default/400_restore_backup.sh
Simplified blkid test to make restore from multiple ISOs
also work on SLE12, see
https://github.com/rear/rear/issues/1081
and generally cleaned up the code for multiple ISOs.
In particular improved messaging in case of multiple ISOs.
Now multiple ISOs "just work well"
at least for me on SLE12.
> Fixed and enhanced code for multiple ISOs.

- usr/share/rear/conf/default.conf
- usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
- usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
- usr/share/rear/output/ISO/Linux-ia64/800_create_isofs.sh
- usr/share/rear/output/ISO/Linux-ppc64/800_create_isofs.sh
- usr/share/rear/output/ISO/Linux-ppc64le/800_create_isofs.sh
Removed dead code regarding ISO_IMAGES variable, see
https://github.com/rear/rear/issues/1080
> Removed dead code.

- usr/share/rear/conf/examples/USB-and-Samba-example.conf
Add example local.conf for creating a USB recovery drive using a Samba share
> Add example local.conf for creating a USB recovery drive using a Samba share

- README.adoc
- doc/rear.8
- doc/rear.8.adoc
- doc/user-guide/07-tips-and-tricks.adoc
- doc/user-guide/11-multiple-backups.adoc
- doc/user-guide/relax-and-recover-user-guide.adoc
- usr/sbin/rear
- usr/share/rear/conf/default.conf
- usr/share/rear/lib/finalizeonly-workflow.sh
- usr/share/rear/lib/help-workflow.sh
- usr/share/rear/lib/layoutonly-workflow.sh
- usr/share/rear/lib/restoreonly-workflow.sh
Documented new variables in default.conf and
added new doc/user-guide/11-multiple-backups.adoc
see https://github.com/rear/rear/issues/1104
and https://github.com/rear/rear/issues/1088
> Documentation for multiple backups

- doc/user-guide/11-multiple-backups.adoc
See
https://github.com/rear/rear/issues/1088#issuecomment-265805547
> Fix documenation for multiple backups with Borg

- usr/share/rear/lib/shell-workflow.sh
- usr/share/rear/lib/validate-workflow.sh
Implement simulation mode for validate and shell workflows
see https://github.com/rear/rear/issues/1098
> Implement simulation mode for validate and shell workflows

- usr/share/rear/restore/NETFS/default/400_restore_backup.sh
More fail safe progress messages while tar backup restore
see https://github.com/rear/rear/issues/1116
> More fail safe progress messages while tar backup restore

- usr/sbin/rear
See
https://github.com/rear/rear/issues/1089#issuecomment-266983001
> More meaningful LogToSyslog message when rear ends

- usr/share/rear/format/USB/default/300_format_usb_disk.sh
- usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
- usr/share/rear/prep/USB/Linux-i386/340_find_mbr_bin.sh
This patch allows USB boot with GPT partition type.
See issue #1153 for more details.
@gdha I hope ReaR 2.0 release is finished and freeze period is over.
If there are any problems with this patch, I can cancel it and recreate later ...
V.
> GPT now uses right MBR code and flags

- usr/share/rear/conf/default.conf
- usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
- usr/share/rear/verify/USB/NETFS/default/540_choose_backup_archive.sh
With the current changes in 070_set_backup_archive.sh
and 540_choose_backup_archive.sh it works for me
see https://github.com/rear/rear/issues/1166
but I need to verify if I didn't break other things.
> Make USB backup selection work (issue1166)

- doc/user-guide/01-introduction.adoc
- doc/user-guide/03-configuration.adoc
- doc/user-guide/04-scenarios.adoc
- doc/user-guide/12-BLOCKCLONE.adoc
- doc/user-guide/relax-and-recover-user-guide.adoc
Hello guys,
As promised, BLOCKCLONE documentation is ready.
Any reviews and comments are more than welcome!
V.
> BLOCKCLONE documentation

- usr/share/rear/conf/default.conf
- usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh
Trying to make how UEFI_BOOTLOADER works
more generally usable as follow-up of
https://github.com/rear/rear/pull/1204
> Make UEFI_BOOTLOADER work more generally

- usr/share/rear/conf/default.conf
- usr/share/rear/format/USB/default/300_format_usb_disk.sh
- usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh
meant as follow-up of
https://github.com/rear/rear/pull/1217
> small coding style iprovements regarding pull request 1217

- usr/share/rear/prep/default/310_include_uefi_tools.sh
This is only a proposal how I think the test for
the /boot/efi directory might be simplified.
Currently I do not understand the logic, cf
https://github.com/rear/rear/commit/6c477d4e99edeb21a1a8c7649c24b2a56de535a7#commitcomment-21329841
and therefore I ask for a careful review here.
> simplified commit 6c477d4e99edeb21a1a8c7649c24b2a56de535a7

- usr/share/rear/layout/prepare/default/270_overrule_migration_mode.sh
- usr/share/rear/skel/default/etc/scripts/system-setup
and other fixes in skel/default/etc/scripts/system-setup
script (cf. https://github.com/rear/rear/issues/1240 )
> More fail safe tests for ReaR specific kernel command line parameters

- usr/share/rear/build/GNU/Linux/420_copy_firmware_files.sh
- usr/share/rear/conf/GNU/Linux.conf
- usr/share/rear/conf/Linux-ppc64.conf
- usr/share/rear/conf/Linux-ppc64le.conf
- usr/share/rear/conf/default.conf
A first attempt for FIRMWARE_FILES support,
see https://github.com/rear/rear/issues/1216
Do not yet merge it.
I need to do some more tests.
> Implemented FIRMWARE_FILES support

- usr/share/rear/conf/default.conf
follow up of https://github.com/rear/rear/pull/1262 and
related to https://github.com/rear/rear/issues/1242
> Describe BOOTLOADER in default.conf

- usr/share/rear/rescue/GNU/Linux/990_sysreqs.sh
Not all systems (like Arch Linux) have got a hostname command, alternatively use uname -u to retrieve the host name. Fix ReaR version error when ran from home directory. Not every system has vgs or lvs, make these sections optional. Not every system has the dig utility installed, make dns name lookup using dig optional. Use tabs with 4 instead of 2 spaces.
> Update 990_sysreqs.sh to make it less error prone

- usr/share/rear/layout/save/default/445_guess_bootloader.sh
> Include mmcblk as bootable device type in guess_bootloader

- usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh
Some persistent naming udev rules can be based on pci slot and not MAC address (sles12).
here is an extract of my `/etc/udev/rules.d/70-persistent-net.rules` on a SUSE SLE12 VM.
```
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="virtio-pci", ATTR{dev_id}=="0x0", KERNELS=="0000:00:01.0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"
```
In that case, we have to allow migration of the new inet name (eth1) to the old one (eth0):
- Cleaning old device entry in udev (eth0)
- Updating new device line by renaming device name with the orignal
one. (eth1 => eth0)
> Renaming network interface when MAC not present in udev

- usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
- usr/share/rear/lib/layout-functions.sh
Cleaning proposal:
Moving the function `is_multipath_path` from `200_patition_layout` script to `lib/layout_functions.sh`
> Moving is_multipath_path function to lib/layout-functions.sh

- usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
Therefore report the esp flag too.
> parted is also able to recreate ESP partition flag

- usr/share/rear/conf/default.conf
- usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
- usr/share/rear/layout/prepare/default/400_autoresize_disks.sh
- usr/share/rear/lib/global-functions.sh
As discussed in #1307, this patch updates arithmetical calculations in partition code.
> Unite calculations in partition code.

- usr/share/rear/layout/prepare/GNU/Linux/130_include_filesystem_code.sh
Cleanup wipefs code, see
https://github.com/rear/rear/pull/1336#issuecomment-298016104
I tested it on SLES12 both with wipefs in the recovery system
and without wipefs in the recovery system (i.e. the dd fallback
also works for me).
@gozora 
I added you as reviewer because you reviewed
https://github.com/rear/rear/pull/1336
> Cleanup wipefs code (related to issue1327 and pullrequest1336)

- usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
Do not create multipath.conf file if multipath devices were present
on source. Even if multipath.conf does not exist. This mean the system can work without multipath.conf and use default options (no firendly names etc..) like Suse.
If the  source system can work without multipath.conf we want to keep it unchanged during rescue and only create multipath.conf during "migration from non-multipath to mulitpath"
> Create multipath.conf only during migration (from non-mulitpath to multipath)

- usr/share/rear/layout/save/default/310_autoexclude_usb.sh
- usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
- usr/share/rear/prep/USB/Linux-i386/350_check_usb_disk.sh
see https://github.com/rear/rear/issues/1376
> replaced some perl regexp with grep native (extended) regexp

- usr/share/rear/backup/DUPLICITY/default/500_make_duplicity_backup.sh
- usr/share/rear/backup/NETFS/default/500_make_backup.sh
- usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
- usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
- usr/share/rear/build/GNU/Linux/600_verify_and_adjust_udev.sh
- usr/share/rear/format/USB/default/200_check_usb_layout.sh
- usr/share/rear/format/USB/default/300_format_usb_disk.sh
- usr/share/rear/lib/_input-output-functions.sh
- usr/share/rear/lib/dump-workflow.sh
- usr/share/rear/lib/format-workflow.sh
- usr/share/rear/lib/global-functions.sh
- usr/share/rear/lib/help-workflow.sh
- usr/share/rear/lib/shell-workflow.sh
- usr/share/rear/prep/NBKDC/default/400_prep_nbkdc.sh
- usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
- usr/share/rear/restore/BLOCKCLONE/default/381_change_restore_defaults.sh
- usr/share/rear/restore/BLOCKCLONE/default/390_create_partitions.sh
- usr/share/rear/restore/BORG/default/300_load_archives.sh
- usr/share/rear/restore/DP/default/450_restore_via_gui.sh
- usr/share/rear/restore/DP/default/460_press_y_to_continue.sh
- usr/share/rear/restore/FDRUPSTREAM/default/250_wait_for_restore.sh
- usr/share/rear/restore/FDRUPSTREAM/default/270_selinux_considerations.sh
- usr/share/rear/restore/NBKDC/default/400_restore_backup.sh
- usr/share/rear/restore/NBU/default/400_restore_with_nbu.sh
- usr/share/rear/restore/NSR/default/400_restore_with_nsr.sh
- usr/share/rear/restore/TSM/default/400_restore_with_tsm.sh
- usr/share/rear/verify/DP/default/500_select_dp_restore.sh
- usr/share/rear/verify/TSM/default/400_verify_tsm.sh
Fix regressions because of redirected STDOUT, see
https://github.com/rear/rear/issues/1398
First step:
Let the help workflow output to the original STDOUT
> Fix where output should go to the original STDOUT

- doc/user-guide/03-configuration.adoc
Hello guys,
Small fix for documentation (#1410).
V.
> Added missing OUTPUT_URL=nfs into documentation.

- usr/share/rear/lib/_input-output-functions.sh
Improvement of https://github.com/rear/rear/pull/1408
therein in particular for the one second delay for automated input
to avoid possibly tight loop of endless retrying UserInput calls:
Now a read call with at least one second timeout is used
where the user can interrupt the automated input
or where the read timeout delays the automated input.
Now (at least from my current point of view) the
UserInput function should be really feature-complete
but cf.
https://github.com/rear/rear/pull/1408#issue-242719587
;-)
I like to have the UserInput function ready in ReaR v 2.2
so that for ReaR v 2.3 I can replace existing read and
select user input by the UserInput function, cf.
https://github.com/rear/rear/issues/1399
> Let user interrupt automated input of the UserInput function

- usr/share/rear/prep/USB/Linux-i386/350_check_usb_disk.sh
Hello guys,
This PR should fix problem mentioned in #1415.
V.
> ReaR failed to run backup to USB device

- usr/share/rear/lib/_input-output-functions.sh
Some fixes for the UserInput function
plus fallback if md5sum is not there.
> Some fixes for the UserInput function

- usr/share/rear/conf/default.conf
- usr/share/rear/layout/prepare/default/300_map_disks.sh
- usr/share/rear/lib/_input-output-functions.sh
Using UserInput in 300_map_disks.sh and
a general overhaul of that script and
made UserInput less verbose unless in debug mode, cf.
https://github.com/rear/rear/issues/1431
Do not yet merge it - it is currently work-in-progress.
> Using UserInput in 300_map_disks.sh and general overhaul of that script

- usr/share/rear/lib/bootloader-functions.sh
Add `$PXE_RECOVER_MODE` variable to PXE_GRUB_STYLE
> Add PXE_RECOVER_MODE in PXE GRUB_STYLE

- usr/share/rear/lib/_input-output-functions.sh
In confidential mode (via '-C') the UserInput function
does to not log possibly confidentia data which means
neither the actual user input nor the default input
nor the choices values are logged.
The confidential UserInput mode is in particular
intended to be used in
https://github.com/rear/rear/pull/1500
> Added confidential mode '-C' for UserInput

- usr/share/rear/build/default/980_verify_rootfs.sh
@schlomo suggested in
https://github.com/rear/rear/issues/1494#issuecomment-330217766
what is implemented here.
> Verify required libraries in recovery system (related to issue 1494)

- usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
- usr/share/rear/build/default/980_verify_rootfs.sh
- usr/share/rear/lib/linux-functions.sh
Further simplified and improved the cleanup
of the binaries and libraries copying code
as follow up of https://github.com/rear/rear/pull/1521
> Improved cleanup binaries and libraries copying code

- usr/share/rear/conf/default.conf
- usr/share/rear/format/USB/default/300_format_usb_disk.sh
- usr/share/rear/format/USB/default/350_label_usb_disk.sh
- usr/share/rear/lib/format-workflow.sh
- usr/share/rear/prep/OBDR/default/500_check_tape_label.sh
- usr/share/rear/prep/OBDR/default/700_write_OBDR_header.sh
- usr/share/rear/prep/USB/Linux-i386/350_check_usb_disk.sh
- usr/share/rear/prep/default/400_save_directories.sh
- usr/share/rear/skel/default/etc/scripts/system-setup
See https://github.com/rear/rear/issues/1535
but not yet tested...
> Implemented USB_DEVICE_FILESYSTEM_LABEL (issue 1535)

- usr/share/rear/build/default/501_check_ssh_keys.sh
- usr/share/rear/conf/default.conf
Better document SSH configuration (related to pull request 1538)
plus be more safe in 501_check_ssh_keys.sh against possibly
touching/modifying/removing files in the original system.
> Better document SSH configuration (related to pull request 1538)

- usr/share/rear/restore/FDRUPSTREAM/default/250_wait_for_restore.sh
Minor text change for FDRUPSTREAM restore instructions.
> replaced Web Portal with batch job reference

- usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
This is a respin of the previous PR I closed because it was suboptimal regarding bridges on virtual interfaces (such as libvirt bridges used with KVM).
Add support for Bridge Interfaces
Bridge interfaces are widely used. This patch enables configurations as
shown below:
1. Bridge over simple Ethernet
2. Bridge over Bond
3. Bridge over Vlan interface
Usually, virtual interfaces are skipped, but for Bridges to work, we
consider Bridges as physical interfaces, because the Bridge interface
holds the IP address, not the physical interface attached to the Bridge.
Commit 0c0ee4a032c1b44135a07e28e89c3da01dde99d5 is identical to the one that has been approved.
Commit ff22996de6ea7035eec4e829053b1ad80a9f390d fixes the support of bridge when using Simplified bonding.
Commit …
> Add support for Bridge Interfaces

- usr/share/rear/prep/GNU/Linux/300_include_grub_tools.sh
> Added /etc/tuned to to COPY_AS_IS list for grub2

- usr/share/rear/lib/filesystems-functions.sh
Fix for https://github.com/rear/rear/issues/1589
> Fix btrfs_subvolume_exists (fix #1589)

- usr/share/rear/prep/default/040_check_backup_and_output_scheme.sh
See https://github.com/rear/rear/issues/1613
> Make BACKUP_URL=iso for mkrescue and mkbackuponly no longer fatal

- usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
- Adapt search for lower interfaces when no 'lower_*' symlink exists (RHEL6)
- Replace 'readlink -f' by 'readlink -e'
- Use 'brctl' when 'ip link' doesn't support 'bridge' type (RHEL6)
- Use function 'resolve' to wrap 'readlink' when it doesn't support more than 1 filename (RHEL6)
> Reworked implementation to support ancient releases (e.g. RHEL6)

- usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
replaced with comment of what this code was doing in earlier versions.
> FIXME [[ "${device#/}" = "$device" ]] comment

- usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
> findmnd -> findmnt

- usr/share/rear/skel/default/usr/lib/systemd/system/getty@.service
- usr/share/rear/skel/default/usr/lib/systemd/system/serial-getty@.service
This PR solve the issue #1644. see issue for details.
> Solved issue #1664 with systemd respawn of serial-console when not present

- usr/share/rear/rescue/GNU/Linux/990_sysreqs.sh
PROCS and SPEED made more alike memory_in_kB assignment
> unnessary cat command removed

- usr/share/rear/lib/recover-workflow.sh
Fixes https://github.com/rear/rear/issues/1670
and works o.k. for me
> Do not write /etc/motd in simulation mode and only in the recovery system

- usr/share/rear/prep/DUPLICITY/default/050_prep_duplicity.sh
- usr/share/rear/restore/DUPLICITY/default/400_restore_duplicity.sh
After testing the updates from PR #1554 several fixes were needed to get duplicity working the whole way.
Perhaps @Lukey3332 could test these updates as well?
> make duplicity work backup and restore - see #1668 - fixes PR #1554

- usr/share/rear/conf/default.conf
fix description about what "noise" means in default.conf
> better describe what noise means

- usr/share/rear/verify/TSM/default/389_check_TSM_connection.sh
- usr/share/rear/verify/TSM/default/389_check_TSM_connexion.sh
Tried to improve TSM connection test and
renamed misspelled 389_check_TSM_connexion.sh
into 389_check_TSM_connection.sh - cf.
https://github.com/rear/rear/issues/1534#issuecomment-351066398
and subsequent comments.
> Tried to improve TSM connection test

- usr/share/rear/restore/BORG/default/400_restore_backup.sh
Fix for issue https://github.com/rear/rear/issues/1678
> `cd’ command replaced by pushd/popd.

- usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh
If a software raid device is in degraded state at the time of the **rear mkrescue** creation (e.g. a device has been removed from a RAID1 array), the disk layout restoration will fail with following error seen in the log:
> mdadm --create /dev/md127 --force --metadata=1.2 --level=raid1 --raid-devices=2 --uuid=a0fc5637:fdf5dafa:a345e010:83293548 --name=boot /dev/sdb1
> +++ echo Y
> mdadm: You haven't given enough devices (real or missing) to create this array
> 
The least intrusive fix is to do the following: Add **missing** special devices to the **mdadm create** command upon restore when expression _raid-devices - #devices > 0_ is true
> Automatically add 'missing' devices to MD arrays with not enough physical devices upon restore

- doc/rear.8
- doc/rear.8.adoc
* PR type
**Enhancement**
**Documentation**
* Reference to related issue (issue link):
https://github.com/rear/rear/issues/1728
* Impact
**Low**
* Did you test this PR?
Yes - I have read my added documentation ;-)
* Brief description of the changes in this PR:
Document the ReaR specific recovery system kernel command line options:
<pre>
debug
unattended
auto_recover or automatic
ip= nm= gw= netdev=
noip
</pre>
> document ReaR specific recovery system kernel options (issue 1728)

- usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
https://github.com/rear/rear/pull/1733
Om my test system as in https://github.com/rear/rear/pull/1733
In 100_include_partition_code.sh do all what belongs to autoresizing partitions
via AUTORESIZE_PARTITIONS only in MIGRATION_MODE.
Without that fix autoresizing partitions would happen in 100_include_partition_code.sh
when AUTORESIZE_PARTITIONS is true also when not in MIGRATION_MODE
but when not in MIGRATION_MODE "rear recover" must and can recreate
byte-by-byte identical partitioning (if a disk size changed MIGRATION_MODE
would be true).
> Fixed 100_include_partition_code.sh regarding autoresizing partitions

- usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
* Reference to related issue (URL): https://github.com/rear/rear/issues/1762
* How was this pull request tested? will test it in rear-automated-testing soon
* Brief description of the changes in this pull request: see #1762
> unattended PXE mode with BAREOS is not unattended enough

- usr/share/rear/conf/default.conf
https://github.com/rear/rear/issues/1693
> Better describe NON_FATAL_BINARIES_WITH_MISSING_LIBRARY (issue#1693)

- doc/rear.8
- doc/rear.8.adoc
https://github.com/rear/rear/issues/1788
The actual man page by reading what `man -l doc/rear.8` shows,
and the doc/rear.8.adoc by looking at
https://github.com/jsmeix/rear/blob/cc72b5794e73b28883f9ccfb78ba841521a8991d/doc/rear.8.adoc
See https://github.com/rear/rear/issues/1788#issuecomment-384992678
> man page BACKUP SOFTWARE INTEGRATION update (issue#1788)

- usr/share/rear/restore/TSM/default/400_restore_with_tsm.sh
Use Print instaed of log and use it only once to improve readability
> Use Print outside for loop instead of Log (readability)

- usr/share/rear/layout/prepare/GNU/Linux/130_include_mount_subvolumes_code.sh
- usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
https://github.com/rear/rear/issues/1796#issuecomment-388753131
Both
recovery of SLES12-GA/SP0 with its default btrfs structure and
recovery of SLES12-SP3 with "LVM-based Proposal" (and the default btrfs structure)
work for me.
In usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
the code that ecludes/disables/comments btrfs subvolumes that belong to snapper
in disklayout.conf is now conditionally run only if there is
a SLES12-SP1 (and later) btrfs subvolumes setup
(i.e. when the default subvolume path contains `@/.snapshots/`),
cf. https://github.com/rear/rear/issues/1796#issuecomment-388763887
Additionally I …
> Make SLES12GA btrfs recovery work again (related to issue 1796)

- packaging/debian/control
* Reference to related issue (URL): https://github.com/rear/rear/issues/1826
* How was this pull request tested? Not tested yet. @didacog Are you able to test this PR?
iproute but that is not present in new ubuntu 18.04, see brainupdaters/drlm#79 (comment)
> Move iproute to Suggests in control file for Debian

- usr/share/rear/conf/default.conf
Fixed a typo plus a small addon in comments in default.conf
> Fixed a typo plus a small addon in comments in default.conf

- usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
Evidence is saved under https://gist.github.com/32cf472bfa4976a2d8d9358fa59ed874
> Fix BAREOS unattended mode; interrupted with question due to bad IF block

- usr/share/rear/layout/prepare/default/300_map_disks.sh
https://github.com/rear/rear/issues/1857
Tested by me on my SLES12 QEMU/KVM test system.
With those enhancements in layout/prepare/default/300_map_disks.sh
things look as in
https://github.com/rear/rear/issues/1857#issuecomment-404209341
Furthermore I added a output_not_recreated_devices function that shows
the currently unmapped disks and dependant devices that will not be recreated
to the user so that the user knows in advance what will not be recreated
with the current mapping so that he can change the mapping as he needs
and in this case things look like:
<pre>
Current disk mapping table (source => target): …
> Added choice to confirm identical layout mapping only once plus disabling MIGRATION_MODE

- usr/share/rear/backup/DUPLICITY/default/500_make_duplicity_backup.sh
Via mkbackup
This fixes the ! expressions. This somehow slipped through in my Tests...
> Yet another Duplicity fix

- usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
* Type: **Enhancement** and **Cleanup**
https://github.com/rear/rear/issues/1921
Not at all tested because currently I have no UEFI test system
Avoid `nullglob` pitfalls in 250_populate_efibootimg.sh
like the workaround in
https://github.com/rear/rear/issues/1921#issuecomment-426999409
and
generally overhalued that script
in particular changed code like
<pre>
if DIR_OF_SOME_FILES_EXISTS ; then
cp DIR_OF_SOME_FILES/* ...
StopIfError "Could not copy ..."
else
Log "Warning: did not find DIR_OF_SOME_FILES"
fi
</pre>
to something like
<pre>
if SOME_FILES_EXISTS ; then
cp SOME_FILES ...
else
Log "Warning: did not find SOME_FILES"
fi
</pre>
because …
> avoid nullglob pitfalls in 250_populate_efibootimg.sh (issue #1921) and generally overhalued that script

- usr/share/rear/skel/default/usr/lib/systemd/system/dbus.service
* Reference to related issue (URL): #1230
* How was this pull request tested? will test via rear-automated-testing
* Brief description of the changes in this pull request: see issue #1230
> Remove After=syslog.target form dbus.service #1230

- usr/share/rear/build/default/985_fix_broken_links.sh
https://github.com/rear/rear/issues/1638
and
https://github.com/rear/rear/pull/1734
Via "rear mkrescue" on my openSUSE Leap 15.0 system
See https://github.com/rear/rear/pull/1734#issuecomment-434635175
plus more verbose error reporting to the user
and much more verbose (i.e. explanatory) comments in the code ;-)
> Enhance and cleanup 985_fix_broken_links.sh (issue 1638 and pull request 1734)

- usr/share/rear/conf/default.conf
#1974 
This is a follow-up of #1980 , removing additional unused path.
> NBU: exclude '/usr/openv/netbackup/baremetal' which is not needed

- doc/user-guide/15-EFISTUB.adoc
* Type: **Other: Documentation**
* Reference to related issue (URL): https://github.com/rear/rear/issues/1942
N/A
Documentation to ReaR EFISTUB support. (https://github.com/rear/rear/pull/2030)
> Documentation for EFISTUB boot support.

- usr/share/rear/conf/GNU/Linux.conf
* Reference to related issue (URL): #2040 
* Brief description of the changes in this pull request: `clear` is a handy little tool to clear the console
> adding clear to PROGS array

- usr/share/rear/conf/default.conf
* Reference to related issue (URL): https://github.com/rear/rear/issues/2105
At customer site in production.
Simple change, only add additional path to NBU_LD_LIBRARY_PATH.
> Address issue https://github.com/rear/rear/issues/2105

- usr/share/rear/conf/default.conf
- usr/share/rear/finalize/GNU/Linux/310_migrate_udev_rules.sh
- usr/share/rear/skel/default/etc/scripts/system-setup
- usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh
* Reference to related issue (URL): #2074 
* How was this pull request tested? not yet - will use rear automated testing
> replace RULE_FILES with a global UDEV_NET_MAC_RULE_FILES

- packaging/rpm/rear.spec
* Impact: **Urgent**
* Reference to related issue (URL): #2135 
* How was this pull request tested? hopefully soon via OBS
* Brief description of the changes in this pull request: see comments given in https://github.com/rear/rear/commit/2819c071681a19fc3382aa84bfaf1654508a64aa
> reverted rear.spec changes for OBS build failures on SELS11 and RHEl5

- README.adoc
* Type:  **Other**
* Reference to related issue (URL): 
none
it wasn't
While it also was `was` when it's been done, `was` looks strange when it's to be done. Get it? :-)
> Small linguistic fix

- usr/share/rear/build/default/990_verify_rootfs.sh
https://github.com/rear/rear/issues/2177
By me with "rear -D mkrescue" on my openSUSE Leap 15.0 system.
Before I had in the log
```
++ for binary in $( find $ROOTFS_DIR -type f -executable -printf '/%P\n' )
++ grep -q 'not found'
+++ dirname /lib/modules/4.12.14-lp150.12.64-default/vdso/vdsox32.so
++ chroot /tmp/rear.DWijRMjkBl3QxbU/rootfs /bin/bash --login -c 'cd /lib/modules/4.12.14-lp150.12.64-default/vdso && ldd /lib/modules/4.12.14-lp150.12.64-default/vdso/vdsox32.so'
++ for binary in $( find $ROOTFS_DIR -type f -executable -printf '/%P\n' )
++ grep -q 'not found'
+++ dirname /lib/modules/4.12.14-lp150.12.64-default/vdso/vdso64.so
++ chroot …
```
> Skip the ldd test for kernel modules (issue #2177)

- doc/user-guide/16-Rubrik-CDM.adoc
Fixes #2255 
Selected the updated link and verified the web page. 
Updated link to SuSE documentation
> Updated link to SuSE documentation

- usr/share/rear/verify/CDM/default/410_use_replica_cdm_cluster_cert.sh
* Impact: **Urgent**
#2263 
Specified an alternate cluster IP and recovered the system succesfully.
Removed the invalid verbose option from find introduced by 83e8c36.
> Removed verbose option from find.

- doc/user-guide/04-scenarios.adoc
* Reference to related issue (URL): **N/A**
* How was this pull request tested? **N/A**
1. updated links to Borg documentation
1. documentation update `lzma,9` to `lzma,6` because according `man borg-compression`
```
Giving levels above 6 is pointless and counterproductive because it does 
not compress better due to the buffer size used by borg 
but it wastes lots of CPU cycles and RAM.
```
> Updated links to Borg documentation.

- README.adoc
- doc/rear-presentation.adoc
- doc/rear.8
- doc/rear.8.adoc
- doc/user-guide/01-introduction.adoc
- doc/user-guide/03-configuration.adoc
- doc/user-guide/09-design-concepts.adoc
- usr/share/rear/conf/default.conf
- usr/share/rear/prep/DP/default/450_check_dp_client_configured.sh
- usr/share/rear/restore/DP/default/300_create_dp_restore_fs_list.sh
- usr/share/rear/restore/DP/default/400_restore_with_dp.sh
- usr/share/rear/skel/DP/var/opt/omni/enhincrdb/.gitignore
- usr/share/rear/verify/DP/default/400_verify_dp.sh
- usr/share/rear/verify/DP/default/450_request_gui_restore.sh
- usr/share/rear/verify/DP/default/500_select_dp_restore.sh
Without those changes the latest version of Data Protector is not working and a few problems in the script prevent proper operation depending on user configuration
none
Applied the changes to a SLES12 SP4 system running rear 2.5.1. Created a new ISO, bootet the system and ran through various scenarios.
Changes to Data Protector branding, adjustment required to support the new Data Protector 10.x agent with Secure Socket Communication, fixed some problems related to SessionID format and problems with object names (host type vs. file system backup).
> Data protector 10

- usr/share/rear/lib/opaladmin-workflow.sh
* Reference to related issue (URL): #2349
* How was this pull request tested? On Ubuntu 18.04.4 LTS with multiple SEDs present
* Brief description of the changes in this pull request: See issue.
> Fix #2349: OPALPBA: cannot change password on multiple SEDs at once

- usr/share/rear/conf/default.conf
* Type: **Enhancement** / **Cleanup**
https://github.com/rear/rear/issues/2345
Works well for my particular use case, see
https://github.com/rear/rear/issues/2345
Have CLONE_ALL_USERS_GROUPS="true" by default
and explain it in default.conf
> CLONE_ALL_USERS_GROUPS="true" by default

- usr/share/rear/restore/NETFS/default/500_selinux_autorelabel.sh
- usr/share/rear/restore/default/500_selinux_autorelabel.sh
* Type: **Other?**
* Reference to related issue (URL): #1957 
* How was this pull request tested? N/A
* Brief description of the changes in this pull request: Added comments to the scripts
> Add proper comments of reason of these 2 scripts around SELinux #1957

- usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh
* Reference to related issue (URL): #2419
* How was this pull request tested? On Ubuntu 18.04.4 LTS and 20.04 LTS
* RAWDISK output: Add distribution-specific module 'linuxefi.mod' to Grub
> Fix #2419: RAWDISK output fails to boot with Grub 2 on UEFI

- usr/share/rear/backup/BLOCKCLONE/default/500_start_clone.sh
- usr/share/rear/finalize/Linux-ppc64le/660_install_grub2.sh
- usr/share/rear/restore/BLOCKCLONE/default/400_restore_clone.sh
- usr/share/rear/restore/NETFS/default/400_restore_backup.sh
- usr/share/rear/restore/YUM/default/405_recreate_users_and_groups.sh
- usr/share/rear/restore/YUM/default/410_restore_backup.sh
https://github.com/rear/rear/issues/2369
and
https://github.com/rear/rear/issues/2458
Tested by @dsamx in https://github.com/rear/rear/issues/2458
Let 'dd' read and write up to 1M=1024*1024 bytes at a time to speed up things
> Let 'dd' read and write up to 1M=1024*1024 bytes at a time to speed up things

- usr/share/rear/finalize/GNU/Linux/240_reassign_luks_keyfiles.sh
- usr/share/rear/layout/prepare/GNU/Linux/160_include_luks_code.sh
- usr/share/rear/lib/drlm-functions.sh
- usr/share/rear/restore/DUPLICITY/default/200_prompt_user_to_start_restore.sh
- usr/share/rear/restore/YUM/default/405_recreate_users_and_groups.sh
- usr/share/rear/verify/CDM/default/410_use_replica_cdm_cluster_cert.sh
https://github.com/rear/rear/issues/2460
Not yet tested at all.
Use ReaR specific TMP_DIR (not TMPDIR or hardcoded /tmp)
plus some more general cleanup work as noticed in scripts.
> Use ReaR specific TMP_DIR (not TMPDIR or hardcoded /tmp)

- .travis.yml
* Reference to related issue (URL): NA
* How was this pull request tested? Travis build
* Brief description of the changes in this pull request: just added arch:ppc64le to .travis.yml and tested.
Thanks,
Eshant
> Adding arch:ppc64le

- doc/user-guide/13-tcg-opal-support.adoc
* Reference to related issue (URL): #2511
* How was this pull request tested? By reading.
* Brief description of the changes in this pull request: Added a Quick Start section plus corrections.
> Improve TCG Opal 2 Documentation, fix #2511

- .travis.yml
* Impact:  **Normal** 
* How was this pull request tested? travis build
Travis job had not been running for some time. Looks like some parse error. Corrected a couple of things. Also added "install step" just to verify that as well.
> Correct travis parse error. Add additional steps

- usr/share/rear/build/GNU/Linux/400_copy_modules.sh
Without this adaption "rear mkrescue" on SLES15-SP3 errors out with
`ERROR: unix exists but no module file?`
bexause `unix` is a builtin kernel "module"
when not the default `MODULES=( 'all_modules' )` is used
i.e. when modules need to be copied individually.
Tested by me and others at SUSE on the upcoming SLES15-SP3
Make build/GNU/Linux/400_copy_modules.sh fail-safe against
newer modinfo (in particular modinfo in kmod-27 since SLES15-SP3)
that outputs on stdout for builtin kernel "modules" and exits with zero exit code like
```
name:           unix
(builtin)
```
in contrast to older modinfo (in particular modinfo before kmod-27 since SLES15-SP3)
that …
> Make 400_copy_modules.sh fail-safe for newer modinfo output and always include MODULES_LOAD

- usr/share/rear/layout/prepare/GNU/Linux/150_include_drbd_code.sh
Workaround against "DRBD9 restore issue, when trying to become primary"
cf. https://github.com/rear/rear/issues/2634
* Type: **Enhancement** / **Workaround**
https://github.com/rear/rear/issues/2634
Cannot be tested by me (I have no DRBD environment)
See the comment in the code.
> Workaround against DRBD9 restore issue #2634

- README.adoc
* Type: **Other?**
* Reference to related issue (URL): n/a
* How was this pull request tested? no - README update PR to test OBS workflow activation
* Brief description of the changes in this pull request: README update
> Update README file a little bit to test OBS

- usr/share/rear/format/USB/default/200_check_usb_layout.sh
- usr/share/rear/format/USB/default/300_format_usb_disk.sh
- usr/share/rear/format/USB/default/350_label_usb_disk.sh
- usr/share/rear/lib/format-workflow.sh
- usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
https://github.com/rear/rear/pull/2656
Not at all tested by me
Improved format/USB/default/300_format_usb_disk.sh
in particular regarding creating BIOS boot partition.
> Cleanup USB format scripts

- usr/share/rear/lib/layout-functions.sh
Basically no impact on systems with a few disks.
Medium impact on systems with many disks (hundreds).
High impact on systems with very many disks (thousands).
https://github.com/rear/rear/pull/2597
https://github.com/rear/rear/pull/2299/files#r709909416
I can only test on non-multipath systems with a few disks,
see https://github.com/rear/rear/pull/2708#issuecomment-967073823
and https://github.com/rear/rear/pull/2708#issuecomment-967108185
Get 'multipath -l' out of the function is_multipath_path
by adding a separated function is_multipath_used
that runs 'multipath -l' (which is expensive because it scans all devices) …
> New function is_multipath_used in layout-functions.sh

- usr/share/rear/rescue/default/500_ssh.sh
not at all
Since ssh-agent gets added it makes sense to add ssh-add as well.
> also add ssh-add prog when ssh-agent is added

- .travis.yml
- README.adoc
* Type: **Other**
* Reference to related issue (URL): #2757 
* How was this pull request tested? -
* Brief description of the changes in this pull request: Since Travis is not in use for this project (any more) the entries in its configuration file were commented out and its link removed in the README.adoc
> Remove Travis related configuration and link.

- usr/share/rear/backup/RSYNC/default/450_calculate_req_space.sh
* Impact:  **Normal**
* Reference to related issue (URL): #2760
* How was this pull request tested? not yet
* Brief description of the changes in this pull request: avoid space checking on remote rsync server
> Comment out remote space check with rsync #2760

- doc/user-guide/06-layout-configuration.adoc
- usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh
- usr/share/rear/layout/prepare/default/420_autoresize_last_partitions.sh
- usr/share/rear/layout/recreate/default/120_confirm_wipedisk_disks.sh
- usr/share/rear/layout/recreate/default/220_verify_layout.sh
- usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh
- usr/share/rear/lib/layout-functions.sh
https://github.com/rear/rear/issues/2759
See below
https://github.com/rear/rear/pull/2800#issuecomment-1120970696
> Use disklayout.conf keyword 'raidarray' instead of 'raid'

- usr/share/rear/lib/global-functions.sh
https://github.com/rear/rear/pull/2813#discussion_r885576867
https://github.com/rear/rear/pull/2457
Not yet tested
In lib/global-functions.sh in the function mount_url()
renamed the user config variable
USER_INPUT_RELAXRECOVER_SYMLINK_TARGET
as USER_INPUT_ISO_SYMLINK_TARGET
because the old name contained a user config value:
RELAXRECOVER was an old default value of ISO_VOLID, see
https://github.com/rear/rear/pull/2457
Accordingly also renamed the local variables
relaxrecover_block_device
relaxrecover_symlink_name
relaxrecover_symlink_target
as
iso_block_device
iso_symlink_name
iso_symlink_target
> Replace 'RELAXRECOVER' in variable names

- doc/rear-release-notes.txt
- doc/rear.8
- doc/rear.8.adoc
- packaging/debian/changelog
- packaging/rpm/rear.spec
- usr/sbin/rear
* Type: **ReaR 2.7 Release Preparations**
https://github.com/rear/rear/issues/2751
See https://github.com/rear/rear/wiki/Release-process
Set VERSION=2.7 in usr/sbin/rear
> Preparations for ReaR 2.7

- usr/share/rear/backup/NETFS/default/500_make_backup.sh
- usr/share/rear/build/default/501_check_ssh_keys.sh
- usr/share/rear/build/default/990_verify_rootfs.sh
- usr/share/rear/finalize/GNU/Linux/250_migrate_lun_wwid.sh
- usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
- usr/share/rear/layout/prepare/GNU/Linux/136_include_btrfs_subvolumes_SLES_code.sh
- usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
- usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
- usr/share/rear/layout/save/GNU/Linux/280_multipath_layout.sh
- usr/share/rear/layout/save/GNU/Linux/510_current_disk_usage.sh
- usr/share/rear/lib/_input-output-functions.sh
- usr/share/rear/lib/columns-functions.sh
- usr/share/rear/lib/global-functions.sh
- usr/share/rear/prep/GNU/Linux/240_include_multipath_tools.sh
- usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
- usr/share/rear/prep/RSYNC/GNU/Linux/200_selinux_in_use.sh
- usr/share/rear/rescue/NETFS/default/610_save_capabilities.sh
- usr/share/rear/restore/TSM/default/400_restore_with_tsm.sh
- usr/share/rear/restore/YUM/default/400_restore_packages.sh
- usr/share/rear/skel/default/etc/scripts/system-setup
Use simpler and faster syntax STRING+=" additional words"
see https://github.com/rear/rear/issues/2848
> Use STRING+=" additional words" everywhere

- .packit.yaml
* How was this pull request tested? By `packit validate-config` in root of the cloned repo.
Rename or remove all deprecated keys and options as advised by Packit CLI:
* `metadata` key in jobs is deprecated and can be removed
* `synced_files` configuration key was renamed to `files_to_sync`
* `upstream_project_name` configuration key was renamed to `upstream_package_name`
> Modernize Packit configuration

- usr/share/rear/lib/sesam-functions.sh
- usr/share/rear/prep/SESAM/default/400_prep_sesam.sh
> issue: #3018: fix sesam default exlude pathes

- usr/share/rear/lib/layout-functions.sh
https://github.com/rear/rear/pull/1765
https://github.com/rear/rear/commit/14c062627e15d3be799b1a8bd220634a0aa032b9
Not tested - only added comments in the code.
In lib/layout-functions.sh
better explain certain complicated parts
of the apply_layout_mappings() implementation
by additional comments in the code
> Better explain apply_layout_mappings() implementation

- usr/share/rear/init/default/100_check_stale_nfs_mounts.sh
* Reference to related issue (URL): #3109 
* How was this pull request tested? Manual with a local NAS system
* Description of the changes in this pull request: See issue #3109 for the full story, but in short we want to bail out ReaR if there is a stale NFS mount point.
> Stale NFS detection in a very early stage #3109

- doc/rear.8.adoc
- usr/share/rear/conf/default.conf
- usr/share/rear/prep/VEEAM/default/400_prep_veeam.sh
- usr/share/rear/restore/VEEAM/default/450_find_backup.sh
- usr/share/rear/restore/VEEAM/default/500_restore.sh
- usr/share/rear/verify/VEEAM/default/400_verify_veeam.sh
* Reference to related issue (URL): #3075
* How was this pull request tested? Baremetal, VMware, KVM, QEMU, RHEL7, RHEL8, RHEL9, Veeam V11 & Veeam V12
Add support for Veeam Agent for Linux Bare Metal Recovery
> Add veeam support

- usr/share/rear/conf/default.conf
* Type: **Documentation**
https://github.com/rear/rear/issues/3189#issuecomment-2093032268
https://github.com/rear/rear/issues/3189#issuecomment-2093288555
Not tetsted (only comments in default.conf)
In default.conf better explain the COPY_AS_IS_EXCLUDE_TSM example
that it results a slim TSM client without reduced functionality
and that some language files are needed.
> default.conf COPY_AS_IS_EXCLUDE_TSM example better explained

- usr/share/rear/format/USB/default/200_check_usb_layout.sh
- usr/share/rear/format/USB/default/300_format_usb_disk.sh
* Reference to related issue (URL): #3178 and #3311 
* How was this pull request tested? On a system with nvme devices and  also tested with a normal legacy USB device
* Description of the changes in this pull request: To fix the error 'Unable to determine real USB device based on USB device /dev/nvme?n1'
> #3178 improve USB device detection

- usr/share/rear/lib/config-functions.sh
- usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
* Type: **Bug Fix** / **Enhancement** 
* Reference to related issue (URL): See respective commit messages.
* Set `OS_VENDOR` to `Arch_Linux` on Arch Linux
* Remove incorrect check for `SUSE_LINUX`
edit: typo
> Minor os-detection improvements

- usr/share/rear/lib/validated/Arch_Linux/rolling/i386.txt
* Reference to related issue (URL): #3344
not tested.
Change the occurrences of "Arch" (as the identifier of a distribution) that have remained after PR #3344 to "Arch_Linux".
> cleanup: Finish the change of "Arch to "Arch_Linux"

- usr/share/rear/finalize/Linux-i386/630_install_grub.sh
- usr/share/rear/finalize/Linux-i386/660_install_grub2.sh
- usr/share/rear/layout/save/default/445_guess_bootloader.sh
* Type: **Documentation enhancement**
* How was this pull request tested? Not at all.
Just fixes some text in default.conf.
> Fix some typos 

- usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
* Reference to related issue (URL): #3401 
* How was this pull request tested? On a kubernetes system with this issue
* Description of the changes in this pull request: We need to exclude iSCSI longhorn devices from the disklayout.conf file.
> #3401 discard longhorn devices

- doc/user-guide/12-BLOCKCLONE.adoc
- usr/share/rear/backup/BLOCKCLONE/default/500_start_clone.sh
- usr/share/rear/conf/default.conf
- usr/share/rear/conf/examples/blockclone.conf
- usr/share/rear/restore/BLOCKCLONE/default/400_restore_clone.sh
* Reference to related issue (URL): #3333 
* How was this pull request tested? Manually see #3333 
* Description of the changes in this pull request: See the `usr/share/rear/conf/examples/blockclone.conf` file which contains a full description.
> Using Blockclone to save a disk image of a RPi system

- usr/share/rear/layout/save/default/450_check_network_files.sh
* Reference to related issue (URL): #3405 
* How was this pull request tested? via `rear checklayout`
* Description of the changes in this pull request: Linux systems using NetworkManager only network interfaces were not covered by the script.
> Update 450_check_network_files.sh for NetworkManager

- usr/share/rear/layout/prepare/GNU/Linux/160_include_luks_code.sh
see at the end of
https://github.com/rear/rear/issues/3483#issuecomment-3032444609
see below
https://github.com/rear/rear/pull/3489#issuecomment-3032748572
Use a temporary file in the ReaR recovery system
which contains the LUKS password value to avoid
that a password variable needs to be evaluated.
> Use temporary LUKS password file in 160_include_luks_code.sh

- usr/share/rear/lib/opaladmin-workflow.sh
* Type: **Bug Mitigation**
Mitigate https://github.com/rear/rear/issues/3486
for now until at some later time the OPAL related code
became properly secured against leaking out secrets
by a contributor who actually uses a TCG Opal disk.
https://github.com/rear/rear/issues/3486#issuecomment-3073334020
see below
https://github.com/rear/rear/pull/3496#issuecomment-3073553814
In lib/opaladmin-workflow.sh
get explicit user confirmation that
the user "knows what he does" via a true
OPAL_EXPOSE_SECRETS environment variable
for OPAL specific secrets or in general via
the '--expose-secrets' option for any secrets
or inform the user that secrets could leak …
> Get explicit user confirmation in opaladmin-workflow.sh
